In [48]:
import numpy as np
import pandas as pd
import seaborn as sns

import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import KFold, StratifiedKFold

from opfython.models import SupervisedOPF
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, ConfusionMatrixDisplay, roc_auc_score, balanced_accuracy_score, matthews_corrcoef, average_precision_score

from sklearn.neighbors import KNeighborsClassifier, NearestCentroid
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC as SupportVectorMachineClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier

from sklearn.inspection import permutation_importance

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.model_selection import ParameterGrid

# Resampling removido: não faz parte do protocolo.

from scipy.stats import wilcoxon
import scipy.stats as st

import logging
opfython_logger = logging.getLogger("opfython")
opfython_logger.setLevel(logging.CRITICAL + 1)
opfython_logger.propagate = False
import warnings

In [49]:
df = pd.read_csv('NPHA-doctor-visits.csv')

In [50]:
df

,Number of Doctors Visited,Age,Phyiscal Health,Mental Health,Dental Health,Employment,Stress Keeps Patient from Sleeping,Medication Keeps Patient from Sleeping,Pain Keeps Patient from Sleeping,Bathroom Needs Keeps Patient from Sleeping,Uknown Keeps Patient from Sleeping,Trouble Sleeping,Prescription Sleep Medication,Race,Gender
0,3,2,4,3,3,3,0,0,0,0,1,2,3,1,2
1,2,2,4,2,3,3,1,0,0,1,0,3,3,1,1
2,3,2,3,2,3,3,0,0,0,0,1,3,3,4,1
3,1,2,3,2,3,3,0,0,0,1,0,3,3,4,2
4,3,2,3,3,3,3,1,0,0,0,0,2,3,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
709,2,2,2,2,2,3,0,0,0,1,0,3,3,1,1
710,3,2,2,2,2,2,1,0,0,0,1,2,3,1,2
711,3,2,4,2,3,3,0,0,0,0,0,3,3,1,1
712,3,2,3,1,3,3,1,0,1,1,1,3,3,1,2
713,2,2,3,2,2,1,1,0,1,1,0,2,3,1,1

In [51]:
df.shape

(714, 15)

In [52]:
df.isna().sum()

Number of Doctors Visited                     0
Age                                           0
Phyiscal Health                               0
Mental Health                                 0
Dental Health                                 0
Employment                                    0
Stress Keeps Patient from Sleeping            0
Medication Keeps Patient from Sleeping        0
Pain Keeps Patient from Sleeping              0
Bathroom Needs Keeps Patient from Sleeping    0
Uknown Keeps Patient from Sleeping            0
Trouble Sleeping                              0
Prescription Sleep Medication                 0
Race                                          0
Gender                                        0
dtype: int64

In [53]:
df

,Number of Doctors Visited,Age,Phyiscal Health,Mental Health,Dental Health,Employment,Stress Keeps Patient from Sleeping,Medication Keeps Patient from Sleeping,Pain Keeps Patient from Sleeping,Bathroom Needs Keeps Patient from Sleeping,Uknown Keeps Patient from Sleeping,Trouble Sleeping,Prescription Sleep Medication,Race,Gender
0,3,2,4,3,3,3,0,0,0,0,1,2,3,1,2
1,2,2,4,2,3,3,1,0,0,1,0,3,3,1,1
2,3,2,3,2,3,3,0,0,0,0,1,3,3,4,1
3,1,2,3,2,3,3,0,0,0,1,0,3,3,4,2
4,3,2,3,3,3,3,1,0,0,0,0,2,3,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
709,2,2,2,2,2,3,0,0,0,1,0,3,3,1,1
710,3,2,2,2,2,2,1,0,0,0,1,2,3,1,2
711,3,2,4,2,3,3,0,0,0,0,0,3,3,1,1
712,3,2,3,1,3,3,1,0,1,1,1,3,3,1,2
713,2,2,3,2,2,1,1,0,1,1,0,2,3,1,1

In [54]:
#histograma das features

# features = df.select_dtypes(include=['number']).columns

# for feature in features:
#     plt.figure(figsize=(8, 6))
#     sns.histplot(data=df, x=feature, hue='Number of Doctors Visited', kde=False, bins=50, palette="pastel")

#     plt.xlabel(feature)
#     plt.ylabel("Contagem")
#     plt.title(f"Distribuição da feature: {feature}")
#     plt.legend(title="Class")
#     plt.show()

In [55]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 714 entries, 0 to 713
Data columns (total 15 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Number of Doctors Visited                   714 non-null    int64
 1   Age                                         714 non-null    int64
 2   Phyiscal Health                             714 non-null    int64
 3   Mental Health                               714 non-null    int64
 4   Dental Health                               714 non-null    int64
 5   Employment                                  714 non-null    int64
 6   Stress Keeps Patient from Sleeping          714 non-null    int64
 7   Medication Keeps Patient from Sleeping      714 non-null    int64
 8   Pain Keeps Patient from Sleeping            714 non-null    int64
 9   Bathroom Needs Keeps Patient from Sleeping  714 non-null    int64
 10  Uknown Keeps Patient from Sleeping          714 non-null    int64
 11  Trouble Sleeping                            714 non-null    int64
 12  Prescription Sleep Medication               714 non-null    int64
 13  Race                                        714 non-null    int64
 14  Gender                                      714 non-null    int64
dtypes: int64(15)
memory usage: 83.8 KB

In [56]:
df.describe()

,Number of Doctors Visited,Age,Phyiscal Health,Mental Health,Dental Health,Employment,Stress Keeps Patient from Sleeping,Medication Keeps Patient from Sleeping,Pain Keeps Patient from Sleeping,Bathroom Needs Keeps Patient from Sleeping,Uknown Keeps Patient from Sleeping,Trouble Sleeping,Prescription Sleep Medication,Race,Gender
count,714.000000,714.0,714.000000,714.000000,714.000000,714.000000,714.000000,714.000000,714.000000,714.000000,714.000000,714.000000,714.000000,714.000000,714.00000
mean,2.112045,2.0,2.794118,1.988796,3.009804,2.806723,0.247899,0.056022,0.218487,0.504202,0.417367,2.407563,2.829132,1.425770,1.55042
std,0.683441,0.0,0.900939,0.939928,1.361117,0.586582,0.432096,0.230126,0.413510,0.500333,0.493470,0.670349,0.546767,1.003896,0.49780
min,1.000000,2.0,-1.000000,-1.000000,-1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,-1.000000,1.000000,1.00000
25%,2.000000,2.0,2.000000,1.000000,2.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,3.000000,1.000000,1.00000
50%,2.000000,2.0,3.000000,2.000000,3.000000,3.000000,0.000000,0.000000,0.000000,1.000000,0.000000,3.000000,3.000000,1.000000,2.00000
75%,3.000000,2.0,3.000000,3.000000,4.000000,3.000000,0.000000,0.000000,0.000000,1.000000,1.000000,3.000000,3.000000,1.000000,2.00000
max,3.000000,2.0,5.000000,5.000000,6.000000,4.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000,3.000000,5.000000,2.00000

In [57]:
# visualizing the distribution of the features
fig, axes = plt.subplots(3, 5, figsize=(20, 15))
axes = axes.ravel()

for i, column in enumerate(df.columns):
    df[column].value_counts().plot(kind='bar', ax=axes[i])
    axes[i].set_title(column)

plt.tight_layout()
plt.show()

/tmp/ipykernel_666002/806374595.py:10: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [58]:
df['Number of Doctors Visited'].describe()

count    714.000000
mean       2.112045
std        0.683441
min        1.000000
25%        2.000000
50%        2.000000
75%        3.000000
max        3.000000
Name: Number of Doctors Visited, dtype: float64

In [59]:
df['Age'].describe()

count    714.0
mean       2.0
std        0.0
min        2.0
25%        2.0
50%        2.0
75%        2.0
max        2.0
Name: Age, dtype: float64

In [60]:
plt.figure(figsize=(8, 6))
sns.boxplot(y='Number of Doctors Visited', data=df)
plt.title("Boxplot of the Number of Doctors Visited column")
plt.show()

/tmp/ipykernel_666002/716654087.py:4: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [61]:
Q1_UP = df['Number of Doctors Visited'].quantile(0.25)
Q2_UP = df['Number of Doctors Visited'].quantile(0.5)
Q3_UP = df['Number of Doctors Visited'].quantile(0.75)

lower_limit_UP = Q1_UP - 1.5 * (Q3_UP - Q1_UP)
upper_limit_UP = Q3_UP + 1.5 * (Q3_UP - Q1_UP)

print(f"Feature: Number of Doctors Visited")
print(f"- Q1: {Q1_UP:.2f}")
print(f"- Q2 (Mediana): {Q2_UP:.2f}")
print(f"- Q3: {Q3_UP:.2f}")
print(f"- Limite Inferior: {lower_limit_UP:.2f}")
print(f"- Limite Superior: {upper_limit_UP:.2f}")

Feature: Number of Doctors Visited
- Q1: 2.00
- Q2 (Mediana): 2.00
- Q3: 3.00
- Limite Inferior: 0.50
- Limite Superior: 4.50

Existe um viés na Classe 2. Portanto seria bom utilizar tecnica de  subamostragem para a classe super-representada.

In [62]:
# Calculate the class distribution
class_distribution = df['Number of Doctors Visited'].value_counts()
print(class_distribution)

Number of Doctors Visited
2    372
3    211
1    131
Name: count, dtype: int64

In [63]:
df_ = df.copy()

age_dict = { 1: "50-64", 2: "65-80" }
df_['Age'] = df_['Age'].map(age_dict)

race_dict = { 1: "White, Non-Hispanic", 2: "Black, Non-Hispanic", 3: "Other, Non-Hispanic", 4: "Hispanic", 5: "2+ Races, Non-Hispanic" }
df_['Race'] = df_['Race'].map(race_dict)

gender_dict = { 1: "Male", 2: "Female" }
df_['Gender'] = df_['Gender'].map(gender_dict)

plt.subplots(figsize=(20, 10))
for i, col in enumerate(['Age', 'Race' , 'Gender']):
    plt.subplot(1, 3, i + 1)

    x = df_[col].value_counts()
    plt.bar(x.index, x.values)
    plt.title('Distribution of Patient ' + col)
    plt.xticks(rotation=45, ha='right')
    plt.ylabel('Count')

plt.show()

/tmp/ipykernel_666002/533527952.py:22: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [64]:
fig, axes = plt.subplots(1, 3, figsize=(20, 10))
for i, col in enumerate(['Age', 'Race', 'Gender']):
    x = df_[col].value_counts()
    axes[i].bar(x.index.astype(str), x.values, color=sns.color_palette("viridis", len(x)))
    axes[i].set_title('Distribution of Patient ' + col)
    axes[i].set_xlabel(col)
    axes[i].set_ylabel('Count')
    # Adicionar valores em cima das barras
    for j, v in enumerate(x.values):
        axes[i].text(j, v + 0.5, str(v), ha='center', fontweight='bold')

plt.tight_layout()
plt.show()

/tmp/ipykernel_666002/3179644547.py:13: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [65]:
# Calculate the correlation matrix
corr_matrix = df.corr()

# Create a heatmap
plt.figure(figsize=(18, 8))
sns.heatmap(corr_matrix, cmap='coolwarm', annot=True, fmt=".2f", linewidths=0.5)

# Add annotations to the heatmap
for i in range(len(corr_matrix)):
    for j in range(len(corr_matrix)):
        text = f"{corr_matrix.iloc[i, j]:.2f}"
        plt.text(j + 0.5, i + 0.5, text, ha='center', va='center', color='black')

plt.title("Correlation Matrix")
plt.show()

/tmp/ipykernel_666002/1832467298.py:15: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [66]:
# Target documentado: 1 consulta -> 0; 2/3 consultas -> 1.
df['Number of Doctors Visited'] = df['Number of Doctors Visited'].map({1: 0, 2: 1, 3: 1}).astype('int8')
class_counts = df['Number of Doctors Visited'].value_counts().sort_index()
class_percentages = df['Number of Doctors Visited'].value_counts(normalize=True).sort_index().mul(100)
print('Target: 0=0-1 consulta; 1=2+ consultas')
print(pd.DataFrame({'count': class_counts, 'percent': class_percentages}))

Target: 0=0-1 consulta; 1=2+ consultas
                           count    percent
Number of Doctors Visited
0                            131  18.347339
1                            583  81.652661

LEGADO: codificação do alvo desativada; pipeline final usa target binário explícito.

In [67]:
categorical_features = [c for c in df.columns if c != 'Number of Doctors Visited']
df_encoded = pd.get_dummies(df, columns=categorical_features, drop_first=False)
df_encoded

,Number of Doctors Visited,Age_2,Phyiscal Health_-1,Phyiscal Health_1,Phyiscal Health_2,Phyiscal Health_3,Phyiscal Health_4,Phyiscal Health_5,Mental Health_-1,Mental Health_1,...,Prescription Sleep Medication_1,Prescription Sleep Medication_2,Prescription Sleep Medication_3,Race_1,Race_2,Race_3,Race_4,Race_5,Gender_1,Gender_2
0,1,True,False,False,False,False,True,False,False,False,...,False,False,True,True,False,False,False,False,False,True
1,1,True,False,False,False,False,True,False,False,False,...,False,False,True,True,False,False,False,False,True,False
2,1,True,False,False,False,True,False,False,False,False,...,False,False,True,False,False,False,True,False,True,False
3,0,True,False,False,False,True,False,False,False,False,...,False,False,True,False,False,False,True,False,False,True
4,1,True,False,False,False,True,False,False,False,False,...,False,False,True,True,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
709,1,True,False,False,True,False,False,False,False,False,...,False,False,True,True,False,False,False,False,True,False
710,1,True,False,False,True,False,False,False,False,False,...,False,False,True,True,False,False,False,False,False,True
711,1,True,False,False,False,False,True,False,False,False,...,False,False,True,True,False,False,False,False,True,False
712,1,True,False,False,False,True,False,False,False,True,...,False,False,True,True,False,False,False,False,False,True
713,1,True,False,False,False,True,False,False,False,False,...,False,False,True,True,False,False,False,False,True,False

In [68]:
df_encoded = df_encoded.reset_index(drop=True)

In [69]:
X = df_encoded.drop(columns=['Number of Doctors Visited'])
y = df_encoded['Number of Doctors Visited'].astype('int8')

In [70]:
X

,Age_2,Phyiscal Health_-1,Phyiscal Health_1,Phyiscal Health_2,Phyiscal Health_3,Phyiscal Health_4,Phyiscal Health_5,Mental Health_-1,Mental Health_1,Mental Health_2,...,Prescription Sleep Medication_1,Prescription Sleep Medication_2,Prescription Sleep Medication_3,Race_1,Race_2,Race_3,Race_4,Race_5,Gender_1,Gender_2
0,True,False,False,False,False,True,False,False,False,False,...,False,False,True,True,False,False,False,False,False,True
1,True,False,False,False,False,True,False,False,False,True,...,False,False,True,True,False,False,False,False,True,False
2,True,False,False,False,True,False,False,False,False,True,...,False,False,True,False,False,False,True,False,True,False
3,True,False,False,False,True,False,False,False,False,True,...,False,False,True,False,False,False,True,False,False,True
4,True,False,False,False,True,False,False,False,False,False,...,False,False,True,True,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
709,True,False,False,True,False,False,False,False,False,True,...,False,False,True,True,False,False,False,False,True,False
710,True,False,False,True,False,False,False,False,False,True,...,False,False,True,True,False,False,False,False,False,True
711,True,False,False,False,False,True,False,False,False,True,...,False,False,True,True,False,False,False,False,True,False
712,True,False,False,False,True,False,False,False,True,False,...,False,False,True,True,False,False,False,False,False,True
713,True,False,False,False,True,False,False,False,False,True,...,False,False,True,True,False,False,False,False,True,False

In [71]:
y

0      1
1      1
2      1
3      0
4      1
      ..
709    1
710    1
711    1
712    1
713    1
Name: Number of Doctors Visited, Length: 714, dtype: int8

In [72]:
# feature_importances = pd.DataFrame(model.feature_importances_,
#                                    index = X.columns,
#                                    columns=['importance']).sort_values('importance', ascending=False)

# # Plotting
# plt.figure(figsize=(10, 6))
# feature_importances.plot(kind='barh')

In [73]:
y

0      1
1      1
2      1
3      0
4      1
      ..
709    1
710    1
711    1
712    1
713    1
Name: Number of Doctors Visited, Length: 714, dtype: int8

In [74]:
colunas_lixo = [
    'Race_5', 'Uknown Keeps Patient from Sleeping_0', 'Prescription Sleep Medication_2',
    'Phyiscal Health_1', 'Mental Health_-1', 'Race_4', 'Dental Health_1',
    'Prescription Sleep Medication_-1', 'Dental Health_-1', 'Mental Health_5',
    'Phyiscal Health_-1', 'Age_2', 'Gender_1', 'Phyiscal Health_3', 'Phyiscal Health_5', 'Dental Health_3',
    'Race_2', 'Trouble Sleeping_3', 'Mental Health_3', 'Gender_2',
    'Employment_1', 'Trouble Sleeping_2', 'Dental Health_6', 'Trouble Sleeping_-1'
]

In [75]:
X = X.drop(columns=colunas_lixo)

In [76]:
print(f"Dimensões atuais: {X.shape}")

Dimensões atuais: (714, 25)

In [77]:
X_resampled = X.values
y_resampled = y.to_numpy()

In [78]:
y = pd.Series(y_resampled, name='Number of Doctors Visited').astype('int8')
class_distribution = y.value_counts().sort_index()
print("Class distribution (sem resampling):")
print(class_distribution)

Class distribution (sem resampling):
Number of Doctors Visited
0    131
1    583
Name: count, dtype: int64

In [79]:
ax = y.value_counts().plot(kind='bar', title='Number of Doctors Visited', color=sns.color_palette("viridis", len(y.value_counts())))
ax.set_xlabel('Classes')
ax.set_ylabel('Count')
for p in ax.patches:
    ax.text(p.get_x() + p.get_width()/2, p.get_height() + 0.5, str(int(p.get_height())), ha='center', fontweight='bold')
plt.show()

/tmp/ipykernel_666002/3165614967.py:6: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [80]:
scaler = StandardScaler()
X_escalonado = scaler.fit_transform(X)

In [81]:
pca = PCA(n_components=2)
componentes_principais = pca.fit_transform(X_escalonado)
df_pca = pd.DataFrame(data=componentes_principais, columns=['PC1', 'PC2'])
df_pca['Classe_Alvo'] = y

In [82]:
plt.figure(figsize=(10, 8))
sns.scatterplot(
    x='PC1', 
    y='PC2', 
    hue='Classe_Alvo', 
    palette='viridis',
    data=df_pca, 
    alpha=0.8,
    s=70
)

In [83]:
sns.scatterplot(x='PC1', y='PC2', hue='Classe_Alvo', palette='viridis', data=df_pca, alpha=0.8, s=70)
expl_1 = pca.explained_variance_ratio_[0]*100
expl_2 = pca.explained_variance_ratio_[1]*100
plt.title('Gráfico de Componentes Principais em 2D (PCA Plot)', fontsize=15)
plt.xlabel(f"Componente Principal 1 ({expl_1:.2f}% de variância agrupada)")
plt.ylabel(f"Componente Principal 2 ({expl_2:.2f}% de variância agrupada)")
plt.legend(title='Classe', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

/tmp/ipykernel_666002/3556441085.py:10: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [84]:
pca_3d = PCA(n_components=3)
comps_3d = pca_3d.fit_transform(X_escalonado)
    
df_pca3 = pd.DataFrame(data=comps_3d, columns=['PC1', 'PC2', 'PC3'])
df_pca3['Classe_Alvo'] = y
    
# Matplotlib puro pro 3D 
fig3d = plt.figure(figsize=(12, 10))
ax = fig3d.add_subplot(111, projection='3d')

cores = ['purple', 'teal', 'gold'] 
classes_unicas = sorted(list(df_pca3['Classe_Alvo'].unique()))
    
# Plota classe por classe
for cls, cor in zip(classes_unicas, cores):
    subset = df_pca3[df_pca3['Classe_Alvo'] == cls]
    ax.scatter(subset['PC1'], subset['PC2'], subset['PC3'], 
                color=cor, label=f'Classe {cls}', s=60, alpha=0.9, edgecolor='black', linewidth=0.5)

e1_3d = pca_3d.explained_variance_ratio_[0]*100
e2_3d = pca_3d.explained_variance_ratio_[1]*100
e3_3d = pca_3d.explained_variance_ratio_[2]*100

ax.set_xlabel(f"PC1 ({e1_3d:.2f}%)", fontweight='bold', labelpad=10)
ax.set_ylabel(f"PC2 ({e2_3d:.2f}%)", fontweight='bold', labelpad=10)
ax.set_zlabel(f"PC3 ({e3_3d:.2f}%)", fontweight='bold', labelpad=10)
plt.title('Profundidade Dimensional Alvo (PCA 3D)', fontsize=16)
plt.legend(title='Target/Classe', loc='best')

# Opcional (rotacionar ângulo)
ax.view_init(elev=20, azim=135)
plt.tight_layout()
plt.show()

/tmp/ipykernel_666002/298286174.py:33: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [85]:
df = pd.DataFrame(X, columns=X.columns)

In [86]:
df_encoded.shape

(714, 50)

In [87]:
df

,Phyiscal Health_2,Phyiscal Health_4,Mental Health_1,Mental Health_2,Mental Health_4,Dental Health_2,Dental Health_4,Dental Health_5,Employment_2,Employment_3,...,Pain Keeps Patient from Sleeping_0,Pain Keeps Patient from Sleeping_1,Bathroom Needs Keeps Patient from Sleeping_0,Bathroom Needs Keeps Patient from Sleeping_1,Uknown Keeps Patient from Sleeping_1,Trouble Sleeping_1,Prescription Sleep Medication_1,Prescription Sleep Medication_3,Race_1,Race_3
0,False,True,False,False,False,False,False,False,False,True,...,True,False,True,False,True,False,False,True,True,False
1,False,True,False,True,False,False,False,False,False,True,...,True,False,False,True,False,False,False,True,True,False
2,False,False,False,True,False,False,False,False,False,True,...,True,False,True,False,True,False,False,True,False,False
3,False,False,False,True,False,False,False,False,False,True,...,True,False,False,True,False,False,False,True,False,False
4,False,False,False,False,False,False,False,False,False,True,...,True,False,True,False,False,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
709,True,False,False,True,False,True,False,False,False,True,...,True,False,False,True,False,False,False,True,True,False
710,True,False,False,True,False,True,False,False,True,False,...,True,False,True,False,True,False,False,True,True,False
711,False,True,False,True,False,False,False,False,False,True,...,True,False,True,False,False,False,False,True,True,False
712,False,False,True,False,False,False,False,False,False,True,...,False,True,False,True,True,False,False,True,True,False
713,False,False,False,True,False,True,False,False,False,False,...,False,True,False,True,False,False,False,True,True,False

In [88]:
x = df

In [89]:
x

,Phyiscal Health_2,Phyiscal Health_4,Mental Health_1,Mental Health_2,Mental Health_4,Dental Health_2,Dental Health_4,Dental Health_5,Employment_2,Employment_3,...,Pain Keeps Patient from Sleeping_0,Pain Keeps Patient from Sleeping_1,Bathroom Needs Keeps Patient from Sleeping_0,Bathroom Needs Keeps Patient from Sleeping_1,Uknown Keeps Patient from Sleeping_1,Trouble Sleeping_1,Prescription Sleep Medication_1,Prescription Sleep Medication_3,Race_1,Race_3
0,False,True,False,False,False,False,False,False,False,True,...,True,False,True,False,True,False,False,True,True,False
1,False,True,False,True,False,False,False,False,False,True,...,True,False,False,True,False,False,False,True,True,False
2,False,False,False,True,False,False,False,False,False,True,...,True,False,True,False,True,False,False,True,False,False
3,False,False,False,True,False,False,False,False,False,True,...,True,False,False,True,False,False,False,True,False,False
4,False,False,False,False,False,False,False,False,False,True,...,True,False,True,False,False,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
709,True,False,False,True,False,True,False,False,False,True,...,True,False,False,True,False,False,False,True,True,False
710,True,False,False,True,False,True,False,False,True,False,...,True,False,True,False,True,False,False,True,True,False
711,False,True,False,True,False,False,False,False,False,True,...,True,False,True,False,False,False,False,True,True,False
712,False,False,True,False,False,False,False,False,False,True,...,False,True,False,True,True,False,False,True,True,False
713,False,False,False,True,False,True,False,False,False,False,...,False,True,False,True,False,False,False,True,True,False

In [90]:
x = x.values

In [91]:
x

array([[False,  True, False, ...,  True,  True, False],
       [False,  True, False, ...,  True,  True, False],
       [False, False, False, ...,  True, False, False],
       ...,
       [False,  True, False, ...,  True,  True, False],
       [False, False,  True, ...,  True,  True, False],
       [False, False, False, ...,  True,  True, False]], shape=(714, 25))

# Protocolo experimental canônico
As células 0–45 são EDA histórica e não fornecem objetos ao treino. Este bloco recarrega os dados, fixa o protocolo e separa resultados corrigidos de resultados legados.

In [92]:
from pathlib import Path
from datetime import datetime, timezone
import hashlib
import json
import platform
import sys
import warnings
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

import numpy as np
import pandas as pd
import sklearn
from sklearn.base import clone
from sklearn.calibration import CalibratedClassifierCV
from sklearn.compose import ColumnTransformer
from sklearn.dummy import DummyClassifier
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    balanced_accuracy_score,
    confusion_matrix,
    f1_score,
    matthews_corrcoef,
    precision_score,
    recall_score,
    precision_recall_curve,
    roc_curve,
    roc_auc_score,
)
from sklearn.model_selection import ParameterGrid, StratifiedKFold
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier, NearestCentroid
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from opfython.models import SupervisedOPF
from xgboost import XGBClassifier

SEED = 42
TARGET_COLUMN = "Number of Doctors Visited"
TARGET_MAP = {1: 0, 2: 1, 3: 1}
TARGET_LABELS = {0: "0–1 consulta", 1: "2+ consultas"}
DATA_PATH = Path("src/NPHA-doctor-visits.csv")
if not DATA_PATH.exists():
    DATA_PATH = Path("NPHA-doctor-visits.csv")
if not DATA_PATH.exists():
    DATA_PATH = Path("/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/src/NPHA-doctor-visits.csv")
assert DATA_PATH.exists(), "CSV não encontrado"
raw_data = pd.read_csv(DATA_PATH)
assert len(raw_data) == 714, f"n inesperado: {len(raw_data)}"
assert TARGET_COLUMN in raw_data.columns
assert set(raw_data[TARGET_COLUMN].dropna().unique()).issubset(TARGET_MAP)
y = raw_data[TARGET_COLUMN].map(TARGET_MAP).astype("int8")
assert set(y.unique()) == {0, 1}
X = raw_data.drop(columns=[TARGET_COLUMN]).copy()
class_counts = y.value_counts().sort_index()
class_percentages = y.value_counts(normalize=True).sort_index().mul(100)
print("Target:", TARGET_LABELS)
print(class_counts)
print(class_percentages)

outer_cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=SEED)
inner_cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)
y_array = y.to_numpy()
fold_indices = []
for outer_fold, (train_index, test_index) in enumerate(outer_cv.split(X, y_array), 1):
    fold_indices.append({
        "outer_fold": outer_fold,
        "train_index": train_index.tolist(),
        "test_index": test_index.tolist(),
    })

param_grid_KNN = {
    "n_neighbors": [5, 10, 20],
    "weights": ["uniform", "distance"],
}
param_grid_DT = {
    "max_depth": [3, 5, 7, None],
    "min_samples_leaf": [1, 5],
}
param_grid_RF = {
    "n_estimators": [100, 200],
    "max_depth": [3, 5, None],
    "min_samples_leaf": [1, 5],
}
param_grid_SVM = {
    "C": [0.1, 1, 10],
    "kernel": ["linear", "rbf"],
}
param_grid_MLP = {
    "hidden_layer_sizes": [(32,), (32, 16)],
    "alpha": [0.0001, 0.01],
    "max_iter": [500],
}
param_grid_LR = {
    "C": [0.01, 0.1, 1, 10],
    "solver": ["lbfgs"],
    "max_iter": [1000],
}
param_grid_XGB = {
    "n_estimators": [100, 200],
    "max_depth": [3, 5],
    "learning_rate": [0.05, 0.1],
}
param_grid_NB = {"var_smoothing": [1e-11, 1e-9, 1e-7]}
param_grid_NC = {
    "metric": ["euclidean", "manhattan"],
    "shrink_threshold": [None, 0.1],
}
param_grid_OPF = {"distance": ["euclidean", "manhattan"]}
param_grid_AdaBoost = {
    "n_estimators": [50, 100, 200],
    "learning_rate": [0.05, 0.1, 1.0],
}
param_grid_Dummy = {"strategy": ["most_frequent"]}

Target: {0: '0–1 consulta', 1: '2+ consultas'}
Number of Doctors Visited
0    131
1    583
Name: count, dtype: int64
Number of Doctors Visited
0    18.347339
1    81.652661
Name: proportion, dtype: float64

In [93]:
def build_preprocessor(frame):
    numeric = frame.select_dtypes(include=[np.number]).columns.tolist()
    categorical = [column for column in frame.columns if column not in numeric]
    transformers = []
    if numeric:
        transformers.append(
            (
                "numeric",
                Pipeline(
                    [
                        ("imputer", SimpleImputer(strategy="median")),
                        ("scaler", StandardScaler()),
                    ]
                ),
                numeric,
            )
        )
    if categorical:
        transformers.append(
            (
                "categorical",
                Pipeline(
                    [
                        ("imputer", SimpleImputer(strategy="most_frequent")),
                        (
                            "encoder",
                            OneHotEncoder(
                                handle_unknown="ignore",
                                sparse_output=False,
                            ),
                        ),
                    ]
                ),
                categorical,
            )
        )
    return ColumnTransformer(transformers=transformers, remainder="drop")


def prevalence_weights(y_fit):
    values, counts = np.unique(np.asarray(y_fit), return_counts=True)
    frequencies = dict(zip(values.tolist(), counts.tolist()))
    assert set(frequencies) == {0, 1}
    return {
        0: len(y_fit) / (2 * frequencies[0]),
        1: len(y_fit) / (2 * frequencies[1]),
    }


def fit_mdi_selector(encoded_fit, feature_names, feature_origins, y_fit):
    auxiliary = RandomForestClassifier(n_estimators=100, random_state=SEED, class_weight=None, n_jobs=1)
    auxiliary.fit(encoded_fit, y_fit)
    importances = np.asarray(auxiliary.feature_importances_, dtype=float)
    order = np.argsort(importances)[::-1]
    ordered_importance = importances[order]
    cumulative = np.cumsum(ordered_importance) / (ordered_importance.sum() or 1.0)
    prefix_size = np.searchsorted(cumulative, 0.80) + 1
    selected_mask = np.zeros(len(feature_names), dtype=bool)
    selected_mask[order[:prefix_size]] = True
    metadata = [
        {
            "feature_transformed": feature_names[index],
            "feature_origin": feature_origins[index],
            "importance": float(ordered_importance[position]),
            "cumulative": float(cumulative[position]),
            "selected": bool(position < prefix_size),
        }
        for position, index in enumerate(order)
    ]
    return selected_mask, metadata


def prepare_split(X_fit, y_fit, X_apply, use_mdi=False):
    preprocessor = build_preprocessor(X_fit)
    encoded_fit = preprocessor.fit_transform(X_fit)
    encoded_apply = preprocessor.transform(X_apply)
    feature_names = preprocessor.get_feature_names_out().tolist()
    record = {
        "selected_mask": None,
        "feature_names": feature_names,
        "importances": None,
        "cumulative": None,
        "feature_origin": feature_names,
        "mdi_records": [],
    }
    if not use_mdi:
        return preprocessor, encoded_fit, encoded_apply, record
    feature_origins = []
    for transformer_name, _, columns in preprocessor.transformers_:
        if transformer_name == "categorical":
            encoder = preprocessor.named_transformers_["categorical"].named_steps["encoder"]
            feature_origins.extend(
                origin for origin, categories in zip(columns, encoder.categories_)
                for _ in categories
            )
        else:
            feature_origins.extend(columns)
    selected_mask, mdi_records = fit_mdi_selector(
        encoded_fit, feature_names, feature_origins, y_fit
    )
    importances = np.asarray([item["importance"] for item in mdi_records], dtype=float)
    cumulative = np.cumsum(importances) / (importances.sum() or 1.0)
    prefix_size = np.searchsorted(cumulative, 0.80) + 1
    record.update(
        {
            "selected_mask": selected_mask.tolist(),
            "importances": [item["importance"] for item in mdi_records],
            "cumulative": [item["cumulative"] for item in mdi_records],
            "feature_origin": [item["feature_origin"] for item in mdi_records],
            "mdi_records": mdi_records,
        }
    )
    assert cumulative[prefix_size - 1] >= 0.80
    return preprocessor, encoded_fit[:, selected_mask], encoded_apply[:, selected_mask], record


def make_estimator(name, params, scenario="baseline", y_fit=None):
    applied = dict(params)
    if name == "KNN":
        return KNeighborsClassifier(**applied)
    if name == "DT":
        if scenario == "cost_sensitive":
            applied["class_weight"] = prevalence_weights(y_fit)
        applied["random_state"] = SEED
        return DecisionTreeClassifier(**applied)
    if name == "RF":
        if scenario == "cost_sensitive":
            applied["class_weight"] = prevalence_weights(y_fit)
        applied["random_state"] = SEED
        applied["n_jobs"] = 1
        return RandomForestClassifier(**applied)
    if name == "SVM":
        if scenario == "cost_sensitive":
            applied["class_weight"] = prevalence_weights(y_fit)
        base = SVC(**applied)
        return CalibratedClassifierCV(
            estimator=base,
            cv=5,
            method="sigmoid",
        )
    if name == "MLP":
        applied["random_state"] = SEED
        return MLPClassifier(**applied)
    if name == "LR":
        if scenario == "cost_sensitive":
            applied["class_weight"] = prevalence_weights(y_fit)
        return LogisticRegression(**applied)
    if name == "XGB":
        if scenario == "cost_sensitive":
            weights = prevalence_weights(y_fit)
            applied["scale_pos_weight"] = weights[1] / weights[0]
        applied["random_state"] = SEED
        applied["n_jobs"] = 1
        return XGBClassifier(**applied)
    if name == "NB":
        return GaussianNB(**applied)
    if name == "NC":
        return NearestCentroid(**applied)
    if name == "AdaBoost":
        applied["random_state"] = SEED
        return AdaBoostClassifier(**applied)
    if name == "Dummy":
        return DummyClassifier(**applied, random_state=SEED)
    if name == "OPF":
        return SupervisedOPF(**applied)
    raise KeyError(name)


def predict_with_score(model, X_apply):
    prediction = np.asarray(model.predict(X_apply))
    if hasattr(model, "predict_proba"):
        probabilities = np.asarray(model.predict_proba(X_apply))
        classes = np.asarray(model.classes_)
        score0 = probabilities[:, np.flatnonzero(classes == 0)[0]]
        score1 = probabilities[:, np.flatnonzero(classes == 1)[0]]
        return prediction, score0, score1, "predict_proba"
    if hasattr(model, "decision_function"):
        decision = np.asarray(model.decision_function(X_apply))
        if decision.ndim == 1:
            return prediction, -decision, decision, "decision_function"
        classes = np.asarray(model.classes_)
        return (
            prediction,
            decision[:, np.flatnonzero(classes == 0)[0]],
            decision[:, np.flatnonzero(classes == 1)[0]],
            "decision_function",
        )
    return prediction, None, None, "unavailable"


def binary_metrics(y_true, prediction, score0=None, score1=None):
    matrix = confusion_matrix(y_true, prediction, labels=[0, 1])
    tn, fp, fn, tp = matrix.ravel()
    result = {
        "accuracy": accuracy_score(y_true, prediction),
        "precision_0": precision_score(y_true, prediction, labels=[0], average=None, zero_division=0)[0],
        "precision_1": precision_score(y_true, prediction, labels=[1], average=None, zero_division=0)[0],
        "recall_0": recall_score(y_true, prediction, labels=[0], average=None, zero_division=0)[0],
        "recall_1": recall_score(y_true, prediction, labels=[1], average=None, zero_division=0)[0],
        "f1_0": f1_score(y_true, prediction, labels=[0], average=None, zero_division=0)[0],
        "f1_1": f1_score(y_true, prediction, labels=[1], average=None, zero_division=0)[0],
        "f1_macro": f1_score(y_true, prediction, labels=[0, 1], average="macro", zero_division=0),
        "f1_weighted": f1_score(y_true, prediction, labels=[0, 1], average="weighted", zero_division=0),
        "precision_macro": precision_score(y_true, prediction, labels=[0, 1], average="macro", zero_division=0),
        "recall_macro": recall_score(y_true, prediction, labels=[0, 1], average="macro", zero_division=0),
        "balanced_accuracy": balanced_accuracy_score(y_true, prediction),
        "mcc": matthews_corrcoef(y_true, prediction),
        "specificity": tn / (tn + fp) if tn + fp else np.nan,
        "sensitivity": tp / (tp + fn) if tp + fn else np.nan,
        "TN": int(tn),
        "FP": int(fp),
        "FN": int(fn),
        "TP": int(tp),
        "score_source": "unavailable" if score1 is None else "continuous",
        "auroc": roc_auc_score(y_true, score1) if score1 is not None else np.nan,
        "ap_0": average_precision_score(1 - np.asarray(y_true), score0) if score0 is not None else np.nan,
        "ap_1": average_precision_score(y_true, score1) if score1 is not None else np.nan,
    }
    return result

# Fase 1 — Baseline
Todas as features, Dummy e roster histórico.

In [94]:
roster = ["KNN", "DT", "RF", "SVM", "MLP", "LR", "XGB", "NB", "NC", "OPF", "AdaBoost"]
grids = {"KNN": param_grid_KNN, "DT": param_grid_DT, "RF": param_grid_RF, "SVM": param_grid_SVM, "MLP": param_grid_MLP, "LR": param_grid_LR, "XGB": param_grid_XGB, "NB": param_grid_NB, "NC": param_grid_NC, "OPF": param_grid_OPF, "AdaBoost": param_grid_AdaBoost}
phase1_oof = {name: np.full(len(y_array), -1, dtype=int) for name in roster + ["Dummy"]}
phase1_scores = {name: np.full(len(y_array), np.nan) for name in roster + ["Dummy"]}
phase1_rows = []
phase1_search = []
for outer_fold, (train_index, test_index) in enumerate(outer_cv.split(X, y_array), 1):
    X_train = X.iloc[train_index]
    X_test = X.iloc[test_index]
    y_train = y_array[train_index]
    y_test = y_array[test_index]
    for name in roster + ["Dummy"]:
        grid = param_grid_Dummy if name == "Dummy" else grids[name]
        candidates = []
        for params in ParameterGrid(grid):
            inner_scores = []
            for inner_fold, (inner_train, inner_valid) in enumerate(inner_cv.split(X_train, y_train), 1):
                preprocessor, encoded_train, encoded_valid, mdi_record = prepare_split(X_train.iloc[inner_train], y_train[inner_train], X_train.iloc[inner_valid])
                model = make_estimator(name, params, y_fit=y_train[inner_train])
                if name == "OPF":
                    model.fit(np.asarray(encoded_train), np.asarray(y_train[inner_train], dtype=np.int32))
                    prediction = model.predict(np.asarray(encoded_valid))
                else:
                    model.fit(encoded_train, y_train[inner_train])
                    prediction = model.predict(encoded_valid)
                inner_scores.append(f1_score(y_train[inner_valid], prediction, labels=[0, 1], average="macro", zero_division=0))
                phase1_search.append({"scenario": "baseline", "model": name, "outer_fold": outer_fold, "inner_fold": inner_fold, "params": dict(params), "params_applied": model.get_params(deep=True) if hasattr(model, "get_params") else dict(params), "f1_macro": inner_scores[-1]})
            candidates.append((float(np.mean(inner_scores)), dict(params)))
        best_f1, best_params = max(candidates, key=lambda item: item[0])
        preprocessor, encoded_train, encoded_test, mdi_record = prepare_split(X_train, y_train, X_test)
        model = make_estimator(name, best_params, y_fit=y_train)
        if name == "OPF":
            model.fit(np.asarray(encoded_train), np.asarray(y_train, dtype=np.int32))
            prediction, score0, score1, score_source = predict_with_score(model, np.asarray(encoded_test))
        else:
            model.fit(encoded_train, y_train)
            prediction, score0, score1, score_source = predict_with_score(model, encoded_test)
        metrics = binary_metrics(y_test, prediction, score0, score1)
        metrics.update({"scenario": "baseline", "model": name, "outer_fold": outer_fold, "params": best_params, "inner_f1_macro": best_f1})
        phase1_rows.append(metrics)
        phase1_oof[name][test_index] = prediction
        if score1 is not None:
            phase1_scores[name][test_index] = score1
        print("Fase 1", name, metrics)

Fase 1 KNN {'accuracy': 0.75, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8059701492537313), 'recall_0': np.float64(0.0), 'recall_1': np.float64(0.9152542372881356), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8571428571428571), 'f1_macro': 0.42857142857142855, 'f1_weighted': 0.7023809523809523, 'precision_macro': 0.40298507462686567, 'recall_macro': 0.4576271186440678, 'balanced_accuracy': 0.4576271186440678, 'mcc': -0.12823107147006824, 'specificity': np.float64(0.0), 'sensitivity': np.float64(0.9152542372881356), 'TN': 0, 'FP': 13, 'FN': 5, 'TP': 54, 'score_source': 'continuous', 'auroc': 0.4902216427640157, 'ap_0': 0.17858044615260238, 'ap_1': 0.8226043170507016, 'scenario': 'baseline', 'model': 'KNN', 'outer_fold': 1, 'params': {'n_neighbors': 5, 'weights': 'distance'}, 'inner_f1_macro': 0.48583631986178144}
Fase 1 DT {'accuracy': 0.6527777777777778, 'precision_0': np.float64(0.16666666666666666), 'precision_1': np.float64(0.8148148148148148), 'recall_0': np.float64(0.23076923076923078), 'recall_1': np.float64(0.7457627118644068), 'f1_0': np.float64(0.1935483870967742), 'f1_1': np.float64(0.7787610619469026), 'f1_macro': 0.4861547245218384, 'f1_weighted': 0.6730976623211851, 'precision_macro': 0.4907407407407407, 'recall_macro': 0.4882659713168188, 'balanced_accuracy': 0.4882659713168188, 'mcc': -0.02084690996125416, 'specificity': np.float64(0.23076923076923078), 'sensitivity': np.float64(0.7457627118644068), 'TN': 3, 'FP': 10, 'FN': 15, 'TP': 44, 'score_source': 'continuous', 'auroc': 0.4810951760104302, 'ap_0': 0.18504273504273502, 'ap_1': 0.8111817643485797, 'scenario': 'baseline', 'model': 'DT', 'outer_fold': 1, 'params': {'max_depth': None, 'min_samples_leaf': 1}, 'inner_f1_macro': 0.5025316401177824}
Fase 1 RF {'accuracy': 0.7638888888888888, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8088235294117647), 'recall_0': np.float64(0.0), 'recall_1': np.float64(0.9322033898305084), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8661417322834646), 'f1_macro': 0.4330708661417323, 'f1_weighted': 0.7097550306211723, 'precision_macro': 0.40441176470588236, 'recall_macro': 0.4661016949152542, 'balanced_accuracy': 0.4661016949152542, 'mcc': -0.1138469000458504, 'specificity': np.float64(0.0), 'sensitivity': np.float64(0.9322033898305084), 'TN': 0, 'FP': 13, 'FN': 4, 'TP': 55, 'score_source': 'continuous', 'auroc': 0.559973924380704, 'ap_0': 0.2165050559425372, 'ap_1': 0.8655075788026302, 'scenario': 'baseline', 'model': 'RF', 'outer_fold': 1, 'params': {'max_depth': None, 'min_samples_leaf': 1, 'n_estimators': 100}, 'inner_f1_macro': 0.4818805607469015}
Fase 1 SVM {'accuracy': 0.8194444444444444, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8194444444444444), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.9007633587786259), 'f1_macro': 0.45038167938931295, 'f1_weighted': 0.7381255301102629, 'precision_macro': 0.4097222222222222, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 13, 'FN': 0, 'TP': 59, 'score_source': 'continuous', 'auroc': 0.4471968709256845, 'ap_0': 0.1764573549138486, 'ap_1': 0.8274874759147883, 'scenario': 'baseline', 'model': 'SVM', 'outer_fold': 1, 'params': {'C': 0.1, 'kernel': 'linear'}, 'inner_f1_macro': 0.44939986263058634}

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

Fase 1 MLP {'accuracy': 0.8194444444444444, 'precision_0': np.float64(0.5), 'precision_1': np.float64(0.8285714285714286), 'recall_0': np.float64(0.07692307692307693), 'recall_1': np.float64(0.9830508474576272), 'f1_0': np.float64(0.13333333333333333), 'f1_1': np.float64(0.8992248062015504), 'f1_macro': 0.5162790697674419, 'f1_weighted': 0.7609388458225668, 'precision_macro': 0.6642857142857144, 'recall_macro': 0.529986962190352, 'balanced_accuracy': 0.529986962190352, 'mcc': 0.14037705656838215, 'specificity': np.float64(0.07692307692307693), 'sensitivity': np.float64(0.9830508474576272), 'TN': 1, 'FP': 12, 'FN': 1, 'TP': 58, 'score_source': 'continuous', 'auroc': 0.634941329856584, 'ap_0': 0.29282719695105053, 'ap_1': 0.9090614668759465, 'scenario': 'baseline', 'model': 'MLP', 'outer_fold': 1, 'params': {'alpha': 0.01, 'hidden_layer_sizes': (32,), 'max_iter': 500}, 'inner_f1_macro': 0.4795592417052627}
Fase 1 LR {'accuracy': 0.8194444444444444, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8194444444444444), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.9007633587786259), 'f1_macro': 0.45038167938931295, 'f1_weighted': 0.7381255301102629, 'precision_macro': 0.4097222222222222, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 13, 'FN': 0, 'TP': 59, 'score_source': 'continuous', 'auroc': 0.6597131681877444, 'ap_0': 0.2953927891319415, 'ap_1': 0.9095031500879605, 'scenario': 'baseline', 'model': 'LR', 'outer_fold': 1, 'params': {'C': 0.01, 'max_iter': 1000, 'solver': 'lbfgs'}, 'inner_f1_macro': 0.44939986263058634}
Fase 1 XGB {'accuracy': 0.7777777777777778, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8115942028985508), 'recall_0': np.float64(0.0), 'recall_1': np.float64(0.9491525423728814), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.875), 'f1_macro': 0.4375, 'f1_weighted': 0.7170138888888888, 'precision_macro': 0.4057971014492754, 'recall_macro': 0.4745762711864407, 'balanced_accuracy': 0.4745762711864407, 'mcc': -0.09787724855562428, 'specificity': np.float64(0.0), 'sensitivity': np.float64(0.9491525423728814), 'TN': 0, 'FP': 13, 'FN': 3, 'TP': 56, 'score_source': 'continuous', 'auroc': 0.6688396349413298, 'ap_0': 0.2649912291077635, 'ap_1': 0.9158382803299345, 'scenario': 'baseline', 'model': 'XGB', 'outer_fold': 1, 'params': {'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 200}, 'inner_f1_macro': 0.4770371557008518}
Fase 1 NB {'accuracy': 0.8055555555555556, 'precision_0': np.float64(0.4), 'precision_1': np.float64(0.835820895522388), 'recall_0': np.float64(0.15384615384615385), 'recall_1': np.float64(0.9491525423728814), 'f1_0': np.float64(0.2222222222222222), 'f1_1': np.float64(0.8888888888888888), 'f1_macro': 0.5555555555555556, 'f1_weighted': 0.7685185185185185, 'precision_macro': 0.6179104477611941, 'recall_macro': 0.5514993481095176, 'balanced_accuracy': 0.5514993481095176, 'mcc': 0.155850071479006, 'specificity': np.float64(0.15384615384615385), 'sensitivity': np.float64(0.9491525423728814), 'TN': 2, 'FP': 11, 'FN': 3, 'TP': 56, 'score_source': 'continuous', 'auroc': 0.6662320730117341, 'ap_0': 0.29105053843327855, 'ap_1': 0.9048893931899173, 'scenario': 'baseline', 'model': 'NB', 'outer_fold': 1, 'params': {'var_smoothing': 1e-11}, 'inner_f1_macro': 0.4856995335772541}

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(

Fase 1 NC {'accuracy': 0.5555555555555556, 'precision_0': np.float64(0.21212121212121213), 'precision_1': np.float64(0.8461538461538461), 'recall_0': np.float64(0.5384615384615384), 'recall_1': np.float64(0.559322033898305), 'f1_0': np.float64(0.30434782608695654), 'f1_1': np.float64(0.673469387755102), 'f1_macro': 0.4889086069210293, 'f1_weighted': 0.6068224391205758, 'precision_macro': 0.5291375291375291, 'recall_macro': 0.5488917861799217, 'balanced_accuracy': 0.5488917861799217, 'mcc': 0.07548737230565958, 'specificity': np.float64(0.5384615384615384), 'sensitivity': np.float64(0.559322033898305), 'TN': 7, 'FP': 6, 'FN': 26, 'TP': 33, 'score_source': 'continuous', 'auroc': 0.6179921773142113, 'ap_0': 0.28290442114371184, 'ap_1': 0.8925504134673372, 'scenario': 'baseline', 'model': 'NC', 'outer_fold': 1, 'params': {'metric': 'euclidean', 'shrink_threshold': None}, 'inner_f1_macro': 0.45892838431981176}
2026-09-13 19:40:20,326 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:40:20,327 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:40:20,327 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:40:20,327 - opfython.core.opf — INFO — Class created.
2026-09-13 19:40:20,328 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:40:20,328 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:40:20,330 - opfython.models.supervised — DEBUG — Finding prototypes ...

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(

2026-09-13 19:40:20,533 - opfython.models.supervised — DEBUG — Prototypes: [335, 98, 417, 351, 215, 96, 403, 122, 303, 416, 35, 455, 37, 46, 273, 309, 297, 127, 21, 268, 206, 112, 498, 138, 118, 22, 97, 435, 392, 246, 166, 160, 276, 340, 378, 42, 248, 496, 211, 334, 421, 240, 254, 280, 451, 423, 89, 350, 139, 213, 125, 478, 52, 121, 7, 8, 352, 474, 102, 398, 23, 45, 241, 75, 313, 141, 287, 271, 66, 73, 472, 128, 419, 216, 61, 13, 437, 209, 376, 226, 158, 326, 445, 258, 65, 432, 404, 25, 134, 144, 360, 272, 64, 454, 193, 10, 263, 133, 76, 159, 278, 67, 68, 265, 243, 348, 29, 99, 257, 300, 470, 507, 239, 120, 203, 181, 18, 406, 2, 488, 316, 296, 431, 408, 444, 450, 130, 429, 367, 469, 3, 78, 154, 290, 386, 317, 188, 221, 286, 19, 465, 225, 180, 349, 249, 270, 81, 85, 460, 1, 397, 20, 466, 418, 155, 105, 142, 95, 260, 53, 6, 327, 489, 84, 365, 92, 383, 59, 69, 483, 152, 208, 231, 482, 24, 169, 60, 302, 150, 110, 399, 124, 354, 262, 310, 344, 41, 479, 129, 370, 269, 132, 428, 195, 233, 382, 184, 200, 201, 217, 362, 373, 294, 261, 443, 224, 44, 285, 304, 156, 79, 173, 62, 487, 493, 232, 186, 187, 380, 194].
2026-09-13 19:40:20,711 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:40:20,712 - opfython.models.supervised — INFO — Training time: 0.38314270973205566 seconds.
2026-09-13 19:40:20,712 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:40:20,791 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:40:20,792 - opfython.models.supervised — INFO — Prediction time: 0.07932758331298828 seconds.
2026-09-13 19:40:20,801 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:40:20,802 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:40:20,802 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:40:20,803 - opfython.core.opf — INFO — Class created.
2026-09-13 19:40:20,803 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:40:20,803 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:40:20,805 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:40:20,894 - opfython.models.supervised — DEBUG — Prototypes: [417, 345, 325, 274, 448, 409, 113, 55, 487, 457, 282, 50, 306, 447, 141, 295, 494, 403, 32, 463, 342, 302, 416, 480, 401, 399, 454, 497, 179, 96, 388, 252, 186, 115, 276, 333, 247, 421, 45, 211, 485, 258, 442, 281, 89, 166, 327, 493, 475, 343, 151, 134, 65, 8, 405, 395, 310, 111, 153, 249, 474, 201, 21, 315, 48, 255, 336, 175, 477, 73, 319, 39, 195, 80, 434, 349, 142, 419, 66, 86, 13, 318, 176, 446, 233, 374, 24, 428, 404, 444, 275, 74, 188, 157, 224, 352, 452, 508, 505, 70, 455, 77, 14, 88, 177, 500, 340, 372, 391, 173, 129, 272, 190, 312, 3, 294, 406, 506, 246, 132, 298, 286, 214, 217, 386, 232, 466, 285, 9, 202, 313, 178, 341, 273, 361, 472, 289, 384, 215, 97, 462, 1, 331, 236, 414, 189, 467, 418, 394, 18, 381, 98, 62, 81, 483, 170, 358, 103, 489, 56, 320, 109, 7, 219, 238, 482, 278, 441, 22, 301, 64, 171, 138, 347, 90, 53, 262, 335, 44, 154, 131, 307, 259, 364, 192, 43, 365, 100, 380, 213, 292, 71, 491, 354, 458, 464, 225, 199, 212, 512, 174, 261, 94, 93, 473, 377, 227, 200, 91, 253, 502, 326].
2026-09-13 19:40:21,070 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:40:21,071 - opfython.models.supervised — INFO — Training time: 0.26703667640686035 seconds.
2026-09-13 19:40:21,071 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:40:21,146 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:40:21,146 - opfython.models.supervised — INFO — Prediction time: 0.07483935356140137 seconds.
2026-09-13 19:40:21,156 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:40:21,157 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:40:21,157 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:40:21,157 - opfython.core.opf — INFO — Class created.
2026-09-13 19:40:21,157 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:40:21,158 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:40:21,159 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:40:21,265 - opfython.models.supervised — DEBUG — Prototypes: [142, 502, 39, 504, 168, 91, 296, 173, 319, 207, 294, 11, 199, 176, 414, 183, 340, 393, 139, 388, 239, 481, 193, 80, 326, 42, 83, 472, 15, 445, 246, 378, 443, 269, 304, 360, 72, 428, 129, 155, 40, 236, 509, 25, 146, 73, 284, 10, 108, 77, 17, 287, 172, 74, 51, 322, 351, 377, 395, 169, 125, 442, 71, 305, 281, 185, 450, 407, 35, 34, 352, 455, 28, 52, 285, 330, 446, 138, 302, 494, 482, 121, 405, 403, 150, 496, 334, 111, 196, 491, 411, 118, 109, 56, 238, 75, 416, 68, 36, 128, 22, 110, 112, 486, 495, 259, 157, 233, 333, 254, 364, 264, 27, 290, 451, 440, 291, 420, 162, 86, 337, 493, 474, 355, 383, 113, 1, 353, 391, 235, 137, 132, 66, 478, 57, 7, 8, 399, 369, 23, 50, 497, 85, 283, 171, 315, 151, 470, 358, 223, 228, 200, 21, 253, 130, 427, 410, 318, 480, 465, 417, 288, 439, 484, 164, 99, 367, 430, 58, 6, 327, 195, 87, 240, 24, 184, 65, 306, 127, 313, 165, 243, 425, 136, 357, 479, 141, 370, 265, 374, 135, 372, 96, 152, 46, 379, 423, 203, 221, 145, 354, 49, 299, 492, 167, 216, 245, 307, 456, 170, 268, 249, 488, 205, 206, 60, 234, 382, 214, 88, 81, 503, 336].
2026-09-13 19:40:21,471 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:40:21,472 - opfython.models.supervised — INFO — Training time: 0.3136308193206787 seconds.
2026-09-13 19:40:21,473 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:40:21,561 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:40:21,562 - opfython.models.supervised — INFO — Prediction time: 0.08892107009887695 seconds.
2026-09-13 19:40:21,574 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:40:21,574 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:40:21,575 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:40:21,575 - opfython.core.opf — INFO — Class created.
2026-09-13 19:40:21,575 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:40:21,576 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:40:21,577 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:40:21,689 - opfython.models.supervised — DEBUG — Prototypes: [59, 114, 223, 486, 236, 75, 35, 287, 350, 36, 407, 310, 419, 53, 313, 330, 138, 305, 494, 480, 123, 405, 95, 151, 496, 393, 263, 37, 174, 44, 113, 131, 339, 425, 209, 265, 157, 232, 422, 504, 257, 48, 217, 380, 484, 288, 351, 152, 453, 292, 88, 41, 333, 473, 282, 424, 446, 354, 383, 117, 2, 233, 136, 161, 65, 8, 9, 399, 316, 111, 284, 25, 321, 51, 498, 268, 86, 259, 206, 472, 343, 171, 297, 261, 87, 501, 227, 290, 234, 155, 359, 454, 508, 186, 182, 26, 73, 70, 211, 11, 112, 146, 74, 52, 283, 184, 139, 340, 237, 421, 66, 192, 79, 438, 356, 326, 42, 16, 325, 172, 449, 274, 28, 246, 101, 450, 397, 18, 378, 409, 448, 71, 505, 256, 200, 21, 308, 30, 221, 444, 3, 433, 411, 220, 225, 96, 1, 461, 103, 296, 12, 245, 377, 349, 142, 173, 39, 430, 367, 468, 4, 503, 170, 93, 176, 337, 249, 441, 478, 385, 97, 80, 482, 166, 364, 102, 490, 61, 164, 228, 250, 481, 291, 445, 198, 89, 239, 477, 141, 417, 191, 342, 47, 271, 370, 372, 99, 145, 429, 213, 252, 46, 384, 212, 135, 467, 458, 463, 188, 303, 50, 295, 218, 169, 238, 408, 244, 360, 311, 513, 203, 94, 92, 251, 488, 493, 205, 90, 81, 264, 382, 241, 502, 133].
2026-09-13 19:40:21,907 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:40:21,908 - opfython.models.supervised — INFO — Training time: 0.3318619728088379 seconds.
2026-09-13 19:40:21,909 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:40:22,002 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:40:22,003 - opfython.models.supervised — INFO — Prediction time: 0.09348869323730469 seconds.
2026-09-13 19:40:22,015 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:40:22,016 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:40:22,018 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:40:22,019 - opfython.core.opf — INFO — Class created.
2026-09-13 19:40:22,019 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:40:22,020 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:40:22,022 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:40:22,132 - opfython.models.supervised — DEBUG — Prototypes: [418, 352, 330, 279, 106, 188, 491, 411, 450, 105, 50, 210, 487, 222, 71, 326, 278, 449, 459, 37, 302, 18, 29, 28, 350, 466, 407, 406, 142, 395, 248, 174, 169, 91, 30, 123, 19, 107, 38, 281, 338, 217, 150, 329, 421, 250, 495, 42, 382, 485, 423, 272, 445, 286, 84, 333, 453, 97, 353, 383, 110, 1, 127, 59, 478, 51, 219, 394, 243, 82, 291, 276, 68, 322, 36, 186, 76, 438, 358, 81, 475, 319, 60, 419, 218, 223, 380, 23, 67, 261, 434, 408, 274, 179, 65, 277, 457, 199, 8, 266, 104, 136, 69, 10, 137, 21, 73, 12, 502, 83, 167, 283, 70, 46, 348, 378, 398, 164, 121, 446, 66, 312, 2, 296, 410, 364, 24, 452, 448, 474, 298, 209, 208, 212, 125, 368, 503, 133, 33, 505, 163, 88, 293, 389, 168, 313, 229, 196, 16, 232, 468, 275, 171, 92, 96, 336, 235, 416, 177, 480, 342, 41, 17, 374, 400, 215, 483, 284, 367, 85, 225, 20, 178, 58, 301, 386, 56, 122, 308, 132, 193, 54, 130, 146, 103, 202, 237, 40, 479, 258, 135, 429, 108, 385, 206, 344, 371, 191, 363, 492, 45, 290, 162, 224, 469, 460, 355, 467, 79, 165, 7, 89, 87, 488, 493, 477, 86, 249, 504, 332].
2026-09-13 19:40:22,390 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:40:22,392 - opfython.models.supervised — INFO — Training time: 0.37116336822509766 seconds.
2026-09-13 19:40:22,393 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:40:22,539 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:40:22,540 - opfython.models.supervised — INFO — Prediction time: 0.14655590057373047 seconds.
2026-09-13 19:40:22,556 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:40:22,557 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:40:22,558 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:40:22,559 - opfython.core.opf — INFO — Class created.
2026-09-13 19:40:22,560 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:40:22,562 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:40:22,565 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:40:22,704 - opfython.models.supervised — DEBUG — Prototypes: [335, 176, 417, 351, 215, 332, 46, 273, 331, 447, 127, 297, 455, 282, 303, 21, 416, 122, 403, 35, 206, 498, 138, 112, 435, 96, 42, 378, 248, 496, 211, 409, 334, 421, 350, 139, 451, 280, 423, 89, 213, 125, 478, 52, 121, 7, 8, 313, 95, 23, 45, 500, 271, 75, 241, 157, 216, 128, 419, 73, 472, 61, 437, 209, 13, 376, 226, 341, 64, 272, 454, 193, 10, 263, 25, 134, 144, 360, 452, 170, 133, 159, 76, 278, 158, 90, 243, 118, 22, 97, 432, 404, 392, 398, 352, 347, 102, 246, 68, 289, 67, 326, 166, 276, 340, 287, 321, 203, 81, 1, 460, 317, 180, 221, 188, 286, 19, 465, 225, 367, 3, 469, 504, 130, 429, 78, 154, 160, 65, 258, 260, 24, 169, 53, 6, 327, 489, 84, 365, 175, 92, 383, 59, 208, 231, 483, 152, 348, 290, 386, 270, 240, 361, 254, 150, 27, 445, 275, 470, 507, 29, 99, 239, 120, 60, 181, 2, 488, 316, 431, 408, 345, 110, 399, 444, 397, 20, 269, 370, 249, 18, 296, 262, 310, 450, 11, 142, 281, 195, 167, 344, 41, 466, 418, 252, 212, 487, 493, 156, 82, 382, 201, 124, 354, 56, 217, 94, 184, 200, 132, 428, 294, 261, 443, 224, 44, 285, 479, 305, 471, 62, 232, 79, 173, 486, 380, 194, 186].
2026-09-13 19:40:22,955 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:40:22,956 - opfython.models.supervised — INFO — Training time: 0.3934357166290283 seconds.
2026-09-13 19:40:22,957 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:40:23,051 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:40:23,052 - opfython.models.supervised — INFO — Prediction time: 0.09436225891113281 seconds.
2026-09-13 19:40:23,062 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:40:23,063 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:40:23,064 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:40:23,064 - opfython.core.opf — INFO — Class created.
2026-09-13 19:40:23,065 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:40:23,066 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:40:23,067 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:40:23,166 - opfython.models.supervised — DEBUG — Prototypes: [417, 345, 325, 274, 448, 409, 113, 55, 487, 403, 32, 302, 416, 463, 342, 457, 40, 50, 306, 447, 141, 295, 494, 480, 401, 96, 454, 497, 179, 115, 45, 485, 89, 38, 327, 493, 475, 166, 442, 281, 343, 151, 134, 65, 8, 405, 395, 21, 48, 201, 249, 474, 336, 175, 388, 396, 73, 319, 39, 195, 80, 434, 349, 142, 419, 66, 13, 24, 446, 233, 86, 374, 157, 352, 74, 188, 70, 37, 455, 88, 177, 500, 77, 14, 272, 190, 176, 107, 312, 3, 428, 404, 406, 186, 276, 333, 318, 286, 315, 340, 391, 310, 111, 414, 189, 97, 1, 462, 313, 178, 285, 202, 9, 232, 371, 466, 361, 472, 215, 358, 103, 489, 56, 320, 109, 381, 62, 219, 238, 7, 90, 53, 262, 278, 482, 331, 236, 289, 384, 483, 170, 273, 372, 217, 173, 129, 247, 353, 258, 506, 441, 444, 275, 477, 22, 301, 64, 246, 132, 365, 511, 259, 267, 131, 307, 364, 214, 394, 18, 72, 422, 294, 192, 298, 154, 449, 43, 467, 418, 257, 223, 193, 58, 335, 44, 203, 100, 174, 98, 380, 292, 71, 213, 82, 138, 347, 443, 458, 464, 225, 503, 83, 199, 512, 212, 473, 456, 94, 488, 377, 227, 91, 502, 87, 200].
2026-09-13 19:40:23,364 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:40:23,365 - opfython.models.supervised — INFO — Training time: 0.2993886470794678 seconds.
2026-09-13 19:40:23,366 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:40:23,448 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:40:23,449 - opfython.models.supervised — INFO — Prediction time: 0.08205866813659668 seconds.
2026-09-13 19:40:23,459 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:40:23,459 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:40:23,460 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:40:23,460 - opfython.core.opf — INFO — Class created.
2026-09-13 19:40:23,460 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:40:23,461 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:40:23,462 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:40:23,551 - opfython.models.supervised — DEBUG — Prototypes: [142, 39, 504, 168, 91, 173, 319, 207, 294, 11, 199, 176, 139, 388, 239, 481, 193, 80, 326, 42, 83, 472, 445, 246, 378, 15, 342, 155, 40, 236, 509, 25, 146, 73, 10, 108, 287, 125, 172, 51, 77, 17, 305, 281, 185, 157, 234, 259, 495, 233, 333, 407, 35, 34, 352, 455, 28, 52, 285, 330, 446, 138, 302, 494, 482, 238, 75, 334, 111, 56, 109, 405, 466, 150, 496, 36, 121, 416, 68, 290, 451, 440, 291, 420, 279, 86, 337, 493, 474, 353, 391, 235, 137, 478, 57, 132, 7, 8, 399, 23, 50, 497, 85, 283, 171, 355, 113, 1, 315, 257, 128, 22, 110, 428, 129, 74, 304, 351, 395, 271, 87, 240, 24, 184, 58, 6, 327, 195, 367, 99, 72, 269, 369, 377, 228, 296, 254, 364, 264, 169, 486, 442, 71, 480, 443, 286, 470, 358, 27, 112, 65, 372, 512, 318, 484, 164, 200, 253, 130, 427, 410, 288, 439, 370, 348, 223, 188, 127, 313, 414, 183, 265, 340, 393, 152, 262, 465, 417, 301, 189, 306, 243, 46, 60, 374, 135, 208, 379, 488, 170, 94, 216, 186, 81, 299, 49, 136, 357, 245, 441, 479, 400, 203, 221, 249, 456, 30, 145, 354, 477, 487, 88, 382, 241, 503, 84, 205, 345].
2026-09-13 19:40:23,738 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:40:23,739 - opfython.models.supervised — INFO — Training time: 0.277498722076416 seconds.
2026-09-13 19:40:23,739 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:40:23,822 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:40:23,824 - opfython.models.supervised — INFO — Prediction time: 0.08405876159667969 seconds.
2026-09-13 19:40:23,834 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:40:23,835 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:40:23,835 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:40:23,836 - opfython.core.opf — INFO — Class created.
2026-09-13 19:40:23,836 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:40:23,837 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:40:23,838 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:40:23,927 - opfython.models.supervised — DEBUG — Prototypes: [59, 114, 223, 486, 407, 36, 35, 350, 310, 419, 53, 313, 330, 138, 305, 494, 480, 236, 75, 405, 95, 151, 496, 174, 37, 123, 265, 157, 232, 422, 209, 48, 380, 484, 64, 453, 292, 88, 41, 333, 473, 282, 424, 446, 351, 152, 233, 136, 316, 111, 25, 51, 259, 86, 354, 263, 117, 2, 393, 400, 237, 139, 421, 66, 192, 79, 438, 356, 326, 42, 16, 28, 155, 27, 234, 359, 454, 508, 186, 147, 26, 73, 285, 70, 211, 11, 276, 112, 146, 290, 128, 227, 501, 52, 283, 184, 56, 87, 172, 107, 397, 18, 409, 450, 246, 325, 74, 161, 65, 8, 9, 399, 297, 321, 221, 96, 1, 461, 296, 12, 245, 377, 367, 4, 468, 142, 430, 39, 503, 170, 93, 176, 275, 385, 97, 364, 102, 490, 61, 194, 228, 250, 89, 239, 291, 481, 337, 249, 378, 225, 482, 166, 44, 164, 113, 131, 505, 445, 448, 71, 478, 198, 257, 441, 256, 449, 274, 200, 444, 3, 433, 411, 346, 288, 339, 122, 402, 370, 410, 220, 425, 187, 372, 512, 30, 342, 469, 47, 451, 213, 181, 202, 46, 255, 417, 271, 81, 303, 50, 384, 188, 218, 244, 447, 477, 401, 238, 110, 458, 463, 145, 429, 135, 467, 493, 488, 82, 251, 203, 513, 470, 457, 94, 382, 241, 487, 90, 502, 85, 205, 343].
2026-09-13 19:40:24,119 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:40:24,120 - opfython.models.supervised — INFO — Training time: 0.28309082984924316 seconds.
2026-09-13 19:40:24,121 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:40:24,203 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:40:24,204 - opfython.models.supervised — INFO — Prediction time: 0.08258557319641113 seconds.
2026-09-13 19:40:24,215 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:40:24,215 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:40:24,216 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:40:24,217 - opfython.core.opf — INFO — Class created.
2026-09-13 19:40:24,217 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:40:24,217 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:40:24,219 - opfython.models.supervised — DEBUG — Finding prototypes ...

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

Fase 1 MLP {'accuracy': 0.7222222222222222, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8), 'recall_0': np.float64(0.0), 'recall_1': np.float64(0.8813559322033898), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8387096774193549), 'f1_macro': 0.41935483870967744, 'f1_weighted': 0.6872759856630825, 'precision_macro': 0.4, 'recall_macro': 0.4406779661016949, 'balanced_accuracy': 0.4406779661016949, 'mcc': -0.15404159684748153, 'specificity': np.float64(0.0), 'sensitivity': np.float64(0.8813559322033898), 'TN': 0, 'FP': 13, 'FN': 7, 'TP': 52, 'score_source': 'continuous', 'auroc': 0.46088657105606257, 'ap_0': 0.17313150321495002, 'ap_1': 0.8150504556618142, 'scenario': 'baseline', 'model': 'MLP', 'outer_fold': 2, 'params': {'alpha': 0.01, 'hidden_layer_sizes': (32, 16), 'max_iter': 500}, 'inner_f1_macro': 0.5001603660000752}
Fase 1 LR {'accuracy': 0.8194444444444444, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8194444444444444), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.9007633587786259), 'f1_macro': 0.45038167938931295, 'f1_weighted': 0.7381255301102629, 'precision_macro': 0.4097222222222222, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 13, 'FN': 0, 'TP': 59, 'score_source': 'continuous', 'auroc': 0.4869621903520208, 'ap_0': 0.1809340907380465, 'ap_1': 0.8402175637030496, 'scenario': 'baseline', 'model': 'LR', 'outer_fold': 2, 'params': {'C': 0.01, 'max_iter': 1000, 'solver': 'lbfgs'}, 'inner_f1_macro': 0.44939986263058634}
Fase 1 XGB {'accuracy': 0.75, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8059701492537313), 'recall_0': np.float64(0.0), 'recall_1': np.float64(0.9152542372881356), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8571428571428571), 'f1_macro': 0.42857142857142855, 'f1_weighted': 0.7023809523809523, 'precision_macro': 0.40298507462686567, 'recall_macro': 0.4576271186440678, 'balanced_accuracy': 0.4576271186440678, 'mcc': -0.12823107147006824, 'specificity': np.float64(0.0), 'sensitivity': np.float64(0.9152542372881356), 'TN': 0, 'FP': 13, 'FN': 5, 'TP': 54, 'score_source': 'continuous', 'auroc': 0.46349413298565845, 'ap_0': 0.1730403566967615, 'ap_1': 0.837883728516501, 'scenario': 'baseline', 'model': 'XGB', 'outer_fold': 2, 'params': {'learning_rate': 0.05, 'max_depth': 5, 'n_estimators': 200}, 'inner_f1_macro': 0.4692457070517683}
Fase 1 NB {'accuracy': 0.6527777777777778, 'precision_0': np.float64(0.07142857142857142), 'precision_1': np.float64(0.7931034482758621), 'recall_0': np.float64(0.07692307692307693), 'recall_1': np.float64(0.7796610169491526), 'f1_0': np.float64(0.07407407407407407), 'f1_1': np.float64(0.7863247863247863), 'f1_macro': 0.4301994301994302, 'f1_weighted': 0.6577239632795188, 'precision_macro': 0.43226600985221675, 'recall_macro': 0.4282920469361148, 'balanced_accuracy': 0.4282920469361148, 'mcc': -0.13938530462494111, 'specificity': np.float64(0.07692307692307693), 'sensitivity': np.float64(0.7796610169491526), 'TN': 1, 'FP': 12, 'FN': 13, 'TP': 46, 'score_source': 'continuous', 'auroc': 0.41786179921773137, 'ap_0': 0.15512257663401427, 'ap_1': 0.8324130536043699, 'scenario': 'baseline', 'model': 'NB', 'outer_fold': 2, 'params': {'var_smoothing': 1e-11}, 'inner_f1_macro': 0.5369934702948976}

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(

Fase 1 NC {'accuracy': 0.4583333333333333, 'precision_0': np.float64(0.15789473684210525), 'precision_1': np.float64(0.7941176470588235), 'recall_0': np.float64(0.46153846153846156), 'recall_1': np.float64(0.4576271186440678), 'f1_0': np.float64(0.23529411764705882), 'f1_1': np.float64(0.5806451612903226), 'f1_macro': 0.4079696394686907, 'f1_weighted': 0.5182901117436222, 'precision_macro': 0.47600619195046434, 'recall_macro': 0.4595827900912647, 'balanced_accuracy': 0.4595827900912647, 'mcc': -0.062282028754625005, 'specificity': np.float64(0.46153846153846156), 'sensitivity': np.float64(0.4576271186440678), 'TN': 6, 'FP': 7, 'FN': 32, 'TP': 27, 'score_source': 'continuous', 'auroc': 0.423076923076923, 'ap_0': 0.15773407257148853, 'ap_1': 0.8168658162638602, 'scenario': 'baseline', 'model': 'NC', 'outer_fold': 2, 'params': {'metric': 'euclidean', 'shrink_threshold': None}, 'inner_f1_macro': 0.4867700777976296}
2026-09-13 19:40:55,735 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:40:55,735 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:40:55,736 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:40:55,736 - opfython.core.opf — INFO — Class created.
2026-09-13 19:40:55,737 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:40:55,737 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:40:55,739 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:40:55,823 - opfython.models.supervised — DEBUG — Prototypes: [318, 59, 416, 349, 47, 87, 86, 199, 487, 209, 64, 457, 83, 327, 271, 447, 116, 294, 300, 19, 415, 34, 33, 346, 464, 502, 127, 150, 74, 233, 94, 390, 338, 28, 88, 421, 247, 134, 500, 40, 190, 486, 240, 419, 275, 347, 128, 389, 159, 48, 452, 279, 70, 76, 334, 498, 140, 420, 401, 80, 381, 89, 478, 110, 364, 350, 303, 92, 397, 60, 428, 308, 84, 269, 20, 315, 175, 239, 108, 509, 207, 133, 356, 510, 453, 129, 22, 183, 61, 455, 8, 85, 123, 103, 195, 148, 69, 506, 44, 145, 220, 262, 372, 14, 254, 46, 68, 474, 322, 228, 117, 210, 58, 206, 25, 96, 257, 444, 62, 147, 321, 433, 107, 403, 311, 2, 293, 256, 5, 6, 396, 408, 472, 267, 298, 344, 393, 196, 431, 405, 443, 451, 283, 177, 9, 217, 345, 268, 120, 99, 363, 470, 144, 507, 286, 383, 152, 337, 223, 360, 467, 417, 439, 178, 157, 212, 78, 491, 361, 395, 151, 55, 378, 142, 484, 203, 227, 21, 158, 57, 299, 176, 260, 277, 441, 153, 479, 119, 130, 161, 198, 310, 244, 367, 77, 374, 432, 238, 250, 39, 186, 230, 377, 291, 362, 43, 282, 146, 290, 211, 143, 216, 115, 384, 301, 489, 497, 229, 174, 375, 184].
2026-09-13 19:40:56,001 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:40:56,002 - opfython.models.supervised — INFO — Training time: 0.2645912170410156 seconds.
2026-09-13 19:40:56,002 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:40:56,078 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:40:56,079 - opfython.models.supervised — INFO — Prediction time: 0.07645583152770996 seconds.
2026-09-13 19:40:56,088 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:40:56,088 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:40:56,088 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:40:56,089 - opfython.core.opf — INFO — Class created.
2026-09-13 19:40:56,089 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:40:56,090 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:40:56,091 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:40:56,172 - opfython.models.supervised — DEBUG — Prototypes: [312, 63, 341, 416, 322, 104, 52, 103, 211, 459, 151, 460, 39, 47, 301, 319, 447, 128, 292, 298, 17, 415, 29, 403, 28, 338, 465, 482, 400, 398, 141, 498, 386, 252, 173, 165, 89, 240, 435, 40, 329, 274, 217, 410, 232, 321, 419, 247, 253, 238, 456, 258, 441, 268, 81, 497, 59, 337, 95, 401, 178, 53, 339, 142, 124, 61, 6, 7, 393, 478, 357, 342, 336, 109, 394, 425, 18, 45, 304, 145, 282, 271, 246, 123, 106, 64, 220, 129, 230, 314, 37, 77, 475, 10, 446, 226, 370, 21, 113, 187, 261, 443, 66, 162, 429, 404, 68, 136, 65, 34, 457, 380, 284, 276, 510, 163, 80, 504, 69, 388, 12, 367, 228, 160, 14, 50, 307, 2, 291, 406, 295, 62, 208, 214, 486, 90, 1, 463, 266, 184, 308, 201, 164, 72, 33, 133, 426, 506, 159, 85, 285, 168, 94, 431, 354, 154, 376, 58, 392, 73, 485, 155, 277, 484, 440, 120, 302, 60, 452, 469, 417, 181, 297, 197, 175, 265, 210, 306, 250, 359, 364, 127, 361, 92, 428, 256, 200, 237, 375, 122, 206, 289, 442, 221, 299, 44, 158, 86, 84, 473, 236, 195, 384, 373, 191, 82, 74, 505, 324].
2026-09-13 19:40:56,350 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:40:56,351 - opfython.models.supervised — INFO — Training time: 0.2612624168395996 seconds.
2026-09-13 19:40:56,352 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:40:56,430 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:40:56,430 - opfython.models.supervised — INFO — Prediction time: 0.0784149169921875 seconds.
2026-09-13 19:40:56,439 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:40:56,440 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:40:56,440 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:40:56,440 - opfython.core.opf — INFO — Class created.
2026-09-13 19:40:56,441 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:40:56,441 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:40:56,442 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:40:56,524 - opfython.models.supervised — DEBUG — Prototypes: [86, 0, 91, 291, 9, 240, 465, 330, 314, 161, 349, 279, 130, 111, 35, 366, 470, 1, 83, 156, 294, 165, 337, 244, 322, 39, 77, 474, 126, 483, 231, 12, 442, 269, 109, 160, 321, 65, 445, 145, 141, 229, 360, 511, 25, 70, 67, 281, 8, 101, 133, 223, 80, 286, 505, 68, 319, 157, 113, 242, 272, 16, 266, 52, 324, 278, 173, 313, 497, 260, 199, 44, 454, 146, 228, 328, 486, 255, 361, 264, 457, 129, 49, 308, 326, 446, 125, 299, 407, 31, 303, 463, 350, 404, 402, 139, 499, 329, 183, 54, 102, 230, 69, 456, 99, 415, 283, 63, 32, 162, 467, 439, 276, 418, 61, 347, 92, 451, 288, 384, 405, 62, 333, 120, 5, 6, 397, 479, 55, 352, 306, 105, 398, 311, 100, 142, 23, 318, 48, 501, 159, 292, 280, 254, 118, 508, 27, 103, 409, 472, 427, 411, 441, 482, 220, 466, 416, 222, 449, 214, 348, 285, 480, 128, 198, 171, 396, 73, 60, 380, 485, 153, 24, 172, 302, 196, 115, 309, 224, 484, 124, 354, 143, 218, 98, 395, 21, 370, 428, 253, 261, 205, 248, 368, 267, 379, 43, 212, 47, 290, 158, 297, 232, 408, 320, 84, 180, 192, 387, 489, 56, 247, 251, 487, 194, 195, 81, 259, 383, 378, 186, 506, 332, 495].
2026-09-13 19:40:56,699 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:40:56,700 - opfython.models.supervised — INFO — Training time: 0.25807952880859375 seconds.
2026-09-13 19:40:56,700 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:40:56,777 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:40:56,778 - opfython.models.supervised — INFO — Prediction time: 0.0776529312133789 seconds.
2026-09-13 19:40:56,787 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:40:56,788 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:40:56,788 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:40:56,789 - opfython.core.opf — INFO — Class created.
2026-09-13 19:40:56,789 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:40:56,789 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:40:56,791 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:40:56,877 - opfython.models.supervised — DEBUG — Prototypes: [329, 104, 55, 103, 488, 319, 0, 229, 69, 128, 152, 497, 284, 51, 459, 42, 407, 35, 34, 347, 481, 404, 403, 138, 500, 36, 251, 439, 43, 390, 263, 168, 487, 265, 498, 46, 457, 147, 225, 245, 328, 421, 486, 258, 269, 348, 139, 389, 173, 56, 454, 290, 79, 90, 331, 496, 153, 422, 445, 150, 64, 6, 7, 106, 363, 468, 350, 309, 108, 398, 311, 102, 142, 257, 122, 507, 260, 288, 161, 24, 220, 70, 38, 146, 227, 356, 455, 510, 68, 283, 66, 202, 9, 417, 252, 317, 50, 394, 15, 374, 158, 511, 17, 270, 53, 282, 172, 67, 323, 40, 129, 242, 230, 13, 450, 240, 377, 27, 112, 181, 434, 408, 313, 2, 303, 429, 29, 105, 448, 425, 375, 433, 412, 294, 316, 213, 345, 211, 219, 362, 3, 469, 133, 115, 296, 385, 314, 162, 234, 330, 293, 10, 238, 466, 346, 88, 94, 463, 1, 334, 243, 447, 453, 480, 235, 485, 344, 397, 21, 380, 216, 93, 359, 492, 221, 247, 483, 289, 484, 195, 119, 444, 23, 144, 63, 127, 352, 155, 166, 478, 131, 197, 171, 143, 370, 126, 365, 215, 261, 312, 367, 91, 205, 249, 45, 340, 48, 292, 301, 446, 237, 157, 159, 300, 74, 84, 82, 458, 191, 490, 57, 495, 248, 193, 194, 80, 73, 504, 99].
2026-09-13 19:40:57,051 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:40:57,052 - opfython.models.supervised — INFO — Training time: 0.26212644577026367 seconds.
2026-09-13 19:40:57,052 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:40:57,130 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:40:57,131 - opfython.models.supervised — INFO — Prediction time: 0.07798194885253906 seconds.
2026-09-13 19:40:57,140 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:40:57,140 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:40:57,141 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:40:57,141 - opfython.core.opf — INFO — Class created.
2026-09-13 19:40:57,141 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:40:57,141 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:40:57,143 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:40:57,226 - opfython.models.supervised — DEBUG — Prototypes: [315, 57, 418, 349, 325, 177, 216, 64, 461, 95, 462, 36, 408, 120, 26, 44, 304, 322, 449, 299, 417, 108, 407, 405, 457, 392, 249, 163, 156, 84, 27, 238, 439, 438, 203, 212, 232, 419, 499, 40, 458, 401, 279, 334, 347, 131, 391, 168, 309, 344, 90, 77, 33, 329, 497, 454, 92, 420, 445, 384, 53, 99, 118, 55, 365, 479, 58, 429, 16, 42, 288, 273, 136, 214, 455, 511, 31, 194, 59, 459, 65, 18, 274, 62, 8, 6, 97, 125, 281, 512, 155, 76, 505, 63, 313, 43, 228, 265, 373, 271, 167, 311, 73, 56, 230, 60, 260, 226, 376, 448, 435, 22, 154, 193, 318, 410, 475, 508, 296, 345, 396, 202, 24, 211, 205, 85, 89, 466, 287, 189, 7, 224, 470, 308, 220, 346, 272, 107, 151, 507, 364, 474, 2, 81, 159, 332, 394, 88, 491, 362, 399, 68, 52, 17, 166, 54, 298, 209, 234, 485, 282, 444, 122, 351, 446, 453, 481, 398, 15, 370, 113, 305, 188, 266, 480, 134, 96, 434, 173, 243, 253, 39, 368, 169, 381, 433, 153, 199, 293, 262, 223, 300, 152, 259, 82, 80, 198, 338, 185, 390, 478, 207, 490, 496, 48, 213, 379, 180, 187, 339, 78, 250, 506, 328].
2026-09-13 19:40:57,399 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:40:57,400 - opfython.models.supervised — INFO — Training time: 0.25771474838256836 seconds.
2026-09-13 19:40:57,400 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:40:57,475 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:40:57,476 - opfython.models.supervised — INFO — Prediction time: 0.07469582557678223 seconds.
2026-09-13 19:40:57,485 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:40:57,485 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:40:57,486 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:40:57,487 - opfython.core.opf — INFO — Class created.
2026-09-13 19:40:57,487 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:40:57,488 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:40:57,492 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:40:57,575 - opfython.models.supervised — DEBUG — Prototypes: [318, 59, 416, 349, 47, 87, 86, 199, 487, 209, 64, 457, 83, 300, 34, 415, 33, 346, 464, 327, 305, 447, 116, 294, 100, 502, 127, 150, 74, 233, 94, 247, 134, 500, 40, 486, 452, 279, 70, 76, 334, 498, 140, 420, 401, 80, 381, 347, 389, 128, 159, 48, 89, 110, 478, 350, 303, 92, 308, 84, 20, 269, 315, 14, 46, 133, 298, 207, 356, 453, 510, 160, 22, 183, 61, 455, 8, 85, 123, 412, 148, 69, 506, 44, 103, 195, 393, 12, 372, 220, 68, 474, 322, 113, 25, 117, 210, 206, 58, 11, 311, 2, 433, 403, 275, 338, 147, 82, 321, 344, 283, 177, 9, 217, 120, 99, 363, 470, 144, 507, 152, 62, 257, 337, 223, 21, 158, 78, 491, 361, 378, 200, 395, 212, 203, 191, 227, 484, 142, 364, 268, 60, 145, 444, 274, 240, 357, 390, 397, 196, 28, 88, 176, 260, 472, 509, 239, 108, 57, 267, 432, 238, 428, 277, 441, 5, 396, 6, 408, 431, 443, 293, 286, 383, 451, 421, 161, 198, 310, 244, 367, 251, 467, 417, 341, 439, 186, 105, 162, 299, 489, 497, 39, 250, 178, 157, 146, 445, 377, 43, 193, 479, 398, 50, 291, 259, 216, 442, 67, 229, 471, 473, 37, 115, 384, 375, 184, 174, 342].
2026-09-13 19:40:57,753 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:40:57,754 - opfython.models.supervised — INFO — Training time: 0.26503467559814453 seconds.
2026-09-13 19:40:57,754 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:40:57,828 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:40:57,829 - opfython.models.supervised — INFO — Prediction time: 0.07411313056945801 seconds.
2026-09-13 19:40:57,837 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:40:57,838 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:40:57,838 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:40:57,838 - opfython.core.opf — INFO — Class created.
2026-09-13 19:40:57,839 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:40:57,839 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:40:57,840 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:40:57,921 - opfython.models.supervised — DEBUG — Prototypes: [312, 63, 341, 416, 322, 104, 52, 103, 403, 29, 28, 338, 465, 298, 415, 460, 24, 47, 301, 319, 447, 128, 292, 482, 151, 459, 116, 498, 141, 400, 433, 165, 89, 240, 435, 217, 410, 232, 321, 419, 253, 337, 95, 81, 36, 497, 152, 441, 401, 178, 53, 478, 124, 61, 339, 142, 6, 7, 393, 342, 336, 109, 18, 45, 500, 79, 271, 161, 220, 129, 230, 314, 37, 77, 475, 21, 446, 226, 10, 62, 370, 68, 136, 65, 34, 457, 380, 276, 510, 163, 80, 504, 284, 388, 12, 367, 228, 14, 50, 307, 2, 162, 99, 304, 249, 406, 429, 404, 214, 69, 238, 133, 426, 33, 506, 159, 85, 164, 308, 168, 201, 90, 463, 1, 94, 315, 354, 376, 58, 392, 73, 222, 277, 484, 66, 261, 72, 357, 285, 282, 485, 155, 154, 64, 160, 386, 173, 394, 247, 351, 258, 440, 106, 443, 273, 246, 123, 361, 512, 274, 329, 425, 334, 115, 397, 265, 210, 3, 306, 359, 208, 250, 291, 180, 120, 302, 452, 156, 469, 417, 122, 181, 297, 200, 121, 364, 225, 197, 175, 289, 387, 375, 486, 44, 206, 442, 158, 236, 473, 474, 195, 373, 191, 82, 74, 505, 78].
2026-09-13 19:40:58,094 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:40:58,095 - opfython.models.supervised — INFO — Training time: 0.2553708553314209 seconds.
2026-09-13 19:40:58,095 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:40:58,170 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:40:58,171 - opfython.models.supervised — INFO — Prediction time: 0.0753624439239502 seconds.
2026-09-13 19:40:58,180 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:40:58,180 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:40:58,180 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:40:58,181 - opfython.core.opf — INFO — Class created.
2026-09-13 19:40:58,181 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:40:58,182 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:40:58,183 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:40:58,265 - opfython.models.supervised — DEBUG — Prototypes: [86, 0, 91, 291, 9, 240, 465, 330, 314, 161, 130, 111, 156, 83, 366, 470, 1, 165, 322, 39, 77, 474, 126, 483, 231, 12, 25, 134, 145, 229, 360, 511, 174, 67, 8, 101, 133, 286, 113, 223, 242, 272, 278, 173, 52, 80, 16, 313, 160, 96, 49, 282, 326, 446, 125, 299, 496, 457, 41, 303, 22, 31, 407, 463, 350, 402, 404, 467, 139, 499, 230, 69, 329, 183, 54, 219, 102, 488, 456, 99, 32, 162, 415, 283, 112, 63, 260, 146, 497, 228, 328, 199, 44, 454, 486, 439, 95, 418, 61, 347, 92, 451, 288, 384, 405, 120, 62, 333, 479, 55, 5, 6, 397, 352, 306, 105, 311, 100, 23, 159, 48, 501, 280, 79, 409, 57, 68, 321, 292, 318, 65, 269, 337, 244, 449, 396, 73, 60, 380, 491, 24, 172, 233, 224, 210, 485, 153, 279, 294, 35, 42, 157, 255, 361, 264, 196, 472, 442, 284, 27, 103, 398, 109, 254, 118, 508, 115, 309, 220, 428, 253, 222, 505, 427, 411, 344, 441, 482, 214, 273, 368, 218, 395, 21, 285, 377, 268, 447, 341, 154, 466, 416, 205, 169, 43, 198, 171, 158, 443, 379, 489, 267, 383, 47, 212, 124, 354, 262, 480, 74, 37, 471, 247, 192, 478, 378, 186, 506, 78, 194, 342, 81, 226].
2026-09-13 19:40:58,435 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:40:58,435 - opfython.models.supervised — INFO — Training time: 0.25336575508117676 seconds.
2026-09-13 19:40:58,436 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:40:58,508 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:40:58,509 - opfython.models.supervised — INFO — Prediction time: 0.07270002365112305 seconds.
2026-09-13 19:40:58,518 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:40:58,518 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:40:58,518 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:40:58,519 - opfython.core.opf — INFO — Class created.
2026-09-13 19:40:58,519 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:40:58,520 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:40:58,521 - opfython.models.supervised — DEBUG — Finding prototypes ...

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

Fase 1 MLP {'accuracy': 0.7222222222222222, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8), 'recall_0': np.float64(0.0), 'recall_1': np.float64(0.8813559322033898), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8387096774193549), 'f1_macro': 0.41935483870967744, 'f1_weighted': 0.6872759856630825, 'precision_macro': 0.4, 'recall_macro': 0.4406779661016949, 'balanced_accuracy': 0.4406779661016949, 'mcc': -0.15404159684748153, 'specificity': np.float64(0.0), 'sensitivity': np.float64(0.8813559322033898), 'TN': 0, 'FP': 13, 'FN': 7, 'TP': 52, 'score_source': 'continuous', 'auroc': 0.46740547588005216, 'ap_0': 0.17199575757620914, 'ap_1': 0.8143448451350238, 'scenario': 'baseline', 'model': 'MLP', 'outer_fold': 3, 'params': {'alpha': 0.0001, 'hidden_layer_sizes': (32, 16), 'max_iter': 500}, 'inner_f1_macro': 0.48867450356202974}
Fase 1 LR {'accuracy': 0.8194444444444444, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8194444444444444), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.9007633587786259), 'f1_macro': 0.45038167938931295, 'f1_weighted': 0.7381255301102629, 'precision_macro': 0.4097222222222222, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 13, 'FN': 0, 'TP': 59, 'score_source': 'continuous', 'auroc': 0.43481095176010426, 'ap_0': 0.16429283596646566, 'ap_1': 0.7880284903186123, 'scenario': 'baseline', 'model': 'LR', 'outer_fold': 3, 'params': {'C': 1, 'max_iter': 1000, 'solver': 'lbfgs'}, 'inner_f1_macro': 0.4563639110137556}
Fase 1 XGB {'accuracy': 0.7083333333333334, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.796875), 'recall_0': np.float64(0.0), 'recall_1': np.float64(0.864406779661017), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8292682926829268), 'f1_macro': 0.4146341463414634, 'f1_weighted': 0.6795392953929539, 'precision_macro': 0.3984375, 'recall_macro': 0.4322033898305085, 'balanced_accuracy': 0.4322033898305085, 'mcc': -0.16595894938615371, 'specificity': np.float64(0.0), 'sensitivity': np.float64(0.864406779661017), 'TN': 0, 'FP': 13, 'FN': 8, 'TP': 51, 'score_source': 'continuous', 'auroc': 0.4230769230769231, 'ap_0': 0.15716423829209777, 'ap_1': 0.8248296523296242, 'scenario': 'baseline', 'model': 'XGB', 'outer_fold': 3, 'params': {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}, 'inner_f1_macro': 0.4800109702560686}
Fase 1 NB {'accuracy': 0.4861111111111111, 'precision_0': np.float64(0.16666666666666666), 'precision_1': np.float64(0.8055555555555556), 'recall_0': np.float64(0.46153846153846156), 'recall_1': np.float64(0.4915254237288136), 'f1_0': np.float64(0.24489795918367346), 'f1_1': np.float64(0.6105263157894737), 'f1_macro': 0.42771213748657355, 'f1_weighted': 0.5445100847356487, 'precision_macro': 0.4861111111111111, 'recall_macro': 0.4765319426336376, 'balanced_accuracy': 0.4765319426336376, 'mcc': -0.036107907233705945, 'specificity': np.float64(0.46153846153846156), 'sensitivity': np.float64(0.4915254237288136), 'TN': 6, 'FP': 7, 'FN': 30, 'TP': 29, 'score_source': 'continuous', 'auroc': 0.4661016949152542, 'ap_0': 0.17482626533629878, 'ap_1': 0.8058092467349373, 'scenario': 'baseline', 'model': 'NB', 'outer_fold': 3, 'params': {'var_smoothing': 1e-09}, 'inner_f1_macro': 0.45343312788807466}

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(

Fase 1 NC {'accuracy': 0.5, 'precision_0': np.float64(0.17142857142857143), 'precision_1': np.float64(0.8108108108108109), 'recall_0': np.float64(0.46153846153846156), 'recall_1': np.float64(0.5084745762711864), 'f1_0': np.float64(0.25), 'f1_1': np.float64(0.625), 'f1_macro': 0.4375, 'f1_weighted': 0.5572916666666666, 'precision_macro': 0.4911196911196911, 'recall_macro': 0.485006518904824, 'balanced_accuracy': 0.485006518904824, 'mcc': -0.023077845940748878, 'specificity': np.float64(0.46153846153846156), 'sensitivity': np.float64(0.5084745762711864), 'TN': 6, 'FP': 7, 'FN': 29, 'TP': 30, 'score_source': 'continuous', 'auroc': 0.4465449804432855, 'ap_0': 0.16640170741422883, 'ap_1': 0.7943383158263054, 'scenario': 'baseline', 'model': 'NC', 'outer_fold': 3, 'params': {'metric': 'euclidean', 'shrink_threshold': None}, 'inner_f1_macro': 0.4733812383313373}
2026-09-13 19:41:38,549 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:41:38,550 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:41:38,550 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:41:38,550 - opfython.core.opf — INFO — Class created.
2026-09-13 19:41:38,551 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:41:38,551 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:41:38,553 - opfython.models.supervised — DEBUG — Finding prototypes ...

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(

2026-09-13 19:41:38,678 - opfython.models.supervised — DEBUG — Prototypes: [416, 353, 455, 91, 218, 93, 116, 23, 47, 32, 282, 305, 126, 22, 401, 35, 121, 80, 275, 399, 398, 452, 499, 36, 160, 437, 245, 436, 256, 387, 165, 31, 95, 251, 419, 43, 453, 396, 263, 276, 440, 290, 421, 350, 85, 380, 352, 386, 138, 216, 124, 120, 96, 479, 53, 313, 366, 24, 323, 501, 260, 253, 474, 189, 158, 317, 141, 296, 280, 250, 118, 507, 67, 329, 37, 174, 240, 212, 74, 473, 127, 417, 219, 62, 357, 12, 445, 231, 29, 308, 328, 159, 83, 266, 103, 442, 66, 433, 402, 26, 133, 144, 217, 359, 140, 281, 64, 195, 9, 270, 92, 68, 14, 246, 204, 286, 113, 46, 324, 351, 156, 441, 65, 16, 332, 50, 278, 169, 450, 320, 2, 304, 404, 307, 7, 403, 471, 205, 203, 210, 431, 407, 184, 18, 208, 130, 429, 108, 78, 155, 295, 191, 10, 229, 464, 279, 81, 84, 460, 1, 162, 340, 236, 481, 394, 21, 164, 268, 54, 489, 330, 89, 423, 378, 364, 207, 70, 25, 168, 309, 211, 365, 483, 287, 123, 355, 269, 190, 345, 42, 143, 277, 480, 142, 122, 196, 242, 432, 261, 300, 425, 186, 456, 302, 377, 187, 201, 361, 228, 157, 301, 220, 310, 45, 154, 294, 487, 495, 241, 57, 215].
2026-09-13 19:41:38,896 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:41:38,897 - opfython.models.supervised — INFO — Training time: 0.34569454193115234 seconds.
2026-09-13 19:41:38,898 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:41:39,016 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:41:39,017 - opfython.models.supervised — INFO — Prediction time: 0.11841154098510742 seconds.
2026-09-13 19:41:39,030 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:41:39,031 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:41:39,032 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:41:39,032 - opfython.core.opf — INFO — Class created.
2026-09-13 19:41:39,033 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:41:39,034 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:41:39,036 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:41:39,150 - opfython.models.supervised — DEBUG — Prototypes: [318, 68, 346, 416, 326, 111, 55, 109, 487, 456, 108, 401, 33, 464, 344, 457, 27, 323, 281, 20, 482, 140, 275, 398, 96, 150, 498, 179, 435, 251, 42, 262, 496, 46, 371, 160, 486, 89, 329, 399, 102, 191, 56, 345, 383, 113, 65, 132, 8, 403, 391, 310, 22, 176, 49, 264, 279, 203, 258, 475, 338, 313, 153, 294, 384, 392, 261, 421, 429, 402, 141, 417, 227, 66, 434, 82, 12, 87, 317, 444, 238, 158, 352, 74, 77, 71, 152, 454, 210, 280, 285, 125, 178, 88, 75, 174, 440, 72, 15, 54, 449, 79, 4, 342, 314, 240, 3, 404, 69, 304, 506, 256, 131, 441, 422, 73, 283, 349, 198, 236, 216, 465, 367, 293, 205, 343, 278, 297, 37, 97, 462, 1, 413, 188, 333, 243, 480, 270, 390, 83, 218, 375, 484, 171, 90, 229, 356, 57, 489, 321, 95, 106, 204, 127, 311, 14, 121, 395, 483, 286, 137, 348, 389, 19, 364, 45, 337, 478, 143, 217, 107, 259, 193, 306, 136, 192, 58, 428, 195, 424, 154, 167, 458, 201, 213, 129, 301, 490, 353, 492, 235, 466, 228, 175, 300, 307, 93, 92, 67, 474, 60, 224, 502, 376].
2026-09-13 19:41:39,382 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:41:39,383 - opfython.models.supervised — INFO — Training time: 0.34848856925964355 seconds.
2026-09-13 19:41:39,384 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:41:39,490 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:41:39,490 - opfython.models.supervised — INFO — Prediction time: 0.1060340404510498 seconds.
2026-09-13 19:41:39,502 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:41:39,503 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:41:39,504 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:41:39,505 - opfython.core.opf — INFO — Class created.
2026-09-13 19:41:39,505 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:41:39,506 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:41:39,508 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:41:39,612 - opfython.models.supervised — DEBUG — Prototypes: [300, 10, 337, 354, 142, 117, 169, 504, 90, 304, 40, 175, 413, 182, 194, 81, 432, 359, 84, 473, 139, 416, 242, 14, 443, 248, 27, 329, 114, 278, 441, 72, 156, 133, 362, 450, 506, 26, 77, 74, 290, 9, 106, 79, 16, 294, 173, 75, 52, 170, 122, 19, 331, 398, 287, 184, 213, 269, 505, 376, 261, 363, 455, 141, 332, 308, 138, 405, 132, 462, 355, 484, 402, 400, 149, 496, 241, 76, 336, 108, 57, 229, 454, 105, 415, 291, 69, 325, 37, 433, 258, 125, 23, 107, 45, 29, 109, 387, 267, 180, 342, 293, 186, 58, 239, 136, 353, 101, 86, 42, 339, 495, 475, 163, 438, 296, 419, 403, 383, 130, 67, 7, 407, 395, 479, 315, 70, 24, 51, 263, 208, 474, 347, 319, 151, 301, 289, 43, 350, 471, 226, 203, 21, 427, 409, 440, 449, 482, 230, 245, 224, 480, 140, 279, 394, 13, 485, 165, 365, 380, 59, 104, 93, 420, 25, 312, 234, 254, 209, 123, 316, 17, 177, 87, 346, 47, 134, 370, 228, 321, 265, 275, 152, 135, 357, 428, 192, 273, 217, 257, 423, 456, 379, 490, 307, 171, 305, 464, 145, 206, 513, 91, 89, 327, 453, 50, 299, 168, 131, 488, 60, 494, 256, 503, 381].
2026-09-13 19:41:39,825 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:41:39,826 - opfython.models.supervised — INFO — Training time: 0.31897902488708496 seconds.
2026-09-13 19:41:39,826 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:41:39,916 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:41:39,917 - opfython.models.supervised — INFO — Prediction time: 0.09061264991760254 seconds.
2026-09-13 19:41:39,928 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:41:39,929 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:41:39,929 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:41:39,929 - opfython.core.opf — INFO — Class created.
2026-09-13 19:41:39,930 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:41:39,930 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:41:39,932 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:41:40,034 - opfython.models.supervised — DEBUG — Prototypes: [325, 69, 333, 293, 196, 411, 450, 109, 60, 240, 76, 37, 405, 457, 141, 54, 292, 449, 137, 312, 497, 150, 128, 465, 110, 437, 262, 439, 115, 174, 95, 111, 273, 353, 495, 48, 377, 158, 485, 269, 421, 277, 354, 151, 185, 61, 443, 300, 422, 163, 88, 335, 473, 404, 162, 66, 477, 8, 407, 397, 316, 350, 237, 365, 466, 429, 304, 291, 268, 131, 505, 112, 32, 419, 138, 193, 81, 438, 356, 328, 43, 67, 15, 327, 172, 30, 117, 280, 250, 101, 448, 434, 406, 212, 10, 108, 71, 213, 456, 156, 238, 453, 153, 146, 27, 74, 263, 296, 124, 173, 87, 75, 56, 53, 252, 285, 20, 331, 57, 290, 183, 320, 3, 311, 445, 72, 452, 348, 351, 392, 221, 230, 433, 410, 387, 341, 180, 294, 223, 408, 203, 21, 374, 248, 463, 142, 121, 171, 503, 92, 307, 40, 96, 102, 1, 339, 254, 416, 182, 480, 228, 395, 24, 242, 89, 396, 282, 82, 227, 483, 167, 490, 62, 329, 94, 424, 7, 233, 257, 482, 297, 208, 126, 18, 225, 319, 26, 478, 140, 378, 370, 278, 380, 491, 310, 493, 360, 241, 314, 214, 184, 84, 513, 206, 218, 135, 93, 91, 68, 51, 170, 259, 488, 494, 502, 132, 381].
2026-09-13 19:41:40,247 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:41:40,249 - opfython.models.supervised — INFO — Training time: 0.31768107414245605 seconds.
2026-09-13 19:41:40,249 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:41:40,338 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:41:40,339 - opfython.models.supervised — INFO — Prediction time: 0.0886528491973877 seconds.
2026-09-13 19:41:40,351 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:41:40,352 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:41:40,352 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:41:40,353 - opfython.core.opf — INFO — Class created.
2026-09-13 19:41:40,353 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:41:40,354 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:41:40,356 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:41:40,459 - opfython.models.supervised — DEBUG — Prototypes: [322, 63, 418, 354, 332, 189, 51, 102, 458, 156, 226, 72, 466, 352, 459, 140, 328, 18, 286, 304, 280, 405, 403, 141, 471, 122, 19, 103, 169, 470, 438, 31, 109, 262, 496, 43, 377, 151, 486, 254, 419, 267, 361, 289, 340, 281, 444, 293, 421, 84, 495, 349, 97, 384, 406, 353, 142, 180, 317, 223, 130, 337, 105, 390, 125, 60, 479, 429, 20, 46, 256, 145, 344, 313, 253, 194, 507, 128, 325, 37, 187, 78, 439, 358, 81, 476, 61, 227, 222, 446, 271, 68, 435, 123, 66, 285, 456, 22, 175, 144, 70, 7, 101, 75, 11, 248, 83, 168, 350, 316, 2, 303, 167, 201, 324, 164, 509, 408, 283, 178, 58, 475, 64, 306, 91, 465, 96, 296, 8, 236, 468, 333, 351, 284, 133, 430, 34, 505, 163, 87, 297, 170, 416, 176, 338, 392, 209, 215, 298, 397, 490, 79, 214, 382, 484, 160, 21, 177, 307, 218, 242, 483, 291, 12, 85, 229, 121, 310, 25, 485, 212, 315, 258, 268, 396, 17, 370, 129, 146, 202, 245, 434, 185, 265, 376, 364, 106, 427, 381, 301, 67, 493, 371, 165, 300, 235, 362, 469, 460, 356, 88, 86, 45, 295, 244, 488, 52, 478, 54, 504, 124].
2026-09-13 19:41:40,671 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:41:40,672 - opfython.models.supervised — INFO — Training time: 0.3175530433654785 seconds.
2026-09-13 19:41:40,673 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:41:40,763 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:41:40,763 - opfython.models.supervised — INFO — Prediction time: 0.09043431282043457 seconds.
2026-09-13 19:41:40,776 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:41:40,777 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:41:40,777 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:41:40,778 - opfython.core.opf — INFO — Class created.
2026-09-13 19:41:40,778 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:41:40,779 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:41:40,780 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:41:40,880 - opfython.models.supervised — DEBUG — Prototypes: [416, 353, 455, 91, 218, 334, 116, 23, 47, 282, 333, 446, 126, 305, 401, 121, 462, 399, 80, 452, 499, 160, 36, 245, 437, 436, 93, 43, 453, 440, 290, 421, 276, 350, 85, 380, 352, 138, 216, 124, 96, 386, 479, 53, 120, 24, 158, 501, 280, 189, 253, 474, 387, 395, 67, 329, 37, 174, 240, 212, 74, 473, 127, 417, 219, 62, 12, 29, 357, 445, 231, 26, 133, 144, 217, 359, 506, 281, 64, 195, 9, 92, 286, 113, 46, 68, 14, 246, 204, 278, 169, 50, 76, 16, 159, 88, 320, 233, 2, 433, 402, 404, 165, 170, 328, 296, 323, 351, 391, 205, 324, 81, 1, 460, 84, 295, 10, 229, 464, 337, 130, 429, 108, 78, 155, 162, 340, 236, 66, 266, 25, 168, 54, 330, 378, 207, 268, 389, 211, 200, 287, 483, 279, 251, 360, 263, 156, 441, 65, 481, 471, 7, 407, 403, 507, 31, 95, 442, 250, 118, 208, 432, 431, 184, 428, 347, 203, 210, 106, 397, 277, 394, 21, 164, 304, 269, 314, 190, 18, 128, 142, 448, 196, 115, 345, 42, 487, 495, 261, 157, 443, 302, 57, 215, 377, 425, 186, 123, 355, 228, 187, 201, 480, 45, 161, 294, 456, 72, 465, 363, 241, 472, 132, 202].
2026-09-13 19:41:41,096 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:41:41,097 - opfython.models.supervised — INFO — Training time: 0.31820058822631836 seconds.
2026-09-13 19:41:41,098 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:41:41,193 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:41:41,193 - opfython.models.supervised — INFO — Prediction time: 0.09498357772827148 seconds.
2026-09-13 19:41:41,205 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:41:41,205 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:41:41,206 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:41:41,206 - opfython.core.opf — INFO — Class created.
2026-09-13 19:41:41,207 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:41:41,207 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:41:41,209 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:41:41,312 - opfython.models.supervised — DEBUG — Prototypes: [318, 68, 346, 416, 326, 111, 55, 109, 487, 456, 108, 401, 134, 464, 344, 457, 144, 323, 20, 281, 482, 140, 275, 398, 96, 150, 498, 179, 435, 251, 262, 496, 160, 46, 371, 486, 276, 89, 329, 495, 476, 39, 399, 102, 191, 56, 345, 383, 113, 132, 65, 8, 403, 391, 22, 176, 49, 279, 203, 258, 475, 338, 264, 384, 392, 285, 178, 88, 74, 77, 158, 225, 352, 450, 152, 10, 71, 280, 454, 210, 15, 54, 434, 82, 141, 417, 227, 66, 12, 444, 238, 87, 317, 177, 209, 79, 4, 314, 3, 404, 429, 402, 75, 342, 387, 293, 327, 367, 236, 465, 216, 97, 1, 462, 270, 90, 229, 57, 489, 321, 95, 375, 356, 218, 83, 390, 14, 286, 483, 294, 310, 484, 171, 278, 297, 37, 42, 174, 125, 69, 440, 72, 480, 204, 272, 506, 333, 243, 127, 311, 256, 131, 283, 349, 428, 308, 198, 425, 121, 395, 73, 422, 389, 19, 421, 192, 217, 107, 259, 372, 413, 188, 441, 446, 129, 313, 193, 306, 364, 237, 45, 337, 136, 206, 175, 98, 301, 423, 200, 424, 137, 348, 377, 60, 224, 235, 478, 394, 439, 201, 213, 466, 458, 85, 473, 67, 228, 474, 38].
2026-09-13 19:41:41,528 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:41:41,529 - opfython.models.supervised — INFO — Training time: 0.32111310958862305 seconds.
2026-09-13 19:41:41,529 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:41:41,627 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:41:41,628 - opfython.models.supervised — INFO — Prediction time: 0.09785676002502441 seconds.
2026-09-13 19:41:41,639 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:41:41,640 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:41:41,640 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:41:41,641 - opfython.core.opf — INFO — Class created.
2026-09-13 19:41:41,642 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:41:41,642 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:41:41,645 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:41:41,751 - opfython.models.supervised — DEBUG — Prototypes: [9, 106, 26, 77, 156, 362, 450, 506, 74, 294, 122, 173, 52, 79, 16, 250, 283, 19, 287, 184, 139, 343, 242, 416, 194, 81, 432, 359, 84, 473, 27, 329, 443, 248, 14, 263, 474, 208, 347, 51, 24, 498, 289, 172, 163, 438, 296, 419, 86, 339, 353, 101, 383, 403, 186, 58, 239, 136, 67, 130, 479, 7, 407, 395, 455, 141, 332, 308, 138, 405, 132, 462, 355, 484, 241, 76, 336, 108, 57, 229, 454, 105, 402, 94, 149, 496, 37, 433, 258, 415, 291, 69, 325, 269, 213, 387, 396, 201, 180, 125, 23, 107, 75, 226, 301, 323, 142, 117, 169, 504, 90, 300, 10, 337, 175, 72, 278, 279, 59, 104, 93, 196, 420, 25, 183, 380, 365, 17, 394, 234, 221, 254, 398, 485, 165, 319, 45, 304, 40, 13, 70, 170, 358, 293, 342, 29, 109, 209, 261, 363, 471, 441, 123, 316, 230, 428, 427, 409, 203, 350, 440, 482, 228, 2, 321, 265, 449, 377, 413, 182, 275, 152, 346, 47, 217, 124, 224, 205, 188, 312, 307, 245, 273, 134, 370, 211, 382, 171, 442, 379, 135, 357, 480, 464, 456, 50, 174, 299, 206, 513, 256, 470, 488, 310, 494, 41, 145, 21, 453, 91, 222, 503, 85].
2026-09-13 19:41:41,983 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:41:41,983 - opfython.models.supervised — INFO — Training time: 0.34027957916259766 seconds.
2026-09-13 19:41:41,986 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:41:42,081 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:41:42,082 - opfython.models.supervised — INFO — Prediction time: 0.09525442123413086 seconds.
2026-09-13 19:41:42,093 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:41:42,094 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:41:42,095 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:41:42,095 - opfython.core.opf — INFO — Class created.
2026-09-13 19:41:42,096 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:41:42,096 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:41:42,099 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:41:42,200 - opfython.models.supervised — DEBUG — Prototypes: [325, 69, 333, 293, 196, 411, 450, 109, 60, 226, 486, 240, 76, 36, 54, 25, 292, 312, 137, 33, 457, 288, 405, 37, 497, 150, 439, 262, 174, 95, 115, 111, 273, 353, 495, 158, 48, 377, 485, 354, 151, 185, 61, 88, 42, 335, 473, 163, 443, 300, 422, 350, 217, 477, 419, 138, 193, 81, 438, 356, 328, 43, 67, 15, 30, 156, 29, 238, 453, 153, 181, 27, 74, 71, 456, 213, 10, 108, 296, 124, 173, 87, 53, 263, 392, 17, 290, 183, 20, 57, 320, 252, 3, 172, 105, 434, 406, 128, 465, 110, 162, 66, 8, 407, 397, 327, 75, 304, 323, 351, 250, 448, 96, 1, 102, 248, 463, 142, 430, 121, 40, 503, 171, 92, 416, 182, 267, 339, 254, 396, 18, 82, 227, 490, 62, 329, 94, 195, 424, 233, 257, 7, 242, 89, 26, 297, 482, 483, 167, 466, 117, 194, 237, 321, 307, 269, 359, 277, 208, 284, 505, 445, 72, 480, 112, 32, 268, 131, 126, 228, 387, 180, 223, 375, 433, 410, 294, 341, 203, 348, 119, 400, 221, 230, 225, 4, 319, 278, 311, 395, 24, 186, 378, 279, 344, 469, 168, 205, 214, 127, 446, 488, 494, 209, 310, 389, 380, 427, 478, 399, 444, 206, 218, 241, 107, 51, 175, 84, 259, 68, 468, 470, 135, 21, 145, 219, 502, 86].
2026-09-13 19:41:42,410 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:41:42,411 - opfython.models.supervised — INFO — Training time: 0.3134002685546875 seconds.
2026-09-13 19:41:42,411 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:41:42,505 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:41:42,506 - opfython.models.supervised — INFO — Prediction time: 0.09468460083007812 seconds.
2026-09-13 19:41:42,519 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:41:42,520 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:41:42,520 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:41:42,521 - opfython.core.opf — INFO — Class created.
2026-09-13 19:41:42,521 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:41:42,522 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:41:42,523 - opfython.models.supervised — DEBUG — Finding prototypes ...

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

Fase 1 MLP {'accuracy': 0.7777777777777778, 'precision_0': np.float64(0.25), 'precision_1': np.float64(0.8088235294117647), 'recall_0': np.float64(0.07142857142857142), 'recall_1': np.float64(0.9482758620689655), 'f1_0': np.float64(0.1111111111111111), 'f1_1': np.float64(0.873015873015873), 'f1_macro': 0.4920634920634921, 'f1_weighted': 0.7248677248677249, 'precision_macro': 0.5294117647058824, 'recall_macro': 0.5098522167487685, 'balanced_accuracy': 0.5098522167487685, 'mcc': 0.03404532748240977, 'specificity': np.float64(0.07142857142857142), 'sensitivity': np.float64(0.9482758620689655), 'TN': 1, 'FP': 13, 'FN': 3, 'TP': 55, 'score_source': 'continuous', 'auroc': 0.583743842364532, 'ap_0': 0.2519930028505869, 'ap_1': 0.8700136316772343, 'scenario': 'baseline', 'model': 'MLP', 'outer_fold': 4, 'params': {'alpha': 0.01, 'hidden_layer_sizes': (32,), 'max_iter': 500}, 'inner_f1_macro': 0.4700020281751609}
Fase 1 LR {'accuracy': 0.8055555555555556, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8055555555555556), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8923076923076924), 'f1_macro': 0.4461538461538462, 'f1_weighted': 0.7188034188034188, 'precision_macro': 0.4027777777777778, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 14, 'FN': 0, 'TP': 58, 'score_source': 'continuous', 'auroc': 0.6096059113300492, 'ap_0': 0.2802869762442381, 'ap_1': 0.8772921020243777, 'scenario': 'baseline', 'model': 'LR', 'outer_fold': 4, 'params': {'C': 0.01, 'max_iter': 1000, 'solver': 'lbfgs'}, 'inner_f1_macro': 0.4498734455816001}
Fase 1 XGB {'accuracy': 0.7638888888888888, 'precision_0': np.float64(0.2), 'precision_1': np.float64(0.8059701492537313), 'recall_0': np.float64(0.07142857142857142), 'recall_1': np.float64(0.9310344827586207), 'f1_0': np.float64(0.10526315789473684), 'f1_1': np.float64(0.864), 'f1_macro': 0.4846315789473684, 'f1_weighted': 0.7164678362573099, 'precision_macro': 0.5029850746268657, 'recall_macro': 0.5012315270935961, 'balanced_accuracy': 0.5012315270935961, 'mcc': 0.0038346839658001653, 'specificity': np.float64(0.07142857142857142), 'sensitivity': np.float64(0.9310344827586207), 'TN': 1, 'FP': 13, 'FN': 4, 'TP': 54, 'score_source': 'continuous', 'auroc': 0.5394088669950738, 'ap_0': 0.2640297538016434, 'ap_1': 0.8723311245117696, 'scenario': 'baseline', 'model': 'XGB', 'outer_fold': 4, 'params': {'learning_rate': 0.05, 'max_depth': 5, 'n_estimators': 200}, 'inner_f1_macro': 0.48092433909739346}
Fase 1 NB {'accuracy': 0.7361111111111112, 'precision_0': np.float64(0.3333333333333333), 'precision_1': np.float64(0.8421052631578947), 'recall_0': np.float64(0.35714285714285715), 'recall_1': np.float64(0.8275862068965517), 'f1_0': np.float64(0.3448275862068966), 'f1_1': np.float64(0.8347826086956521), 'f1_macro': 0.5898050974512743, 'f1_weighted': 0.7395135765450607, 'precision_macro': 0.587719298245614, 'recall_macro': 0.5923645320197044, 'balanced_accuracy': 0.5923645320197044, 'mcc': 0.18002390876273094, 'specificity': np.float64(0.35714285714285715), 'sensitivity': np.float64(0.8275862068965517), 'TN': 5, 'FP': 9, 'FN': 10, 'TP': 48, 'score_source': 'continuous', 'auroc': 0.6108374384236452, 'ap_0': 0.2850013663198234, 'ap_1': 0.8770379462647364, 'scenario': 'baseline', 'model': 'NB', 'outer_fold': 4, 'params': {'var_smoothing': 1e-11}, 'inner_f1_macro': 0.512437601785815}

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(

Fase 1 NC {'accuracy': 0.5416666666666666, 'precision_0': np.float64(0.2564102564102564), 'precision_1': np.float64(0.8787878787878788), 'recall_0': np.float64(0.7142857142857143), 'recall_1': np.float64(0.5), 'f1_0': np.float64(0.37735849056603776), 'f1_1': np.float64(0.6373626373626373), 'f1_macro': 0.5073605639643375, 'f1_weighted': 0.5868062754855207, 'precision_macro': 0.5675990675990676, 'recall_macro': 0.6071428571428572, 'balanced_accuracy': 0.6071428571428572, 'mcc': 0.17020878053446295, 'specificity': np.float64(0.7142857142857143), 'sensitivity': np.float64(0.5), 'TN': 10, 'FP': 4, 'FN': 29, 'TP': 29, 'score_source': 'continuous', 'auroc': 0.5788177339901479, 'ap_0': 0.2558718828850979, 'ap_1': 0.8523958881524794, 'scenario': 'baseline', 'model': 'NC', 'outer_fold': 4, 'params': {'metric': 'euclidean', 'shrink_threshold': None}, 'inner_f1_macro': 0.4726238700810904}
2026-09-13 19:42:20,596 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:42:20,598 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:42:20,598 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:42:20,599 - opfython.core.opf — INFO — Class created.
2026-09-13 19:42:20,599 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:42:20,600 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:42:20,603 - opfython.models.supervised — DEBUG — Finding prototypes ...

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(

2026-09-13 19:42:20,738 - opfython.models.supervised — DEBUG — Prototypes: [326, 60, 336, 93, 47, 92, 205, 486, 456, 89, 43, 277, 447, 122, 497, 33, 31, 107, 156, 79, 238, 36, 391, 342, 252, 142, 498, 40, 377, 398, 420, 285, 452, 348, 82, 73, 80, 338, 496, 475, 85, 419, 401, 384, 353, 380, 96, 166, 48, 351, 121, 118, 213, 381, 312, 100, 94, 317, 90, 72, 246, 21, 500, 254, 275, 291, 244, 179, 507, 426, 214, 141, 359, 509, 453, 506, 130, 63, 61, 192, 276, 66, 13, 282, 111, 155, 375, 227, 349, 152, 442, 62, 15, 332, 259, 273, 164, 451, 70, 203, 473, 436, 235, 357, 123, 416, 215, 11, 446, 225, 329, 154, 101, 262, 443, 431, 403, 320, 2, 301, 303, 245, 505, 258, 7, 8, 407, 429, 207, 131, 242, 321, 180, 219, 186, 223, 465, 374, 274, 106, 127, 365, 504, 151, 3, 77, 294, 386, 340, 230, 27, 56, 220, 49, 489, 330, 78, 421, 209, 234, 483, 283, 466, 415, 160, 204, 319, 249, 371, 18, 113, 314, 185, 479, 125, 74, 263, 413, 171, 168, 307, 137, 430, 255, 243, 129, 425, 376, 363, 457, 463, 299, 181, 199, 441, 360, 222, 493, 153, 298, 216, 41, 290, 308, 59, 488, 495, 472, 183, 184, 75, 251, 383, 379, 177].
2026-09-13 19:42:20,987 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:42:20,988 - opfython.models.supervised — INFO — Training time: 0.387498140335083 seconds.
2026-09-13 19:42:20,989 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:42:21,099 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:42:21,100 - opfython.models.supervised — INFO — Prediction time: 0.11010527610778809 seconds.
2026-09-13 19:42:21,125 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:42:21,126 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:42:21,127 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:42:21,127 - opfython.core.opf — INFO — Class created.
2026-09-13 19:42:21,127 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:42:21,128 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:42:21,131 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:42:21,264 - opfython.models.supervised — DEBUG — Prototypes: [414, 346, 457, 106, 127, 18, 109, 46, 276, 324, 446, 458, 40, 304, 17, 413, 402, 32, 464, 343, 174, 92, 430, 108, 245, 433, 222, 239, 257, 155, 497, 203, 344, 387, 186, 52, 136, 86, 38, 328, 495, 476, 162, 440, 284, 419, 382, 400, 111, 309, 340, 8, 404, 64, 311, 107, 84, 253, 19, 260, 274, 171, 289, 425, 388, 395, 180, 224, 137, 416, 62, 82, 475, 317, 193, 76, 432, 12, 445, 232, 373, 320, 172, 427, 403, 22, 442, 279, 334, 66, 275, 455, 69, 11, 146, 281, 508, 221, 85, 500, 70, 73, 269, 370, 234, 341, 170, 272, 184, 299, 3, 438, 251, 504, 262, 506, 250, 130, 300, 197, 15, 214, 280, 348, 213, 219, 25, 33, 93, 100, 463, 1, 288, 9, 200, 314, 173, 229, 342, 358, 501, 141, 503, 169, 89, 292, 384, 177, 332, 237, 412, 183, 474, 68, 217, 467, 415, 53, 7, 321, 421, 104, 99, 278, 356, 164, 394, 59, 77, 266, 484, 166, 87, 226, 199, 125, 310, 357, 14, 215, 313, 255, 179, 336, 44, 16, 366, 361, 189, 303, 363, 96, 43, 391, 144, 424, 459, 465, 119, 297, 67, 128, 212, 441, 230, 492, 225, 305, 512, 63, 90, 192, 456, 489, 54, 494, 478, 507, 198, 337, 381, 377, 196, 88, 78, 502, 327].
2026-09-13 19:42:21,583 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:42:21,584 - opfython.models.supervised — INFO — Training time: 0.4551849365234375 seconds.
2026-09-13 19:42:21,585 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:42:21,704 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:42:21,705 - opfython.models.supervised — INFO — Prediction time: 0.11916065216064453 seconds.
2026-09-13 19:42:21,721 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:42:21,722 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:42:21,723 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:42:21,724 - opfython.core.opf — INFO — Class created.
2026-09-13 19:42:21,724 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:42:21,725 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:42:21,727 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:42:21,862 - opfython.models.supervised — DEBUG — Prototypes: [91, 0, 461, 98, 138, 116, 163, 504, 86, 296, 10, 205, 321, 169, 241, 244, 198, 389, 173, 341, 248, 413, 179, 281, 68, 211, 453, 151, 143, 237, 363, 508, 148, 82, 168, 501, 164, 121, 441, 69, 309, 18, 50, 270, 284, 181, 451, 135, 343, 247, 190, 233, 76, 80, 473, 360, 13, 442, 272, 308, 328, 167, 70, 427, 407, 245, 278, 320, 332, 286, 445, 134, 496, 456, 26, 406, 33, 311, 32, 353, 462, 483, 157, 455, 53, 226, 335, 113, 108, 193, 492, 410, 287, 414, 65, 325, 170, 90, 123, 107, 326, 41, 235, 249, 334, 505, 45, 217, 486, 404, 350, 99, 452, 83, 338, 418, 189, 439, 293, 354, 391, 236, 132, 356, 382, 110, 1, 128, 7, 8, 315, 22, 497, 265, 81, 259, 203, 474, 347, 285, 166, 297, 256, 126, 40, 436, 257, 269, 307, 63, 471, 289, 342, 199, 19, 425, 409, 25, 34, 481, 465, 415, 229, 449, 222, 232, 251, 54, 490, 89, 97, 366, 419, 103, 398, 274, 77, 60, 84, 239, 485, 160, 204, 276, 16, 438, 291, 62, 225, 104, 479, 137, 352, 175, 372, 21, 149, 105, 370, 94, 369, 183, 426, 188, 266, 422, 457, 463, 141, 355, 220, 44, 302, 46, 493, 440, 364, 238, 200, 513, 312, 165, 9, 87, 85, 327, 64, 489, 494, 478, 202, 381, 212, 503, 337].
2026-09-13 19:42:22,116 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:42:22,117 - opfython.models.supervised — INFO — Training time: 0.39119625091552734 seconds.
2026-09-13 19:42:22,117 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:42:22,240 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:42:22,241 - opfython.models.supervised — INFO — Prediction time: 0.1231839656829834 seconds.
2026-09-13 19:42:22,253 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:42:22,254 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:42:22,255 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:42:22,256 - opfython.core.opf — INFO — Class created.
2026-09-13 19:42:22,256 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:42:22,257 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:42:22,259 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:42:22,393 - opfython.models.supervised — DEBUG — Prototypes: [417, 354, 333, 287, 190, 493, 114, 411, 105, 53, 220, 487, 33, 406, 309, 416, 32, 351, 458, 40, 47, 314, 331, 130, 481, 123, 22, 106, 253, 437, 41, 486, 266, 496, 45, 380, 485, 229, 332, 178, 54, 352, 391, 349, 98, 454, 293, 444, 294, 355, 382, 109, 1, 231, 129, 107, 313, 365, 7, 8, 64, 317, 103, 83, 261, 23, 498, 166, 258, 125, 505, 392, 400, 172, 340, 289, 263, 84, 501, 167, 291, 66, 457, 206, 286, 145, 150, 507, 68, 71, 73, 15, 69, 376, 397, 164, 120, 18, 50, 329, 273, 187, 76, 436, 356, 131, 419, 233, 62, 13, 450, 242, 379, 447, 275, 113, 67, 320, 2, 259, 504, 272, 469, 430, 410, 256, 321, 168, 299, 10, 240, 464, 350, 285, 134, 117, 428, 503, 364, 3, 301, 387, 91, 97, 415, 175, 300, 197, 216, 223, 218, 412, 446, 479, 484, 277, 399, 77, 221, 483, 161, 490, 55, 327, 90, 96, 362, 226, 363, 482, 292, 443, 16, 162, 61, 477, 132, 219, 264, 319, 367, 284, 343, 44, 146, 431, 269, 257, 369, 93, 43, 137, 427, 425, 198, 212, 46, 298, 214, 180, 194, 165, 304, 88, 86, 489, 56, 476, 200, 201, 385, 381, 193, 85, 78, 502, 334].
2026-09-13 19:42:22,638 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:42:22,639 - opfython.models.supervised — INFO — Training time: 0.3814520835876465 seconds.
2026-09-13 19:42:22,639 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:42:22,751 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:42:22,751 - opfython.models.supervised — INFO — Prediction time: 0.11146903038024902 seconds.
2026-09-13 19:42:22,766 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:42:22,767 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:42:22,767 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:42:22,768 - opfython.core.opf — INFO — Class created.
2026-09-13 19:42:22,768 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:42:22,769 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:42:22,774 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:42:22,892 - opfython.models.supervised — DEBUG — Prototypes: [322, 60, 352, 416, 330, 106, 47, 104, 458, 102, 308, 415, 407, 28, 27, 350, 466, 459, 36, 44, 282, 311, 495, 133, 17, 276, 481, 124, 18, 105, 167, 88, 438, 246, 435, 393, 338, 171, 285, 222, 329, 240, 258, 150, 496, 41, 380, 486, 453, 290, 347, 96, 81, 34, 99, 418, 444, 406, 386, 353, 382, 108, 2, 176, 48, 224, 131, 107, 392, 127, 315, 280, 61, 426, 14, 263, 46, 278, 174, 148, 32, 225, 359, 508, 454, 68, 65, 70, 11, 211, 287, 120, 165, 80, 502, 375, 238, 66, 348, 318, 3, 302, 78, 20, 185, 73, 437, 357, 58, 417, 223, 226, 378, 236, 113, 266, 64, 445, 63, 452, 431, 22, 441, 194, 15, 305, 390, 23, 29, 212, 89, 465, 1, 95, 234, 468, 294, 9, 331, 349, 279, 461, 365, 503, 161, 116, 505, 139, 297, 388, 169, 480, 215, 267, 399, 74, 55, 484, 159, 94, 489, 157, 219, 241, 483, 288, 198, 122, 312, 443, 82, 228, 12, 57, 342, 40, 130, 371, 369, 92, 179, 307, 430, 251, 261, 478, 336, 374, 39, 397, 460, 490, 429, 163, 301, 42, 293, 233, 360, 162, 300, 372, 145, 469, 172, 207, 379, 195, 85, 84, 59, 227, 475, 83, 75, 257, 504, 332].
2026-09-13 19:42:23,148 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:42:23,149 - opfython.models.supervised — INFO — Training time: 0.37894773483276367 seconds.
2026-09-13 19:42:23,149 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:42:23,268 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:42:23,269 - opfython.models.supervised — INFO — Prediction time: 0.11939048767089844 seconds.
2026-09-13 19:42:23,283 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:42:23,284 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:42:23,284 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:42:23,284 - opfython.core.opf — INFO — Class created.
2026-09-13 19:42:23,285 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:42:23,286 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:42:23,289 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:42:23,391 - opfython.models.supervised — DEBUG — Prototypes: [326, 60, 336, 174, 47, 92, 205, 486, 456, 89, 43, 277, 447, 122, 497, 33, 278, 156, 79, 238, 107, 252, 142, 498, 40, 377, 419, 85, 73, 338, 496, 475, 348, 82, 452, 285, 384, 401, 166, 48, 118, 351, 121, 353, 196, 96, 317, 90, 21, 500, 275, 72, 246, 254, 214, 141, 359, 509, 453, 136, 130, 63, 61, 192, 276, 282, 111, 155, 66, 13, 375, 227, 273, 164, 15, 23, 436, 235, 357, 70, 473, 123, 416, 215, 446, 225, 11, 154, 191, 320, 2, 248, 431, 403, 329, 349, 395, 213, 381, 127, 427, 106, 365, 504, 3, 77, 151, 321, 337, 219, 180, 223, 465, 374, 49, 489, 330, 78, 173, 421, 283, 483, 393, 209, 102, 234, 291, 274, 294, 386, 36, 152, 442, 62, 94, 443, 280, 340, 230, 507, 309, 7, 407, 8, 244, 430, 243, 391, 287, 207, 429, 426, 113, 314, 185, 265, 204, 272, 249, 104, 399, 301, 160, 263, 74, 420, 303, 245, 505, 258, 256, 212, 137, 286, 27, 267, 168, 307, 220, 488, 495, 371, 224, 376, 471, 413, 440, 299, 153, 444, 383, 466, 415, 222, 41, 268, 441, 181, 199, 129, 425, 457, 463, 479, 59, 216, 472, 105, 379, 218, 75, 67, 183, 10].
2026-09-13 19:42:23,626 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:42:23,627 - opfython.models.supervised — INFO — Training time: 0.33913373947143555 seconds.
2026-09-13 19:42:23,628 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:42:23,739 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:42:23,740 - opfython.models.supervised — INFO — Prediction time: 0.11167693138122559 seconds.
2026-09-13 19:42:23,751 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:42:23,751 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:42:23,752 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:42:23,752 - opfython.core.opf — INFO — Class created.
2026-09-13 19:42:23,753 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:42:23,754 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:42:23,757 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:42:23,863 - opfython.models.supervised — DEBUG — Prototypes: [414, 346, 457, 106, 127, 18, 109, 46, 276, 324, 446, 458, 140, 304, 17, 413, 402, 32, 464, 343, 121, 174, 92, 430, 108, 245, 433, 222, 239, 257, 155, 497, 203, 440, 284, 419, 162, 86, 328, 495, 476, 382, 38, 340, 307, 344, 387, 186, 52, 111, 311, 107, 19, 274, 84, 253, 171, 260, 388, 395, 137, 416, 224, 62, 12, 82, 475, 193, 76, 432, 317, 445, 232, 373, 334, 66, 275, 455, 69, 11, 146, 281, 508, 500, 85, 352, 221, 73, 4, 370, 234, 272, 184, 172, 205, 427, 403, 180, 219, 70, 320, 341, 391, 214, 358, 501, 141, 503, 169, 89, 173, 314, 229, 326, 288, 9, 177, 93, 463, 1, 394, 14, 77, 59, 99, 356, 321, 53, 104, 421, 7, 87, 49, 226, 8, 404, 332, 237, 289, 292, 384, 484, 166, 64, 164, 170, 199, 506, 22, 442, 279, 125, 310, 250, 130, 217, 280, 348, 363, 511, 262, 251, 197, 357, 425, 361, 215, 313, 213, 255, 299, 3, 179, 300, 376, 412, 183, 25, 33, 261, 223, 448, 68, 452, 474, 336, 44, 467, 415, 128, 43, 189, 303, 201, 381, 78, 297, 67, 119, 230, 212, 441, 459, 465, 144, 424, 507, 494, 489, 79, 473, 63, 225, 211, 456, 90, 478, 377, 196, 228, 88, 502, 83, 198, 337, 247].
2026-09-13 19:42:24,081 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:42:24,082 - opfython.models.supervised — INFO — Training time: 0.3276100158691406 seconds.
2026-09-13 19:42:24,082 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:42:24,192 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:42:24,193 - opfython.models.supervised — INFO — Prediction time: 0.1102759838104248 seconds.
2026-09-13 19:42:24,206 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:42:24,206 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:42:24,207 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:42:24,208 - opfython.core.opf — INFO — Class created.
2026-09-13 19:42:24,208 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:42:24,209 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:42:24,211 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:42:24,316 - opfython.models.supervised — DEBUG — Prototypes: [91, 0, 461, 321, 169, 296, 336, 10, 244, 138, 116, 424, 504, 163, 86, 173, 389, 135, 247, 190, 76, 80, 473, 13, 63, 151, 23, 237, 363, 508, 148, 72, 68, 211, 453, 82, 168, 501, 18, 50, 284, 181, 245, 278, 320, 332, 316, 445, 134, 496, 456, 26, 406, 33, 311, 32, 353, 462, 455, 157, 335, 218, 108, 193, 492, 410, 287, 226, 53, 402, 170, 90, 414, 117, 65, 325, 45, 486, 235, 249, 334, 354, 391, 452, 99, 439, 293, 418, 189, 83, 338, 495, 475, 404, 236, 132, 128, 7, 8, 22, 497, 81, 259, 285, 166, 265, 356, 1, 110, 427, 407, 167, 210, 328, 413, 179, 341, 248, 70, 272, 54, 490, 89, 97, 366, 192, 419, 398, 60, 77, 232, 251, 16, 84, 239, 393, 505, 449, 297, 41, 123, 107, 160, 164, 121, 471, 441, 69, 481, 289, 342, 370, 512, 256, 126, 442, 229, 426, 199, 423, 425, 409, 291, 438, 269, 257, 115, 401, 222, 369, 283, 225, 2, 352, 175, 485, 204, 276, 183, 40, 149, 25, 66, 346, 447, 465, 415, 44, 489, 494, 206, 302, 165, 92, 46, 220, 440, 479, 400, 457, 463, 78, 215, 200, 513, 64, 238, 470, 38, 141, 355, 478, 488, 381, 212, 503, 127, 202, 347].
2026-09-13 19:42:24,545 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:42:24,546 - opfython.models.supervised — INFO — Training time: 0.33586668968200684 seconds.
2026-09-13 19:42:24,546 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:42:24,642 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:42:24,643 - opfython.models.supervised — INFO — Prediction time: 0.09592390060424805 seconds.
2026-09-13 19:42:24,655 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:42:24,656 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:42:24,657 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:42:24,657 - opfython.core.opf — INFO — Class created.
2026-09-13 19:42:24,658 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:42:24,659 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:42:24,663 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:42:24,761 - opfython.models.supervised — DEBUG — Prototypes: [417, 354, 333, 287, 190, 493, 114, 411, 105, 53, 32, 351, 33, 406, 309, 416, 458, 295, 47, 314, 21, 283, 481, 130, 118, 123, 22, 106, 437, 253, 435, 496, 266, 45, 380, 485, 229, 332, 293, 454, 349, 98, 444, 294, 178, 54, 352, 391, 231, 129, 107, 355, 1, 109, 317, 103, 23, 186, 498, 83, 261, 201, 472, 344, 166, 392, 400, 233, 131, 419, 62, 187, 76, 436, 356, 13, 450, 242, 379, 66, 286, 457, 206, 36, 150, 232, 455, 507, 71, 68, 291, 120, 167, 84, 501, 73, 15, 18, 50, 320, 2, 172, 181, 69, 364, 3, 428, 134, 117, 299, 10, 240, 464, 321, 168, 91, 97, 415, 175, 218, 277, 399, 16, 77, 221, 490, 55, 327, 90, 96, 362, 189, 226, 292, 482, 7, 8, 67, 275, 64, 376, 223, 365, 301, 387, 483, 161, 164, 486, 285, 469, 505, 447, 288, 443, 258, 125, 430, 410, 272, 259, 289, 340, 300, 313, 197, 367, 219, 319, 115, 403, 446, 479, 264, 216, 412, 270, 230, 146, 431, 257, 343, 44, 451, 162, 43, 61, 121, 460, 385, 58, 89, 369, 93, 512, 202, 165, 448, 489, 46, 484, 180, 194, 214, 477, 402, 198, 212, 137, 427, 209, 37, 470, 381, 235, 85, 78, 502, 82, 200].
2026-09-13 19:42:24,972 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:42:24,972 - opfython.models.supervised — INFO — Training time: 0.3123607635498047 seconds.
2026-09-13 19:42:24,973 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:42:25,060 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:42:25,061 - opfython.models.supervised — INFO — Prediction time: 0.08779001235961914 seconds.
2026-09-13 19:42:25,072 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:42:25,072 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:42:25,073 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:42:25,073 - opfython.core.opf — INFO — Class created.
2026-09-13 19:42:25,073 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:42:25,074 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:42:25,076 - opfython.models.supervised — DEBUG — Finding prototypes ...

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

Fase 1 MLP {'accuracy': 0.7605633802816901, 'precision_0': np.float64(0.16666666666666666), 'precision_1': np.float64(0.8153846153846154), 'recall_0': np.float64(0.07692307692307693), 'recall_1': np.float64(0.9137931034482759), 'f1_0': np.float64(0.10526315789473684), 'f1_1': np.float64(0.8617886178861789), 'f1_macro': 0.48352588789045786, 'f1_weighted': 0.7232698716905627, 'precision_macro': 0.491025641025641, 'recall_macro': 0.49535809018567645, 'balanced_accuracy': 0.49535809018567645, 'mcc': -0.01290862734768342, 'specificity': np.float64(0.07692307692307693), 'sensitivity': np.float64(0.9137931034482759), 'TN': 1, 'FP': 12, 'FN': 5, 'TP': 53, 'score_source': 'continuous', 'auroc': 0.44297082228116713, 'ap_0': 0.1954224535623864, 'ap_1': 0.8137281235477007, 'scenario': 'baseline', 'model': 'MLP', 'outer_fold': 5, 'params': {'alpha': 0.0001, 'hidden_layer_sizes': (32, 16), 'max_iter': 500}, 'inner_f1_macro': 0.47312922205740177}
Fase 1 LR {'accuracy': 0.8169014084507042, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8169014084507042), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8992248062015504), 'f1_macro': 0.4496124031007752, 'f1_weighted': 0.7345780106998581, 'precision_macro': 0.4084507042253521, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 13, 'FN': 0, 'TP': 58, 'score_source': 'continuous', 'auroc': 0.4933687002652519, 'ap_0': 0.1822376495143907, 'ap_1': 0.8457788671279378, 'scenario': 'baseline', 'model': 'LR', 'outer_fold': 5, 'params': {'C': 0.01, 'max_iter': 1000, 'solver': 'lbfgs'}, 'inner_f1_macro': 0.449488279960383}
Fase 1 XGB {'accuracy': 0.7887323943661971, 'precision_0': np.float64(0.25), 'precision_1': np.float64(0.8208955223880597), 'recall_0': np.float64(0.07692307692307693), 'recall_1': np.float64(0.9482758620689655), 'f1_0': np.float64(0.11764705882352941), 'f1_1': np.float64(0.88), 'f1_macro': 0.4988235294117647, 'f1_weighted': 0.7404142502071251, 'precision_macro': 0.5354477611940298, 'recall_macro': 0.5125994694960212, 'balanced_accuracy': 0.5125994694960212, 'mcc': 0.04226691310547407, 'specificity': np.float64(0.07692307692307693), 'sensitivity': np.float64(0.9482758620689655), 'TN': 1, 'FP': 12, 'FN': 3, 'TP': 55, 'score_source': 'continuous', 'auroc': 0.4549071618037135, 'ap_0': 0.2105558589688637, 'ap_1': 0.7995388298924729, 'scenario': 'baseline', 'model': 'XGB', 'outer_fold': 5, 'params': {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}, 'inner_f1_macro': 0.4845950118840833}
Fase 1 NB {'accuracy': 0.6056338028169014, 'precision_0': np.float64(0.10526315789473684), 'precision_1': np.float64(0.7884615384615384), 'recall_0': np.float64(0.15384615384615385), 'recall_1': np.float64(0.7068965517241379), 'f1_0': np.float64(0.125), 'f1_1': np.float64(0.7454545454545455), 'f1_macro': 0.43522727272727274, 'f1_weighted': 0.6318501920614596, 'precision_macro': 0.44686234817813764, 'recall_macro': 0.4303713527851459, 'balanced_accuracy': 0.4303713527851459, 'mcc': -0.12165365284331094, 'specificity': np.float64(0.15384615384615385), 'sensitivity': np.float64(0.7068965517241379), 'TN': 2, 'FP': 11, 'FN': 17, 'TP': 41, 'score_source': 'continuous', 'auroc': 0.423076923076923, 'ap_0': 0.1898173531115083, 'ap_1': 0.8239134348892415, 'scenario': 'baseline', 'model': 'NB', 'outer_fold': 5, 'params': {'var_smoothing': 1e-11}, 'inner_f1_macro': 0.4686935572564351}

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(

Fase 1 NC {'accuracy': 0.4647887323943662, 'precision_0': np.float64(0.14285714285714285), 'precision_1': np.float64(0.7777777777777778), 'recall_0': np.float64(0.38461538461538464), 'recall_1': np.float64(0.4827586206896552), 'f1_0': np.float64(0.20833333333333334), 'f1_1': np.float64(0.5957446808510638), 'f1_macro': 0.4020390070921986, 'f1_weighted': 0.5248102087703527, 'precision_macro': 0.46031746031746035, 'recall_macro': 0.4336870026525199, 'balanced_accuracy': 0.4336870026525199, 'mcc': -0.10259567532229666, 'specificity': np.float64(0.38461538461538464), 'sensitivity': np.float64(0.4827586206896552), 'TN': 5, 'FP': 8, 'FN': 30, 'TP': 28, 'score_source': 'continuous', 'auroc': 0.4694960212201592, 'ap_0': 0.17615148275129106, 'ap_1': 0.8467508841749062, 'scenario': 'baseline', 'model': 'NC', 'outer_fold': 5, 'params': {'metric': 'euclidean', 'shrink_threshold': None}, 'inner_f1_macro': 0.4708284975154826}
2026-09-13 19:43:03,469 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:43:03,469 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:43:03,470 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:43:03,470 - opfython.core.opf — INFO — Class created.
2026-09-13 19:43:03,471 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:43:03,471 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:43:03,473 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:43:03,571 - opfython.models.supervised — DEBUG — Prototypes: [322, 61, 417, 351, 334, 91, 215, 89, 114, 20, 90, 45, 277, 449, 124, 298, 459, 128, 305, 19, 416, 404, 120, 465, 105, 402, 401, 134, 499, 391, 249, 34, 436, 238, 437, 423, 281, 341, 41, 377, 486, 195, 213, 420, 231, 333, 251, 186, 244, 257, 487, 121, 171, 210, 234, 69, 476, 125, 419, 216, 60, 325, 155, 26, 326, 100, 262, 445, 64, 448, 434, 405, 406, 63, 189, 457, 23, 276, 66, 36, 142, 455, 8, 266, 88, 68, 12, 200, 282, 110, 156, 71, 321, 247, 348, 303, 14, 47, 259, 442, 285, 422, 272, 454, 284, 384, 350, 135, 214, 123, 352, 379, 398, 367, 93, 390, 480, 317, 21, 44, 245, 477, 290, 275, 243, 117, 508, 315, 2, 297, 153, 474, 29, 92, 201, 261, 301, 444, 408, 453, 129, 430, 104, 366, 505, 472, 3, 74, 152, 157, 316, 289, 335, 9, 223, 468, 349, 274, 340, 229, 78, 82, 1, 50, 84, 327, 76, 490, 81, 364, 22, 304, 59, 209, 233, 485, 380, 57, 148, 432, 397, 18, 122, 354, 273, 203, 179, 481, 127, 139, 87, 371, 79, 39, 394, 112, 462, 183, 51, 226, 131, 428, 43, 460, 466, 433, 242, 418, 185, 151, 154, 295, 198, 302, 361, 258, 378, 175].

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(

2026-09-13 19:43:03,798 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:43:03,798 - opfython.models.supervised — INFO — Training time: 0.3267812728881836 seconds.
2026-09-13 19:43:03,799 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:43:03,914 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:43:03,915 - opfython.models.supervised — INFO — Prediction time: 0.11542987823486328 seconds.
2026-09-13 19:43:03,925 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:43:03,926 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:43:03,926 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:43:03,927 - opfython.core.opf — INFO — Class created.
2026-09-13 19:43:03,927 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:43:03,928 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:43:03,931 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:43:04,031 - opfython.models.supervised — DEBUG — Prototypes: [314, 66, 54, 108, 106, 216, 417, 345, 489, 225, 73, 461, 103, 126, 18, 107, 138, 160, 296, 496, 277, 48, 307, 17, 39, 462, 301, 416, 404, 92, 29, 342, 466, 401, 400, 148, 498, 387, 255, 175, 435, 245, 30, 40, 281, 333, 250, 420, 43, 209, 458, 488, 261, 343, 136, 137, 454, 283, 339, 99, 85, 36, 327, 495, 161, 478, 402, 346, 376, 2, 104, 187, 330, 306, 131, 63, 110, 19, 46, 258, 275, 83, 251, 309, 150, 288, 508, 429, 405, 318, 37, 194, 78, 434, 350, 81, 477, 64, 419, 11, 317, 172, 23, 116, 264, 444, 70, 72, 74, 68, 203, 459, 8, 105, 144, 75, 13, 84, 223, 173, 501, 371, 233, 50, 340, 273, 185, 295, 3, 406, 447, 422, 426, 443, 69, 453, 170, 510, 507, 249, 129, 214, 198, 440, 217, 93, 272, 1, 98, 231, 370, 469, 287, 15, 325, 311, 174, 341, 274, 169, 120, 504, 90, 177, 331, 236, 414, 183, 482, 151, 480, 140, 366, 134, 55, 319, 97, 490, 358, 163, 394, 60, 378, 10, 265, 388, 486, 165, 20, 184, 62, 300, 219, 240, 485, 282, 441, 166, 135, 348, 86, 16, 393, 365, 188, 428, 248, 259, 91, 215, 360, 254, 500, 206, 243, 41, 390, 377, 143, 344, 171, 293, 267, 359, 354, 463, 467, 460, 242, 476, 201, 335, 375, 232, 87, 256, 503, 326].
2026-09-13 19:43:04,228 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:43:04,229 - opfython.models.supervised — INFO — Training time: 0.3002786636352539 seconds.
2026-09-13 19:43:04,230 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:43:04,334 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:43:04,335 - opfython.models.supervised — INFO — Prediction time: 0.10498237609863281 seconds.
2026-09-13 19:43:04,345 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:43:04,346 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:43:04,346 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:43:04,347 - opfython.core.opf — INFO — Class created.
2026-09-13 19:43:04,347 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:43:04,347 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:43:04,349 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:43:04,460 - opfython.models.supervised — DEBUG — Prototypes: [368, 502, 471, 141, 115, 36, 504, 165, 145, 167, 295, 333, 9, 244, 466, 171, 339, 246, 413, 177, 181, 318, 452, 292, 350, 95, 83, 39, 336, 494, 159, 440, 419, 477, 405, 384, 235, 134, 354, 380, 1, 106, 390, 128, 64, 480, 315, 102, 149, 22, 319, 48, 497, 264, 257, 126, 507, 67, 407, 130, 32, 352, 464, 307, 458, 140, 50, 286, 328, 446, 136, 495, 404, 403, 454, 496, 457, 101, 55, 224, 103, 192, 332, 492, 217, 410, 287, 488, 415, 66, 321, 322, 124, 468, 104, 168, 89, 252, 432, 105, 261, 206, 248, 234, 331, 505, 378, 238, 137, 417, 324, 40, 190, 78, 431, 359, 81, 475, 12, 445, 24, 176, 72, 37, 153, 236, 509, 8, 276, 143, 414, 75, 14, 289, 120, 230, 49, 351, 305, 17, 53, 270, 284, 179, 362, 408, 441, 69, 166, 27, 442, 422, 258, 268, 375, 228, 391, 357, 199, 70, 473, 483, 226, 274, 397, 225, 382, 11, 393, 485, 162, 84, 239, 56, 5, 325, 88, 99, 420, 401, 23, 178, 63, 306, 203, 122, 367, 231, 249, 290, 439, 15, 163, 133, 356, 426, 409, 481, 139, 269, 372, 132, 150, 183, 427, 188, 265, 142, 424, 459, 381, 220, 304, 44, 47, 212, 363, 340, 251, 202, 10, 379, 195, 85, 297, 503, 335].
2026-09-13 19:43:04,674 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:43:04,674 - opfython.models.supervised — INFO — Training time: 0.3269081115722656 seconds.
2026-09-13 19:43:04,675 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:43:04,783 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:43:04,784 - opfython.models.supervised — INFO — Prediction time: 0.10841870307922363 seconds.
2026-09-13 19:43:04,796 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:43:04,797 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:43:04,797 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:43:04,798 - opfython.core.opf — INFO — Class created.
2026-09-13 19:43:04,798 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:43:04,799 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:43:04,800 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:43:04,899 - opfython.models.supervised — DEBUG — Prototypes: [333, 104, 56, 103, 219, 490, 232, 71, 461, 156, 323, 0, 409, 129, 309, 420, 34, 351, 50, 312, 329, 452, 133, 305, 124, 22, 42, 168, 90, 252, 440, 266, 204, 247, 228, 332, 423, 258, 382, 45, 488, 271, 424, 284, 447, 295, 82, 335, 349, 96, 407, 352, 143, 392, 179, 318, 355, 383, 1, 338, 229, 311, 63, 127, 106, 66, 480, 23, 499, 259, 80, 257, 126, 506, 315, 264, 393, 340, 425, 291, 261, 81, 502, 166, 292, 68, 288, 8, 102, 180, 150, 230, 457, 509, 72, 24, 70, 138, 49, 17, 53, 273, 286, 177, 187, 76, 439, 357, 134, 422, 233, 64, 12, 165, 325, 112, 275, 435, 410, 397, 14, 379, 242, 316, 2, 304, 449, 69, 456, 29, 105, 300, 321, 216, 307, 196, 434, 412, 221, 367, 3, 471, 136, 432, 117, 36, 504, 299, 9, 202, 317, 167, 350, 418, 175, 91, 174, 483, 399, 20, 277, 400, 62, 11, 486, 161, 83, 234, 95, 364, 492, 57, 89, 426, 5, 159, 201, 122, 485, 293, 446, 15, 218, 101, 262, 374, 130, 481, 171, 272, 146, 372, 93, 208, 250, 44, 384, 131, 470, 493, 181, 193, 48, 164, 303, 163, 214, 128, 200, 343, 84, 265, 503, 99].
2026-09-13 19:43:05,105 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:43:05,106 - opfython.models.supervised — INFO — Training time: 0.3072245121002197 seconds.
2026-09-13 19:43:05,107 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:43:05,203 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:43:05,204 - opfython.models.supervised — INFO — Prediction time: 0.09596848487854004 seconds.
2026-09-13 19:43:05,215 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:43:05,216 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:43:05,216 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:43:05,217 - opfython.core.opf — INFO — Class created.
2026-09-13 19:43:05,218 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:43:05,218 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:43:05,220 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:43:05,324 - opfython.models.supervised — DEBUG — Prototypes: [418, 352, 328, 104, 492, 112, 49, 213, 462, 100, 69, 226, 326, 283, 449, 463, 37, 27, 349, 468, 406, 472, 141, 497, 167, 28, 38, 257, 198, 380, 41, 487, 205, 222, 419, 421, 277, 445, 291, 82, 332, 346, 95, 455, 290, 387, 407, 350, 142, 176, 315, 223, 131, 334, 309, 62, 127, 58, 311, 101, 145, 250, 80, 294, 281, 480, 429, 133, 10, 227, 239, 439, 75, 357, 322, 35, 78, 317, 23, 447, 266, 111, 434, 408, 66, 448, 149, 32, 224, 456, 510, 20, 70, 68, 282, 64, 460, 201, 287, 120, 166, 81, 503, 72, 272, 376, 237, 347, 46, 13, 304, 403, 313, 3, 299, 409, 279, 476, 508, 163, 25, 286, 337, 265, 136, 430, 31, 366, 504, 475, 506, 162, 86, 314, 196, 232, 15, 234, 470, 280, 88, 94, 1, 170, 416, 174, 399, 11, 55, 383, 169, 485, 490, 93, 364, 219, 241, 484, 288, 195, 122, 19, 146, 57, 305, 83, 228, 159, 212, 99, 253, 134, 263, 486, 178, 433, 249, 260, 202, 243, 464, 469, 369, 90, 335, 271, 138, 428, 382, 124, 398, 187, 208, 361, 371, 130, 164, 321, 44, 161, 242, 60, 194, 341, 381, 189, 84, 256, 505, 331].
2026-09-13 19:43:05,539 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:43:05,540 - opfython.models.supervised — INFO — Training time: 0.3210713863372803 seconds.
2026-09-13 19:43:05,541 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:43:05,635 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:43:05,636 - opfython.models.supervised — INFO — Prediction time: 0.09482192993164062 seconds.
2026-09-13 19:43:05,651 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:43:05,652 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:43:05,652 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:43:05,653 - opfython.core.opf — INFO — Class created.
2026-09-13 19:43:05,653 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:43:05,654 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:43:05,655 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:43:05,767 - opfython.models.supervised — DEBUG — Prototypes: [322, 61, 417, 351, 334, 91, 215, 331, 114, 20, 90, 459, 286, 45, 277, 449, 124, 298, 404, 120, 33, 305, 416, 402, 77, 134, 499, 105, 34, 436, 89, 238, 437, 41, 377, 486, 213, 409, 231, 333, 420, 186, 251, 319, 171, 210, 234, 69, 476, 125, 419, 216, 60, 326, 26, 406, 442, 285, 422, 272, 454, 284, 384, 350, 135, 214, 123, 93, 390, 21, 44, 501, 275, 477, 245, 14, 47, 142, 36, 455, 66, 23, 189, 63, 457, 8, 88, 282, 156, 71, 68, 12, 200, 155, 188, 315, 226, 2, 352, 249, 391, 398, 434, 405, 201, 290, 320, 348, 394, 281, 341, 325, 321, 247, 78, 1, 82, 289, 9, 223, 468, 335, 316, 157, 366, 3, 472, 505, 129, 104, 152, 74, 22, 163, 50, 172, 327, 76, 490, 81, 364, 380, 204, 264, 209, 101, 233, 367, 509, 64, 262, 340, 229, 480, 317, 274, 244, 360, 257, 474, 508, 148, 153, 110, 487, 445, 280, 100, 243, 117, 59, 371, 513, 29, 92, 203, 444, 408, 433, 242, 432, 397, 18, 297, 423, 453, 179, 428, 139, 450, 265, 183, 112, 167, 304, 383, 39, 154, 446, 43, 198, 122, 354, 481, 399, 51, 131, 460, 466, 185, 418, 475, 473, 378, 175].
2026-09-13 19:43:05,970 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:43:05,971 - opfython.models.supervised — INFO — Training time: 0.3171076774597168 seconds.
2026-09-13 19:43:05,971 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:43:06,060 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:43:06,061 - opfython.models.supervised — INFO — Prediction time: 0.08861708641052246 seconds.
2026-09-13 19:43:06,071 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:43:06,072 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:43:06,072 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:43:06,073 - opfython.core.opf — INFO — Class created.
2026-09-13 19:43:06,074 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:43:06,075 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:43:06,076 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:43:06,180 - opfython.models.supervised — DEBUG — Prototypes: [314, 66, 54, 108, 106, 216, 417, 345, 489, 225, 73, 461, 103, 126, 18, 107, 462, 39, 48, 307, 322, 138, 296, 404, 29, 92, 416, 301, 342, 466, 401, 148, 498, 121, 175, 245, 435, 30, 43, 458, 488, 454, 283, 339, 99, 85, 327, 402, 343, 137, 63, 131, 19, 46, 251, 83, 64, 419, 194, 78, 434, 318, 37, 350, 81, 477, 11, 23, 72, 74, 68, 203, 459, 8, 105, 144, 84, 173, 501, 75, 13, 371, 233, 273, 185, 51, 309, 253, 104, 406, 57, 429, 405, 346, 376, 2, 255, 387, 396, 101, 172, 317, 340, 390, 214, 281, 333, 169, 120, 504, 90, 311, 174, 228, 325, 287, 370, 231, 469, 177, 93, 98, 1, 288, 275, 70, 264, 110, 136, 20, 184, 55, 490, 319, 97, 358, 378, 60, 219, 240, 163, 486, 165, 86, 282, 485, 274, 10, 40, 250, 353, 261, 507, 441, 443, 69, 482, 236, 331, 444, 280, 170, 124, 62, 116, 249, 129, 265, 394, 217, 198, 440, 3, 414, 183, 365, 512, 426, 119, 398, 428, 248, 270, 295, 422, 188, 151, 284, 393, 16, 206, 181, 215, 360, 254, 41, 366, 134, 91, 171, 445, 377, 135, 348, 480, 79, 494, 463, 467, 35, 476, 475, 242, 143, 344, 375, 226, 503, 82, 201, 335, 87, 221].
2026-09-13 19:43:06,398 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:43:06,399 - opfython.models.supervised — INFO — Training time: 0.32392096519470215 seconds.
2026-09-13 19:43:06,400 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:43:06,495 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:43:06,496 - opfython.models.supervised — INFO — Prediction time: 0.09537124633789062 seconds.
2026-09-13 19:43:06,509 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:43:06,509 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:43:06,510 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:43:06,511 - opfython.core.opf — INFO — Class created.
2026-09-13 19:43:06,511 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:43:06,512 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:43:06,514 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:43:06,611 - opfython.models.supervised — DEBUG — Prototypes: [8, 414, 143, 276, 153, 209, 236, 509, 148, 24, 176, 72, 289, 510, 230, 49, 75, 14, 305, 17, 53, 284, 179, 137, 341, 238, 417, 324, 40, 190, 78, 431, 359, 81, 475, 12, 440, 282, 419, 83, 336, 62, 350, 95, 452, 292, 405, 384, 235, 134, 106, 390, 64, 128, 315, 102, 22, 48, 497, 82, 285, 332, 192, 55, 103, 224, 488, 457, 101, 130, 307, 407, 32, 352, 464, 458, 28, 50, 286, 328, 446, 136, 495, 404, 468, 454, 496, 403, 168, 89, 252, 432, 415, 116, 66, 321, 234, 410, 248, 331, 261, 206, 362, 408, 354, 380, 1, 124, 104, 295, 9, 244, 466, 333, 368, 2, 471, 502, 141, 115, 36, 504, 165, 171, 145, 274, 84, 239, 23, 178, 56, 191, 325, 88, 99, 420, 382, 90, 225, 15, 397, 231, 447, 249, 480, 318, 339, 246, 485, 162, 351, 11, 67, 181, 203, 441, 69, 483, 166, 27, 105, 63, 257, 126, 122, 226, 199, 391, 112, 290, 439, 113, 401, 70, 422, 473, 426, 409, 317, 413, 177, 269, 427, 228, 501, 375, 268, 258, 183, 442, 448, 163, 212, 175, 184, 306, 372, 245, 132, 205, 381, 133, 356, 220, 304, 481, 400, 142, 424, 47, 278, 44, 459, 79, 251, 38, 379, 195, 85, 392, 202, 344, 503, 127, 254].
2026-09-13 19:43:06,824 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:43:06,824 - opfython.models.supervised — INFO — Training time: 0.3118417263031006 seconds.
2026-09-13 19:43:06,825 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:43:06,919 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:43:06,920 - opfython.models.supervised — INFO — Prediction time: 0.0950770378112793 seconds.
2026-09-13 19:43:06,931 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:43:06,931 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:43:06,932 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:43:06,933 - opfython.core.opf — INFO — Class created.
2026-09-13 19:43:06,934 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:43:06,935 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:43:06,937 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:43:07,046 - opfython.models.supervised — DEBUG — Prototypes: [333, 104, 56, 103, 219, 490, 232, 71, 461, 156, 409, 129, 34, 351, 309, 420, 50, 312, 329, 452, 133, 305, 224, 323, 0, 168, 90, 252, 440, 204, 266, 45, 382, 488, 228, 332, 247, 423, 424, 284, 447, 295, 82, 335, 349, 96, 407, 352, 143, 392, 127, 63, 106, 23, 499, 80, 259, 268, 194, 355, 1, 393, 402, 264, 233, 134, 422, 64, 187, 76, 439, 357, 12, 24, 72, 70, 150, 230, 457, 509, 180, 288, 68, 8, 280, 102, 138, 166, 81, 292, 502, 49, 308, 17, 53, 286, 177, 165, 98, 397, 14, 379, 242, 316, 2, 315, 261, 435, 410, 182, 223, 325, 338, 229, 124, 22, 216, 300, 321, 142, 367, 3, 471, 136, 117, 317, 167, 202, 299, 9, 418, 175, 400, 220, 95, 364, 492, 57, 89, 188, 100, 5, 15, 277, 83, 234, 293, 485, 66, 179, 159, 486, 161, 258, 360, 271, 42, 480, 318, 201, 279, 506, 446, 449, 69, 483, 257, 126, 350, 122, 112, 275, 29, 105, 221, 196, 91, 431, 434, 412, 291, 340, 115, 405, 272, 218, 304, 331, 399, 20, 425, 262, 146, 208, 123, 44, 256, 374, 130, 372, 93, 513, 386, 164, 450, 203, 48, 384, 181, 193, 214, 481, 404, 131, 470, 37, 474, 84, 394, 503, 79, 200, 343, 254].
2026-09-13 19:43:07,260 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:43:07,261 - opfython.models.supervised — INFO — Training time: 0.32527852058410645 seconds.
2026-09-13 19:43:07,261 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:43:07,346 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:43:07,347 - opfython.models.supervised — INFO — Prediction time: 0.08469676971435547 seconds.
2026-09-13 19:43:07,359 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:43:07,360 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:43:07,360 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:43:07,360 - opfython.core.opf — INFO — Class created.
2026-09-13 19:43:07,361 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:43:07,361 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:43:07,364 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:43:07,465 - opfython.models.supervised — DEBUG — Prototypes: [418, 352, 497, 141, 406, 472, 27, 349, 468, 463, 37, 326, 283, 300, 17, 276, 328, 104, 49, 213, 462, 100, 226, 69, 116, 167, 28, 257, 198, 41, 380, 487, 346, 95, 455, 290, 445, 291, 421, 185, 82, 332, 407, 387, 350, 142, 223, 131, 58, 127, 311, 101, 250, 45, 80, 477, 341, 149, 510, 20, 70, 68, 64, 201, 460, 287, 120, 166, 81, 503, 46, 13, 322, 35, 439, 75, 357, 133, 239, 227, 78, 67, 10, 59, 23, 165, 200, 409, 72, 295, 376, 237, 313, 3, 434, 408, 347, 396, 294, 318, 216, 234, 211, 470, 375, 314, 329, 232, 191, 31, 136, 430, 366, 475, 506, 162, 86, 170, 88, 94, 1, 416, 174, 93, 490, 364, 383, 55, 214, 219, 241, 11, 399, 19, 288, 484, 228, 83, 62, 176, 403, 280, 480, 315, 66, 266, 438, 38, 476, 222, 419, 508, 286, 337, 163, 279, 304, 447, 305, 57, 111, 429, 433, 249, 263, 212, 4, 114, 404, 299, 400, 253, 195, 485, 269, 122, 178, 134, 99, 25, 369, 265, 159, 124, 335, 202, 123, 179, 398, 187, 197, 371, 235, 130, 382, 486, 208, 164, 89, 44, 273, 464, 469, 138, 428, 76, 242, 321, 381, 189, 230, 84, 394, 505, 79, 246, 194].
2026-09-13 19:43:07,680 - opfython.models.supervised — INFO — Classifier has been fitted.

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

Fase 1 MLP {'accuracy': 0.6901408450704225, 'precision_0': np.float64(0.09090909090909091), 'precision_1': np.float64(0.8), 'recall_0': np.float64(0.07692307692307693), 'recall_1': np.float64(0.8275862068965517), 'f1_0': np.float64(0.08333333333333333), 'f1_1': np.float64(0.8135593220338984), 'f1_macro': 0.44844632768361586, 'f1_weighted': 0.6798559719901329, 'precision_macro': 0.4454545454545455, 'recall_macro': 0.45225464190981435, 'balanced_accuracy': 0.45225464190981435, 'mcc': -0.10206453369245702, 'specificity': np.float64(0.07692307692307693), 'sensitivity': np.float64(0.8275862068965517), 'TN': 1, 'FP': 12, 'FN': 10, 'TP': 48, 'score_source': 'continuous', 'auroc': 0.4807692307692307, 'ap_0': 0.17900446101204182, 'ap_1': 0.8262679036397116, 'scenario': 'baseline', 'model': 'MLP', 'outer_fold': 6, 'params': {'alpha': 0.01, 'hidden_layer_sizes': (32, 16), 'max_iter': 500}, 'inner_f1_macro': 0.491266322960948}
Fase 1 LR {'accuracy': 0.8169014084507042, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8169014084507042), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8992248062015504), 'f1_macro': 0.4496124031007752, 'f1_weighted': 0.7345780106998581, 'precision_macro': 0.4084507042253521, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 13, 'FN': 0, 'TP': 58, 'score_source': 'continuous', 'auroc': 0.6571618037135278, 'ap_0': 0.25100414606995447, 'ap_1': 0.9047518012563095, 'scenario': 'baseline', 'model': 'LR', 'outer_fold': 6, 'params': {'C': 0.01, 'max_iter': 1000, 'solver': 'lbfgs'}, 'inner_f1_macro': 0.449488279960383}
Fase 1 XGB {'accuracy': 0.7746478873239436, 'precision_0': np.float64(0.2), 'precision_1': np.float64(0.8181818181818182), 'recall_0': np.float64(0.07692307692307693), 'recall_1': np.float64(0.9310344827586207), 'f1_0': np.float64(0.1111111111111111), 'f1_1': np.float64(0.8709677419354839), 'f1_macro': 0.49103942652329746, 'f1_weighted': 0.731839063052148, 'precision_macro': 0.5090909090909091, 'recall_macro': 0.5039787798408488, 'balanced_accuracy': 0.5039787798408488, 'mcc': 0.012028420648763203, 'specificity': np.float64(0.07692307692307693), 'sensitivity': np.float64(0.9310344827586207), 'TN': 1, 'FP': 12, 'FN': 4, 'TP': 54, 'score_source': 'continuous', 'auroc': 0.6306366047745359, 'ap_0': 0.2537599969993617, 'ap_1': 0.8612028351266708, 'scenario': 'baseline', 'model': 'XGB', 'outer_fold': 6, 'params': {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}, 'inner_f1_macro': 0.49838324584752475}
Fase 1 NB {'accuracy': 0.7183098591549296, 'precision_0': np.float64(0.1111111111111111), 'precision_1': np.float64(0.8064516129032258), 'recall_0': np.float64(0.07692307692307693), 'recall_1': np.float64(0.8620689655172413), 'f1_0': np.float64(0.09090909090909091), 'f1_1': np.float64(0.8333333333333334), 'f1_macro': 0.46212121212121215, 'f1_weighted': 0.6973965002134016, 'precision_macro': 0.45878136200716846, 'recall_macro': 0.4694960212201591, 'balanced_accuracy': 0.4694960212201591, 'mcc': -0.07091776811680625, 'specificity': np.float64(0.07692307692307693), 'sensitivity': np.float64(0.8620689655172413), 'TN': 1, 'FP': 12, 'FN': 8, 'TP': 50, 'score_source': 'continuous', 'auroc': 0.6929708222811671, 'ap_0': 0.292106451529096, 'ap_1': 0.9212868135174255, 'scenario': 'baseline', 'model': 'NB', 'outer_fold': 6, 'params': {'var_smoothing': 1e-11}, 'inner_f1_macro': 0.4677153518798228}

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(

Fase 1 NC {'accuracy': 0.647887323943662, 'precision_0': np.float64(0.3235294117647059), 'precision_1': np.float64(0.9459459459459459), 'recall_0': np.float64(0.8461538461538461), 'recall_1': np.float64(0.603448275862069), 'f1_0': np.float64(0.46808510638297873), 'f1_1': np.float64(0.7368421052631579), 'f1_macro': 0.6024636058230683, 'f1_weighted': 0.6876330772991814, 'precision_macro': 0.634737678855326, 'recall_macro': 0.7248010610079576, 'balanced_accuracy': 0.7248010610079576, 'mcc': 0.34807569960815543, 'specificity': np.float64(0.8461538461538461), 'sensitivity': np.float64(0.603448275862069), 'TN': 11, 'FP': 2, 'FN': 23, 'TP': 35, 'score_source': 'continuous', 'auroc': 0.7088859416445623, 'ap_0': 0.28930399836596776, 'ap_1': 0.9207623695740418, 'scenario': 'baseline', 'model': 'NC', 'outer_fold': 6, 'params': {'metric': 'euclidean', 'shrink_threshold': None}, 'inner_f1_macro': 0.4508736349635775}
2026-09-13 19:43:46,828 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:43:46,829 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:43:46,830 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:43:46,831 - opfython.core.opf — INFO — Class created.
2026-09-13 19:43:46,831 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:43:46,831 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:43:46,833 - opfython.models.supervised — DEBUG — Finding prototypes ...

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(

2026-09-13 19:43:46,956 - opfython.models.supervised — DEBUG — Prototypes: [419, 348, 456, 147, 217, 329, 46, 279, 448, 127, 298, 457, 30, 34, 35, 112, 501, 136, 159, 469, 241, 102, 390, 254, 165, 119, 94, 22, 437, 205, 43, 375, 255, 499, 486, 212, 235, 423, 248, 262, 285, 453, 425, 89, 76, 334, 497, 478, 402, 86, 169, 51, 346, 389, 214, 125, 97, 479, 349, 100, 398, 7, 8, 397, 308, 250, 503, 188, 477, 341, 289, 277, 247, 182, 432, 65, 439, 238, 61, 421, 13, 323, 157, 213, 373, 228, 446, 282, 66, 382, 133, 24, 143, 215, 354, 510, 170, 10, 268, 132, 158, 75, 67, 269, 371, 230, 45, 16, 264, 49, 29, 96, 301, 154, 344, 203, 209, 64, 428, 474, 62, 406, 444, 2, 337, 233, 314, 190, 19, 226, 370, 467, 183, 111, 129, 251, 362, 472, 505, 3, 134, 153, 291, 383, 416, 167, 468, 420, 276, 303, 84, 491, 359, 52, 325, 80, 396, 266, 69, 206, 378, 485, 151, 23, 304, 60, 189, 284, 484, 445, 77, 219, 480, 128, 340, 42, 263, 364, 275, 131, 431, 434, 246, 259, 207, 140, 286, 365, 171, 41, 394, 124, 471, 202, 296, 63, 186, 201, 377, 495, 356, 225, 155, 295, 218, 404, 197, 400, 71, 489, 53, 509, 109, 187, 376, 180, 422].
2026-09-13 19:43:47,192 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:43:47,193 - opfython.models.supervised — INFO — Training time: 0.36158037185668945 seconds.
2026-09-13 19:43:47,194 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:43:47,300 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:43:47,301 - opfython.models.supervised — INFO — Prediction time: 0.10620379447937012 seconds.
2026-09-13 19:43:47,313 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:43:47,315 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:43:47,315 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:43:47,316 - opfython.core.opf — INFO — Class created.
2026-09-13 19:43:47,317 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:43:47,318 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:43:47,320 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:43:47,450 - opfython.models.supervised — DEBUG — Prototypes: [314, 66, 322, 280, 112, 493, 212, 411, 489, 404, 135, 301, 418, 465, 459, 26, 448, 279, 141, 296, 497, 220, 482, 401, 399, 149, 499, 178, 96, 247, 438, 117, 387, 329, 185, 258, 435, 498, 260, 46, 370, 158, 223, 242, 422, 487, 254, 264, 339, 150, 191, 311, 337, 103, 454, 283, 89, 106, 325, 496, 402, 341, 373, 116, 2, 224, 139, 327, 162, 63, 8, 406, 394, 113, 386, 305, 473, 479, 67, 287, 277, 136, 316, 39, 195, 80, 437, 64, 420, 85, 313, 315, 175, 120, 267, 71, 368, 235, 156, 151, 348, 455, 75, 72, 69, 208, 278, 176, 88, 501, 77, 272, 366, 237, 338, 15, 53, 276, 189, 446, 70, 453, 407, 475, 299, 198, 13, 443, 3, 253, 97, 102, 1, 286, 9, 233, 468, 323, 310, 177, 145, 124, 172, 504, 93, 289, 381, 181, 416, 188, 218, 388, 393, 81, 61, 376, 217, 485, 169, 491, 54, 317, 95, 101, 423, 222, 244, 484, 203, 131, 307, 90, 227, 21, 153, 14, 122, 398, 469, 419, 216, 109, 265, 356, 361, 137, 45, 332, 19, 392, 358, 192, 100, 44, 389, 460, 466, 431, 294, 375, 494, 232, 209, 173, 293, 138, 382, 200, 513, 328, 94, 92, 246, 249, 488, 201, 202, 372, 236, 91, 259, 503, 324].
2026-09-13 19:43:47,761 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:43:47,762 - opfython.models.supervised — INFO — Training time: 0.4430868625640869 seconds.
2026-09-13 19:43:47,763 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:43:47,870 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:43:47,871 - opfython.models.supervised — INFO — Prediction time: 0.1072084903717041 seconds.
2026-09-13 19:43:47,885 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:43:47,886 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:43:47,887 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:43:47,888 - opfython.core.opf — INFO — Class created.
2026-09-13 19:43:47,888 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:43:47,889 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:43:47,895 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:43:48,016 - opfython.models.supervised — DEBUG — Prototypes: [95, 0, 461, 101, 294, 11, 329, 245, 348, 364, 502, 471, 142, 120, 167, 504, 91, 176, 415, 183, 336, 391, 323, 42, 195, 79, 83, 475, 66, 240, 236, 116, 275, 444, 171, 322, 154, 134, 238, 356, 451, 508, 187, 75, 24, 71, 214, 286, 10, 278, 257, 86, 172, 501, 77, 280, 371, 247, 51, 347, 168, 125, 19, 325, 273, 52, 287, 446, 138, 456, 141, 407, 133, 33, 307, 416, 483, 121, 404, 402, 147, 497, 328, 109, 417, 350, 68, 319, 239, 74, 455, 160, 129, 468, 108, 256, 435, 113, 35, 450, 388, 102, 346, 421, 104, 87, 332, 495, 477, 383, 405, 351, 377, 1, 237, 137, 311, 158, 65, 479, 55, 7, 8, 397, 469, 261, 85, 426, 409, 27, 110, 230, 260, 200, 303, 223, 295, 202, 15, 21, 413, 235, 443, 411, 228, 396, 17, 62, 379, 276, 14, 484, 163, 56, 490, 93, 423, 23, 306, 64, 208, 127, 233, 363, 291, 441, 151, 465, 418, 340, 47, 365, 226, 315, 263, 480, 140, 150, 107, 430, 259, 269, 457, 463, 136, 470, 222, 144, 349, 205, 220, 493, 241, 408, 169, 299, 217, 358, 300, 513, 442, 92, 90, 253, 489, 57, 478, 206, 207, 376, 198, 88, 265, 503, 331].
2026-09-13 19:43:48,265 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:43:48,266 - opfython.models.supervised — INFO — Training time: 0.3754427433013916 seconds.
2026-09-13 19:43:48,266 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:43:48,364 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:43:48,365 - opfython.models.supervised — INFO — Prediction time: 0.09851431846618652 seconds.
2026-09-13 19:43:48,376 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:43:48,377 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:43:48,378 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:43:48,378 - opfython.core.opf — INFO — Class created.
2026-09-13 19:43:48,379 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:43:48,380 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:43:48,381 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:43:48,498 - opfython.models.supervised — DEBUG — Prototypes: [321, 66, 350, 422, 329, 108, 459, 159, 234, 74, 134, 304, 497, 290, 52, 43, 409, 130, 310, 421, 34, 286, 121, 406, 405, 469, 128, 24, 458, 391, 268, 442, 256, 114, 171, 93, 35, 440, 221, 428, 498, 270, 47, 377, 153, 230, 250, 425, 487, 263, 287, 427, 385, 407, 295, 351, 379, 112, 1, 348, 145, 183, 57, 311, 345, 110, 390, 63, 157, 7, 8, 470, 265, 87, 299, 289, 262, 198, 25, 75, 72, 68, 208, 10, 338, 141, 420, 502, 226, 51, 19, 277, 55, 288, 181, 192, 79, 441, 85, 476, 64, 424, 231, 235, 376, 244, 117, 193, 279, 451, 70, 168, 124, 450, 69, 456, 29, 109, 434, 474, 199, 20, 246, 373, 346, 396, 448, 2, 217, 224, 94, 464, 188, 284, 316, 170, 298, 330, 11, 347, 361, 3, 472, 138, 435, 37, 504, 167, 91, 301, 386, 173, 335, 249, 88, 58, 493, 324, 100, 359, 429, 382, 61, 222, 80, 485, 163, 227, 251, 484, 293, 204, 126, 312, 62, 486, 240, 218, 220, 315, 267, 176, 480, 136, 149, 107, 363, 365, 97, 140, 433, 46, 399, 23, 368, 460, 466, 131, 471, 216, 211, 236, 410, 381, 200, 356, 82, 201, 214, 92, 190, 253, 491, 59, 257, 488, 202, 203, 89, 269, 503, 332].
2026-09-13 19:43:48,723 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:43:48,724 - opfython.models.supervised — INFO — Training time: 0.3437037467956543 seconds.
2026-09-13 19:43:48,724 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:43:48,817 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:43:48,818 - opfython.models.supervised — INFO — Prediction time: 0.09298515319824219 seconds.
2026-09-13 19:43:48,829 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:43:48,830 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:43:48,831 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:43:48,831 - opfython.core.opf — INFO — Class created.
2026-09-13 19:43:48,831 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:43:48,832 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:43:48,833 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:43:48,941 - opfython.models.supervised — DEBUG — Prototypes: [326, 192, 228, 71, 419, 285, 128, 19, 107, 408, 132, 305, 467, 460, 39, 47, 309, 121, 407, 405, 143, 499, 459, 279, 170, 92, 30, 438, 214, 223, 153, 422, 261, 497, 44, 375, 486, 254, 266, 346, 144, 182, 51, 343, 100, 454, 290, 84, 328, 424, 158, 383, 225, 379, 479, 60, 256, 82, 63, 282, 180, 151, 34, 226, 354, 509, 455, 72, 21, 69, 65, 284, 9, 273, 139, 168, 83, 503, 74, 275, 344, 68, 321, 37, 189, 77, 440, 81, 476, 224, 229, 373, 239, 448, 269, 67, 167, 103, 320, 410, 165, 510, 109, 447, 66, 453, 25, 108, 197, 16, 349, 391, 333, 175, 400, 296, 93, 99, 465, 1, 293, 10, 237, 469, 200, 312, 169, 345, 362, 504, 294, 385, 332, 240, 417, 178, 216, 399, 270, 78, 57, 98, 359, 160, 20, 179, 59, 304, 220, 243, 484, 289, 445, 85, 231, 126, 310, 13, 213, 311, 259, 336, 43, 18, 367, 398, 134, 365, 95, 148, 106, 267, 436, 253, 264, 480, 172, 42, 396, 138, 431, 338, 380, 298, 369, 494, 356, 470, 236, 166, 449, 79, 90, 88, 461, 478, 217, 489, 302, 377, 193, 86, 295, 260, 505, 381].
2026-09-13 19:43:49,153 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:43:49,154 - opfython.models.supervised — INFO — Training time: 0.3221609592437744 seconds.
2026-09-13 19:43:49,155 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:43:49,263 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:43:49,264 - opfython.models.supervised — INFO — Prediction time: 0.10814523696899414 seconds.
2026-09-13 19:43:49,278 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:43:49,279 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:43:49,280 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:43:49,280 - opfython.core.opf — INFO — Class created.
2026-09-13 19:43:49,281 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:43:49,282 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:43:49,286 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:43:49,406 - opfython.models.supervised — DEBUG — Prototypes: [419, 348, 456, 147, 217, 329, 46, 279, 448, 127, 298, 457, 30, 34, 35, 501, 136, 112, 159, 469, 241, 102, 43, 375, 486, 255, 499, 212, 410, 235, 423, 285, 453, 425, 89, 76, 334, 497, 478, 402, 86, 169, 51, 346, 389, 214, 125, 97, 479, 349, 306, 100, 250, 503, 188, 477, 341, 390, 398, 143, 215, 354, 510, 170, 133, 24, 66, 278, 10, 268, 132, 75, 158, 45, 230, 269, 371, 303, 16, 49, 317, 439, 238, 61, 421, 13, 157, 90, 373, 228, 165, 209, 119, 22, 94, 323, 289, 318, 314, 183, 190, 19, 226, 370, 467, 362, 3, 472, 505, 129, 111, 153, 134, 52, 178, 325, 80, 491, 84, 359, 378, 206, 396, 69, 23, 168, 77, 219, 284, 484, 7, 8, 397, 437, 205, 485, 151, 291, 383, 248, 355, 262, 154, 337, 233, 189, 446, 282, 445, 29, 96, 62, 60, 365, 513, 434, 246, 444, 2, 416, 167, 247, 432, 344, 263, 364, 203, 64, 428, 474, 276, 171, 140, 286, 340, 42, 468, 420, 197, 118, 41, 394, 260, 213, 155, 447, 296, 63, 202, 225, 480, 399, 186, 201, 131, 431, 509, 109, 124, 471, 71, 495, 475, 473, 376, 180, 187].
2026-09-13 19:43:49,624 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:43:49,625 - opfython.models.supervised — INFO — Training time: 0.3418588638305664 seconds.
2026-09-13 19:43:49,625 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:43:49,722 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:43:49,723 - opfython.models.supervised — INFO — Prediction time: 0.09728622436523438 seconds.
2026-09-13 19:43:49,734 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:43:49,734 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:43:49,735 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:43:49,735 - opfython.core.opf — INFO — Class created.
2026-09-13 19:43:49,736 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:43:49,737 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:43:49,738 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:43:49,839 - opfython.models.supervised — DEBUG — Prototypes: [314, 66, 322, 280, 112, 493, 212, 411, 459, 285, 448, 306, 141, 296, 497, 404, 31, 301, 418, 465, 482, 220, 401, 96, 149, 499, 178, 247, 438, 498, 260, 158, 223, 242, 422, 46, 370, 487, 339, 150, 454, 283, 337, 103, 89, 38, 325, 496, 106, 402, 224, 139, 113, 386, 341, 116, 2, 387, 395, 136, 316, 39, 195, 80, 437, 85, 313, 64, 420, 13, 156, 151, 348, 455, 75, 72, 69, 208, 278, 176, 88, 501, 276, 189, 53, 15, 77, 4, 366, 237, 175, 107, 407, 368, 235, 489, 185, 287, 312, 338, 389, 162, 63, 8, 406, 394, 315, 97, 1, 102, 145, 124, 172, 504, 93, 310, 177, 204, 286, 9, 233, 468, 197, 181, 376, 61, 393, 81, 491, 54, 317, 95, 101, 423, 222, 244, 14, 21, 90, 227, 71, 267, 479, 311, 67, 191, 289, 381, 485, 169, 473, 120, 196, 254, 349, 264, 435, 203, 269, 475, 446, 70, 131, 307, 218, 431, 198, 443, 3, 416, 188, 253, 265, 356, 122, 398, 216, 109, 427, 358, 512, 392, 19, 332, 45, 170, 469, 419, 209, 186, 44, 137, 361, 294, 388, 173, 447, 375, 232, 445, 460, 466, 494, 200, 513, 246, 476, 138, 382, 318, 65, 94, 92, 372, 229, 91, 82, 503, 86, 201, 333].
2026-09-13 19:43:50,039 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:43:50,041 - opfython.models.supervised — INFO — Training time: 0.3034703731536865 seconds.
2026-09-13 19:43:50,041 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:43:50,138 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:43:50,139 - opfython.models.supervised — INFO — Prediction time: 0.09786581993103027 seconds.
2026-09-13 19:43:50,151 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:43:50,152 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:43:50,152 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:43:50,153 - opfython.core.opf — INFO — Class created.
2026-09-13 19:43:50,153 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:43:50,153 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:43:50,155 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:43:50,263 - opfython.models.supervised — DEBUG — Prototypes: [95, 0, 461, 294, 329, 11, 245, 364, 502, 471, 142, 427, 120, 38, 504, 167, 91, 176, 323, 42, 195, 79, 83, 475, 236, 240, 66, 15, 10, 278, 71, 286, 214, 24, 75, 39, 154, 356, 86, 172, 501, 51, 257, 19, 171, 213, 85, 261, 207, 476, 50, 421, 161, 87, 332, 346, 102, 450, 405, 383, 237, 137, 65, 479, 55, 456, 141, 52, 312, 446, 138, 33, 231, 133, 407, 307, 416, 483, 404, 94, 147, 497, 239, 74, 328, 109, 417, 350, 68, 319, 455, 160, 121, 35, 256, 435, 113, 409, 351, 264, 1, 77, 3, 247, 280, 371, 230, 129, 468, 108, 322, 158, 7, 8, 397, 396, 17, 62, 379, 56, 490, 93, 196, 423, 23, 184, 390, 233, 447, 242, 347, 484, 163, 469, 208, 277, 486, 168, 125, 444, 289, 27, 110, 127, 64, 228, 260, 388, 295, 311, 202, 426, 291, 441, 430, 259, 365, 226, 2, 235, 315, 343, 443, 411, 223, 263, 413, 151, 21, 188, 303, 270, 336, 391, 415, 183, 150, 292, 340, 473, 47, 465, 418, 217, 128, 169, 445, 300, 442, 222, 205, 220, 457, 463, 480, 136, 470, 493, 253, 40, 472, 489, 144, 349, 92, 90, 478, 376, 198, 88, 80, 503, 84, 206, 12].
2026-09-13 19:43:50,471 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:43:50,472 - opfython.models.supervised — INFO — Training time: 0.31827306747436523 seconds.
2026-09-13 19:43:50,472 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:43:50,557 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:43:50,558 - opfython.models.supervised — INFO — Prediction time: 0.08506894111633301 seconds.
2026-09-13 19:43:50,569 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:43:50,569 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:43:50,570 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:43:50,570 - opfython.core.opf — INFO — Class created.
2026-09-13 19:43:50,570 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:43:50,571 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:43:50,572 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:43:50,672 - opfython.models.supervised — DEBUG — Prototypes: [321, 66, 350, 422, 121, 128, 24, 406, 469, 93, 409, 130, 310, 421, 34, 52, 290, 452, 134, 304, 497, 329, 108, 195, 495, 213, 459, 159, 234, 74, 256, 442, 171, 35, 114, 109, 47, 377, 487, 270, 498, 153, 230, 250, 425, 427, 287, 385, 348, 390, 145, 183, 57, 345, 212, 110, 265, 87, 351, 268, 112, 1, 391, 400, 235, 231, 64, 424, 192, 79, 441, 85, 476, 15, 376, 244, 68, 208, 25, 142, 147, 72, 226, 502, 51, 10, 338, 141, 420, 19, 55, 288, 181, 458, 299, 319, 260, 316, 170, 298, 330, 11, 361, 3, 472, 138, 435, 37, 504, 167, 91, 173, 94, 464, 58, 493, 324, 100, 359, 194, 429, 382, 61, 222, 88, 393, 227, 251, 293, 484, 335, 249, 7, 8, 63, 157, 440, 221, 470, 301, 386, 485, 163, 204, 282, 246, 373, 224, 346, 396, 168, 197, 450, 69, 451, 292, 70, 279, 474, 263, 29, 126, 312, 365, 513, 262, 199, 448, 2, 434, 363, 220, 342, 120, 403, 267, 217, 176, 428, 149, 295, 274, 399, 23, 211, 127, 240, 218, 46, 368, 243, 81, 381, 431, 200, 486, 216, 480, 402, 201, 214, 460, 466, 140, 433, 131, 471, 82, 253, 473, 475, 39, 242, 491, 92, 190, 89, 503, 86, 202, 340, 258].
2026-09-13 19:43:50,891 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:43:50,892 - opfython.models.supervised — INFO — Training time: 0.320753812789917 seconds.
2026-09-13 19:43:50,892 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:43:50,984 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:43:50,985 - opfython.models.supervised — INFO — Prediction time: 0.09212327003479004 seconds.
2026-09-13 19:43:50,995 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:43:50,996 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:43:50,996 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:43:50,997 - opfython.core.opf — INFO — Class created.
2026-09-13 19:43:50,997 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:43:50,998 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:43:50,999 - opfython.models.supervised — DEBUG — Finding prototypes ...

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

Fase 1 MLP {'accuracy': 0.8028169014084507, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8142857142857143), 'recall_0': np.float64(0.0), 'recall_1': np.float64(0.9827586206896551), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.890625), 'f1_macro': 0.4453125, 'f1_weighted': 0.7275528169014085, 'precision_macro': 0.40714285714285714, 'recall_macro': 0.49137931034482757, 'balanced_accuracy': 0.49137931034482757, 'mcc': -0.056585956237831254, 'specificity': np.float64(0.0), 'sensitivity': np.float64(0.9827586206896551), 'TN': 0, 'FP': 13, 'FN': 1, 'TP': 57, 'score_source': 'continuous', 'auroc': 0.5404509283819628, 'ap_0': 0.2131393795737156, 'ap_1': 0.8419380257667564, 'scenario': 'baseline', 'model': 'MLP', 'outer_fold': 7, 'params': {'alpha': 0.01, 'hidden_layer_sizes': (32,), 'max_iter': 500}, 'inner_f1_macro': 0.47294142570456427}
Fase 1 LR {'accuracy': 0.8169014084507042, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8169014084507042), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8992248062015504), 'f1_macro': 0.4496124031007752, 'f1_weighted': 0.7345780106998581, 'precision_macro': 0.4084507042253521, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 13, 'FN': 0, 'TP': 58, 'score_source': 'continuous', 'auroc': 0.5775862068965516, 'ap_0': 0.2459778831435031, 'ap_1': 0.8630907822865955, 'scenario': 'baseline', 'model': 'LR', 'outer_fold': 7, 'params': {'C': 0.01, 'max_iter': 1000, 'solver': 'lbfgs'}, 'inner_f1_macro': 0.449488279960383}
Fase 1 XGB {'accuracy': 0.8169014084507042, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8169014084507042), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8992248062015504), 'f1_macro': 0.4496124031007752, 'f1_weighted': 0.7345780106998581, 'precision_macro': 0.4084507042253521, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 13, 'FN': 0, 'TP': 58, 'score_source': 'continuous', 'auroc': 0.4767904509283819, 'ap_0': 0.19789445585382598, 'ap_1': 0.8151663334682375, 'scenario': 'baseline', 'model': 'XGB', 'outer_fold': 7, 'params': {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 100}, 'inner_f1_macro': 0.48200495232128937}
Fase 1 NB {'accuracy': 0.704225352112676, 'precision_0': np.float64(0.16666666666666666), 'precision_1': np.float64(0.8135593220338984), 'recall_0': np.float64(0.15384615384615385), 'recall_1': np.float64(0.8275862068965517), 'f1_0': np.float64(0.16), 'f1_1': np.float64(0.8205128205128205), 'f1_macro': 0.49025641025641026, 'f1_weighted': 0.6995738533766703, 'precision_macro': 0.4901129943502825, 'recall_macro': 0.4907161803713528, 'balanced_accuracy': 0.4907161803713528, 'mcc': -0.019161333682120706, 'specificity': np.float64(0.15384615384615385), 'sensitivity': np.float64(0.8275862068965517), 'TN': 2, 'FP': 11, 'FN': 10, 'TP': 48, 'score_source': 'continuous', 'auroc': 0.4781167108753316, 'ap_0': 0.2054488510665749, 'ap_1': 0.8449897243314081, 'scenario': 'baseline', 'model': 'NB', 'outer_fold': 7, 'params': {'var_smoothing': 1e-11}, 'inner_f1_macro': 0.44946192009097663}

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(

Fase 1 NC {'accuracy': 0.49295774647887325, 'precision_0': np.float64(0.17142857142857143), 'precision_1': np.float64(0.8055555555555556), 'recall_0': np.float64(0.46153846153846156), 'recall_1': np.float64(0.5), 'f1_0': np.float64(0.25), 'f1_1': np.float64(0.6170212765957447), 'f1_macro': 0.43351063829787234, 'f1_weighted': 0.5498201977824394, 'precision_macro': 0.48849206349206353, 'recall_macro': 0.4807692307692308, 'balanced_accuracy': 0.4807692307692308, 'mcc': -0.02975274584346603, 'specificity': np.float64(0.46153846153846156), 'sensitivity': np.float64(0.5), 'TN': 6, 'FP': 7, 'FN': 29, 'TP': 29, 'score_source': 'continuous', 'auroc': 0.5510610079575596, 'ap_0': 0.261888350781236, 'ap_1': 0.8615672932555062, 'scenario': 'baseline', 'model': 'NC', 'outer_fold': 7, 'params': {'metric': 'euclidean', 'shrink_threshold': 0.1}, 'inner_f1_macro': 0.47523549665741244}
2026-09-13 19:44:27,604 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:44:27,605 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:44:27,605 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:44:27,606 - opfython.core.opf — INFO — Class created.
2026-09-13 19:44:27,606 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:44:27,607 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:44:27,608 - opfython.models.supervised — DEBUG — Finding prototypes ...

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(

2026-09-13 19:44:27,718 - opfython.models.supervised — DEBUG — Prototypes: [344, 83, 451, 420, 86, 75, 337, 496, 474, 381, 401, 167, 52, 216, 125, 478, 311, 362, 97, 315, 92, 73, 252, 21, 46, 501, 261, 322, 292, 279, 508, 250, 184, 507, 331, 280, 126, 302, 456, 38, 307, 19, 36, 35, 346, 463, 219, 67, 455, 149, 91, 325, 348, 500, 138, 389, 256, 158, 79, 244, 102, 435, 95, 339, 29, 96, 258, 145, 498, 43, 485, 283, 427, 217, 143, 510, 168, 134, 23, 63, 454, 2, 6, 93, 133, 156, 74, 68, 273, 323, 253, 345, 442, 64, 14, 266, 49, 176, 213, 239, 351, 436, 127, 416, 220, 62, 446, 231, 26, 328, 106, 268, 443, 65, 433, 27, 318, 233, 1, 301, 450, 267, 4, 402, 397, 304, 471, 207, 431, 406, 154, 103, 209, 361, 505, 291, 335, 7, 229, 465, 278, 395, 18, 466, 415, 396, 270, 10, 489, 53, 78, 82, 89, 421, 212, 238, 482, 191, 483, 271, 109, 399, 22, 281, 61, 12, 208, 317, 254, 367, 42, 342, 141, 205, 413, 174, 265, 363, 128, 186, 327, 479, 160, 432, 249, 262, 132, 426, 365, 169, 197, 241, 377, 424, 299, 124, 469, 155, 298, 228, 493, 45, 290, 153, 356, 308, 487, 495, 240, 189, 190, 56, 215].
2026-09-13 19:44:27,960 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:44:27,961 - opfython.models.supervised — INFO — Training time: 0.3538060188293457 seconds.
2026-09-13 19:44:27,961 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:44:28,067 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:44:28,068 - opfython.models.supervised — INFO — Prediction time: 0.1063377857208252 seconds.
2026-09-13 19:44:28,081 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:44:28,082 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:44:28,082 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:44:28,083 - opfython.core.opf — INFO — Class created.
2026-09-13 19:44:28,083 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:44:28,084 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:44:28,086 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:44:28,221 - opfython.models.supervised — DEBUG — Prototypes: [340, 0, 116, 373, 88, 38, 328, 495, 475, 276, 420, 440, 379, 452, 305, 331, 337, 113, 385, 135, 65, 4, 5, 393, 307, 478, 19, 49, 264, 314, 86, 257, 156, 175, 309, 255, 133, 506, 401, 136, 303, 31, 458, 25, 322, 17, 298, 141, 496, 480, 275, 325, 112, 121, 407, 110, 55, 487, 414, 339, 399, 94, 152, 499, 469, 131, 18, 111, 33, 229, 117, 250, 386, 332, 184, 486, 281, 497, 262, 161, 225, 244, 324, 418, 259, 87, 501, 176, 283, 69, 456, 155, 73, 75, 380, 77, 11, 365, 240, 74, 173, 509, 14, 53, 268, 319, 39, 194, 79, 433, 345, 142, 416, 66, 9, 445, 238, 368, 22, 271, 120, 442, 71, 428, 132, 311, 1, 403, 40, 317, 300, 335, 199, 15, 215, 221, 217, 383, 236, 466, 289, 7, 177, 312, 277, 354, 472, 292, 35, 218, 484, 56, 106, 421, 100, 429, 392, 179, 80, 63, 375, 483, 204, 196, 12, 219, 310, 170, 230, 89, 357, 359, 97, 147, 425, 122, 209, 247, 44, 389, 459, 465, 202, 213, 369, 45, 490, 214, 301, 190, 48, 288, 297, 70, 172, 174, 296, 412, 423, 267, 415, 205, 467, 492, 235, 304, 391, 246, 508, 372, 195, 90, 261, 503, 327].
2026-09-13 19:44:28,511 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:44:28,512 - opfython.models.supervised — INFO — Training time: 0.4271714687347412 seconds.
2026-09-13 19:44:28,512 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:44:28,646 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:44:28,647 - opfython.models.supervised — INFO — Prediction time: 0.13442468643188477 seconds.
2026-09-13 19:44:28,661 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:44:28,662 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:44:28,663 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:44:28,663 - opfython.core.opf — INFO — Class created.
2026-09-13 19:44:28,664 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:44:28,664 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:44:28,666 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:44:28,831 - opfython.models.supervised — DEBUG — Prototypes: [6, 283, 77, 13, 156, 38, 358, 508, 75, 25, 73, 9, 257, 291, 509, 171, 84, 501, 52, 53, 347, 372, 394, 168, 440, 70, 449, 308, 16, 276, 398, 134, 326, 41, 139, 251, 242, 11, 26, 248, 373, 443, 116, 279, 441, 71, 427, 129, 417, 286, 438, 292, 346, 99, 450, 403, 186, 57, 239, 388, 67, 336, 132, 3, 4, 396, 477, 351, 473, 397, 312, 23, 51, 497, 83, 263, 170, 316, 152, 305, 138, 495, 288, 328, 455, 28, 404, 34, 462, 348, 309, 481, 332, 221, 109, 197, 491, 408, 413, 350, 107, 56, 486, 241, 74, 329, 454, 105, 496, 324, 256, 113, 173, 92, 35, 389, 268, 180, 127, 108, 110, 43, 27, 238, 331, 416, 157, 47, 220, 374, 406, 402, 278, 261, 130, 506, 344, 470, 227, 296, 410, 371, 318, 172, 299, 383, 480, 464, 414, 231, 379, 64, 484, 85, 280, 58, 489, 91, 24, 183, 66, 210, 235, 253, 483, 282, 412, 194, 478, 141, 368, 21, 153, 106, 135, 144, 422, 426, 272, 260, 136, 352, 366, 95, 188, 229, 500, 266, 456, 46, 224, 302, 50, 295, 492, 378, 205, 247, 169, 301, 167, 217, 176, 360, 310, 222, 341, 206, 89, 112, 487, 59, 493, 255, 208, 209, 376, 200, 86, 269, 503, 335].
2026-09-13 19:44:29,112 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:44:29,113 - opfython.models.supervised — INFO — Training time: 0.44828224182128906 seconds.
2026-09-13 19:44:29,114 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:44:29,267 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:44:29,268 - opfython.models.supervised — INFO — Prediction time: 0.15328192710876465 seconds.
2026-09-13 19:44:29,291 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:44:29,292 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:44:29,292 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:44:29,293 - opfython.core.opf — INFO — Class created.
2026-09-13 19:44:29,294 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:44:29,295 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:44:29,297 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:44:29,439 - opfython.models.supervised — DEBUG — Prototypes: [349, 0, 112, 381, 445, 295, 85, 287, 335, 496, 474, 234, 132, 129, 65, 4, 5, 399, 110, 391, 429, 315, 105, 150, 266, 84, 299, 288, 264, 128, 138, 134, 313, 406, 34, 347, 35, 481, 121, 162, 459, 104, 332, 108, 58, 107, 487, 418, 411, 126, 22, 405, 147, 258, 114, 44, 29, 109, 291, 339, 497, 272, 48, 378, 157, 232, 251, 422, 485, 42, 324, 237, 135, 420, 66, 191, 77, 438, 327, 41, 11, 376, 233, 117, 192, 448, 290, 451, 24, 143, 71, 155, 235, 355, 508, 183, 69, 386, 6, 284, 106, 142, 293, 170, 502, 72, 52, 396, 13, 373, 248, 309, 16, 55, 318, 1, 307, 408, 344, 433, 410, 346, 220, 227, 199, 18, 243, 447, 449, 360, 469, 319, 333, 242, 298, 7, 246, 466, 301, 267, 397, 20, 480, 478, 137, 416, 189, 398, 63, 78, 282, 483, 86, 239, 97, 491, 60, 92, 193, 164, 23, 180, 64, 229, 253, 152, 131, 351, 120, 403, 14, 151, 223, 317, 268, 368, 47, 341, 434, 275, 263, 279, 363, 365, 94, 211, 255, 46, 382, 141, 348, 201, 216, 460, 465, 218, 50, 168, 283, 305, 514, 446, 245, 458, 90, 67, 238, 489, 61, 260, 486, 203, 204, 226, 380, 209, 240, 87, 79, 503, 334].
2026-09-13 19:44:29,739 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:44:29,740 - opfython.models.supervised — INFO — Training time: 0.44452953338623047 seconds.
2026-09-13 19:44:29,740 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:44:29,880 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:44:29,881 - opfython.models.supervised — INFO — Prediction time: 0.1403036117553711 seconds.
2026-09-13 19:44:29,900 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:44:29,901 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:44:29,902 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:44:29,903 - opfython.core.opf — INFO — Class created.
2026-09-13 19:44:29,904 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:44:29,906 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:44:29,911 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:44:30,070 - opfython.models.supervised — DEBUG — Prototypes: [347, 0, 112, 378, 343, 97, 452, 444, 290, 419, 187, 83, 406, 384, 180, 52, 228, 135, 131, 61, 109, 391, 477, 18, 499, 265, 320, 201, 166, 295, 283, 407, 132, 307, 29, 345, 466, 459, 39, 325, 284, 405, 90, 146, 498, 328, 210, 191, 491, 106, 51, 486, 458, 160, 346, 416, 71, 230, 126, 17, 107, 392, 261, 174, 31, 168, 40, 108, 262, 496, 44, 375, 484, 226, 244, 327, 287, 335, 427, 433, 128, 188, 76, 438, 352, 62, 417, 227, 231, 373, 239, 67, 273, 20, 141, 69, 34, 154, 229, 356, 509, 8, 65, 456, 7, 277, 105, 140, 74, 11, 215, 288, 510, 503, 82, 70, 370, 241, 47, 344, 165, 315, 1, 302, 445, 66, 451, 26, 38, 322, 441, 474, 305, 220, 431, 410, 214, 196, 10, 13, 129, 256, 316, 167, 294, 329, 14, 237, 369, 282, 362, 473, 297, 386, 480, 381, 58, 398, 77, 275, 394, 84, 233, 489, 95, 19, 177, 60, 222, 246, 482, 118, 402, 134, 349, 483, 397, 16, 276, 311, 202, 478, 137, 367, 43, 338, 150, 104, 432, 257, 266, 380, 460, 467, 212, 368, 42, 357, 199, 514, 63, 232, 87, 186, 488, 494, 377, 194, 200, 505, 331, 85, 78].
2026-09-13 19:44:30,365 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:44:30,366 - opfython.models.supervised — INFO — Training time: 0.45964741706848145 seconds.
2026-09-13 19:44:30,367 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:44:30,476 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:44:30,478 - opfython.models.supervised — INFO — Prediction time: 0.11002039909362793 seconds.
2026-09-13 19:44:30,493 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:44:30,494 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:44:30,495 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:44:30,496 - opfython.core.opf — INFO — Class created.
2026-09-13 19:44:30,496 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:44:30,497 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:44:30,500 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:44:30,632 - opfython.models.supervised — DEBUG — Prototypes: [344, 83, 451, 420, 86, 75, 337, 496, 474, 381, 401, 167, 52, 216, 125, 478, 315, 92, 21, 46, 501, 279, 73, 252, 261, 67, 219, 455, 91, 456, 287, 331, 312, 126, 302, 307, 19, 36, 35, 346, 500, 138, 158, 79, 244, 112, 102, 498, 258, 145, 43, 485, 184, 253, 217, 143, 510, 168, 134, 23, 63, 454, 74, 156, 294, 6, 93, 133, 233, 273, 306, 14, 49, 239, 176, 436, 351, 127, 416, 220, 62, 26, 328, 446, 231, 318, 1, 325, 348, 433, 27, 292, 322, 345, 393, 323, 371, 291, 7, 229, 465, 335, 361, 505, 65, 268, 97, 508, 489, 82, 53, 78, 178, 421, 89, 396, 212, 238, 12, 391, 222, 278, 10, 378, 443, 282, 435, 95, 471, 4, 406, 397, 402, 442, 64, 29, 96, 389, 256, 207, 209, 432, 249, 431, 250, 237, 507, 427, 191, 483, 271, 363, 208, 317, 254, 109, 399, 22, 281, 61, 395, 18, 301, 339, 283, 128, 263, 215, 141, 286, 429, 154, 186, 327, 365, 169, 513, 197, 117, 342, 42, 487, 495, 413, 440, 265, 299, 155, 444, 171, 380, 377, 466, 415, 228, 441, 45, 274, 132, 426, 479, 160, 124, 469, 240, 472, 189, 343].
2026-09-13 19:44:30,923 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:44:30,924 - opfython.models.supervised — INFO — Training time: 0.42557859420776367 seconds.
2026-09-13 19:44:30,924 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:44:31,021 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:44:31,022 - opfython.models.supervised — INFO — Prediction time: 0.09728503227233887 seconds.
2026-09-13 19:44:31,036 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:44:31,036 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:44:31,037 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:44:31,038 - opfython.core.opf — INFO — Class created.
2026-09-13 19:44:31,038 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:44:31,040 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:44:31,041 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:44:31,153 - opfython.models.supervised — DEBUG — Prototypes: [340, 0, 116, 386, 394, 336, 88, 38, 328, 495, 475, 276, 420, 440, 379, 452, 385, 337, 113, 135, 4, 5, 393, 19, 49, 86, 257, 278, 175, 314, 298, 141, 496, 17, 322, 145, 458, 303, 32, 401, 464, 480, 275, 325, 112, 121, 407, 110, 55, 487, 414, 339, 229, 30, 399, 94, 152, 499, 469, 131, 18, 111, 33, 117, 250, 497, 262, 161, 225, 244, 324, 418, 197, 142, 416, 194, 79, 433, 345, 319, 39, 66, 9, 22, 445, 238, 368, 73, 75, 69, 155, 456, 380, 283, 509, 176, 87, 501, 77, 11, 365, 240, 14, 53, 311, 1, 309, 259, 403, 221, 428, 132, 184, 281, 332, 74, 307, 217, 354, 502, 472, 289, 7, 236, 466, 312, 124, 177, 233, 198, 375, 95, 63, 220, 80, 392, 12, 56, 106, 421, 230, 89, 292, 381, 277, 173, 486, 442, 280, 478, 196, 255, 133, 271, 120, 71, 506, 199, 335, 357, 219, 310, 215, 204, 483, 371, 300, 265, 226, 208, 170, 209, 130, 44, 389, 59, 378, 359, 97, 512, 81, 174, 443, 369, 426, 412, 423, 267, 297, 70, 48, 122, 484, 190, 214, 301, 441, 235, 202, 213, 467, 415, 147, 425, 508, 459, 465, 288, 246, 474, 372, 195, 231, 90, 503, 85].
2026-09-13 19:44:31,405 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:44:31,406 - opfython.models.supervised — INFO — Training time: 0.3658483028411865 seconds.
2026-09-13 19:44:31,406 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:44:31,506 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:44:31,508 - opfython.models.supervised — INFO — Prediction time: 0.10080933570861816 seconds.
2026-09-13 19:44:31,522 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:44:31,523 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:44:31,524 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:44:31,524 - opfython.core.opf — INFO — Class created.
2026-09-13 19:44:31,525 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:44:31,526 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:44:31,529 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:44:31,639 - opfython.models.supervised — DEBUG — Prototypes: [6, 283, 73, 9, 75, 25, 156, 358, 508, 38, 291, 509, 171, 84, 52, 77, 13, 257, 16, 308, 134, 326, 41, 26, 139, 251, 242, 11, 417, 286, 438, 292, 346, 99, 450, 403, 186, 57, 67, 336, 132, 477, 3, 4, 396, 351, 345, 316, 106, 23, 51, 497, 83, 263, 170, 268, 404, 34, 462, 348, 309, 455, 293, 328, 288, 138, 305, 495, 481, 454, 105, 332, 109, 197, 491, 408, 221, 413, 350, 107, 56, 486, 241, 74, 121, 496, 324, 35, 256, 173, 92, 110, 113, 238, 331, 416, 157, 47, 374, 389, 397, 406, 402, 443, 248, 373, 180, 427, 129, 239, 388, 347, 394, 227, 318, 120, 172, 244, 333, 203, 19, 71, 279, 379, 64, 58, 196, 91, 489, 24, 183, 281, 85, 280, 235, 253, 372, 233, 398, 116, 195, 498, 299, 383, 43, 108, 127, 168, 440, 70, 480, 202, 470, 27, 261, 130, 66, 441, 506, 231, 426, 260, 296, 312, 423, 344, 210, 484, 282, 410, 278, 153, 366, 188, 512, 341, 445, 217, 126, 304, 46, 412, 436, 135, 368, 229, 78, 266, 191, 302, 391, 169, 93, 382, 50, 224, 464, 414, 136, 352, 247, 439, 478, 206, 222, 144, 422, 456, 378, 255, 39, 487, 307, 493, 476, 376, 200, 86, 390, 503, 131, 208, 342].
2026-09-13 19:44:31,889 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:44:31,890 - opfython.models.supervised — INFO — Training time: 0.3640463352203369 seconds.
2026-09-13 19:44:31,891 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:44:31,995 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:44:31,996 - opfython.models.supervised — INFO — Prediction time: 0.10490107536315918 seconds.
2026-09-13 19:44:32,009 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:44:32,010 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:44:32,011 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:44:32,011 - opfython.core.opf — INFO — Class created.
2026-09-13 19:44:32,012 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:44:32,013 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:44:32,015 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:44:32,137 - opfython.models.supervised — DEBUG — Prototypes: [349, 0, 112, 85, 474, 335, 496, 190, 445, 295, 40, 234, 132, 110, 391, 129, 65, 4, 5, 399, 315, 105, 266, 84, 134, 289, 406, 34, 347, 35, 481, 162, 459, 104, 332, 215, 108, 194, 494, 411, 107, 58, 126, 22, 405, 147, 258, 436, 121, 418, 109, 114, 270, 497, 272, 157, 232, 251, 422, 48, 378, 485, 197, 6, 106, 142, 284, 71, 9, 74, 24, 155, 235, 355, 508, 183, 69, 293, 509, 170, 502, 52, 248, 285, 373, 309, 16, 55, 135, 420, 237, 66, 191, 77, 438, 327, 41, 11, 318, 1, 408, 291, 339, 227, 72, 376, 233, 299, 322, 346, 396, 298, 7, 246, 466, 333, 319, 242, 360, 469, 229, 253, 97, 491, 60, 92, 193, 398, 78, 63, 23, 180, 14, 86, 239, 164, 393, 453, 448, 290, 29, 434, 263, 64, 264, 128, 433, 410, 199, 429, 220, 307, 344, 120, 403, 447, 480, 152, 363, 397, 20, 18, 276, 223, 317, 268, 151, 301, 267, 365, 184, 513, 166, 483, 341, 471, 47, 243, 211, 125, 127, 200, 449, 46, 416, 443, 279, 305, 168, 489, 50, 131, 351, 218, 245, 446, 478, 402, 201, 216, 460, 465, 39, 67, 238, 470, 472, 141, 348, 458, 90, 217, 488, 87, 79, 380, 209, 240, 503, 83, 203, 342].
2026-09-13 19:44:32,406 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:44:32,407 - opfython.models.supervised — INFO — Training time: 0.39326024055480957 seconds.
2026-09-13 19:44:32,407 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:44:32,511 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:44:32,512 - opfython.models.supervised — INFO — Prediction time: 0.10422062873840332 seconds.
2026-09-13 19:44:32,528 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:44:32,528 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:44:32,529 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:44:32,530 - opfython.core.opf — INFO — Class created.
2026-09-13 19:44:32,530 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:44:32,532 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:44:32,534 - opfython.models.supervised — DEBUG — Finding prototypes ...

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

Fase 1 MLP {'accuracy': 0.7464788732394366, 'precision_0': np.float64(0.14285714285714285), 'precision_1': np.float64(0.8125), 'recall_0': np.float64(0.07692307692307693), 'recall_1': np.float64(0.896551724137931), 'f1_0': np.float64(0.1), 'f1_1': np.float64(0.8524590163934426), 'f1_macro': 0.4762295081967213, 'f1_weighted': 0.7146848302932347, 'precision_macro': 0.4776785714285714, 'recall_macro': 0.48673740053050396, 'balanced_accuracy': 0.48673740053050396, 'mcc': -0.034411635632722946, 'specificity': np.float64(0.07692307692307693), 'sensitivity': np.float64(0.896551724137931), 'TN': 1, 'FP': 12, 'FN': 6, 'TP': 52, 'score_source': 'continuous', 'auroc': 0.5702917771883289, 'ap_0': 0.20945705133294804, 'ap_1': 0.8874513733144761, 'scenario': 'baseline', 'model': 'MLP', 'outer_fold': 8, 'params': {'alpha': 0.01, 'hidden_layer_sizes': (32, 16), 'max_iter': 500}, 'inner_f1_macro': 0.47140290156308245}
Fase 1 LR {'accuracy': 0.8169014084507042, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8169014084507042), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8992248062015504), 'f1_macro': 0.4496124031007752, 'f1_weighted': 0.7345780106998581, 'precision_macro': 0.4084507042253521, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 13, 'FN': 0, 'TP': 58, 'score_source': 'continuous', 'auroc': 0.6525198938992042, 'ap_0': 0.2790178520557393, 'ap_1': 0.8955898450932248, 'scenario': 'baseline', 'model': 'LR', 'outer_fold': 8, 'params': {'C': 0.01, 'max_iter': 1000, 'solver': 'lbfgs'}, 'inner_f1_macro': 0.449488279960383}
Fase 1 XGB {'accuracy': 0.8169014084507042, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8169014084507042), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8992248062015504), 'f1_macro': 0.4496124031007752, 'f1_weighted': 0.7345780106998581, 'precision_macro': 0.4084507042253521, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 13, 'FN': 0, 'TP': 58, 'score_source': 'continuous', 'auroc': 0.6180371352785146, 'ap_0': 0.32497638527050293, 'ap_1': 0.8755409193729942, 'scenario': 'baseline', 'model': 'XGB', 'outer_fold': 8, 'params': {'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 200}, 'inner_f1_macro': 0.4789153194731625}
Fase 1 NB {'accuracy': 0.704225352112676, 'precision_0': np.float64(0.21428571428571427), 'precision_1': np.float64(0.8245614035087719), 'recall_0': np.float64(0.23076923076923078), 'recall_1': np.float64(0.8103448275862069), 'f1_0': np.float64(0.2222222222222222), 'f1_1': np.float64(0.8173913043478261), 'f1_macro': 0.5198067632850242, 'f1_weighted': 0.7084166836769409, 'precision_macro': 0.5194235588972431, 'recall_macro': 0.5205570291777188, 'balanced_accuracy': 0.5205570291777188, 'mcc': 0.03996451761178992, 'specificity': np.float64(0.23076923076923078), 'sensitivity': np.float64(0.8103448275862069), 'TN': 3, 'FP': 10, 'FN': 11, 'TP': 47, 'score_source': 'continuous', 'auroc': 0.6087533156498675, 'ap_0': 0.2544034493627609, 'ap_1': 0.8779615021694243, 'scenario': 'baseline', 'model': 'NB', 'outer_fold': 8, 'params': {'var_smoothing': 1e-11}, 'inner_f1_macro': 0.49591613627681796}

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(

Fase 1 NC {'accuracy': 0.4647887323943662, 'precision_0': np.float64(0.16216216216216217), 'precision_1': np.float64(0.7941176470588235), 'recall_0': np.float64(0.46153846153846156), 'recall_1': np.float64(0.46551724137931033), 'f1_0': np.float64(0.24), 'f1_1': np.float64(0.5869565217391305), 'f1_macro': 0.41347826086956524, 'f1_weighted': 0.5234292712798531, 'precision_macro': 0.4781399046104928, 'recall_macro': 0.463527851458886, 'balanced_accuracy': 0.463527851458886, 'mcc': -0.0564724586384913, 'specificity': np.float64(0.46153846153846156), 'sensitivity': np.float64(0.46551724137931033), 'TN': 6, 'FP': 7, 'FN': 31, 'TP': 27, 'score_source': 'unavailable', 'auroc': nan, 'ap_0': nan, 'ap_1': nan, 'scenario': 'baseline', 'model': 'NC', 'outer_fold': 8, 'params': {'metric': 'manhattan', 'shrink_threshold': 0.1}, 'inner_f1_macro': 0.45971018879340153}
2026-09-13 19:45:10,649 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:45:10,650 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:45:10,650 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:45:10,651 - opfython.core.opf — INFO — Class created.
2026-09-13 19:45:10,651 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:45:10,652 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:45:10,657 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:45:10,758 - opfython.models.supervised — DEBUG — Prototypes: [416, 350, 49, 93, 459, 91, 210, 304, 415, 35, 347, 464, 45, 20, 273, 310, 297, 502, 134, 390, 248, 115, 94, 21, 438, 235, 436, 250, 140, 500, 242, 420, 256, 348, 135, 159, 50, 454, 281, 443, 282, 422, 143, 402, 83, 382, 351, 476, 98, 398, 479, 309, 60, 141, 6, 405, 397, 470, 22, 321, 44, 73, 244, 314, 510, 340, 277, 241, 171, 509, 209, 139, 356, 160, 130, 24, 64, 183, 9, 263, 129, 66, 12, 279, 112, 65, 372, 223, 14, 258, 330, 399, 149, 63, 166, 205, 230, 124, 418, 353, 71, 323, 374, 221, 27, 327, 301, 434, 404, 28, 317, 423, 270, 302, 30, 96, 386, 172, 16, 288, 196, 429, 194, 202, 432, 409, 406, 151, 371, 219, 467, 287, 17, 179, 346, 271, 363, 506, 472, 148, 106, 507, 2, 76, 80, 82, 462, 1, 153, 339, 225, 300, 445, 453, 468, 417, 262, 396, 67, 58, 379, 485, 145, 23, 158, 303, 59, 204, 229, 178, 113, 311, 13, 216, 195, 137, 92, 344, 41, 480, 125, 198, 246, 316, 186, 232, 200, 366, 161, 433, 240, 253, 128, 428, 378, 122, 471, 192, 295, 444, 150, 294, 218, 175, 191, 357, 43, 286, 147, 305, 231, 77, 458, 119, 490, 51, 498, 84, 376, 222, 74, 249].

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(

2026-09-13 19:45:10,990 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:45:10,991 - opfython.models.supervised — INFO — Training time: 0.33847999572753906 seconds.
2026-09-13 19:45:10,991 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:45:11,087 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:45:11,088 - opfython.models.supervised — INFO — Prediction time: 0.09631228446960449 seconds.
2026-09-13 19:45:11,099 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:45:11,099 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:45:11,100 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:45:11,101 - opfython.core.opf — INFO — Class created.
2026-09-13 19:45:11,102 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:45:11,103 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:45:11,104 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:45:11,202 - opfython.models.supervised — DEBUG — Prototypes: [316, 66, 416, 342, 325, 274, 494, 118, 410, 108, 53, 222, 72, 365, 460, 161, 128, 19, 109, 300, 32, 415, 465, 339, 322, 306, 448, 401, 399, 148, 499, 387, 254, 177, 242, 436, 110, 489, 218, 234, 420, 256, 157, 240, 507, 248, 371, 340, 149, 181, 54, 402, 281, 343, 374, 113, 2, 219, 137, 64, 329, 132, 479, 111, 386, 7, 405, 394, 305, 338, 67, 309, 106, 151, 250, 476, 196, 20, 313, 48, 258, 169, 247, 130, 508, 430, 129, 404, 139, 418, 223, 65, 318, 38, 187, 77, 435, 347, 83, 315, 24, 117, 188, 263, 155, 509, 71, 73, 8, 107, 75, 13, 243, 278, 510, 214, 50, 314, 444, 69, 310, 230, 406, 332, 454, 447, 208, 271, 180, 93, 269, 1, 185, 285, 9, 326, 311, 225, 142, 119, 168, 506, 288, 382, 481, 413, 178, 192, 15, 487, 392, 17, 469, 417, 55, 104, 319, 91, 98, 432, 353, 377, 211, 393, 78, 264, 486, 165, 21, 179, 299, 63, 215, 236, 485, 279, 442, 136, 345, 226, 207, 85, 362, 44, 334, 126, 307, 152, 210, 105, 261, 357, 359, 96, 182, 43, 389, 429, 246, 259, 206, 298, 47, 293, 376, 461, 466, 495, 228, 167, 351, 194, 204, 513, 301, 89, 88, 133, 478, 213, 195, 379, 373, 190, 86, 79, 255, 505, 328].
2026-09-13 19:45:11,408 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:45:11,409 - opfython.models.supervised — INFO — Training time: 0.3058481216430664 seconds.
2026-09-13 19:45:11,410 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:45:11,514 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:45:11,515 - opfython.models.supervised — INFO — Prediction time: 0.10366201400756836 seconds.
2026-09-13 19:45:11,526 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:45:11,526 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:45:11,527 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:45:11,527 - opfython.core.opf — INFO — Class created.
2026-09-13 19:45:11,528 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:45:11,528 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:45:11,531 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:45:11,643 - opfython.models.supervised — DEBUG — Prototypes: [241, 371, 318, 334, 165, 238, 282, 118, 138, 38, 506, 160, 504, 364, 471, 2, 87, 295, 167, 338, 391, 66, 416, 184, 77, 432, 355, 325, 41, 80, 322, 229, 233, 445, 243, 115, 185, 24, 74, 151, 358, 9, 275, 105, 141, 224, 50, 161, 123, 442, 71, 17, 327, 270, 164, 101, 261, 496, 245, 228, 332, 256, 359, 268, 306, 132, 414, 34, 350, 462, 51, 283, 329, 446, 404, 402, 454, 498, 333, 108, 54, 218, 106, 488, 457, 104, 415, 411, 68, 251, 433, 112, 43, 440, 290, 419, 280, 348, 98, 451, 289, 405, 384, 352, 378, 1, 388, 176, 230, 130, 65, 110, 69, 479, 22, 49, 264, 321, 82, 257, 474, 315, 147, 163, 28, 109, 408, 222, 372, 303, 192, 19, 293, 427, 410, 214, 482, 220, 225, 484, 288, 247, 55, 491, 326, 90, 96, 420, 396, 62, 380, 273, 13, 390, 83, 235, 485, 23, 305, 64, 196, 15, 217, 317, 259, 134, 354, 239, 286, 480, 136, 150, 148, 205, 249, 413, 173, 269, 140, 424, 374, 362, 395, 187, 458, 463, 428, 265, 271, 379, 300, 212, 370, 162, 299, 234, 407, 494, 360, 46, 465, 307, 339, 88, 86, 248, 489, 56, 478, 252, 487, 195, 11, 377, 189, 84, 260, 505, 336].
2026-09-13 19:45:11,865 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:45:11,866 - opfython.models.supervised — INFO — Training time: 0.33725547790527344 seconds.
2026-09-13 19:45:11,868 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:45:11,963 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:45:11,964 - opfython.models.supervised — INFO — Prediction time: 0.0954122543334961 seconds.
2026-09-13 19:45:11,975 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:45:11,976 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:45:11,977 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:45:11,977 - opfython.core.opf — INFO — Class created.
2026-09-13 19:45:11,978 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:45:11,978 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:45:11,982 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:45:12,086 - opfython.models.supervised — DEBUG — Prototypes: [324, 66, 333, 285, 106, 115, 55, 212, 490, 72, 227, 34, 349, 35, 51, 311, 406, 405, 143, 469, 123, 23, 105, 43, 391, 263, 170, 489, 441, 222, 244, 332, 423, 264, 151, 499, 256, 270, 350, 144, 174, 56, 457, 291, 347, 97, 448, 156, 424, 407, 352, 380, 109, 1, 224, 129, 310, 107, 390, 63, 336, 126, 6, 7, 314, 103, 146, 258, 84, 24, 49, 267, 164, 255, 125, 507, 340, 287, 228, 131, 421, 64, 440, 77, 326, 40, 452, 238, 377, 27, 114, 181, 273, 436, 409, 28, 25, 139, 70, 149, 225, 356, 458, 509, 145, 284, 9, 104, 138, 75, 14, 209, 288, 510, 218, 71, 374, 240, 50, 162, 308, 17, 329, 272, 402, 317, 450, 68, 456, 67, 306, 435, 413, 282, 297, 208, 216, 214, 90, 96, 464, 236, 210, 467, 373, 296, 10, 195, 318, 165, 348, 283, 362, 2, 472, 504, 134, 432, 37, 88, 161, 300, 387, 167, 338, 242, 417, 171, 482, 399, 21, 275, 85, 230, 57, 494, 327, 89, 95, 360, 426, 382, 213, 486, 158, 219, 246, 485, 289, 194, 121, 312, 447, 128, 354, 211, 316, 261, 414, 169, 147, 480, 132, 430, 366, 93, 364, 271, 369, 45, 396, 201, 248, 30, 137, 343, 462, 466, 302, 48, 295, 206, 176, 186, 235, 496, 449, 160, 229, 358, 163, 451, 514, 190, 65, 492, 58, 497, 479, 192, 193, 385, 505, 335].
2026-09-13 19:45:12,293 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:45:12,294 - opfython.models.supervised — INFO — Training time: 0.31557393074035645 seconds.
2026-09-13 19:45:12,295 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:45:12,395 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:45:12,396 - opfython.models.supervised — INFO — Prediction time: 0.1007380485534668 seconds.
2026-09-13 19:45:12,409 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:45:12,410 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:45:12,410 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:45:12,411 - opfython.core.opf — INFO — Class created.
2026-09-13 19:45:12,411 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:45:12,412 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:45:12,413 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:45:12,516 - opfython.models.supervised — DEBUG — Prototypes: [321, 62, 417, 349, 329, 279, 105, 494, 201, 411, 104, 220, 69, 462, 101, 124, 19, 47, 278, 326, 449, 305, 18, 30, 29, 117, 407, 405, 145, 500, 391, 255, 168, 106, 242, 438, 336, 216, 151, 328, 419, 281, 347, 146, 455, 286, 95, 345, 446, 287, 421, 177, 384, 218, 132, 309, 129, 479, 49, 6, 7, 400, 107, 114, 264, 178, 74, 439, 353, 134, 235, 221, 79, 23, 448, 232, 374, 435, 126, 21, 512, 67, 277, 283, 511, 212, 68, 72, 269, 371, 234, 46, 159, 13, 262, 303, 402, 275, 314, 409, 25, 444, 184, 15, 301, 60, 300, 206, 292, 319, 249, 90, 127, 210, 89, 94, 465, 1, 291, 9, 231, 469, 330, 315, 163, 346, 276, 136, 116, 363, 430, 3, 294, 386, 334, 236, 228, 399, 57, 75, 93, 360, 491, 50, 87, 423, 20, 304, 59, 284, 485, 445, 11, 223, 81, 340, 42, 364, 17, 368, 398, 366, 91, 434, 259, 248, 41, 396, 138, 428, 123, 393, 191, 463, 381, 415, 426, 418, 193, 470, 480, 307, 45, 290, 187, 202, 160, 297, 199, 169, 77, 85, 83, 239, 490, 51, 496, 378, 182, 189, 190, 82, 76, 506, 99].
2026-09-13 19:45:12,723 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:45:12,724 - opfython.models.supervised — INFO — Training time: 0.31194281578063965 seconds.
2026-09-13 19:45:12,724 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:45:12,817 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:45:12,818 - opfython.models.supervised — INFO — Prediction time: 0.09330534934997559 seconds.
2026-09-13 19:45:12,831 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:45:12,832 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:45:12,833 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:45:12,833 - opfython.core.opf — INFO — Class created.
2026-09-13 19:45:12,834 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:45:12,835 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:45:12,837 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:45:12,934 - opfython.models.supervised — DEBUG — Prototypes: [416, 350, 49, 93, 459, 91, 210, 333, 304, 120, 415, 35, 347, 45, 273, 332, 448, 502, 134, 107, 436, 235, 438, 250, 140, 500, 443, 282, 422, 143, 454, 281, 382, 402, 83, 159, 50, 348, 135, 479, 351, 307, 98, 314, 92, 22, 44, 244, 73, 139, 302, 209, 356, 160, 130, 24, 64, 183, 9, 263, 129, 279, 112, 66, 12, 372, 223, 151, 87, 71, 195, 323, 166, 205, 230, 124, 418, 327, 26, 353, 27, 374, 221, 317, 434, 404, 390, 398, 115, 21, 94, 202, 65, 288, 321, 196, 80, 1, 462, 287, 336, 371, 219, 467, 17, 363, 506, 472, 148, 106, 507, 2, 76, 153, 322, 14, 330, 262, 396, 67, 58, 379, 360, 204, 229, 13, 23, 158, 6, 7, 397, 60, 141, 485, 145, 271, 399, 470, 339, 225, 178, 509, 149, 242, 420, 256, 270, 30, 96, 59, 241, 113, 311, 433, 240, 432, 409, 429, 277, 340, 442, 445, 408, 198, 316, 246, 194, 172, 16, 423, 453, 254, 208, 366, 161, 137, 450, 344, 474, 41, 186, 114, 468, 417, 162, 303, 296, 216, 490, 498, 53, 150, 446, 378, 480, 192, 175, 191, 128, 428, 43, 286, 68, 122, 471, 231, 295, 218, 444, 77, 458, 376, 214, 255, 74, 391].
2026-09-13 19:45:13,140 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:45:13,141 - opfython.models.supervised — INFO — Training time: 0.30512452125549316 seconds.
2026-09-13 19:45:13,142 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:45:13,235 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:45:13,236 - opfython.models.supervised — INFO — Prediction time: 0.09399294853210449 seconds.
2026-09-13 19:45:13,247 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:45:13,247 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:45:13,248 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:45:13,248 - opfython.core.opf — INFO — Class created.
2026-09-13 19:45:13,249 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:45:13,249 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:45:13,253 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:45:13,354 - opfython.models.supervised — DEBUG — Prototypes: [316, 66, 416, 342, 325, 274, 494, 118, 410, 108, 53, 222, 72, 128, 19, 109, 365, 460, 161, 322, 273, 448, 300, 415, 32, 465, 339, 401, 92, 148, 499, 120, 242, 436, 110, 256, 157, 218, 234, 420, 338, 303, 402, 329, 340, 149, 181, 54, 219, 137, 64, 479, 111, 386, 132, 7, 405, 394, 20, 101, 48, 196, 250, 476, 169, 309, 106, 191, 343, 113, 2, 254, 387, 395, 139, 418, 223, 65, 318, 38, 187, 77, 435, 347, 24, 83, 315, 155, 135, 220, 509, 455, 150, 73, 71, 8, 107, 278, 124, 75, 13, 214, 243, 310, 230, 170, 102, 406, 430, 404, 177, 208, 240, 93, 270, 1, 285, 9, 326, 311, 225, 142, 119, 168, 506, 413, 178, 55, 319, 21, 179, 98, 353, 377, 61, 393, 78, 264, 215, 236, 279, 485, 67, 486, 165, 117, 188, 288, 35, 382, 248, 350, 489, 508, 442, 444, 69, 481, 247, 130, 63, 429, 246, 426, 337, 268, 357, 126, 307, 261, 392, 17, 332, 182, 192, 15, 210, 105, 271, 180, 152, 281, 359, 372, 450, 334, 475, 44, 469, 417, 85, 397, 43, 226, 207, 379, 197, 293, 388, 487, 47, 376, 193, 423, 228, 136, 345, 206, 298, 443, 461, 466, 194, 513, 204, 478, 213, 490, 373, 190, 86, 79, 505, 84, 195, 10].
2026-09-13 19:45:13,559 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:45:13,560 - opfython.models.supervised — INFO — Training time: 0.30979251861572266 seconds.
2026-09-13 19:45:13,560 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:45:13,656 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:45:13,657 - opfython.models.supervised — INFO — Prediction time: 0.09611344337463379 seconds.
2026-09-13 19:45:13,668 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:45:13,669 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:45:13,669 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:45:13,670 - opfython.core.opf — INFO — Class created.
2026-09-13 19:45:13,670 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:45:13,671 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:45:13,673 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:45:13,774 - opfython.models.supervised — DEBUG — Prototypes: [241, 371, 318, 165, 138, 118, 38, 506, 160, 87, 504, 364, 471, 2, 167, 184, 77, 432, 355, 325, 41, 66, 416, 229, 233, 80, 322, 445, 243, 24, 74, 151, 231, 358, 452, 509, 146, 9, 275, 105, 141, 224, 50, 215, 304, 164, 101, 306, 132, 414, 34, 350, 462, 51, 283, 329, 446, 404, 91, 454, 498, 333, 108, 54, 218, 106, 488, 457, 104, 251, 433, 415, 119, 68, 261, 496, 228, 332, 245, 440, 290, 419, 280, 348, 98, 451, 289, 384, 405, 388, 65, 337, 130, 110, 352, 1, 22, 163, 49, 82, 257, 408, 315, 258, 293, 321, 17, 327, 230, 55, 491, 326, 90, 96, 186, 420, 396, 62, 380, 23, 174, 15, 235, 83, 225, 116, 247, 69, 176, 282, 107, 390, 43, 295, 161, 510, 487, 222, 372, 256, 359, 268, 442, 71, 482, 479, 288, 484, 28, 109, 64, 220, 428, 334, 427, 410, 217, 196, 485, 317, 259, 214, 192, 19, 178, 303, 266, 338, 391, 286, 376, 148, 395, 187, 205, 125, 370, 179, 305, 343, 473, 239, 413, 173, 269, 150, 58, 383, 198, 265, 162, 443, 300, 379, 271, 134, 354, 441, 212, 465, 458, 463, 140, 424, 480, 207, 248, 40, 489, 478, 377, 189, 84, 78, 505, 81, 195, 11].
2026-09-13 19:45:13,989 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:45:13,990 - opfython.models.supervised — INFO — Training time: 0.31809425354003906 seconds.
2026-09-13 19:45:13,990 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:45:14,085 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:45:14,086 - opfython.models.supervised — INFO — Prediction time: 0.09555888175964355 seconds.
2026-09-13 19:45:14,097 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:45:14,098 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:45:14,099 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:45:14,099 - opfython.core.opf — INFO — Class created.
2026-09-13 19:45:14,100 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:45:14,101 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:45:14,105 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:45:14,206 - opfython.models.supervised — DEBUG — Prototypes: [324, 66, 333, 106, 55, 212, 490, 227, 372, 72, 34, 349, 51, 133, 311, 22, 304, 441, 406, 405, 143, 469, 123, 23, 105, 264, 499, 151, 222, 244, 332, 423, 350, 144, 174, 56, 457, 291, 347, 97, 448, 156, 424, 407, 224, 129, 107, 390, 63, 336, 126, 6, 7, 352, 1, 109, 314, 103, 24, 49, 258, 84, 391, 400, 228, 131, 421, 64, 440, 77, 326, 40, 27, 452, 238, 377, 149, 26, 225, 356, 458, 509, 175, 139, 25, 70, 284, 9, 277, 104, 138, 288, 510, 218, 75, 14, 374, 240, 50, 308, 317, 436, 409, 170, 216, 71, 310, 17, 329, 417, 171, 373, 296, 10, 236, 467, 195, 318, 165, 134, 37, 432, 362, 504, 472, 2, 88, 161, 90, 464, 167, 57, 494, 327, 89, 95, 360, 182, 426, 382, 213, 219, 246, 275, 85, 230, 289, 485, 338, 242, 486, 158, 283, 402, 300, 387, 43, 256, 357, 270, 162, 67, 489, 35, 194, 507, 447, 450, 68, 482, 272, 255, 125, 121, 312, 214, 435, 413, 287, 340, 297, 282, 345, 271, 364, 211, 316, 399, 21, 261, 208, 169, 414, 430, 11, 30, 303, 45, 201, 122, 268, 223, 451, 366, 93, 343, 492, 497, 369, 237, 196, 163, 60, 302, 393, 48, 128, 354, 235, 176, 186, 480, 206, 449, 229, 102, 137, 80, 462, 466, 190, 514, 65, 479, 505, 83, 192].
2026-09-13 19:45:14,420 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:45:14,421 - opfython.models.supervised — INFO — Training time: 0.3197331428527832 seconds.
2026-09-13 19:45:14,422 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:45:14,514 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:45:14,515 - opfython.models.supervised — INFO — Prediction time: 0.09257030487060547 seconds.
2026-09-13 19:45:14,526 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:45:14,527 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:45:14,528 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:45:14,529 - opfython.core.opf — INFO — Class created.
2026-09-13 19:45:14,529 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:45:14,530 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:45:14,534 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:45:14,635 - opfython.models.supervised — DEBUG — Prototypes: [321, 62, 417, 349, 329, 279, 105, 494, 201, 411, 104, 220, 69, 462, 101, 124, 19, 131, 305, 29, 47, 18, 278, 299, 405, 407, 88, 145, 500, 117, 106, 438, 216, 151, 328, 419, 273, 446, 287, 421, 384, 129, 345, 95, 455, 286, 347, 146, 218, 132, 479, 49, 6, 7, 400, 21, 140, 67, 283, 511, 212, 46, 72, 4, 371, 234, 134, 337, 221, 235, 178, 74, 439, 353, 448, 232, 374, 79, 23, 314, 162, 196, 409, 435, 126, 68, 292, 319, 291, 9, 231, 469, 330, 315, 163, 136, 116, 33, 430, 507, 363, 3, 89, 465, 1, 399, 57, 75, 93, 360, 491, 50, 87, 180, 423, 100, 11, 20, 376, 284, 485, 334, 236, 107, 276, 13, 303, 223, 81, 402, 294, 386, 159, 391, 168, 206, 487, 445, 275, 25, 434, 248, 59, 210, 281, 336, 429, 249, 90, 127, 343, 364, 184, 15, 260, 217, 171, 300, 242, 366, 298, 41, 172, 304, 123, 191, 398, 17, 340, 42, 490, 496, 228, 40, 381, 199, 169, 45, 160, 425, 186, 415, 426, 470, 418, 480, 187, 202, 463, 138, 428, 77, 239, 35, 461, 85, 378, 225, 82, 76, 506, 128, 189, 509].
2026-09-13 19:45:14,845 - opfython.models.supervised — INFO — Classifier has been fitted.

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

Fase 1 MLP {'accuracy': 0.676056338028169, 'precision_0': np.float64(0.08333333333333333), 'precision_1': np.float64(0.7966101694915254), 'recall_0': np.float64(0.07692307692307693), 'recall_1': np.float64(0.8103448275862069), 'f1_0': np.float64(0.08), 'f1_1': np.float64(0.8034188034188035), 'f1_macro': 0.4417094017094017, 'f1_weighted': 0.6709618394125437, 'precision_macro': 0.4399717514124294, 'recall_macro': 0.44363395225464186, 'balanced_accuracy': 0.44363395225464186, 'mcc': -0.11633666878430429, 'specificity': np.float64(0.07692307692307693), 'sensitivity': np.float64(0.8103448275862069), 'TN': 1, 'FP': 12, 'FN': 11, 'TP': 47, 'score_source': 'continuous', 'auroc': 0.47015915119363394, 'ap_0': 0.17102680014084792, 'ap_1': 0.8513133750999274, 'scenario': 'baseline', 'model': 'MLP', 'outer_fold': 9, 'params': {'alpha': 0.01, 'hidden_layer_sizes': (32, 16), 'max_iter': 500}, 'inner_f1_macro': 0.5166947697484768}
Fase 1 LR {'accuracy': 0.8169014084507042, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8169014084507042), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8992248062015504), 'f1_macro': 0.4496124031007752, 'f1_weighted': 0.7345780106998581, 'precision_macro': 0.4084507042253521, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 13, 'FN': 0, 'TP': 58, 'score_source': 'continuous', 'auroc': 0.5086206896551724, 'ap_0': 0.1948286200337225, 'ap_1': 0.8494561999780901, 'scenario': 'baseline', 'model': 'LR', 'outer_fold': 9, 'params': {'C': 0.01, 'max_iter': 1000, 'solver': 'lbfgs'}, 'inner_f1_macro': 0.449488279960383}
Fase 1 XGB {'accuracy': 0.8028169014084507, 'precision_0': np.float64(0.3333333333333333), 'precision_1': np.float64(0.8235294117647058), 'recall_0': np.float64(0.07692307692307693), 'recall_1': np.float64(0.9655172413793104), 'f1_0': np.float64(0.125), 'f1_1': np.float64(0.8888888888888888), 'f1_macro': 0.5069444444444444, 'f1_weighted': 0.7490219092331768, 'precision_macro': 0.5784313725490196, 'recall_macro': 0.5212201591511937, 'balanced_accuracy': 0.5212201591511937, 'mcc': 0.08159230865557747, 'specificity': np.float64(0.07692307692307693), 'sensitivity': np.float64(0.9655172413793104), 'TN': 1, 'FP': 12, 'FN': 2, 'TP': 56, 'score_source': 'continuous', 'auroc': 0.4582228116710876, 'ap_0': 0.23902623271080614, 'ap_1': 0.8147156099994289, 'scenario': 'baseline', 'model': 'XGB', 'outer_fold': 9, 'params': {'learning_rate': 0.05, 'max_depth': 5, 'n_estimators': 200}, 'inner_f1_macro': 0.4849378617383017}
Fase 1 NB {'accuracy': 0.6901408450704225, 'precision_0': np.float64(0.15384615384615385), 'precision_1': np.float64(0.8103448275862069), 'recall_0': np.float64(0.15384615384615385), 'recall_1': np.float64(0.8103448275862069), 'f1_0': np.float64(0.15384615384615385), 'f1_1': np.float64(0.8103448275862069), 'f1_macro': 0.48209549071618035, 'f1_weighted': 0.6901408450704225, 'precision_macro': 0.48209549071618035, 'recall_macro': 0.48209549071618035, 'balanced_accuracy': 0.48209549071618035, 'mcc': -0.03580901856763926, 'specificity': np.float64(0.15384615384615385), 'sensitivity': np.float64(0.8103448275862069), 'TN': 2, 'FP': 11, 'FN': 11, 'TP': 47, 'score_source': 'continuous', 'auroc': 0.5789124668435013, 'ap_0': 0.2506788925959049, 'ap_1': 0.8821864767439539, 'scenario': 'baseline', 'model': 'NB', 'outer_fold': 9, 'params': {'var_smoothing': 1e-11}, 'inner_f1_macro': 0.5045018977655392}

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(

Fase 1 NC {'accuracy': 0.5070422535211268, 'precision_0': np.float64(0.19444444444444445), 'precision_1': np.float64(0.8285714285714286), 'recall_0': np.float64(0.5384615384615384), 'recall_1': np.float64(0.5), 'f1_0': np.float64(0.2857142857142857), 'f1_1': np.float64(0.6236559139784946), 'f1_macro': 0.45468509984639016, 'f1_weighted': 0.5617792778174423, 'precision_macro': 0.5115079365079366, 'recall_macro': 0.5192307692307692, 'balanced_accuracy': 0.5192307692307692, 'mcc': 0.02975274584346603, 'specificity': np.float64(0.5384615384615384), 'sensitivity': np.float64(0.5), 'TN': 7, 'FP': 6, 'FN': 29, 'TP': 29, 'score_source': 'continuous', 'auroc': 0.5404509283819627, 'ap_0': 0.22197259577164868, 'ap_1': 0.8640061546115461, 'scenario': 'baseline', 'model': 'NC', 'outer_fold': 9, 'params': {'metric': 'euclidean', 'shrink_threshold': None}, 'inner_f1_macro': 0.4731195760684771}
2026-09-13 19:45:50,574 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:45:50,575 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:45:50,576 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:45:50,577 - opfython.core.opf — INFO — Class created.
2026-09-13 19:45:50,577 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:45:50,578 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:45:50,579 - opfython.models.supervised — DEBUG — Finding prototypes ...

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(

2026-09-13 19:45:50,682 - opfython.models.supervised — DEBUG — Prototypes: [52, 93, 458, 90, 220, 333, 312, 448, 128, 302, 403, 35, 470, 351, 36, 466, 307, 417, 401, 400, 455, 499, 37, 159, 242, 101, 118, 22, 94, 44, 379, 255, 497, 487, 215, 236, 336, 421, 248, 261, 453, 287, 76, 38, 339, 495, 478, 86, 443, 288, 423, 387, 353, 382, 99, 169, 53, 352, 140, 217, 126, 481, 96, 393, 311, 348, 471, 62, 104, 364, 6, 7, 398, 431, 316, 91, 74, 250, 23, 501, 324, 257, 156, 293, 278, 31, 95, 15, 263, 49, 158, 75, 504, 64, 456, 194, 279, 25, 166, 8, 92, 135, 47, 325, 232, 269, 329, 39, 73, 476, 129, 419, 377, 230, 28, 445, 282, 435, 404, 319, 2, 301, 157, 87, 328, 276, 168, 406, 283, 341, 63, 433, 409, 182, 17, 80, 271, 464, 1, 171, 320, 190, 225, 18, 228, 376, 277, 109, 131, 505, 154, 251, 78, 295, 389, 397, 20, 210, 451, 205, 349, 482, 130, 374, 143, 83, 281, 24, 167, 306, 61, 209, 384, 151, 285, 486, 442, 125, 354, 116, 313, 189, 184, 134, 430, 434, 258, 247, 369, 275, 415, 441, 262, 383, 203, 418, 469, 42, 459, 467, 299, 444, 492, 155, 298, 221, 46, 292, 371, 513, 362, 185, 202, 308, 196, 489, 494, 122, 239, 187, 188, 56, 216, 381, 179, 509].
2026-09-13 19:45:50,895 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:45:50,895 - opfython.models.supervised — INFO — Training time: 0.3174779415130615 seconds.
2026-09-13 19:45:50,896 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:45:50,994 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:45:50,995 - opfython.models.supervised — INFO — Prediction time: 0.09785985946655273 seconds.
2026-09-13 19:45:51,005 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:45:51,006 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:45:51,007 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:45:51,007 - opfython.core.opf — INFO — Class created.
2026-09-13 19:45:51,008 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:45:51,008 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:45:51,010 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:45:51,111 - opfython.models.supervised — DEBUG — Prototypes: [319, 68, 56, 111, 219, 460, 166, 107, 404, 34, 33, 343, 304, 416, 461, 145, 52, 309, 324, 448, 142, 300, 124, 401, 472, 456, 498, 473, 130, 20, 110, 178, 248, 437, 496, 260, 207, 161, 254, 420, 65, 340, 102, 88, 329, 402, 345, 379, 115, 2, 190, 315, 66, 134, 308, 113, 140, 69, 312, 108, 155, 21, 316, 50, 202, 174, 291, 278, 356, 7, 8, 396, 431, 405, 86, 477, 318, 195, 80, 436, 350, 226, 418, 447, 237, 375, 120, 196, 71, 154, 458, 208, 279, 77, 13, 283, 127, 176, 87, 500, 372, 239, 74, 341, 15, 54, 265, 313, 3, 299, 407, 276, 302, 444, 423, 73, 429, 410, 361, 501, 475, 293, 38, 314, 177, 235, 371, 277, 96, 465, 1, 193, 332, 241, 221, 470, 417, 394, 18, 57, 106, 321, 95, 101, 433, 358, 382, 64, 395, 81, 284, 487, 442, 139, 347, 89, 267, 481, 144, 205, 187, 269, 310, 203, 336, 46, 156, 273, 364, 192, 303, 148, 426, 430, 262, 45, 392, 218, 360, 462, 468, 482, 366, 98, 337, 297, 72, 49, 290, 381, 172, 173, 296, 229, 354, 305, 199, 513, 93, 92, 214, 508, 122, 201, 378, 238, 90, 82, 259, 502, 328].
2026-09-13 19:45:51,323 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:45:51,324 - opfython.models.supervised — INFO — Training time: 0.31481170654296875 seconds.
2026-09-13 19:45:51,324 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:45:51,417 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:45:51,418 - opfython.models.supervised — INFO — Prediction time: 0.09276604652404785 seconds.
2026-09-13 19:45:51,429 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:45:51,430 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:45:51,431 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:45:51,431 - opfython.core.opf — INFO — Class created.
2026-09-13 19:45:51,432 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:45:51,433 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:45:51,435 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:45:51,533 - opfython.models.supervised — DEBUG — Prototypes: [320, 173, 144, 119, 40, 503, 168, 501, 368, 472, 90, 299, 415, 182, 340, 394, 353, 391, 451, 294, 350, 98, 420, 101, 440, 405, 385, 240, 138, 369, 132, 481, 58, 109, 23, 52, 497, 267, 323, 84, 261, 317, 153, 170, 457, 143, 331, 313, 304, 139, 284, 407, 36, 464, 120, 404, 402, 453, 496, 456, 104, 57, 107, 106, 230, 469, 325, 69, 127, 434, 257, 37, 242, 238, 252, 334, 495, 48, 380, 486, 262, 85, 500, 172, 292, 25, 75, 8, 105, 147, 77, 15, 376, 249, 74, 53, 351, 18, 308, 328, 43, 193, 236, 358, 433, 83, 475, 417, 140, 13, 445, 247, 327, 171, 442, 289, 29, 108, 44, 6, 411, 399, 7, 274, 306, 290, 356, 428, 72, 423, 232, 201, 20, 24, 67, 309, 183, 59, 103, 329, 93, 421, 398, 80, 65, 276, 86, 275, 16, 293, 125, 314, 208, 482, 142, 203, 226, 374, 136, 272, 229, 319, 370, 371, 95, 379, 365, 458, 465, 217, 254, 384, 345, 137, 471, 47, 146, 354, 128, 224, 307, 491, 466, 51, 297, 167, 169, 443, 222, 204, 513, 302, 441, 310, 91, 89, 489, 60, 507, 117, 206, 207, 87, 265, 62, 239, 502, 337].
2026-09-13 19:45:51,743 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:45:51,743 - opfython.models.supervised — INFO — Training time: 0.31009936332702637 seconds.
2026-09-13 19:45:51,744 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:45:51,833 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:45:51,834 - opfython.models.supervised — INFO — Prediction time: 0.08962345123291016 seconds.
2026-09-13 19:45:51,845 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:45:51,846 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:45:51,846 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:45:51,847 - opfython.core.opf — INFO — Class created.
2026-09-13 19:45:51,847 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:45:51,848 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:45:51,850 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:45:51,950 - opfython.models.supervised — DEBUG — Prototypes: [326, 68, 59, 108, 106, 420, 311, 131, 36, 352, 461, 32, 54, 314, 135, 496, 485, 407, 405, 469, 126, 24, 107, 257, 442, 113, 171, 207, 270, 156, 234, 251, 424, 504, 263, 459, 48, 488, 275, 448, 298, 425, 287, 86, 336, 477, 43, 350, 99, 456, 297, 408, 355, 385, 1, 353, 148, 182, 60, 235, 133, 313, 130, 66, 109, 395, 481, 433, 317, 104, 151, 265, 85, 422, 136, 190, 79, 441, 328, 44, 13, 246, 381, 452, 28, 116, 191, 437, 409, 26, 505, 74, 70, 290, 8, 105, 143, 76, 15, 294, 123, 230, 378, 248, 73, 324, 53, 351, 18, 276, 56, 288, 180, 320, 2, 307, 411, 450, 292, 333, 363, 6, 7, 401, 293, 341, 302, 199, 220, 228, 261, 244, 377, 289, 140, 170, 121, 40, 502, 368, 472, 91, 168, 94, 465, 186, 339, 250, 418, 179, 226, 280, 400, 80, 64, 387, 87, 279, 98, 365, 438, 61, 103, 329, 93, 427, 367, 16, 295, 447, 487, 25, 291, 65, 132, 357, 224, 319, 482, 138, 125, 315, 204, 383, 152, 371, 436, 262, 272, 47, 399, 211, 254, 31, 111, 382, 364, 345, 51, 305, 71, 218, 513, 494, 167, 238, 362, 216, 202, 514, 92, 90, 491, 62, 495, 253, 507, 119, 203, 344, 384, 196, 88, 269, 503, 335].
2026-09-13 19:45:52,157 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:45:52,157 - opfython.models.supervised — INFO — Training time: 0.30930662155151367 seconds.
2026-09-13 19:45:52,158 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:45:52,248 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:45:52,248 - opfython.models.supervised — INFO — Prediction time: 0.09007453918457031 seconds.
2026-09-13 19:45:52,259 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:45:52,260 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:45:52,261 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:45:52,262 - opfython.core.opf — INFO — Class created.
2026-09-13 19:45:52,262 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:45:52,263 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:45:52,264 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:45:52,367 - opfython.models.supervised — DEBUG — Prototypes: [323, 64, 461, 103, 232, 105, 409, 132, 308, 31, 349, 468, 462, 138, 328, 302, 18, 279, 497, 120, 457, 170, 473, 33, 440, 227, 155, 330, 420, 261, 495, 45, 381, 254, 402, 265, 280, 446, 292, 422, 84, 494, 454, 97, 389, 407, 181, 52, 350, 395, 148, 229, 311, 130, 62, 480, 65, 352, 310, 110, 2, 431, 20, 47, 256, 82, 296, 284, 251, 136, 188, 77, 439, 357, 326, 40, 81, 24, 11, 380, 228, 325, 167, 25, 448, 22, 143, 37, 67, 459, 203, 7, 273, 142, 418, 290, 124, 168, 83, 502, 71, 74, 275, 377, 398, 282, 179, 316, 3, 288, 338, 196, 15, 364, 26, 108, 436, 224, 92, 467, 1, 277, 239, 376, 317, 16, 169, 236, 331, 195, 393, 283, 119, 139, 36, 505, 165, 503, 367, 88, 298, 391, 216, 336, 240, 417, 177, 213, 221, 69, 426, 471, 419, 270, 401, 78, 59, 386, 85, 269, 53, 438, 91, 424, 96, 365, 21, 178, 307, 61, 12, 392, 217, 315, 400, 17, 371, 94, 266, 435, 253, 205, 245, 43, 341, 44, 134, 373, 90, 115, 125, 162, 141, 430, 385, 118, 343, 491, 166, 300, 434, 378, 212, 362, 463, 354, 469, 89, 87, 244, 460, 131, 489, 493, 383, 193, 86, 79, 504, 333].
2026-09-13 19:45:52,567 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:45:52,568 - opfython.models.supervised — INFO — Training time: 0.30511021614074707 seconds.
2026-09-13 19:45:52,569 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:45:52,661 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:45:52,662 - opfython.models.supervised — INFO — Prediction time: 0.0921933650970459 seconds.
2026-09-13 19:45:52,674 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:45:52,675 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:45:52,676 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:45:52,676 - opfython.core.opf — INFO — Class created.
2026-09-13 19:45:52,677 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:45:52,677 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:45:52,679 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:45:52,782 - opfython.models.supervised — DEBUG — Prototypes: [52, 93, 458, 90, 220, 334, 403, 35, 470, 417, 307, 351, 36, 466, 139, 333, 312, 448, 128, 302, 496, 485, 401, 455, 499, 37, 159, 242, 101, 254, 44, 379, 487, 255, 497, 443, 288, 423, 274, 76, 339, 495, 478, 453, 287, 387, 348, 310, 169, 53, 352, 140, 217, 126, 96, 393, 481, 353, 99, 316, 91, 23, 501, 278, 74, 250, 156, 324, 8, 92, 64, 279, 456, 194, 135, 142, 25, 136, 75, 158, 504, 47, 232, 269, 15, 49, 129, 419, 329, 39, 73, 476, 28, 377, 230, 319, 2, 157, 87, 276, 168, 236, 215, 336, 421, 406, 435, 404, 328, 118, 22, 94, 293, 325, 228, 376, 320, 190, 225, 181, 109, 131, 505, 154, 78, 251, 80, 464, 1, 207, 24, 167, 330, 83, 285, 486, 395, 295, 389, 471, 62, 277, 445, 282, 248, 361, 261, 283, 341, 6, 409, 398, 7, 507, 442, 209, 384, 11, 151, 63, 31, 95, 306, 61, 434, 247, 210, 371, 513, 433, 431, 205, 397, 20, 270, 369, 275, 301, 182, 17, 144, 116, 313, 189, 143, 318, 196, 165, 184, 42, 489, 494, 344, 43, 259, 216, 415, 441, 262, 299, 155, 446, 383, 203, 386, 56, 46, 125, 354, 444, 482, 399, 469, 418, 134, 430, 459, 467, 239, 475, 185, 202, 381, 179, 187, 345].
2026-09-13 19:45:52,992 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:45:52,993 - opfython.models.supervised — INFO — Training time: 0.31549620628356934 seconds.
2026-09-13 19:45:52,993 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:45:53,088 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:45:53,091 - opfython.models.supervised — INFO — Prediction time: 0.09749937057495117 seconds.
2026-09-13 19:45:53,105 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:45:53,106 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:45:53,106 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:45:53,106 - opfython.core.opf — INFO — Class created.
2026-09-13 19:45:53,107 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:45:53,107 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:45:53,109 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:45:53,209 - opfython.models.supervised — DEBUG — Prototypes: [319, 68, 56, 111, 219, 404, 34, 33, 343, 304, 416, 461, 145, 52, 309, 324, 448, 142, 300, 495, 485, 401, 472, 456, 498, 166, 460, 107, 473, 130, 20, 110, 178, 248, 437, 124, 117, 260, 161, 496, 207, 88, 329, 340, 102, 402, 66, 134, 345, 307, 115, 2, 312, 108, 21, 50, 86, 477, 195, 80, 436, 350, 318, 71, 458, 87, 454, 176, 283, 77, 13, 372, 239, 15, 54, 313, 3, 175, 104, 407, 226, 447, 237, 375, 431, 405, 223, 74, 291, 316, 341, 392, 96, 1, 465, 314, 177, 361, 501, 475, 371, 235, 217, 113, 140, 57, 106, 321, 95, 358, 101, 382, 64, 395, 81, 89, 267, 284, 487, 69, 190, 277, 293, 38, 332, 241, 7, 410, 396, 8, 442, 254, 420, 276, 302, 35, 221, 430, 204, 429, 427, 348, 339, 73, 423, 273, 364, 299, 394, 18, 366, 512, 269, 203, 156, 287, 444, 470, 417, 131, 192, 303, 45, 368, 236, 46, 336, 218, 360, 205, 187, 98, 60, 337, 173, 445, 297, 390, 381, 49, 139, 347, 443, 481, 398, 148, 426, 462, 468, 508, 122, 290, 83, 172, 199, 513, 40, 476, 123, 214, 90, 82, 378, 17, 502, 133, 201, 435].
2026-09-13 19:45:53,419 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:45:53,420 - opfython.models.supervised — INFO — Training time: 0.3121168613433838 seconds.
2026-09-13 19:45:53,421 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:45:53,509 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:45:53,510 - opfython.models.supervised — INFO — Prediction time: 0.08831667900085449 seconds.
2026-09-13 19:45:53,521 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:45:53,521 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:45:53,522 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:45:53,522 - opfython.core.opf — INFO — Class created.
2026-09-13 19:45:53,523 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:45:53,524 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:45:53,526 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:45:53,633 - opfython.models.supervised — DEBUG — Prototypes: [368, 501, 472, 144, 119, 40, 503, 168, 90, 320, 335, 173, 328, 43, 193, 236, 358, 433, 83, 475, 25, 75, 8, 105, 147, 292, 509, 172, 85, 77, 15, 376, 249, 53, 18, 171, 102, 140, 342, 417, 445, 247, 13, 84, 261, 207, 476, 52, 23, 497, 344, 286, 170, 163, 420, 440, 66, 350, 98, 451, 294, 405, 385, 353, 391, 240, 138, 132, 109, 481, 58, 304, 139, 494, 313, 54, 295, 457, 407, 36, 464, 284, 162, 456, 104, 57, 230, 106, 242, 35, 404, 468, 453, 496, 469, 120, 434, 257, 37, 238, 252, 334, 48, 380, 486, 317, 262, 325, 69, 74, 327, 127, 351, 395, 276, 86, 275, 59, 329, 24, 183, 398, 65, 80, 16, 369, 299, 487, 6, 411, 399, 409, 506, 442, 289, 29, 108, 67, 309, 232, 371, 512, 290, 356, 428, 201, 347, 370, 229, 2, 319, 72, 423, 20, 269, 239, 293, 141, 125, 314, 208, 277, 415, 182, 272, 306, 340, 394, 203, 226, 187, 128, 217, 181, 303, 374, 136, 345, 210, 384, 302, 393, 443, 169, 62, 224, 441, 51, 281, 466, 507, 117, 458, 465, 482, 311, 137, 471, 81, 42, 204, 513, 222, 146, 354, 489, 439, 87, 392, 502, 131, 206].
2026-09-13 19:45:53,842 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:45:53,843 - opfython.models.supervised — INFO — Training time: 0.3187718391418457 seconds.
2026-09-13 19:45:53,843 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:45:53,935 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:45:53,935 - opfython.models.supervised — INFO — Prediction time: 0.09132146835327148 seconds.
2026-09-13 19:45:53,946 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:45:53,947 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:45:53,948 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:45:53,948 - opfython.core.opf — INFO — Class created.
2026-09-13 19:45:53,950 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:45:53,950 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:45:53,952 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:45:54,050 - opfython.models.supervised — DEBUG — Prototypes: [326, 68, 353, 148, 182, 60, 350, 99, 456, 297, 86, 336, 448, 298, 425, 161, 408, 235, 133, 66, 130, 109, 395, 481, 355, 349, 1, 317, 104, 265, 85, 36, 352, 37, 311, 420, 461, 299, 54, 314, 135, 496, 485, 59, 108, 106, 237, 35, 257, 442, 407, 405, 469, 126, 24, 107, 113, 156, 270, 234, 251, 424, 207, 48, 459, 488, 422, 136, 190, 79, 441, 328, 44, 28, 13, 26, 144, 290, 70, 8, 105, 143, 294, 123, 230, 76, 15, 378, 248, 53, 288, 180, 320, 2, 437, 409, 411, 452, 246, 381, 228, 73, 18, 56, 324, 351, 399, 261, 244, 377, 140, 170, 121, 40, 91, 168, 368, 502, 472, 223, 94, 465, 418, 179, 280, 87, 279, 400, 80, 64, 387, 98, 365, 61, 93, 329, 192, 103, 427, 16, 25, 295, 487, 171, 339, 250, 116, 191, 263, 361, 275, 289, 6, 413, 401, 7, 447, 450, 292, 436, 205, 262, 65, 226, 302, 313, 367, 199, 347, 224, 3, 319, 371, 307, 333, 220, 125, 315, 204, 282, 152, 293, 341, 383, 31, 283, 127, 47, 211, 254, 345, 491, 495, 206, 305, 397, 51, 132, 357, 218, 449, 482, 403, 507, 119, 82, 253, 202, 514, 216, 42, 474, 384, 240, 88, 81, 259, 203, 344, 503].
2026-09-13 19:45:54,261 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:45:54,262 - opfython.models.supervised — INFO — Training time: 0.3116002082824707 seconds.
2026-09-13 19:45:54,263 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:45:54,354 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:45:54,354 - opfython.models.supervised — INFO — Prediction time: 0.09087371826171875 seconds.
2026-09-13 19:45:54,365 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:45:54,366 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:45:54,367 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:45:54,367 - opfython.core.opf — INFO — Class created.
2026-09-13 19:45:54,367 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:45:54,368 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:45:54,370 - opfython.models.supervised — DEBUG — Finding prototypes ...

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

Fase 1 MLP {'accuracy': 0.8028169014084507, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8142857142857143), 'recall_0': np.float64(0.0), 'recall_1': np.float64(0.9827586206896551), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.890625), 'f1_macro': 0.4453125, 'f1_weighted': 0.7275528169014085, 'precision_macro': 0.40714285714285714, 'recall_macro': 0.49137931034482757, 'balanced_accuracy': 0.49137931034482757, 'mcc': -0.056585956237831254, 'specificity': np.float64(0.0), 'sensitivity': np.float64(0.9827586206896551), 'TN': 0, 'FP': 13, 'FN': 1, 'TP': 57, 'score_source': 'continuous', 'auroc': 0.4933687002652519, 'ap_0': 0.19287913555492714, 'ap_1': 0.8195926605595842, 'scenario': 'baseline', 'model': 'MLP', 'outer_fold': 10, 'params': {'alpha': 0.0001, 'hidden_layer_sizes': (32,), 'max_iter': 500}, 'inner_f1_macro': 0.4663610010436865}
Fase 1 LR {'accuracy': 0.8169014084507042, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8169014084507042), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8992248062015504), 'f1_macro': 0.4496124031007752, 'f1_weighted': 0.7345780106998581, 'precision_macro': 0.4084507042253521, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 13, 'FN': 0, 'TP': 58, 'score_source': 'continuous', 'auroc': 0.5318302387267905, 'ap_0': 0.21693622096088871, 'ap_1': 0.850253243303006, 'scenario': 'baseline', 'model': 'LR', 'outer_fold': 10, 'params': {'C': 0.01, 'max_iter': 1000, 'solver': 'lbfgs'}, 'inner_f1_macro': 0.449488279960383}
Fase 1 XGB {'accuracy': 0.8169014084507042, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8169014084507042), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8992248062015504), 'f1_macro': 0.4496124031007752, 'f1_weighted': 0.7345780106998581, 'precision_macro': 0.4084507042253521, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 13, 'FN': 0, 'TP': 58, 'score_source': 'continuous', 'auroc': 0.5875331564986738, 'ap_0': 0.25565097842544937, 'ap_1': 0.8570528253003302, 'scenario': 'baseline', 'model': 'XGB', 'outer_fold': 10, 'params': {'learning_rate': 0.05, 'max_depth': 3, 'n_estimators': 100}, 'inner_f1_macro': 0.46534078619323554}
Fase 1 NB {'accuracy': 0.6197183098591549, 'precision_0': np.float64(0.25), 'precision_1': np.float64(0.8604651162790697), 'recall_0': np.float64(0.5384615384615384), 'recall_1': np.float64(0.6379310344827587), 'f1_0': np.float64(0.34146341463414637), 'f1_1': np.float64(0.7326732673267327), 'f1_macro': 0.5370683409804395, 'f1_weighted': 0.6610432942985126, 'precision_macro': 0.5552325581395349, 'recall_macro': 0.5881962864721486, 'balanced_accuracy': 0.5881962864721486, 'mcc': 0.13958949129879394, 'specificity': np.float64(0.5384615384615384), 'sensitivity': np.float64(0.6379310344827587), 'TN': 7, 'FP': 6, 'FN': 21, 'TP': 37, 'score_source': 'continuous', 'auroc': 0.5789124668435014, 'ap_0': 0.3260957697883261, 'ap_1': 0.8497544975443866, 'scenario': 'baseline', 'model': 'NB', 'outer_fold': 10, 'params': {'var_smoothing': 1e-07}, 'inner_f1_macro': 0.4118328177217333}

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(

Fase 1 NC {'accuracy': 0.4788732394366197, 'precision_0': np.float64(0.18421052631578946), 'precision_1': np.float64(0.8181818181818182), 'recall_0': np.float64(0.5384615384615384), 'recall_1': np.float64(0.46551724137931033), 'f1_0': np.float64(0.27450980392156865), 'f1_1': np.float64(0.5934065934065934), 'f1_macro': 0.43395819866408103, 'f1_weighted': 0.5350170404022931, 'precision_macro': 0.5011961722488039, 'recall_macro': 0.5019893899204244, 'balanced_accuracy': 0.5019893899204244, 'mcc': 0.0030852247988512774, 'specificity': np.float64(0.5384615384615384), 'sensitivity': np.float64(0.46551724137931033), 'TN': 7, 'FP': 6, 'FN': 31, 'TP': 27, 'score_source': 'unavailable', 'auroc': nan, 'ap_0': nan, 'ap_1': nan, 'scenario': 'baseline', 'model': 'NC', 'outer_fold': 10, 'params': {'metric': 'manhattan', 'shrink_threshold': 0.1}, 'inner_f1_macro': 0.4574688950181591}
2026-09-13 19:46:30,668 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:46:30,669 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:46:30,670 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:46:30,670 - opfython.core.opf — INFO — Class created.
2026-09-13 19:46:30,671 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:46:30,671 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:46:30,673 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:46:30,770 - opfython.models.supervised — DEBUG — Prototypes: [414, 351, 456, 92, 216, 95, 118, 21, 457, 130, 46, 271, 330, 446, 127, 296, 302, 20, 413, 35, 401, 34, 348, 110, 400, 468, 138, 157, 239, 102, 42, 454, 212, 497, 233, 332, 418, 246, 441, 280, 347, 196, 349, 139, 214, 125, 479, 51, 307, 97, 312, 93, 141, 248, 75, 22, 319, 45, 500, 253, 154, 245, 177, 507, 358, 144, 452, 510, 140, 163, 24, 64, 455, 192, 270, 10, 94, 68, 14, 240, 203, 156, 76, 504, 372, 228, 153, 115, 15, 48, 128, 340, 217, 416, 61, 171, 69, 437, 354, 73, 473, 321, 12, 445, 226, 374, 26, 325, 443, 258, 155, 324, 65, 433, 402, 315, 2, 295, 403, 257, 7, 8, 395, 299, 268, 300, 179, 17, 208, 442, 444, 451, 131, 109, 152, 505, 365, 428, 3, 288, 36, 316, 222, 186, 285, 18, 465, 178, 81, 169, 461, 1, 339, 231, 481, 52, 326, 84, 488, 363, 379, 207, 23, 301, 60, 211, 234, 116, 309, 185, 124, 353, 264, 206, 314, 367, 342, 41, 275, 376, 368, 167, 256, 458, 463, 133, 350, 293, 364, 432, 244, 411, 164, 466, 415, 255, 182, 199, 492, 218, 359, 224, 44, 284, 151, 303, 394, 269, 62, 487, 494, 472, 377, 175].

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neighbors/_nearest_centroid.py:241: UserWarning: self.within_class_std_dev_ has at least 1 zero standard deviation.Inputs within the same classes for at least 1 feature are identical.
  warnings.warn(

2026-09-13 19:46:30,978 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:46:30,979 - opfython.models.supervised — INFO — Training time: 0.30768752098083496 seconds.
2026-09-13 19:46:30,979 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:46:31,064 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:46:31,066 - opfython.models.supervised — INFO — Prediction time: 0.08572912216186523 seconds.
2026-09-13 19:46:31,076 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:46:31,077 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:46:31,077 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:46:31,078 - opfython.core.opf — INFO — Class created.
2026-09-13 19:46:31,078 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:46:31,079 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:46:31,080 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:46:31,177 - opfython.models.supervised — DEBUG — Prototypes: [316, 67, 324, 407, 491, 121, 111, 55, 225, 75, 458, 109, 130, 19, 112, 49, 274, 321, 444, 459, 281, 301, 18, 413, 31, 402, 399, 397, 454, 498, 32, 175, 468, 246, 434, 118, 432, 113, 224, 323, 240, 416, 496, 45, 370, 394, 451, 279, 89, 37, 494, 162, 440, 280, 400, 341, 151, 343, 373, 116, 2, 110, 186, 161, 65, 8, 403, 304, 114, 139, 424, 478, 309, 153, 253, 475, 335, 48, 20, 500, 258, 272, 171, 256, 387, 181, 136, 86, 315, 66, 414, 12, 120, 262, 298, 348, 317, 172, 233, 101, 443, 72, 429, 23, 70, 273, 456, 206, 74, 148, 276, 127, 173, 88, 501, 170, 15, 52, 260, 270, 185, 404, 68, 78, 367, 235, 339, 297, 473, 506, 251, 132, 216, 198, 16, 293, 3, 358, 502, 471, 143, 425, 123, 34, 503, 169, 287, 381, 312, 174, 284, 325, 340, 177, 97, 464, 1, 103, 257, 329, 238, 355, 179, 450, 441, 71, 392, 14, 82, 63, 376, 263, 483, 165, 489, 56, 318, 95, 102, 356, 107, 419, 7, 163, 277, 439, 64, 138, 345, 90, 334, 44, 215, 128, 306, 361, 217, 311, 255, 189, 300, 146, 423, 428, 250, 362, 188, 208, 243, 391, 195, 131, 291, 214, 490, 43, 200, 212, 375, 353, 232, 302, 460, 465, 94, 193, 493, 487, 201, 372, 196, 91, 83, 364].
2026-09-13 19:46:31,374 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:46:31,375 - opfython.models.supervised — INFO — Training time: 0.2957732677459717 seconds.
2026-09-13 19:46:31,375 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:46:31,465 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:46:31,465 - opfython.models.supervised — INFO — Prediction time: 0.08946061134338379 seconds.
2026-09-13 19:46:31,477 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:46:31,477 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:46:31,478 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:46:31,478 - opfython.core.opf — INFO — Class created.
2026-09-13 19:46:31,478 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:46:31,479 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:46:31,481 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:46:31,577 - opfython.models.supervised — DEBUG — Prototypes: [317, 168, 142, 119, 37, 424, 366, 468, 503, 165, 294, 383, 171, 413, 178, 465, 416, 181, 56, 237, 137, 86, 40, 474, 189, 438, 289, 402, 450, 307, 131, 66, 478, 7, 8, 395, 353, 112, 1, 309, 347, 69, 313, 106, 279, 23, 320, 50, 262, 85, 404, 34, 33, 350, 456, 290, 51, 281, 329, 444, 139, 300, 494, 230, 482, 120, 401, 400, 149, 497, 331, 192, 116, 282, 415, 352, 55, 228, 68, 321, 455, 372, 75, 127, 467, 108, 254, 432, 109, 43, 486, 235, 417, 250, 259, 386, 396, 175, 360, 155, 451, 508, 38, 76, 25, 73, 280, 10, 273, 107, 146, 78, 16, 286, 167, 74, 348, 166, 509, 439, 71, 449, 18, 54, 327, 265, 134, 325, 41, 190, 251, 83, 472, 257, 140, 239, 14, 443, 246, 374, 26, 440, 268, 115, 72, 284, 316, 247, 407, 302, 344, 470, 198, 20, 226, 285, 355, 485, 480, 394, 229, 81, 270, 484, 162, 87, 241, 98, 365, 427, 57, 104, 92, 419, 6, 24, 304, 65, 205, 125, 311, 287, 437, 17, 163, 384, 232, 234, 224, 264, 145, 423, 457, 462, 393, 193, 215, 252, 421, 375, 135, 341, 378, 298, 369, 196, 46, 49, 292, 491, 201, 221, 240, 405, 244, 136, 305, 362, 487, 493, 203, 204, 60, 236, 88, 295].
2026-09-13 19:46:31,779 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:46:31,779 - opfython.models.supervised — INFO — Training time: 0.2998201847076416 seconds.
2026-09-13 19:46:31,780 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:46:31,876 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:46:31,877 - opfython.models.supervised — INFO — Prediction time: 0.09686136245727539 seconds.
2026-09-13 19:46:31,888 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:46:31,889 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:46:31,890 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:46:31,890 - opfython.core.opf — INFO — Class created.
2026-09-13 19:46:31,890 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:46:31,891 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:46:31,893 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:46:31,994 - opfython.models.supervised — DEBUG — Prototypes: [322, 67, 417, 353, 331, 189, 57, 108, 233, 74, 309, 131, 416, 34, 350, 51, 22, 280, 482, 134, 404, 402, 146, 497, 391, 266, 127, 23, 109, 438, 35, 168, 94, 440, 253, 260, 421, 47, 376, 400, 281, 445, 87, 495, 474, 39, 454, 292, 354, 379, 1, 58, 179, 351, 231, 380, 365, 130, 64, 478, 7, 8, 398, 68, 314, 106, 149, 262, 85, 259, 128, 423, 430, 18, 270, 54, 283, 177, 153, 359, 25, 75, 72, 69, 37, 458, 10, 107, 141, 290, 124, 166, 86, 73, 263, 135, 419, 234, 65, 14, 187, 257, 79, 358, 439, 40, 325, 321, 449, 242, 374, 117, 188, 272, 446, 434, 27, 407, 110, 244, 372, 317, 2, 305, 220, 288, 356, 196, 299, 296, 204, 20, 464, 349, 95, 461, 100, 415, 176, 336, 247, 225, 347, 465, 418, 59, 489, 326, 99, 424, 159, 397, 80, 63, 382, 274, 484, 161, 88, 235, 227, 250, 203, 125, 312, 24, 308, 291, 444, 17, 150, 222, 316, 264, 348, 269, 367, 198, 218, 341, 46, 433, 258, 133, 355, 210, 251, 140, 429, 381, 302, 70, 45, 49, 295, 216, 306, 493, 240, 163, 361, 215, 375, 199, 514, 324, 92, 91, 475, 507, 119, 255, 485, 201, 202, 378, 192, 89, 81].
2026-09-13 19:46:32,217 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:46:32,218 - opfython.models.supervised — INFO — Training time: 0.32634925842285156 seconds.
2026-09-13 19:46:32,218 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:46:32,308 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:46:32,309 - opfython.models.supervised — INFO — Prediction time: 0.0898594856262207 seconds.
2026-09-13 19:46:32,319 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:46:32,320 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:46:32,320 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:46:32,321 - opfython.core.opf — INFO — Class created.
2026-09-13 19:46:32,321 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:46:32,322 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:46:32,323 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:46:32,421 - opfython.models.supervised — DEBUG — Prototypes: [319, 63, 329, 187, 50, 106, 216, 485, 227, 72, 406, 130, 460, 38, 303, 415, 17, 327, 277, 448, 135, 298, 495, 28, 347, 497, 144, 459, 104, 391, 257, 172, 167, 92, 30, 39, 43, 374, 207, 400, 223, 506, 328, 153, 251, 360, 348, 145, 176, 51, 225, 133, 453, 285, 85, 95, 494, 477, 157, 404, 343, 350, 377, 111, 2, 128, 60, 308, 344, 109, 64, 19, 499, 316, 259, 83, 253, 164, 250, 127, 507, 427, 69, 323, 36, 82, 476, 186, 78, 439, 355, 136, 418, 228, 61, 373, 224, 322, 165, 23, 433, 24, 151, 359, 509, 33, 66, 457, 202, 73, 21, 276, 9, 267, 140, 70, 75, 12, 283, 510, 503, 84, 71, 345, 163, 273, 174, 444, 67, 452, 445, 280, 300, 281, 353, 68, 422, 475, 409, 301, 218, 3, 488, 312, 297, 93, 1, 465, 97, 313, 192, 166, 234, 198, 290, 16, 468, 346, 138, 32, 505, 162, 428, 366, 473, 4, 293, 385, 479, 363, 469, 417, 212, 413, 184, 380, 58, 398, 79, 393, 482, 220, 240, 197, 266, 86, 230, 20, 279, 59, 118, 401, 13, 215, 103, 255, 375, 432, 249, 334, 268, 369, 178, 461, 467, 379, 397, 188, 210, 41, 46, 289, 229, 407, 161, 204, 175, 321, 62, 89, 88, 470, 458, 487, 52, 493, 195, 196, 87, 80, 383, 376, 237, 232].
2026-09-13 19:46:32,625 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:46:32,626 - opfython.models.supervised — INFO — Training time: 0.30351781845092773 seconds.
2026-09-13 19:46:32,626 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:46:32,721 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:46:32,721 - opfython.models.supervised — INFO — Prediction time: 0.09463858604431152 seconds.
2026-09-13 19:46:32,733 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:46:32,734 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:46:32,734 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:46:32,734 - opfython.core.opf — INFO — Class created.
2026-09-13 19:46:32,735 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:46:32,735 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:46:32,737 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:46:32,839 - opfython.models.supervised — DEBUG — Prototypes: [414, 351, 456, 92, 118, 21, 216, 371, 457, 130, 46, 271, 330, 446, 127, 296, 401, 35, 302, 413, 34, 348, 400, 468, 138, 110, 157, 239, 102, 42, 454, 212, 406, 233, 332, 418, 441, 280, 347, 196, 349, 139, 214, 125, 479, 51, 22, 266, 45, 500, 75, 248, 154, 312, 93, 66, 73, 473, 325, 69, 437, 171, 354, 26, 321, 128, 416, 217, 61, 12, 445, 226, 374, 10, 94, 262, 64, 270, 455, 192, 24, 134, 144, 358, 452, 510, 166, 76, 156, 504, 68, 14, 240, 203, 15, 48, 155, 88, 403, 433, 402, 324, 52, 488, 326, 80, 84, 363, 90, 421, 379, 207, 81, 265, 461, 1, 316, 186, 222, 285, 18, 465, 365, 3, 428, 131, 109, 152, 505, 159, 23, 219, 211, 105, 234, 390, 97, 65, 258, 288, 36, 153, 115, 339, 231, 507, 443, 274, 304, 228, 372, 315, 2, 246, 60, 245, 208, 368, 513, 432, 244, 268, 300, 179, 427, 264, 116, 309, 185, 206, 7, 121, 395, 8, 367, 345, 107, 397, 295, 17, 275, 376, 451, 442, 481, 254, 213, 342, 41, 487, 494, 411, 164, 255, 466, 415, 187, 293, 55, 381, 256, 201, 124, 353, 224, 182, 199, 44, 458, 463, 62, 218, 471, 472, 133, 350, 377, 175].
2026-09-13 19:46:33,061 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:46:33,062 - opfython.models.supervised — INFO — Training time: 0.3258476257324219 seconds.
2026-09-13 19:46:33,062 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:46:33,153 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:46:33,154 - opfython.models.supervised — INFO — Prediction time: 0.09092831611633301 seconds.
2026-09-13 19:46:33,165 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:46:33,165 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:46:33,166 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:46:33,166 - opfython.core.opf — INFO — Class created.
2026-09-13 19:46:33,166 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:46:33,167 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:46:33,170 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:46:33,269 - opfython.models.supervised — DEBUG — Prototypes: [316, 67, 324, 407, 491, 121, 111, 55, 218, 485, 225, 75, 458, 109, 130, 19, 112, 413, 301, 31, 402, 459, 25, 49, 274, 321, 444, 399, 96, 454, 498, 175, 32, 246, 434, 113, 224, 240, 323, 416, 45, 370, 451, 279, 89, 37, 494, 104, 440, 280, 341, 151, 20, 48, 500, 272, 475, 253, 335, 171, 258, 136, 86, 315, 66, 414, 12, 70, 273, 456, 206, 74, 510, 276, 127, 173, 88, 501, 15, 52, 270, 185, 172, 105, 309, 254, 110, 443, 233, 404, 343, 256, 116, 2, 387, 393, 78, 4, 298, 81, 216, 181, 429, 23, 161, 65, 8, 403, 317, 394, 358, 502, 471, 143, 425, 123, 34, 503, 169, 174, 312, 230, 325, 284, 177, 97, 464, 1, 103, 72, 262, 114, 139, 263, 392, 82, 63, 376, 356, 102, 489, 56, 318, 95, 419, 107, 7, 14, 90, 339, 287, 381, 483, 165, 120, 194, 68, 186, 163, 329, 238, 473, 506, 170, 478, 367, 235, 251, 132, 362, 512, 198, 424, 128, 306, 277, 439, 361, 217, 311, 255, 337, 428, 250, 179, 293, 3, 441, 71, 188, 297, 257, 446, 131, 334, 44, 391, 195, 208, 129, 189, 300, 215, 199, 43, 379, 291, 388, 214, 375, 138, 345, 232, 200, 212, 146, 423, 493, 487, 460, 465, 472, 474, 94, 457, 372, 196, 91, 83, 201].
2026-09-13 19:46:33,495 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:46:33,496 - opfython.models.supervised — INFO — Training time: 0.3284637928009033 seconds.
2026-09-13 19:46:33,496 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:46:33,603 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:46:33,604 - opfython.models.supervised — INFO — Prediction time: 0.10735225677490234 seconds.
2026-09-13 19:46:33,616 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:46:33,617 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:46:33,618 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:46:33,618 - opfython.core.opf — INFO — Class created.
2026-09-13 19:46:33,618 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:46:33,619 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:46:33,621 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:46:33,728 - opfython.models.supervised — DEBUG — Prototypes: [10, 107, 25, 76, 155, 360, 451, 508, 38, 73, 146, 286, 509, 167, 78, 16, 18, 54, 140, 257, 239, 443, 246, 374, 190, 251, 41, 325, 83, 472, 26, 14, 23, 262, 50, 85, 279, 277, 438, 289, 86, 474, 40, 237, 137, 347, 307, 56, 181, 450, 391, 478, 131, 66, 7, 8, 395, 313, 106, 415, 352, 331, 282, 192, 116, 228, 55, 68, 321, 34, 404, 33, 350, 456, 27, 51, 281, 329, 444, 139, 300, 494, 482, 120, 497, 149, 401, 254, 432, 109, 455, 372, 235, 250, 417, 353, 1, 112, 386, 396, 407, 175, 127, 467, 108, 74, 226, 258, 431, 317, 168, 142, 119, 366, 468, 165, 503, 72, 268, 270, 87, 241, 394, 17, 81, 64, 98, 365, 57, 92, 104, 419, 6, 232, 24, 376, 348, 294, 383, 484, 162, 69, 43, 259, 361, 166, 486, 439, 71, 480, 205, 272, 470, 316, 247, 65, 440, 284, 125, 311, 369, 512, 285, 355, 198, 287, 437, 344, 117, 398, 234, 302, 413, 178, 264, 263, 236, 393, 193, 163, 465, 416, 341, 384, 215, 176, 224, 200, 183, 304, 487, 493, 299, 207, 298, 388, 60, 380, 485, 378, 421, 244, 201, 221, 49, 274, 46, 145, 423, 457, 462, 292, 217, 136, 88, 387, 203, 342, 256].
2026-09-13 19:46:33,946 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:46:33,947 - opfython.models.supervised — INFO — Training time: 0.32764410972595215 seconds.
2026-09-13 19:46:33,948 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:46:34,036 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:46:34,037 - opfython.models.supervised — INFO — Prediction time: 0.08843469619750977 seconds.
2026-09-13 19:46:34,047 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:46:34,048 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:46:34,049 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:46:34,049 - opfython.core.opf — INFO — Class created.
2026-09-13 19:46:34,049 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:46:34,050 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:46:34,052 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:46:34,154 - opfython.models.supervised — DEBUG — Prototypes: [322, 67, 417, 353, 331, 189, 57, 108, 233, 74, 309, 131, 416, 34, 350, 51, 22, 280, 482, 134, 404, 94, 146, 497, 122, 438, 35, 168, 440, 253, 47, 376, 454, 292, 87, 495, 445, 158, 347, 311, 405, 58, 179, 64, 478, 130, 7, 8, 398, 354, 1, 314, 106, 262, 85, 391, 399, 263, 71, 325, 40, 187, 79, 439, 358, 135, 419, 234, 65, 14, 449, 242, 374, 153, 359, 455, 508, 37, 142, 25, 72, 69, 458, 10, 107, 141, 290, 509, 166, 86, 307, 18, 54, 283, 177, 165, 207, 62, 434, 407, 127, 23, 109, 351, 73, 220, 320, 231, 380, 296, 332, 464, 20, 95, 461, 274, 88, 235, 59, 489, 326, 99, 424, 397, 80, 63, 382, 17, 24, 227, 214, 250, 484, 161, 68, 159, 365, 260, 360, 244, 372, 317, 2, 203, 276, 336, 247, 110, 446, 287, 259, 128, 125, 312, 225, 433, 258, 288, 356, 196, 291, 444, 299, 222, 3, 316, 367, 264, 150, 423, 180, 415, 176, 269, 268, 230, 451, 341, 470, 46, 465, 418, 181, 308, 198, 218, 210, 174, 370, 45, 205, 81, 49, 302, 70, 381, 426, 216, 240, 133, 355, 507, 119, 140, 429, 199, 514, 215, 471, 324, 378, 192, 89, 201, 342].
2026-09-13 19:46:34,354 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:46:34,355 - opfython.models.supervised — INFO — Training time: 0.30415797233581543 seconds.
2026-09-13 19:46:34,355 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:46:34,441 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:46:34,442 - opfython.models.supervised — INFO — Prediction time: 0.0864267349243164 seconds.
2026-09-13 19:46:34,453 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:46:34,453 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:46:34,454 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:46:34,454 - opfython.core.opf — INFO — Class created.
2026-09-13 19:46:34,454 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:46:34,455 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:46:34,457 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:46:34,554 - opfython.models.supervised — DEBUG — Prototypes: [319, 63, 329, 187, 50, 106, 227, 72, 406, 130, 460, 38, 303, 415, 17, 327, 277, 448, 135, 298, 495, 28, 347, 497, 144, 459, 104, 120, 416, 167, 92, 437, 30, 223, 328, 153, 43, 374, 85, 271, 494, 477, 95, 453, 285, 344, 306, 348, 145, 225, 133, 51, 176, 128, 60, 19, 499, 275, 83, 253, 164, 131, 323, 36, 82, 476, 186, 78, 439, 355, 23, 136, 418, 228, 61, 151, 147, 359, 509, 66, 457, 202, 21, 73, 276, 70, 9, 267, 140, 283, 510, 503, 75, 12, 273, 174, 165, 101, 350, 257, 111, 2, 433, 24, 71, 322, 373, 224, 138, 428, 32, 505, 162, 366, 504, 473, 4, 166, 313, 234, 198, 290, 16, 468, 93, 465, 1, 109, 345, 398, 489, 79, 58, 380, 13, 220, 116, 240, 20, 393, 64, 293, 385, 251, 360, 163, 507, 391, 172, 444, 67, 479, 445, 280, 218, 250, 127, 59, 281, 353, 432, 249, 312, 3, 86, 230, 118, 401, 427, 68, 422, 475, 197, 482, 266, 215, 255, 297, 375, 260, 397, 188, 369, 178, 41, 204, 173, 446, 487, 493, 379, 383, 53, 46, 413, 424, 210, 469, 417, 461, 467, 62, 229, 474, 87, 80, 376, 237, 232, 195, 338].
2026-09-13 19:46:34,765 - opfython.models.supervised — INFO — Classifier has been fitted.

# Fase 2 — MDI 80%
MDI é ajustado somente no treino de cada split, após transformação de todas as features.

In [95]:
phase2_rows = []
phase2_oof = {name: np.full(len(y_array), -1, dtype=int) for name in roster}
phase2_scores = {name: np.full(len(y_array), np.nan) for name in roster}
phase2_mdi = []
for outer_fold, (train_index, test_index) in enumerate(outer_cv.split(X, y_array), 1):
    X_train = X.iloc[train_index]
    X_test = X.iloc[test_index]
    y_train = y_array[train_index]
    y_test = y_array[test_index]
    for name in roster:
        candidates = []
        for params in ParameterGrid(grids[name]):
            inner_scores = []
            for inner_fold, (inner_train, inner_valid) in enumerate(inner_cv.split(X_train, y_train), 1):
                preprocessor, encoded_train, encoded_valid, mdi_record = prepare_split(X_train.iloc[inner_train], y_train[inner_train], X_train.iloc[inner_valid], use_mdi=True)
                model = make_estimator(name, params, y_fit=y_train[inner_train])
                if name == "OPF":
                    model.fit(np.asarray(encoded_train), np.asarray(y_train[inner_train], dtype=np.int32))
                    prediction = model.predict(np.asarray(encoded_valid))
                else:
                    model.fit(encoded_train, y_train[inner_train])
                    prediction = model.predict(encoded_valid)
                inner_scores.append(f1_score(y_train[inner_valid], prediction, labels=[0, 1], average="macro", zero_division=0))
                phase2_mdi.append({"scenario": "mdi80", "model": name, "outer_fold": outer_fold, "inner_fold": inner_fold, **mdi_record})
            candidates.append((float(np.mean(inner_scores)), dict(params)))
        best_f1, best_params = max(candidates, key=lambda item: item[0])
        preprocessor, encoded_train, encoded_test, mdi_record = prepare_split(X_train, y_train, X_test, use_mdi=True)
        model = make_estimator(name, best_params, y_fit=y_train)
        if name == "OPF":
            model.fit(np.asarray(encoded_train), np.asarray(y_train, dtype=np.int32))
            prediction, score0, score1, _ = predict_with_score(model, np.asarray(encoded_test))
        else:
            model.fit(encoded_train, y_train)
            prediction, score0, score1, _ = predict_with_score(model, encoded_test)
        metrics = binary_metrics(y_test, prediction, score0, score1)
        metrics.update({"scenario": "mdi80", "model": name, "outer_fold": outer_fold, "params": best_params, "inner_f1_macro": best_f1})
        phase2_rows.append(metrics)
        phase2_oof[name][test_index] = prediction
        if score1 is not None:
            phase2_scores[name][test_index] = score1
        phase2_mdi.append({"scenario": "mdi80", "model": name, "outer_fold": outer_fold, "inner_fold": None, **mdi_record})
        print("Fase 2", name, metrics)

Fase 2 KNN {'accuracy': 0.7916666666666666, 'precision_0': np.float64(0.3333333333333333), 'precision_1': np.float64(0.8333333333333334), 'recall_0': np.float64(0.15384615384615385), 'recall_1': np.float64(0.9322033898305084), 'f1_0': np.float64(0.21052631578947367), 'f1_1': np.float64(0.88), 'f1_macro': 0.5452631578947369, 'f1_weighted': 0.7591228070175439, 'precision_macro': 0.5833333333333334, 'recall_macro': 0.5430247718383312, 'balanced_accuracy': 0.5430247718383312, 'mcc': 0.11975638025916219, 'specificity': np.float64(0.15384615384615385), 'sensitivity': np.float64(0.9322033898305084), 'TN': 2, 'FP': 11, 'FN': 4, 'TP': 55, 'score_source': 'continuous', 'auroc': 0.4250325945241199, 'ap_0': 0.22562017927871586, 'ap_1': 0.7813306434746965, 'scenario': 'mdi80', 'model': 'KNN', 'outer_fold': 1, 'params': {'n_neighbors': 5, 'weights': 'distance'}, 'inner_f1_macro': 0.5167853027815077}
Fase 2 DT {'accuracy': 0.7777777777777778, 'precision_0': np.float64(0.2857142857142857), 'precision_1': np.float64(0.8307692307692308), 'recall_0': np.float64(0.15384615384615385), 'recall_1': np.float64(0.9152542372881356), 'f1_0': np.float64(0.2), 'f1_1': np.float64(0.8709677419354839), 'f1_macro': 0.535483870967742, 'f1_weighted': 0.749820788530466, 'precision_macro': 0.5582417582417583, 'recall_macro': 0.5345501955671448, 'balanced_accuracy': 0.5345501955671448, 'mcc': 0.08971653442765408, 'specificity': np.float64(0.15384615384615385), 'sensitivity': np.float64(0.9152542372881356), 'TN': 2, 'FP': 11, 'FN': 5, 'TP': 54, 'score_source': 'continuous', 'auroc': 0.5423728813559322, 'ap_0': 0.27237743863380537, 'ap_1': 0.8412869722222163, 'scenario': 'mdi80', 'model': 'DT', 'outer_fold': 1, 'params': {'max_depth': None, 'min_samples_leaf': 5}, 'inner_f1_macro': 0.5124090641152261}
Fase 2 RF {'accuracy': 0.8055555555555556, 'precision_0': np.float64(0.3333333333333333), 'precision_1': np.float64(0.8260869565217391), 'recall_0': np.float64(0.07692307692307693), 'recall_1': np.float64(0.9661016949152542), 'f1_0': np.float64(0.125), 'f1_1': np.float64(0.890625), 'f1_macro': 0.5078125, 'f1_weighted': 0.7523871527777778, 'precision_macro': 0.5797101449275363, 'recall_macro': 0.5215123859191656, 'balanced_accuracy': 0.5215123859191656, 'mcc': 0.08281921031629746, 'specificity': np.float64(0.07692307692307693), 'sensitivity': np.float64(0.9661016949152542), 'TN': 1, 'FP': 12, 'FN': 2, 'TP': 57, 'score_source': 'continuous', 'auroc': 0.49413298565840935, 'ap_0': 0.23017917035961047, 'ap_1': 0.8280457149436892, 'scenario': 'mdi80', 'model': 'RF', 'outer_fold': 1, 'params': {'max_depth': None, 'min_samples_leaf': 1, 'n_estimators': 200}, 'inner_f1_macro': 0.48893390650149476}
Fase 2 SVM {'accuracy': 0.8194444444444444, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8194444444444444), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.9007633587786259), 'f1_macro': 0.45038167938931295, 'f1_weighted': 0.7381255301102629, 'precision_macro': 0.4097222222222222, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 13, 'FN': 0, 'TP': 59, 'score_source': 'continuous', 'auroc': 0.45762711864406774, 'ap_0': 0.17018500709348688, 'ap_1': 0.8321996817745105, 'scenario': 'mdi80', 'model': 'SVM', 'outer_fold': 1, 'params': {'C': 0.1, 'kernel': 'linear'}, 'inner_f1_macro': 0.44939986263058634}

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

Fase 2 MLP {'accuracy': 0.8194444444444444, 'precision_0': np.float64(0.5), 'precision_1': np.float64(0.8285714285714286), 'recall_0': np.float64(0.07692307692307693), 'recall_1': np.float64(0.9830508474576272), 'f1_0': np.float64(0.13333333333333333), 'f1_1': np.float64(0.8992248062015504), 'f1_macro': 0.5162790697674419, 'f1_weighted': 0.7609388458225668, 'precision_macro': 0.6642857142857144, 'recall_macro': 0.529986962190352, 'balanced_accuracy': 0.529986962190352, 'mcc': 0.14037705656838215, 'specificity': np.float64(0.07692307692307693), 'sensitivity': np.float64(0.9830508474576272), 'TN': 1, 'FP': 12, 'FN': 1, 'TP': 58, 'score_source': 'continuous', 'auroc': 0.6544980443285529, 'ap_0': 0.3302065766644683, 'ap_1': 0.898460737014892, 'scenario': 'mdi80', 'model': 'MLP', 'outer_fold': 1, 'params': {'alpha': 0.01, 'hidden_layer_sizes': (32, 16), 'max_iter': 500}, 'inner_f1_macro': 0.4844097387384384}
Fase 2 LR {'accuracy': 0.8194444444444444, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8194444444444444), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.9007633587786259), 'f1_macro': 0.45038167938931295, 'f1_weighted': 0.7381255301102629, 'precision_macro': 0.4097222222222222, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 13, 'FN': 0, 'TP': 59, 'score_source': 'continuous', 'auroc': 0.5893089960886571, 'ap_0': 0.2428121993488159, 'ap_1': 0.8830797347472681, 'scenario': 'mdi80', 'model': 'LR', 'outer_fold': 1, 'params': {'C': 0.01, 'max_iter': 1000, 'solver': 'lbfgs'}, 'inner_f1_macro': 0.44939986263058634}
Fase 2 XGB {'accuracy': 0.7777777777777778, 'precision_0': np.float64(0.2), 'precision_1': np.float64(0.8208955223880597), 'recall_0': np.float64(0.07692307692307693), 'recall_1': np.float64(0.9322033898305084), 'f1_0': np.float64(0.1111111111111111), 'f1_1': np.float64(0.873015873015873), 'f1_macro': 0.4920634920634921, 'f1_weighted': 0.7354497354497354, 'precision_macro': 0.5104477611940299, 'recall_macro': 0.5045632333767927, 'balanced_accuracy': 0.5045632333767927, 'mcc': 0.013809500004468888, 'specificity': np.float64(0.07692307692307693), 'sensitivity': np.float64(0.9322033898305084), 'TN': 1, 'FP': 12, 'FN': 4, 'TP': 55, 'score_source': 'continuous', 'auroc': 0.5332464146023468, 'ap_0': 0.27465626434240414, 'ap_1': 0.8535033427654728, 'scenario': 'mdi80', 'model': 'XGB', 'outer_fold': 1, 'params': {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}, 'inner_f1_macro': 0.49092975247312126}
Fase 2 NB {'accuracy': 0.7777777777777778, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8115942028985508), 'recall_0': np.float64(0.0), 'recall_1': np.float64(0.9491525423728814), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.875), 'f1_macro': 0.4375, 'f1_weighted': 0.7170138888888888, 'precision_macro': 0.4057971014492754, 'recall_macro': 0.4745762711864407, 'balanced_accuracy': 0.4745762711864407, 'mcc': -0.09787724855562428, 'specificity': np.float64(0.0), 'sensitivity': np.float64(0.9491525423728814), 'TN': 0, 'FP': 13, 'FN': 3, 'TP': 56, 'score_source': 'continuous', 'auroc': 0.5449804432855281, 'ap_0': 0.21249841305320005, 'ap_1': 0.8616357311276361, 'scenario': 'mdi80', 'model': 'NB', 'outer_fold': 1, 'params': {'var_smoothing': 1e-11}, 'inner_f1_macro': 0.47259544999049885}
Fase 2 NC {'accuracy': 0.5277777777777778, 'precision_0': np.float64(0.16129032258064516), 'precision_1': np.float64(0.8048780487804879), 'recall_0': np.float64(0.38461538461538464), 'recall_1': np.float64(0.559322033898305), 'f1_0': np.float64(0.22727272727272727), 'f1_1': np.float64(0.66), 'f1_macro': 0.44363636363636366, 'f1_weighted': 0.5818686868686869, 'precision_macro': 0.4830841856805665, 'recall_macro': 0.47196870925684486, 'balanced_accuracy': 0.47196870925684486, 'mcc': -0.04355098664073034, 'specificity': np.float64(0.38461538461538464), 'sensitivity': np.float64(0.559322033898305), 'TN': 5, 'FP': 8, 'FN': 26, 'TP': 33, 'score_source': 'continuous', 'auroc': 0.5410691003911342, 'ap_0': 0.21263167574863812, 'ap_1': 0.8640608947707391, 'scenario': 'mdi80', 'model': 'NC', 'outer_fold': 1, 'params': {'metric': 'euclidean', 'shrink_threshold': None}, 'inner_f1_macro': 0.4877266176873847}
2026-09-13 19:47:48,077 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:47:48,078 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:47:48,079 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:47:48,079 - opfython.core.opf — INFO — Class created.
2026-09-13 19:47:48,080 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:47:48,080 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:47:48,082 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:47:48,174 - opfython.models.supervised — DEBUG — Prototypes: [335, 176, 208, 108, 417, 351, 367, 274, 469, 504, 130, 332, 154, 94, 118, 319, 97, 215, 403, 131, 122, 359, 303, 416, 230, 35, 455, 37, 46, 273, 331, 447, 127, 297, 432, 498, 138, 384, 290, 363, 392, 418, 166, 29, 510, 292, 160, 20, 470, 377, 344, 299, 345, 435, 96, 412, 181, 397, 258, 317, 92, 286, 188, 284, 229, 211, 53, 19, 150, 84, 171, 212, 225, 365, 240, 249, 421, 110, 83, 128, 93, 216, 389, 419, 496, 61, 422, 42, 16, 24, 72, 73, 196, 2, 361, 316, 437, 446, 158, 445, 254, 65, 390, 41, 17, 276, 296, 382, 124, 333, 350, 139, 32, 451, 57, 352, 102, 423, 410, 213, 164, 223, 262, 5, 380, 117, 283, 478, 343, 486, 7, 8, 370, 184, 398, 64, 220, 454, 54, 272, 81, 267, 144, 45, 360, 452, 500, 407, 170, 162, 25, 321, 10, 263, 120, 133, 501, 483, 287, 71, 76, 75, 241, 278, 260, 313, 243, 222, 383, 59, 239, 68, 265, 444, 408, 294, 348, 261, 379, 44, 195, 281, 233, 425, 183, 479, 95, 203, 156, 257, 477, 201, 132, 224, 431, 487, 493, 79, 354, 509, 186, 40].
2026-09-13 19:47:48,361 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:47:48,362 - opfython.models.supervised — INFO — Training time: 0.2811436653137207 seconds.
2026-09-13 19:47:48,362 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:47:48,444 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:47:48,445 - opfython.models.supervised — INFO — Prediction time: 0.08190441131591797 seconds.
2026-09-13 19:47:48,578 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:47:48,579 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:47:48,579 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:47:48,580 - opfython.core.opf — INFO — Class created.
2026-09-13 19:47:48,580 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:47:48,581 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:47:48,585 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:47:48,678 - opfython.models.supervised — DEBUG — Prototypes: [278, 0, 417, 345, 325, 159, 115, 209, 236, 448, 219, 409, 69, 55, 113, 487, 276, 348, 333, 128, 403, 32, 302, 301, 463, 342, 22, 26, 40, 282, 156, 306, 45, 50, 447, 141, 295, 494, 480, 401, 399, 454, 497, 193, 31, 123, 47, 247, 67, 388, 252, 186, 331, 337, 33, 258, 21, 270, 442, 281, 89, 327, 493, 315, 255, 475, 38, 249, 474, 201, 246, 180, 343, 151, 441, 506, 310, 111, 336, 127, 470, 65, 175, 8, 408, 364, 477, 433, 286, 330, 305, 157, 181, 224, 300, 508, 352, 452, 191, 407, 74, 97, 268, 131, 4, 6, 70, 267, 455, 190, 272, 264, 107, 387, 483, 338, 77, 14, 43, 391, 476, 88, 53, 90, 230, 182, 381, 215, 458, 35, 340, 502, 372, 227, 217, 174, 137, 377, 130, 173, 129, 292, 71, 199, 263, 233, 390, 371, 9, 285, 221, 238, 283, 56, 17, 91, 102, 103, 257, 223, 232, 358, 109, 313, 178, 271, 351, 361, 145, 465, 341, 355, 289, 138, 481, 195, 164, 434, 428, 85, 349, 319, 39, 445, 86, 210, 142, 419, 386, 110, 66, 206, 176, 406, 299, 290, 335, 44, 444, 503, 394, 318, 72, 212, 256, 402, 189, 3, 414, 259, 418, 368, 95, 225, 214, 467, 94, 456, 200, 10].
2026-09-13 19:47:48,866 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:47:48,867 - opfython.models.supervised — INFO — Training time: 0.2855498790740967 seconds.
2026-09-13 19:47:48,868 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:47:48,952 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:47:48,953 - opfython.models.supervised — INFO — Prediction time: 0.08455228805541992 seconds.
2026-09-13 19:47:49,090 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:47:49,091 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:47:49,091 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:47:49,092 - opfython.core.opf — INFO — Class created.
2026-09-13 19:47:49,092 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:47:49,093 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:47:49,094 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:47:49,187 - opfython.models.supervised — DEBUG — Prototypes: [10, 108, 127, 3, 5, 77, 458, 281, 59, 273, 104, 390, 155, 305, 25, 175, 131, 73, 180, 46, 395, 87, 308, 45, 84, 287, 270, 176, 243, 456, 38, 400, 479, 449, 476, 377, 503, 241, 228, 351, 170, 135, 382, 126, 169, 125, 299, 16, 71, 442, 480, 203, 272, 142, 280, 173, 88, 195, 98, 327, 58, 231, 294, 248, 11, 246, 376, 293, 99, 262, 234, 168, 286, 504, 463, 129, 326, 42, 193, 80, 428, 184, 83, 147, 139, 239, 388, 106, 200, 15, 295, 296, 365, 136, 483, 398, 325, 72, 470, 389, 414, 183, 265, 304, 360, 85, 315, 57, 253, 174, 353, 251, 439, 371, 23, 279, 440, 291, 420, 86, 337, 493, 474, 41, 451, 190, 355, 383, 113, 1, 235, 62, 123, 132, 66, 171, 478, 218, 300, 7, 410, 370, 427, 24, 149, 28, 380, 285, 52, 330, 446, 138, 302, 494, 407, 35, 34, 352, 247, 482, 405, 403, 150, 496, 56, 109, 334, 111, 112, 196, 215, 491, 411, 233, 447, 157, 238, 75, 232, 288, 68, 416, 128, 321, 110, 97, 372, 43, 189, 33, 254, 27, 274, 340, 346, 264, 486, 505, 374, 92, 475, 216, 186, 223, 152, 208, 465, 417, 145, 249, 102, 205, 12, 488, 373].
2026-09-13 19:47:49,376 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:47:49,377 - opfython.models.supervised — INFO — Training time: 0.28363537788391113 seconds.
2026-09-13 19:47:49,377 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:47:49,460 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:47:49,460 - opfython.models.supervised — INFO — Prediction time: 0.08284926414489746 seconds.
2026-09-13 19:47:49,610 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:47:49,610 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:47:49,611 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:47:49,611 - opfython.core.opf — INFO — Class created.
2026-09-13 19:47:49,612 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:47:49,613 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:47:49,615 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:47:49,710 - opfython.models.supervised — DEBUG — Prototypes: [228, 121, 59, 223, 486, 142, 331, 376, 39, 57, 367, 468, 110, 170, 503, 236, 464, 75, 442, 131, 113, 319, 286, 53, 330, 138, 305, 407, 36, 35, 350, 310, 358, 386, 417, 444, 271, 200, 100, 405, 95, 409, 151, 496, 196, 393, 263, 420, 174, 301, 23, 30, 510, 37, 469, 342, 307, 346, 414, 135, 139, 421, 237, 389, 109, 48, 72, 326, 42, 192, 79, 438, 356, 66, 423, 296, 248, 12, 232, 377, 246, 101, 90, 22, 61, 194, 164, 102, 187, 245, 364, 257, 267, 291, 317, 357, 264, 122, 99, 402, 372, 172, 337, 274, 344, 449, 177, 3, 295, 288, 339, 384, 259, 108, 86, 312, 206, 85, 290, 275, 316, 501, 261, 385, 97, 256, 96, 285, 280, 70, 62, 14, 11, 140, 73, 147, 26, 321, 25, 508, 155, 146, 297, 83, 343, 448, 411, 478, 303, 71, 130, 6, 104, 354, 117, 2, 453, 63, 283, 184, 446, 185, 424, 412, 88, 181, 351, 152, 33, 458, 89, 56, 382, 129, 294, 233, 136, 243, 502, 400, 477, 440, 65, 161, 29, 8, 9, 370, 203, 397, 46, 381, 50, 378, 202, 427, 218, 309, 213, 252, 360, 221, 220, 225, 207, 457, 436, 94, 476, 145, 375, 244, 433, 488, 493, 208, 507, 205].
2026-09-13 19:47:49,903 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:47:49,904 - opfython.models.supervised — INFO — Training time: 0.2906169891357422 seconds.
2026-09-13 19:47:49,904 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:47:49,990 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:47:49,991 - opfython.models.supervised — INFO — Prediction time: 0.08655357360839844 seconds.
2026-09-13 19:47:50,140 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:47:50,141 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:47:50,142 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:47:50,142 - opfython.core.opf — INFO — Class created.
2026-09-13 19:47:50,143 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:47:50,144 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:47:50,146 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:47:50,247 - opfython.models.supervised — DEBUG — Prototypes: [330, 188, 215, 115, 450, 418, 352, 64, 50, 105, 103, 487, 123, 315, 222, 71, 219, 256, 353, 248, 28, 190, 466, 453, 302, 129, 57, 228, 383, 84, 148, 37, 287, 333, 494, 445, 286, 326, 156, 449, 423, 481, 407, 406, 142, 395, 402, 127, 59, 112, 24, 511, 30, 20, 317, 382, 253, 498, 42, 250, 495, 132, 182, 276, 58, 291, 413, 82, 243, 485, 145, 217, 235, 191, 284, 150, 421, 370, 343, 371, 336, 203, 281, 338, 206, 274, 179, 434, 175, 122, 144, 410, 265, 393, 262, 368, 503, 85, 225, 47, 273, 171, 163, 403, 479, 195, 293, 460, 200, 193, 54, 504, 185, 373, 322, 34, 21, 510, 76, 154, 358, 438, 69, 81, 161, 447, 92, 271, 65, 457, 8, 104, 294, 136, 60, 10, 422, 73, 12, 312, 2, 40, 166, 266, 86, 270, 95, 187, 218, 9, 52, 255, 396, 468, 56, 232, 386, 114, 83, 304, 101, 168, 39, 359, 283, 263, 230, 280, 212, 296, 446, 66, 480, 41, 67, 513, 452, 348, 90, 164, 425, 254, 45, 416, 177, 258, 374, 303, 130, 342, 474, 381, 420, 426, 458, 202, 180, 237, 208, 224, 197, 146, 376, 477, 385, 165, 363, 89, 488, 493].
2026-09-13 19:47:50,451 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:47:50,452 - opfython.models.supervised — INFO — Training time: 0.3071630001068115 seconds.
2026-09-13 19:47:50,452 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:47:50,536 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:47:50,537 - opfython.models.supervised — INFO — Prediction time: 0.0844261646270752 seconds.
2026-09-13 19:47:50,678 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:47:50,679 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:47:50,679 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:47:50,680 - opfython.core.opf — INFO — Class created.
2026-09-13 19:47:50,680 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:47:50,681 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:47:50,682 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:47:50,784 - opfython.models.supervised — DEBUG — Prototypes: [335, 176, 208, 108, 417, 351, 367, 274, 469, 504, 130, 332, 154, 94, 215, 403, 131, 122, 359, 303, 416, 230, 35, 455, 30, 46, 273, 331, 447, 127, 297, 432, 498, 138, 290, 363, 160, 292, 20, 29, 510, 470, 344, 299, 435, 96, 118, 319, 97, 392, 418, 377, 53, 19, 211, 229, 286, 284, 84, 55, 171, 393, 252, 465, 365, 225, 106, 334, 317, 92, 42, 16, 24, 72, 128, 419, 216, 389, 93, 61, 422, 73, 196, 158, 437, 446, 110, 83, 2, 361, 316, 421, 240, 249, 276, 340, 51, 23, 452, 144, 25, 134, 321, 411, 64, 170, 454, 54, 272, 81, 267, 10, 120, 133, 287, 71, 266, 313, 243, 76, 75, 241, 278, 260, 383, 442, 59, 82, 204, 222, 444, 408, 423, 410, 451, 57, 352, 102, 350, 139, 32, 213, 164, 312, 478, 343, 486, 7, 8, 370, 184, 68, 11, 398, 44, 379, 246, 195, 281, 233, 431, 295, 262, 308, 345, 166, 203, 65, 41, 390, 380, 117, 283, 88, 181, 384, 412, 254, 348, 382, 294, 261, 445, 275, 397, 373, 307, 183, 425, 509, 479, 124, 333, 475, 477, 487, 493, 201, 132, 79, 430, 62, 217, 186, 70].
2026-09-13 19:47:50,998 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:47:50,999 - opfython.models.supervised — INFO — Training time: 0.31775736808776855 seconds.
2026-09-13 19:47:50,999 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:47:51,086 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:47:51,087 - opfython.models.supervised — INFO — Prediction time: 0.08705735206604004 seconds.
2026-09-13 19:47:51,232 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:47:51,233 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:47:51,234 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:47:51,235 - opfython.core.opf — INFO — Class created.
2026-09-13 19:47:51,235 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:47:51,236 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:47:51,237 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:47:51,331 - opfython.models.supervised — DEBUG — Prototypes: [278, 0, 417, 345, 325, 159, 115, 209, 236, 448, 219, 409, 69, 55, 113, 487, 128, 403, 32, 302, 301, 511, 416, 211, 463, 342, 22, 40, 457, 45, 306, 19, 295, 141, 269, 401, 96, 454, 497, 331, 435, 123, 47, 249, 474, 201, 89, 327, 21, 166, 442, 281, 336, 246, 180, 343, 151, 441, 506, 127, 470, 65, 175, 293, 8, 408, 364, 310, 116, 111, 388, 396, 483, 338, 97, 267, 268, 131, 152, 6, 57, 272, 190, 455, 70, 453, 181, 157, 300, 74, 264, 207, 387, 35, 458, 88, 87, 53, 42, 182, 230, 397, 381, 344, 77, 14, 43, 391, 502, 262, 142, 307, 386, 419, 110, 195, 164, 434, 428, 85, 349, 319, 39, 445, 86, 210, 66, 406, 299, 176, 257, 103, 223, 232, 358, 285, 78, 221, 238, 233, 371, 283, 56, 17, 91, 102, 109, 313, 178, 271, 351, 361, 145, 355, 289, 335, 44, 394, 318, 444, 503, 206, 465, 189, 3, 414, 259, 286, 305, 71, 217, 372, 227, 193, 31, 186, 292, 276, 348, 333, 33, 476, 418, 138, 481, 340, 298, 41, 72, 199, 451, 263, 424, 174, 137, 173, 129, 256, 377, 130, 247, 353, 258, 402, 212, 225, 214, 198, 467, 94, 456, 200, 10, 328].
2026-09-13 19:47:51,533 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:47:51,534 - opfython.models.supervised — INFO — Training time: 0.2978060245513916 seconds.
2026-09-13 19:47:51,535 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:47:51,619 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:47:51,620 - opfython.models.supervised — INFO — Prediction time: 0.08519792556762695 seconds.
2026-09-13 19:47:51,763 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:47:51,764 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:47:51,764 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:47:51,765 - opfython.core.opf — INFO — Class created.
2026-09-13 19:47:51,765 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:47:51,766 - opfython.models.supervised — INFO — Fitting classifier ...

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

Fase 2 MLP {'accuracy': 0.7638888888888888, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8088235294117647), 'recall_0': np.float64(0.0), 'recall_1': np.float64(0.9322033898305084), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8661417322834646), 'f1_macro': 0.4330708661417323, 'f1_weighted': 0.7097550306211723, 'precision_macro': 0.40441176470588236, 'recall_macro': 0.4661016949152542, 'balanced_accuracy': 0.4661016949152542, 'mcc': -0.1138469000458504, 'specificity': np.float64(0.0), 'sensitivity': np.float64(0.9322033898305084), 'TN': 0, 'FP': 13, 'FN': 4, 'TP': 55, 'score_source': 'continuous', 'auroc': 0.4374185136897001, 'ap_0': 0.1688367347974419, 'ap_1': 0.8055773166709896, 'scenario': 'mdi80', 'model': 'MLP', 'outer_fold': 2, 'params': {'alpha': 0.0001, 'hidden_layer_sizes': (32, 16), 'max_iter': 500}, 'inner_f1_macro': 0.49111862629865144}
Fase 2 LR {'accuracy': 0.8194444444444444, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8194444444444444), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.9007633587786259), 'f1_macro': 0.45038167938931295, 'f1_weighted': 0.7381255301102629, 'precision_macro': 0.4097222222222222, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 13, 'FN': 0, 'TP': 59, 'score_source': 'continuous', 'auroc': 0.44263363754889173, 'ap_0': 0.1709644929571903, 'ap_1': 0.7905209323432252, 'scenario': 'mdi80', 'model': 'LR', 'outer_fold': 2, 'params': {'C': 0.01, 'max_iter': 1000, 'solver': 'lbfgs'}, 'inner_f1_macro': 0.44939986263058634}
Fase 2 XGB {'accuracy': 0.7916666666666666, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8142857142857143), 'recall_0': np.float64(0.0), 'recall_1': np.float64(0.9661016949152542), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8837209302325582), 'f1_macro': 0.4418604651162791, 'f1_weighted': 0.7241602067183464, 'precision_macro': 0.40714285714285714, 'recall_macro': 0.4830508474576271, 'balanced_accuracy': 0.4830508474576271, 'mcc': -0.07934355371256382, 'specificity': np.float64(0.0), 'sensitivity': np.float64(0.9661016949152542), 'TN': 0, 'FP': 13, 'FN': 2, 'TP': 57, 'score_source': 'continuous', 'auroc': 0.4348109517601043, 'ap_0': 0.16176103179500487, 'ap_1': 0.8268950278728568, 'scenario': 'mdi80', 'model': 'XGB', 'outer_fold': 2, 'params': {'learning_rate': 0.05, 'max_depth': 5, 'n_estimators': 200}, 'inner_f1_macro': 0.5097490549165534}
Fase 2 NB {'accuracy': 0.7777777777777778, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8115942028985508), 'recall_0': np.float64(0.0), 'recall_1': np.float64(0.9491525423728814), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.875), 'f1_macro': 0.4375, 'f1_weighted': 0.7170138888888888, 'precision_macro': 0.4057971014492754, 'recall_macro': 0.4745762711864407, 'balanced_accuracy': 0.4745762711864407, 'mcc': -0.09787724855562428, 'specificity': np.float64(0.0), 'sensitivity': np.float64(0.9491525423728814), 'TN': 0, 'FP': 13, 'FN': 3, 'TP': 56, 'score_source': 'continuous', 'auroc': 0.3748370273794003, 'ap_0': 0.14982092356717674, 'ap_1': 0.776995729584795, 'scenario': 'mdi80', 'model': 'NB', 'outer_fold': 2, 'params': {'var_smoothing': 1e-11}, 'inner_f1_macro': 0.4858981876808787}
Fase 2 NC {'accuracy': 0.5, 'precision_0': np.float64(0.15151515151515152), 'precision_1': np.float64(0.7948717948717948), 'recall_0': np.float64(0.38461538461538464), 'recall_1': np.float64(0.5254237288135594), 'f1_0': np.float64(0.21739130434782608), 'f1_1': np.float64(0.6326530612244898), 'f1_macro': 0.42502218278615794, 'f1_weighted': 0.5576752440106478, 'precision_macro': 0.47319347319347316, 'recall_macro': 0.45501955671447203, 'balanced_accuracy': 0.45501955671447203, 'mcc': -0.06944838252120682, 'specificity': np.float64(0.38461538461538464), 'sensitivity': np.float64(0.5254237288135594), 'TN': 5, 'FP': 8, 'FN': 28, 'TP': 31, 'score_source': 'continuous', 'auroc': 0.408735332464146, 'ap_0': 0.16137109521748388, 'ap_1': 0.7788365170945263, 'scenario': 'mdi80', 'model': 'NC', 'outer_fold': 2, 'params': {'metric': 'euclidean', 'shrink_threshold': None}, 'inner_f1_macro': 0.48015119031500514}
2026-09-13 19:49:10,349 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:49:10,350 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:49:10,350 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:49:10,351 - opfython.core.opf — INFO — Class created.
2026-09-13 19:49:10,351 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:49:10,351 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:49:10,353 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:49:10,442 - opfython.models.supervised — DEBUG — Prototypes: [318, 59, 198, 272, 349, 203, 191, 47, 86, 363, 470, 120, 328, 144, 83, 507, 209, 64, 300, 34, 415, 33, 346, 226, 433, 29, 327, 271, 447, 116, 294, 502, 127, 286, 358, 23, 390, 417, 150, 74, 288, 18, 436, 233, 94, 341, 296, 472, 374, 28, 157, 244, 115, 329, 224, 78, 134, 206, 217, 361, 219, 9, 283, 281, 277, 310, 240, 249, 177, 419, 367, 278, 98, 77, 273, 117, 500, 210, 386, 21, 158, 40, 13, 314, 365, 24, 113, 172, 187, 68, 58, 181, 322, 138, 162, 446, 2, 357, 311, 147, 321, 51, 337, 343, 96, 257, 432, 238, 377, 444, 62, 387, 15, 293, 22, 462, 315, 20, 453, 207, 510, 356, 129, 407, 270, 61, 455, 183, 8, 118, 108, 123, 504, 484, 82, 395, 79, 308, 243, 378, 55, 239, 69, 148, 175, 302, 342, 44, 291, 259, 408, 443, 145, 511, 39, 393, 372, 220, 478, 340, 488, 159, 60, 14, 212, 258, 46, 48, 347, 128, 30, 109, 401, 70, 105, 334, 156, 498, 325, 266, 420, 410, 80, 350, 92, 267, 56, 381, 452, 52, 388, 260, 89, 348, 397, 375, 17, 280, 479, 37, 5, 6, 396, 186, 399, 230, 193, 344, 196, 178, 253, 456, 146, 256, 489, 497, 174].
2026-09-13 19:49:10,630 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:49:10,631 - opfython.models.supervised — INFO — Training time: 0.27924680709838867 seconds.
2026-09-13 19:49:10,631 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:49:10,711 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:49:10,712 - opfython.models.supervised — INFO — Prediction time: 0.08017563819885254 seconds.
2026-09-13 19:49:10,857 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:49:10,858 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:49:10,858 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:49:10,859 - opfython.core.opf — INFO — Class created.
2026-09-13 19:49:10,859 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:49:10,860 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:49:10,861 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:49:10,960 - opfython.models.supervised — DEBUG — Prototypes: [312, 63, 344, 210, 3, 341, 322, 189, 52, 103, 133, 211, 33, 426, 506, 159, 467, 285, 19, 298, 349, 415, 403, 29, 28, 338, 465, 460, 132, 429, 319, 301, 404, 17, 292, 128, 267, 482, 400, 406, 498, 141, 386, 417, 173, 433, 165, 287, 240, 110, 435, 332, 294, 334, 371, 129, 220, 101, 272, 314, 37, 77, 201, 62, 238, 181, 445, 2, 351, 307, 277, 306, 370, 94, 55, 218, 217, 366, 226, 82, 315, 188, 164, 308, 487, 395, 146, 421, 247, 255, 361, 278, 115, 92, 162, 21, 113, 154, 428, 169, 443, 261, 375, 258, 66, 384, 391, 455, 441, 98, 81, 121, 497, 317, 337, 95, 342, 109, 401, 385, 263, 339, 142, 227, 25, 178, 53, 64, 14, 222, 50, 373, 16, 280, 394, 505, 106, 166, 61, 124, 478, 114, 489, 6, 7, 359, 195, 376, 58, 246, 392, 184, 266, 304, 249, 276, 78, 80, 79, 450, 90, 265, 65, 387, 457, 70, 18, 500, 68, 485, 123, 501, 282, 75, 202, 289, 409, 44, 510, 372, 367, 228, 194, 422, 237, 200, 494, 206, 208, 214, 197, 259, 256, 486, 213, 86, 458, 476, 364, 477, 274, 509].
2026-09-13 19:49:11,156 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:49:11,156 - opfython.models.supervised — INFO — Training time: 0.2962615489959717 seconds.
2026-09-13 19:49:11,157 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:49:11,237 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:49:11,238 - opfython.models.supervised — INFO — Prediction time: 0.0808103084564209 seconds.
2026-09-13 19:49:11,375 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:49:11,375 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:49:11,376 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:49:11,376 - opfython.core.opf — INFO — Class created.
2026-09-13 19:49:11,376 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:49:11,377 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:49:11,379 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:49:11,474 - opfython.models.supervised — DEBUG — Prototypes: [8, 101, 196, 485, 133, 115, 75, 2, 86, 273, 275, 173, 278, 134, 25, 119, 145, 229, 360, 511, 174, 410, 67, 167, 396, 128, 380, 60, 16, 223, 78, 233, 270, 286, 52, 80, 305, 165, 237, 480, 449, 37, 242, 477, 43, 47, 378, 20, 192, 297, 443, 111, 130, 161, 277, 330, 366, 131, 156, 284, 291, 226, 71, 19, 81, 182, 218, 1, 357, 294, 362, 132, 322, 39, 77, 423, 136, 83, 126, 386, 160, 98, 409, 395, 321, 363, 442, 109, 269, 65, 472, 341, 387, 124, 504, 428, 253, 379, 416, 370, 476, 260, 350, 31, 407, 497, 122, 29, 467, 302, 303, 513, 209, 24, 41, 129, 59, 454, 138, 282, 44, 326, 49, 446, 125, 299, 404, 402, 139, 499, 199, 493, 329, 224, 210, 448, 228, 412, 434, 219, 54, 102, 187, 488, 144, 230, 69, 227, 456, 99, 415, 283, 255, 63, 343, 337, 32, 27, 264, 42, 185, 451, 347, 92, 405, 318, 23, 333, 48, 95, 181, 383, 276, 501, 280, 439, 384, 418, 79, 311, 100, 254, 163, 120, 62, 159, 479, 207, 5, 411, 368, 352, 306, 105, 398, 285, 213, 267, 205, 248, 214, 222, 143, 198, 353, 427, 466, 441, 482, 158, 268, 84, 420, 489, 369, 93, 194, 469].
2026-09-13 19:49:11,666 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:49:11,667 - opfython.models.supervised — INFO — Training time: 0.28965282440185547 seconds.
2026-09-13 19:49:11,668 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:49:11,755 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:49:11,756 - opfython.models.supervised — INFO — Prediction time: 0.08811259269714355 seconds.
2026-09-13 19:49:11,899 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:49:11,900 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:49:11,900 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:49:11,901 - opfython.core.opf — INFO — Class created.
2026-09-13 19:49:11,901 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:49:11,901 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:49:11,903 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:49:12,001 - opfython.models.supervised — DEBUG — Prototypes: [215, 349, 329, 71, 221, 208, 55, 103, 362, 285, 469, 133, 107, 115, 326, 372, 281, 101, 319, 0, 352, 229, 465, 69, 296, 357, 25, 127, 41, 34, 347, 246, 35, 407, 459, 132, 434, 51, 284, 128, 497, 481, 404, 403, 138, 500, 183, 390, 419, 168, 487, 298, 29, 36, 471, 21, 251, 439, 110, 437, 261, 129, 498, 230, 387, 100, 46, 16, 323, 40, 23, 76, 65, 200, 268, 93, 226, 238, 359, 293, 154, 10, 291, 225, 373, 20, 80, 182, 289, 312, 258, 267, 162, 314, 486, 399, 144, 423, 421, 264, 114, 91, 401, 367, 334, 275, 59, 340, 112, 27, 448, 269, 2, 313, 380, 89, 257, 311, 260, 288, 77, 235, 78, 52, 9, 122, 130, 88, 278, 66, 283, 391, 202, 24, 316, 146, 70, 49, 227, 356, 383, 501, 455, 510, 506, 411, 68, 201, 484, 294, 75, 447, 412, 480, 301, 394, 15, 45, 378, 48, 374, 433, 302, 190, 426, 273, 17, 231, 53, 429, 348, 241, 173, 56, 445, 402, 422, 413, 79, 169, 405, 123, 119, 140, 350, 108, 454, 60, 282, 172, 388, 274, 398, 504, 478, 440, 64, 113, 6, 409, 365, 191, 106, 163, 397, 414, 205, 249, 375, 345, 213, 211, 219, 159, 272, 84, 458, 197, 263, 218, 475, 370, 490, 495, 477, 509, 371, 175, 193, 194].
2026-09-13 19:49:12,192 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:49:12,193 - opfython.models.supervised — INFO — Training time: 0.29108428955078125 seconds.
2026-09-13 19:49:12,194 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:49:12,283 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:49:12,284 - opfython.models.supervised — INFO — Prediction time: 0.08980703353881836 seconds.
2026-09-13 19:49:12,424 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:49:12,425 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:49:12,426 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:49:12,426 - opfython.core.opf — INFO — Class created.
2026-09-13 19:49:12,426 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:49:12,427 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:49:12,429 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:49:12,529 - opfython.models.supervised — DEBUG — Prototypes: [315, 57, 351, 418, 349, 364, 276, 474, 325, 66, 363, 98, 177, 494, 210, 209, 234, 412, 430, 151, 95, 461, 216, 64, 22, 408, 120, 84, 130, 462, 36, 435, 26, 233, 44, 304, 322, 449, 357, 299, 417, 407, 405, 410, 178, 122, 35, 392, 249, 163, 156, 291, 15, 24, 27, 475, 377, 338, 341, 238, 361, 439, 247, 438, 203, 78, 319, 176, 220, 308, 7, 287, 212, 372, 226, 285, 189, 282, 376, 307, 48, 88, 137, 169, 254, 470, 146, 362, 224, 277, 17, 72, 40, 311, 73, 196, 56, 192, 54, 154, 94, 106, 403, 368, 283, 250, 1, 358, 170, 447, 286, 332, 260, 49, 340, 434, 243, 381, 60, 390, 398, 457, 76, 75, 221, 399, 505, 89, 133, 281, 74, 68, 6, 444, 125, 97, 85, 266, 268, 18, 312, 62, 8, 16, 31, 42, 214, 502, 511, 383, 455, 59, 459, 288, 71, 153, 446, 294, 481, 184, 425, 453, 293, 262, 228, 265, 39, 396, 373, 378, 207, 297, 420, 413, 445, 404, 271, 167, 53, 384, 77, 114, 164, 329, 497, 117, 229, 86, 113, 90, 454, 50, 168, 58, 347, 227, 379, 14, 284, 480, 32, 99, 157, 55, 118, 185, 366, 479, 337, 489, 506, 261, 105, 306, 202, 345, 152, 259, 206, 82, 460, 134, 96, 478, 279, 490, 496, 510, 187, 4].
2026-09-13 19:49:12,724 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:49:12,725 - opfython.models.supervised — INFO — Training time: 0.29767513275146484 seconds.
2026-09-13 19:49:12,726 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:49:12,815 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:49:12,816 - opfython.models.supervised — INFO — Prediction time: 0.08977961540222168 seconds.
2026-09-13 19:49:12,959 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:49:12,960 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:49:12,960 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:49:12,961 - opfython.core.opf — INFO — Class created.
2026-09-13 19:49:12,962 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:49:12,964 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:49:12,970 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:49:13,101 - opfython.models.supervised — DEBUG — Prototypes: [318, 59, 198, 272, 349, 203, 191, 47, 86, 363, 470, 120, 328, 144, 83, 507, 209, 64, 319, 327, 271, 447, 116, 294, 433, 54, 300, 19, 415, 34, 33, 346, 226, 502, 127, 286, 23, 358, 150, 468, 288, 18, 436, 233, 94, 341, 296, 472, 28, 390, 417, 374, 78, 134, 206, 217, 361, 219, 9, 283, 281, 277, 310, 240, 249, 331, 58, 11, 117, 500, 210, 386, 40, 314, 21, 158, 68, 187, 322, 458, 367, 278, 98, 77, 96, 343, 51, 337, 25, 419, 275, 338, 2, 311, 357, 147, 244, 69, 149, 175, 302, 148, 308, 243, 395, 506, 79, 164, 378, 55, 239, 61, 455, 183, 263, 8, 118, 108, 22, 315, 20, 151, 356, 453, 510, 207, 129, 407, 342, 188, 182, 484, 393, 12, 372, 220, 39, 350, 92, 267, 76, 56, 381, 452, 52, 140, 420, 410, 70, 105, 156, 334, 498, 325, 109, 401, 388, 260, 347, 128, 30, 159, 48, 60, 14, 212, 258, 46, 89, 348, 478, 340, 488, 397, 43, 162, 446, 186, 399, 230, 238, 432, 344, 443, 408, 431, 292, 196, 375, 17, 280, 479, 37, 5, 6, 396, 62, 257, 387, 291, 259, 377, 444, 274, 293, 425, 193, 115, 329, 224, 178, 253, 489, 497, 208, 473, 174].
2026-09-13 19:49:13,312 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:49:13,313 - opfython.models.supervised — INFO — Training time: 0.3466649055480957 seconds.
2026-09-13 19:49:13,313 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:49:13,402 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:49:13,403 - opfython.models.supervised — INFO — Prediction time: 0.08931660652160645 seconds.
2026-09-13 19:49:13,545 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:49:13,546 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:49:13,547 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:49:13,547 - opfython.core.opf — INFO — Class created.
2026-09-13 19:49:13,547 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:49:13,548 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:49:13,549 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:49:13,649 - opfython.models.supervised — DEBUG — Prototypes: [312, 63, 344, 210, 3, 341, 322, 189, 52, 103, 133, 211, 33, 426, 506, 159, 460, 132, 429, 319, 301, 404, 17, 292, 128, 267, 298, 349, 415, 403, 29, 28, 338, 465, 498, 141, 400, 406, 285, 19, 433, 165, 287, 332, 294, 435, 240, 467, 386, 417, 314, 37, 77, 424, 82, 315, 188, 217, 366, 226, 94, 180, 218, 277, 306, 370, 164, 308, 487, 395, 146, 421, 129, 101, 220, 361, 278, 115, 397, 92, 62, 286, 162, 60, 21, 113, 154, 247, 255, 274, 329, 2, 307, 351, 250, 304, 266, 249, 392, 184, 376, 58, 246, 145, 276, 78, 80, 79, 18, 70, 45, 350, 378, 500, 453, 144, 408, 68, 90, 265, 380, 65, 387, 457, 485, 32, 49, 282, 75, 161, 202, 388, 12, 367, 228, 372, 44, 441, 98, 81, 497, 120, 95, 342, 109, 401, 339, 227, 14, 64, 222, 178, 50, 385, 263, 106, 166, 478, 53, 489, 61, 6, 7, 359, 195, 373, 16, 394, 505, 181, 445, 280, 450, 173, 214, 237, 200, 334, 66, 261, 384, 258, 289, 262, 375, 194, 422, 364, 300, 391, 455, 443, 273, 509, 213, 206, 208, 197, 259, 86, 458, 477, 219].
2026-09-13 19:49:13,852 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:49:13,852 - opfython.models.supervised — INFO — Training time: 0.3041062355041504 seconds.
2026-09-13 19:49:13,853 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:49:13,932 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:49:13,933 - opfython.models.supervised — INFO — Prediction time: 0.07957100868225098 seconds.
2026-09-13 19:49:14,075 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:49:14,076 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:49:14,076 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:49:14,077 - opfython.core.opf — INFO — Class created.
2026-09-13 19:49:14,077 - opfython.models.supervised — INFO — Class overrided.

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

Fase 2 MLP {'accuracy': 0.7916666666666666, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8142857142857143), 'recall_0': np.float64(0.0), 'recall_1': np.float64(0.9661016949152542), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8837209302325582), 'f1_macro': 0.4418604651162791, 'f1_weighted': 0.7241602067183464, 'precision_macro': 0.40714285714285714, 'recall_macro': 0.4830508474576271, 'balanced_accuracy': 0.4830508474576271, 'mcc': -0.07934355371256382, 'specificity': np.float64(0.0), 'sensitivity': np.float64(0.9661016949152542), 'TN': 0, 'FP': 13, 'FN': 2, 'TP': 57, 'score_source': 'continuous', 'auroc': 0.4028683181225554, 'ap_0': 0.15261148634553026, 'ap_1': 0.8048098335364036, 'scenario': 'mdi80', 'model': 'MLP', 'outer_fold': 3, 'params': {'alpha': 0.0001, 'hidden_layer_sizes': (32, 16), 'max_iter': 500}, 'inner_f1_macro': 0.5030112246008016}
Fase 2 LR {'accuracy': 0.8194444444444444, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8194444444444444), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.9007633587786259), 'f1_macro': 0.45038167938931295, 'f1_weighted': 0.7381255301102629, 'precision_macro': 0.4097222222222222, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 13, 'FN': 0, 'TP': 59, 'score_source': 'continuous', 'auroc': 0.4132985658409387, 'ap_0': 0.15887123190216235, 'ap_1': 0.7922101995792049, 'scenario': 'mdi80', 'model': 'LR', 'outer_fold': 3, 'params': {'C': 0.01, 'max_iter': 1000, 'solver': 'lbfgs'}, 'inner_f1_macro': 0.44939986263058634}
Fase 2 XGB {'accuracy': 0.7916666666666666, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8142857142857143), 'recall_0': np.float64(0.0), 'recall_1': np.float64(0.9661016949152542), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8837209302325582), 'f1_macro': 0.4418604651162791, 'f1_weighted': 0.7241602067183464, 'precision_macro': 0.40714285714285714, 'recall_macro': 0.4830508474576271, 'balanced_accuracy': 0.4830508474576271, 'mcc': -0.07934355371256382, 'specificity': np.float64(0.0), 'sensitivity': np.float64(0.9661016949152542), 'TN': 0, 'FP': 13, 'FN': 2, 'TP': 57, 'score_source': 'continuous', 'auroc': 0.5032594524119948, 'ap_0': 0.1784662107868949, 'ap_1': 0.8607778514664992, 'scenario': 'mdi80', 'model': 'XGB', 'outer_fold': 3, 'params': {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}, 'inner_f1_macro': 0.5099467718373155}
Fase 2 NB {'accuracy': 0.8055555555555556, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8169014084507042), 'recall_0': np.float64(0.0), 'recall_1': np.float64(0.9830508474576272), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8923076923076924), 'f1_macro': 0.4461538461538462, 'f1_weighted': 0.7311965811965813, 'precision_macro': 0.4084507042253521, 'recall_macro': 0.4915254237288136, 'balanced_accuracy': 0.4915254237288136, 'mcc': -0.05570786262694558, 'specificity': np.float64(0.0), 'sensitivity': np.float64(0.9830508474576272), 'TN': 0, 'FP': 13, 'FN': 1, 'TP': 58, 'score_source': 'continuous', 'auroc': 0.46153846153846156, 'ap_0': 0.1728109361840309, 'ap_1': 0.8030533396536558, 'scenario': 'mdi80', 'model': 'NB', 'outer_fold': 3, 'params': {'var_smoothing': 1e-11}, 'inner_f1_macro': 0.4890947562964003}
Fase 2 NC {'accuracy': 0.5416666666666666, 'precision_0': np.float64(0.14285714285714285), 'precision_1': np.float64(0.7954545454545454), 'recall_0': np.float64(0.3076923076923077), 'recall_1': np.float64(0.5932203389830508), 'f1_0': np.float64(0.1951219512195122), 'f1_1': np.float64(0.6796116504854369), 'f1_macro': 0.4373668008524746, 'f1_weighted': 0.5921343436735339, 'precision_macro': 0.4691558441558441, 'recall_macro': 0.45045632333767927, 'balanced_accuracy': 0.45045632333767927, 'mcc': -0.07818268053898095, 'specificity': np.float64(0.3076923076923077), 'sensitivity': np.float64(0.5932203389830508), 'TN': 4, 'FP': 9, 'FN': 24, 'TP': 35, 'score_source': 'continuous', 'auroc': 0.43155149934810955, 'ap_0': 0.1614537694888877, 'ap_1': 0.8190896211942884, 'scenario': 'mdi80', 'model': 'NC', 'outer_fold': 3, 'params': {'metric': 'euclidean', 'shrink_threshold': None}, 'inner_f1_macro': 0.49680071775463885}
2026-09-13 19:50:31,602 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:50:31,603 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:50:31,604 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:50:31,605 - opfython.core.opf — INFO — Class created.
2026-09-13 19:50:31,605 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:50:31,606 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:50:31,607 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:50:31,717 - opfython.models.supervised — DEBUG — Prototypes: [287, 0, 416, 353, 211, 94, 104, 200, 447, 218, 336, 455, 91, 214, 116, 23, 106, 44, 40, 43, 275, 282, 305, 126, 22, 39, 25, 401, 121, 462, 239, 399, 398, 452, 499, 387, 256, 165, 251, 419, 160, 80, 271, 31, 510, 36, 437, 245, 436, 93, 263, 276, 24, 440, 290, 421, 380, 350, 85, 313, 296, 253, 474, 189, 250, 386, 317, 53, 352, 138, 507, 367, 117, 216, 316, 111, 479, 198, 96, 7, 407, 431, 303, 64, 61, 389, 56, 278, 281, 81, 274, 68, 458, 133, 26, 119, 144, 359, 9, 92, 269, 385, 246, 477, 273, 378, 207, 76, 50, 16, 75, 286, 267, 226, 162, 456, 232, 13, 470, 351, 154, 233, 223, 210, 156, 113, 302, 65, 441, 481, 187, 443, 157, 122, 480, 311, 450, 174, 148, 433, 168, 329, 37, 127, 417, 219, 383, 90, 74, 78, 135, 184, 12, 297, 62, 420, 308, 249, 404, 159, 155, 89, 130, 54, 19, 295, 213, 231, 372, 215, 3, 229, 364, 319, 103, 255, 363, 394, 328, 66, 471, 384, 345, 42, 261, 123, 469, 320, 2, 304, 432, 369, 377, 196, 140, 242, 205, 203, 132, 202, 466, 487, 495, 86, 478].
2026-09-13 19:50:31,927 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:50:31,927 - opfython.models.supervised — INFO — Training time: 0.3209550380706787 seconds.
2026-09-13 19:50:31,928 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:50:32,023 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:50:32,024 - opfython.models.supervised — INFO — Prediction time: 0.09611654281616211 seconds.
2026-09-13 19:50:32,190 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:50:32,190 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:50:32,191 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:50:32,191 - opfython.core.opf — INFO — Class created.
2026-09-13 19:50:32,192 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:50:32,193 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:50:32,195 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:50:32,298 - opfython.models.supervised — DEBUG — Prototypes: [318, 68, 348, 346, 217, 408, 326, 80, 55, 70, 109, 487, 456, 108, 401, 134, 464, 344, 457, 144, 429, 51, 281, 323, 140, 482, 148, 398, 404, 498, 150, 413, 188, 490, 297, 23, 198, 101, 179, 298, 19, 251, 355, 435, 116, 384, 261, 337, 363, 389, 452, 262, 381, 227, 107, 417, 434, 255, 46, 24, 66, 420, 208, 87, 317, 305, 177, 193, 443, 293, 282, 243, 238, 367, 291, 169, 224, 60, 236, 356, 57, 321, 286, 121, 395, 100, 333, 61, 339, 118, 274, 427, 441, 73, 45, 382, 3, 314, 428, 182, 74, 77, 22, 49, 158, 71, 210, 454, 280, 97, 484, 131, 105, 294, 86, 285, 270, 88, 178, 308, 44, 390, 153, 14, 83, 98, 375, 216, 218, 361, 256, 129, 313, 446, 338, 52, 440, 407, 480, 301, 72, 174, 125, 8, 391, 403, 65, 132, 127, 151, 6, 89, 128, 399, 15, 69, 229, 191, 269, 54, 90, 345, 383, 239, 29, 458, 502, 392, 272, 113, 473, 478, 38, 320, 79, 115, 372, 387, 342, 173, 240, 137, 244, 213, 370, 353, 423, 200, 154, 248, 455, 433, 175, 268, 93].
2026-09-13 19:50:32,515 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:50:32,516 - opfython.models.supervised — INFO — Training time: 0.32234835624694824 seconds.
2026-09-13 19:50:32,516 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:50:32,606 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:50:32,606 - opfython.models.supervised — INFO — Prediction time: 0.08975696563720703 seconds.
2026-09-13 19:50:32,752 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:50:32,753 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:50:32,754 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:50:32,754 - opfython.core.opf — INFO — Class created.
2026-09-13 19:50:32,755 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:50:32,755 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:50:32,757 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:50:32,857 - opfython.models.supervised — DEBUG — Prototypes: [9, 106, 209, 485, 123, 303, 5, 287, 184, 26, 129, 156, 174, 362, 450, 185, 411, 74, 179, 79, 16, 32, 380, 95, 394, 17, 87, 314, 19, 233, 85, 173, 279, 294, 456, 175, 245, 398, 477, 8, 470, 480, 41, 204, 168, 250, 171, 134, 170, 122, 206, 487, 442, 440, 482, 139, 316, 242, 384, 416, 194, 81, 432, 359, 84, 90, 203, 14, 302, 142, 18, 104, 117, 40, 337, 300, 236, 248, 10, 59, 22, 365, 228, 238, 2, 504, 169, 463, 304, 196, 114, 265, 72, 471, 346, 47, 413, 182, 275, 428, 192, 379, 135, 501, 405, 36, 462, 355, 25, 44, 455, 332, 308, 138, 484, 402, 400, 149, 496, 213, 20, 188, 35, 241, 335, 336, 108, 234, 115, 57, 71, 200, 454, 162, 105, 237, 415, 187, 69, 325, 125, 23, 107, 98, 29, 282, 433, 258, 387, 267, 180, 45, 342, 293, 358, 276, 223, 319, 126, 58, 186, 70, 263, 474, 208, 347, 239, 64, 120, 498, 24, 419, 438, 296, 272, 86, 339, 495, 323, 403, 475, 383, 353, 101, 315, 301, 507, 67, 172, 306, 7, 409, 395, 479, 219, 427, 370, 92, 476, 217, 257, 226, 211, 224, 503, 145, 222, 273, 91, 453, 244, 488, 494, 102].
2026-09-13 19:50:33,053 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:50:33,054 - opfython.models.supervised — INFO — Training time: 0.29820799827575684 seconds.
2026-09-13 19:50:33,054 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:50:33,140 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:50:33,141 - opfython.models.supervised — INFO — Prediction time: 0.086639404296875 seconds.
2026-09-13 19:50:33,283 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:50:33,283 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:50:33,284 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:50:33,284 - opfython.core.opf — INFO — Class created.
2026-09-13 19:50:33,284 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:50:33,285 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:50:33,287 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:50:33,383 - opfython.models.supervised — DEBUG — Prototypes: [297, 0, 325, 69, 333, 158, 111, 196, 254, 411, 451, 233, 60, 200, 109, 70, 486, 240, 76, 236, 128, 110, 119, 50, 26, 33, 457, 48, 292, 54, 449, 137, 312, 405, 37, 273, 353, 497, 150, 187, 36, 262, 439, 115, 32, 510, 346, 339, 277, 269, 354, 261, 505, 367, 268, 185, 61, 237, 177, 443, 300, 422, 163, 88, 335, 323, 404, 412, 473, 316, 304, 506, 66, 477, 216, 8, 410, 397, 112, 156, 401, 238, 453, 409, 77, 27, 132, 74, 179, 71, 389, 456, 183, 290, 213, 287, 96, 126, 5, 6, 284, 105, 386, 347, 10, 108, 208, 483, 263, 296, 282, 20, 86, 173, 242, 232, 57, 89, 47, 396, 140, 399, 56, 252, 475, 244, 230, 478, 41, 310, 16, 72, 445, 480, 206, 446, 283, 406, 328, 43, 193, 81, 438, 267, 434, 234, 138, 419, 106, 67, 203, 15, 305, 313, 408, 172, 142, 121, 289, 357, 101, 62, 22, 250, 374, 225, 362, 248, 503, 171, 462, 307, 400, 3, 182, 416, 278, 395, 327, 117, 165, 344, 469, 135, 501, 276, 370, 474, 294, 220, 341, 180, 387, 433, 375, 348, 214, 223, 351, 392, 221, 241, 219, 259, 145, 468, 205, 93, 425, 68, 103, 488, 494, 476].
2026-09-13 19:50:33,580 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:50:33,580 - opfython.models.supervised — INFO — Training time: 0.2948729991912842 seconds.
2026-09-13 19:50:33,581 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:50:33,664 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:50:33,665 - opfython.models.supervised — INFO — Prediction time: 0.08358621597290039 seconds.
2026-09-13 19:50:33,808 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:50:33,808 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:50:33,809 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:50:33,810 - opfython.core.opf — INFO — Class created.
2026-09-13 19:50:33,810 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:50:33,810 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:50:33,812 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:50:33,908 - opfython.models.supervised — DEBUG — Prototypes: [322, 63, 356, 212, 354, 418, 332, 76, 218, 112, 51, 65, 102, 487, 133, 329, 372, 34, 226, 72, 505, 163, 122, 19, 103, 297, 23, 286, 328, 448, 459, 58, 435, 466, 352, 405, 408, 416, 176, 268, 25, 511, 31, 298, 169, 17, 475, 376, 347, 262, 227, 387, 100, 496, 187, 78, 439, 252, 21, 377, 358, 43, 69, 325, 37, 447, 81, 203, 61, 200, 420, 182, 151, 222, 236, 240, 296, 159, 8, 95, 315, 291, 254, 263, 261, 114, 93, 401, 167, 2, 361, 316, 161, 434, 171, 381, 338, 276, 55, 345, 446, 267, 68, 388, 42, 66, 53, 391, 456, 91, 279, 285, 136, 22, 319, 412, 20, 46, 360, 452, 224, 499, 383, 506, 410, 70, 484, 346, 131, 7, 75, 11, 201, 378, 45, 397, 96, 313, 278, 382, 92, 253, 256, 168, 308, 41, 368, 344, 166, 350, 301, 273, 67, 1, 394, 121, 97, 283, 178, 444, 293, 421, 411, 84, 157, 174, 495, 124, 406, 327, 389, 274, 353, 142, 26, 180, 64, 85, 48, 460, 223, 57, 234, 504, 399, 35, 337, 60, 125, 113, 479, 343, 105, 390, 135, 239, 396, 454, 202, 245, 362, 493, 209, 215, 198, 426, 164, 165, 270, 485, 88, 457, 371, 478, 289, 469, 369, 508, 488, 235].
2026-09-13 19:50:34,103 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:50:34,104 - opfython.models.supervised — INFO — Training time: 0.29344654083251953 seconds.
2026-09-13 19:50:34,105 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:50:34,193 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:50:34,194 - opfython.models.supervised — INFO — Prediction time: 0.08855319023132324 seconds.
2026-09-13 19:50:34,335 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:50:34,335 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:50:34,336 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:50:34,337 - opfython.core.opf — INFO — Class created.
2026-09-13 19:50:34,337 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:50:34,338 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:50:34,340 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:50:34,436 - opfython.models.supervised — DEBUG — Prototypes: [287, 0, 416, 353, 211, 200, 218, 336, 455, 91, 214, 116, 23, 401, 121, 462, 239, 25, 129, 43, 282, 305, 126, 22, 275, 399, 80, 452, 499, 160, 36, 436, 93, 437, 245, 31, 510, 271, 106, 44, 40, 276, 24, 440, 290, 421, 380, 350, 85, 296, 313, 253, 474, 189, 317, 53, 250, 386, 352, 138, 507, 367, 117, 216, 316, 111, 479, 198, 96, 7, 407, 431, 303, 387, 395, 64, 61, 389, 169, 278, 281, 81, 274, 68, 458, 133, 26, 119, 144, 217, 359, 140, 406, 9, 92, 269, 385, 286, 267, 16, 75, 221, 50, 76, 41, 311, 162, 226, 378, 207, 46, 456, 232, 246, 477, 67, 329, 37, 174, 148, 433, 168, 74, 78, 135, 127, 417, 219, 383, 90, 184, 12, 297, 62, 420, 308, 249, 404, 159, 229, 364, 215, 3, 57, 388, 464, 151, 10, 295, 213, 231, 372, 54, 19, 130, 108, 155, 363, 103, 255, 29, 394, 328, 66, 471, 345, 42, 320, 2, 65, 441, 481, 165, 302, 196, 242, 384, 205, 307, 351, 391, 470, 187, 443, 450, 223, 210, 154, 233, 251, 360, 263, 261, 156, 113, 157, 122, 432, 191, 369, 377, 347, 203, 480, 114, 123, 469, 186, 202, 258, 487, 495, 132, 237, 478, 86, 494].
2026-09-13 19:50:34,633 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:50:34,634 - opfython.models.supervised — INFO — Training time: 0.29492664337158203 seconds.
2026-09-13 19:50:34,634 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:50:34,715 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:50:34,716 - opfython.models.supervised — INFO — Prediction time: 0.08106327056884766 seconds.
2026-09-13 19:50:34,858 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:50:34,858 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:50:34,859 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:50:34,859 - opfython.core.opf — INFO — Class created.
2026-09-13 19:50:34,859 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:50:34,860 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:50:34,864 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:50:34,962 - opfython.models.supervised — DEBUG — Prototypes: [318, 68, 348, 346, 217, 408, 326, 80, 55, 70, 109, 487, 456, 108, 401, 33, 464, 344, 457, 289, 429, 323, 281, 402, 20, 482, 140, 148, 398, 404, 498, 150, 297, 23, 179, 298, 19, 435, 251, 116, 198, 101, 135, 46, 434, 255, 141, 496, 227, 381, 417, 107, 66, 420, 305, 177, 224, 160, 236, 356, 238, 367, 293, 243, 291, 57, 321, 286, 121, 100, 118, 339, 333, 61, 208, 87, 317, 74, 147, 22, 406, 49, 352, 377, 450, 225, 152, 71, 454, 97, 280, 294, 410, 86, 484, 142, 390, 14, 285, 270, 88, 308, 44, 256, 53, 98, 375, 361, 446, 313, 129, 338, 440, 480, 15, 69, 229, 191, 269, 54, 90, 345, 383, 239, 29, 458, 181, 127, 102, 6, 89, 39, 128, 329, 495, 186, 241, 476, 167, 399, 394, 113, 488, 470, 8, 403, 391, 502, 392, 387, 2, 314, 3, 413, 188, 490, 384, 193, 443, 301, 72, 272, 310, 52, 372, 342, 473, 478, 38, 73, 45, 382, 337, 173, 240, 174, 125, 389, 452, 441, 106, 428, 182, 220, 137, 325, 244, 423, 200, 93, 455, 206, 261, 67, 228, 330].
2026-09-13 19:50:35,165 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:50:35,166 - opfython.models.supervised — INFO — Training time: 0.30538320541381836 seconds.
2026-09-13 19:50:35,167 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:50:35,254 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:50:35,255 - opfython.models.supervised — INFO — Prediction time: 0.08728575706481934 seconds.
2026-09-13 19:50:35,393 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:50:35,393 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:50:35,394 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:50:35,394 - opfython.core.opf — INFO — Class created.
2026-09-13 19:50:35,394 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:50:35,395 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:50:35,397 - opfython.models.supervised — DEBUG — Finding prototypes ...

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

Fase 2 MLP {'accuracy': 0.7777777777777778, 'precision_0': np.float64(0.3333333333333333), 'precision_1': np.float64(0.8181818181818182), 'recall_0': np.float64(0.14285714285714285), 'recall_1': np.float64(0.9310344827586207), 'f1_0': np.float64(0.2), 'f1_1': np.float64(0.8709677419354839), 'f1_macro': 0.535483870967742, 'f1_weighted': 0.7405017921146952, 'precision_macro': 0.5757575757575758, 'recall_macro': 0.5369458128078818, 'balanced_accuracy': 0.5369458128078818, 'mcc': 0.10580973892262123, 'specificity': np.float64(0.14285714285714285), 'sensitivity': np.float64(0.9310344827586207), 'TN': 2, 'FP': 12, 'FN': 4, 'TP': 54, 'score_source': 'continuous', 'auroc': 0.500615763546798, 'ap_0': 0.2460088711133289, 'ap_1': 0.8292837087240339, 'scenario': 'mdi80', 'model': 'MLP', 'outer_fold': 4, 'params': {'alpha': 0.0001, 'hidden_layer_sizes': (32, 16), 'max_iter': 500}, 'inner_f1_macro': 0.4796157180369522}
Fase 2 LR {'accuracy': 0.8055555555555556, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8055555555555556), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8923076923076924), 'f1_macro': 0.4461538461538462, 'f1_weighted': 0.7188034188034188, 'precision_macro': 0.4027777777777778, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 14, 'FN': 0, 'TP': 58, 'score_source': 'continuous', 'auroc': 0.5732758620689655, 'ap_0': 0.27849785559869594, 'ap_1': 0.8293566229926308, 'scenario': 'mdi80', 'model': 'LR', 'outer_fold': 4, 'params': {'C': 0.01, 'max_iter': 1000, 'solver': 'lbfgs'}, 'inner_f1_macro': 0.4498734455816001}
Fase 2 XGB {'accuracy': 0.75, 'precision_0': np.float64(0.16666666666666666), 'precision_1': np.float64(0.803030303030303), 'recall_0': np.float64(0.07142857142857142), 'recall_1': np.float64(0.9137931034482759), 'f1_0': np.float64(0.1), 'f1_1': np.float64(0.8548387096774194), 'f1_macro': 0.4774193548387097, 'f1_weighted': 0.7080645161290322, 'precision_macro': 0.4848484848484848, 'recall_macro': 0.49261083743842365, 'balanced_accuracy': 0.49261083743842365, 'mcc': -0.021161947784524248, 'specificity': np.float64(0.07142857142857142), 'sensitivity': np.float64(0.9137931034482759), 'TN': 1, 'FP': 13, 'FN': 5, 'TP': 53, 'score_source': 'continuous', 'auroc': 0.5252463054187192, 'ap_0': 0.21970320838495738, 'ap_1': 0.8546477047480769, 'scenario': 'mdi80', 'model': 'XGB', 'outer_fold': 4, 'params': {'learning_rate': 0.05, 'max_depth': 5, 'n_estimators': 200}, 'inner_f1_macro': 0.4989175165127273}
Fase 2 NB {'accuracy': 0.7777777777777778, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8), 'recall_0': np.float64(0.0), 'recall_1': np.float64(0.9655172413793104), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.875), 'f1_macro': 0.4375, 'f1_weighted': 0.7048611111111112, 'precision_macro': 0.4, 'recall_macro': 0.4827586206896552, 'balanced_accuracy': 0.4827586206896552, 'mcc': -0.08304547985373997, 'specificity': np.float64(0.0), 'sensitivity': np.float64(0.9655172413793104), 'TN': 0, 'FP': 14, 'FN': 2, 'TP': 56, 'score_source': 'continuous', 'auroc': 0.5548029556650247, 'ap_0': 0.28209867454270443, 'ap_1': 0.8133344405922843, 'scenario': 'mdi80', 'model': 'NB', 'outer_fold': 4, 'params': {'var_smoothing': 1e-11}, 'inner_f1_macro': 0.4596732822498292}
Fase 2 NC {'accuracy': 0.5138888888888888, 'precision_0': np.float64(0.21621621621621623), 'precision_1': np.float64(0.8285714285714286), 'recall_0': np.float64(0.5714285714285714), 'recall_1': np.float64(0.5), 'f1_0': np.float64(0.3137254901960784), 'f1_1': np.float64(0.6236559139784946), 'f1_macro': 0.4686907020872865, 'f1_weighted': 0.5633916649096915, 'precision_macro': 0.5223938223938225, 'recall_macro': 0.5357142857142857, 'balanced_accuracy': 0.5357142857142857, 'mcc': 0.05656074155128954, 'specificity': np.float64(0.5714285714285714), 'sensitivity': np.float64(0.5), 'TN': 8, 'FP': 6, 'FN': 29, 'TP': 29, 'score_source': 'continuous', 'auroc': 0.5326354679802956, 'ap_0': 0.25766686136251926, 'ap_1': 0.8030008483132837, 'scenario': 'mdi80', 'model': 'NC', 'outer_fold': 4, 'params': {'metric': 'euclidean', 'shrink_threshold': 0.1}, 'inner_f1_macro': 0.47980056357622847}
2026-09-13 19:51:54,362 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:51:54,363 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:51:54,364 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:51:54,364 - opfython.core.opf — INFO — Class created.
2026-09-13 19:51:54,365 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:51:54,365 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:51:54,367 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:51:54,469 - opfython.models.supervised — DEBUG — Prototypes: [283, 0, 326, 60, 336, 93, 209, 198, 47, 178, 92, 205, 486, 456, 89, 512, 33, 498, 233, 40, 19, 277, 313, 497, 122, 287, 271, 168, 32, 27, 267, 340, 104, 257, 36, 258, 245, 391, 342, 420, 285, 452, 348, 82, 73, 80, 338, 496, 254, 475, 85, 21, 419, 401, 275, 410, 384, 312, 291, 353, 380, 96, 157, 244, 317, 90, 351, 507, 368, 166, 48, 246, 72, 213, 316, 109, 94, 118, 7, 407, 378, 429, 300, 212, 256, 204, 364, 223, 225, 374, 49, 330, 75, 173, 127, 272, 87, 106, 186, 365, 504, 151, 280, 464, 294, 361, 123, 88, 215, 389, 416, 436, 242, 431, 163, 70, 77, 132, 154, 305, 101, 147, 249, 376, 471, 430, 243, 370, 2, 320, 413, 415, 255, 371, 476, 113, 293, 5, 66, 459, 273, 270, 51, 164, 192, 393, 61, 63, 461, 141, 214, 265, 191, 282, 263, 15, 71, 74, 309, 38, 457, 30, 479, 450, 375, 227, 477, 12, 349, 299, 264, 62, 442, 181, 444, 153, 120, 379, 17, 152, 111, 451, 218, 395, 466, 137, 490, 129, 236, 488, 495, 83, 183, 10].
2026-09-13 19:51:54,673 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:51:54,674 - opfython.models.supervised — INFO — Training time: 0.3083922863006592 seconds.
2026-09-13 19:51:54,675 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:51:54,765 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:51:54,766 - opfython.models.supervised — INFO — Prediction time: 0.09071874618530273 seconds.
2026-09-13 19:51:54,915 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:51:54,916 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:51:54,916 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:51:54,916 - opfython.core.opf — INFO — Class created.
2026-09-13 19:51:54,917 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:51:54,917 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:51:54,920 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:51:55,019 - opfython.models.supervised — DEBUG — Prototypes: [344, 0, 97, 414, 346, 127, 315, 109, 186, 64, 71, 457, 106, 425, 402, 32, 340, 92, 304, 60, 413, 464, 283, 86, 26, 458, 400, 153, 46, 276, 324, 446, 440, 17, 419, 496, 149, 174, 430, 108, 25, 33, 471, 245, 433, 159, 8, 404, 361, 111, 371, 388, 476, 395, 2, 268, 332, 338, 222, 237, 250, 239, 253, 84, 128, 311, 257, 138, 497, 19, 375, 381, 189, 274, 289, 410, 61, 363, 337, 212, 272, 129, 184, 351, 302, 427, 126, 125, 150, 6, 141, 49, 226, 358, 501, 503, 169, 215, 345, 459, 15, 377, 124, 397, 292, 353, 197, 56, 502, 192, 365, 473, 366, 134, 305, 336, 474, 374, 417, 415, 93, 236, 278, 480, 270, 66, 455, 7, 137, 224, 334, 386, 11, 267, 269, 484, 293, 290, 62, 418, 146, 193, 160, 432, 248, 69, 82, 168, 444, 167, 172, 80, 205, 301, 85, 133, 104, 173, 306, 229, 200, 281, 266, 53, 271, 88, 98, 394, 9, 288, 232, 369, 286, 99, 261, 223, 73, 43, 3, 370, 234, 219, 299, 194, 297, 67, 116, 115, 68, 44, 512, 452, 341, 443, 170, 508, 183, 412, 442, 279, 144, 238, 251, 262, 230, 217, 214, 280, 348, 376, 213, 225, 244, 478, 467, 490, 90, 456, 489, 494, 202, 318, 198, 396].
2026-09-13 19:51:55,215 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:51:55,216 - opfython.models.supervised — INFO — Training time: 0.2980825901031494 seconds.
2026-09-13 19:51:55,217 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:51:55,303 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:51:55,304 - opfython.models.supervised — INFO — Prediction time: 0.08642840385437012 seconds.
2026-09-13 19:51:55,445 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:51:55,446 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:51:55,447 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:51:55,447 - opfython.core.opf — INFO — Class created.
2026-09-13 19:51:55,447 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:51:55,448 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:51:55,450 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:51:55,544 - opfython.models.supervised — DEBUG — Prototypes: [485, 349, 204, 91, 279, 281, 68, 393, 453, 181, 284, 143, 151, 309, 276, 210, 398, 137, 82, 50, 84, 18, 168, 239, 231, 273, 242, 173, 457, 36, 479, 449, 38, 470, 245, 477, 44, 46, 165, 131, 381, 20, 302, 14, 69, 441, 481, 200, 275, 190, 76, 427, 79, 80, 144, 135, 140, 389, 104, 199, 13, 298, 63, 209, 417, 138, 169, 321, 163, 504, 296, 234, 97, 2, 225, 366, 244, 54, 10, 89, 96, 167, 70, 471, 346, 390, 426, 188, 266, 415, 320, 413, 422, 372, 476, 53, 67, 196, 108, 335, 235, 410, 232, 113, 414, 249, 455, 157, 291, 287, 65, 325, 123, 323, 107, 95, 134, 496, 286, 45, 332, 445, 456, 26, 406, 33, 311, 310, 32, 353, 462, 483, 41, 370, 115, 25, 277, 341, 348, 269, 257, 256, 171, 354, 438, 259, 81, 119, 236, 22, 158, 418, 439, 293, 265, 83, 338, 495, 475, 404, 285, 39, 452, 185, 356, 382, 110, 1, 315, 297, 7, 409, 369, 425, 376, 289, 358, 342, 271, 221, 222, 229, 149, 465, 141, 87, 454, 100, 489, 494, 202, 11].
2026-09-13 19:51:55,750 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:51:55,751 - opfython.models.supervised — INFO — Training time: 0.30304956436157227 seconds.
2026-09-13 19:51:55,752 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:51:55,834 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:51:55,835 - opfython.models.supervised — INFO — Prediction time: 0.0822298526763916 seconds.
2026-09-13 19:51:55,984 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:51:55,985 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:51:55,985 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:51:55,985 - opfython.core.opf — INFO — Class created.
2026-09-13 19:51:55,986 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:51:55,986 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:51:55,988 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:51:56,086 - opfython.models.supervised — DEBUG — Prototypes: [352, 0, 94, 417, 169, 333, 322, 226, 114, 53, 65, 105, 103, 487, 178, 70, 123, 22, 106, 32, 293, 454, 406, 311, 349, 98, 355, 109, 1, 309, 416, 382, 458, 295, 47, 314, 331, 130, 444, 21, 386, 392, 400, 112, 231, 271, 439, 253, 437, 486, 155, 7, 8, 367, 107, 261, 374, 83, 485, 401, 147, 229, 246, 194, 317, 292, 334, 443, 258, 368, 385, 23, 498, 380, 512, 266, 195, 344, 369, 300, 412, 166, 180, 430, 305, 289, 340, 214, 219, 3, 353, 364, 18, 228, 234, 428, 262, 276, 50, 134, 117, 284, 170, 243, 463, 121, 144, 5, 402, 301, 360, 477, 199, 279, 502, 185, 371, 197, 415, 475, 175, 198, 469, 212, 343, 418, 381, 19, 187, 156, 436, 256, 150, 128, 68, 176, 91, 282, 66, 457, 131, 280, 233, 389, 12, 281, 483, 302, 308, 80, 62, 421, 73, 15, 320, 2, 43, 326, 399, 97, 299, 242, 375, 297, 55, 327, 501, 95, 85, 263, 189, 230, 270, 96, 240, 92, 82, 291, 277, 84, 101, 168, 236, 237, 288, 113, 440, 67, 275, 513, 44, 446, 479, 448, 164, 424, 269, 46, 137, 247, 425, 259, 504, 272, 432, 216, 223, 476, 146, 218, 484, 491, 165, 359, 489, 370, 200].
2026-09-13 19:51:56,277 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:51:56,278 - opfython.models.supervised — INFO — Training time: 0.2907562255859375 seconds.
2026-09-13 19:51:56,278 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:51:56,361 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:51:56,362 - opfython.models.supervised — INFO — Prediction time: 0.08312773704528809 seconds.
2026-09-13 19:51:56,501 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:51:56,502 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:51:56,502 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:51:56,503 - opfython.core.opf — INFO — Class created.
2026-09-13 19:51:56,503 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:51:56,503 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:51:56,505 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:51:56,597 - opfython.models.supervised — DEBUG — Prototypes: [322, 60, 354, 416, 352, 330, 71, 219, 206, 47, 104, 62, 488, 365, 4, 503, 161, 373, 102, 505, 124, 18, 105, 276, 44, 282, 311, 495, 133, 17, 36, 459, 431, 308, 415, 407, 28, 27, 350, 466, 481, 297, 361, 19, 167, 298, 23, 511, 29, 246, 441, 438, 342, 304, 194, 393, 370, 171, 271, 336, 344, 113, 94, 150, 223, 234, 240, 294, 157, 9, 222, 374, 93, 83, 187, 325, 288, 378, 317, 329, 358, 258, 226, 185, 496, 73, 155, 242, 173, 250, 437, 357, 41, 13, 58, 417, 200, 78, 369, 289, 164, 101, 179, 64, 40, 391, 3, 302, 318, 430, 251, 211, 148, 410, 225, 359, 385, 454, 498, 508, 144, 65, 68, 201, 89, 273, 275, 484, 345, 70, 11, 39, 397, 381, 42, 287, 120, 267, 79, 80, 38, 309, 399, 95, 315, 254, 375, 238, 343, 348, 445, 63, 480, 301, 268, 34, 347, 96, 353, 108, 2, 278, 174, 453, 52, 81, 123, 326, 184, 418, 411, 444, 175, 406, 176, 48, 61, 14, 228, 46, 82, 460, 237, 202, 504, 400, 224, 131, 232, 33, 478, 107, 351, 195, 367, 379, 207, 360, 145, 244, 212, 162, 265, 261, 85, 457, 209, 59, 475].
2026-09-13 19:51:56,785 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:51:56,786 - opfython.models.supervised — INFO — Training time: 0.28241658210754395 seconds.
2026-09-13 19:51:56,787 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:51:56,866 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:51:56,867 - opfython.models.supervised — INFO — Prediction time: 0.08007049560546875 seconds.
2026-09-13 19:51:57,004 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:51:57,004 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:51:57,005 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:51:57,005 - opfython.core.opf — INFO — Class created.
2026-09-13 19:51:57,005 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:51:57,006 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:51:57,007 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:51:57,103 - opfython.models.supervised — DEBUG — Prototypes: [283, 0, 326, 60, 336, 93, 209, 102, 47, 178, 92, 205, 486, 456, 89, 40, 277, 43, 447, 122, 497, 33, 233, 27, 267, 340, 408, 238, 21, 286, 85, 172, 383, 500, 338, 73, 496, 254, 475, 401, 410, 80, 348, 82, 452, 176, 384, 419, 291, 312, 72, 246, 166, 474, 48, 317, 90, 244, 157, 351, 507, 368, 213, 316, 109, 118, 94, 353, 196, 96, 365, 504, 321, 87, 127, 151, 280, 256, 212, 204, 364, 223, 225, 374, 49, 330, 75, 173, 294, 361, 123, 416, 215, 389, 88, 436, 242, 431, 163, 70, 132, 154, 305, 101, 147, 249, 376, 471, 74, 309, 38, 71, 15, 155, 263, 282, 141, 306, 63, 158, 273, 192, 61, 393, 268, 113, 293, 5, 66, 459, 265, 191, 457, 30, 375, 227, 479, 450, 297, 320, 2, 413, 168, 32, 438, 477, 415, 349, 395, 104, 502, 36, 430, 243, 370, 7, 407, 429, 300, 62, 442, 299, 181, 444, 451, 258, 245, 264, 153, 120, 379, 17, 152, 111, 255, 371, 476, 137, 391, 28, 207, 59, 216, 466, 490, 253, 488, 495, 129, 231, 83, 183, 10, 494].
2026-09-13 19:51:57,305 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:51:57,305 - opfython.models.supervised — INFO — Training time: 0.2991361618041992 seconds.
2026-09-13 19:51:57,306 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:51:57,387 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:51:57,388 - opfython.models.supervised — INFO — Prediction time: 0.08139634132385254 seconds.
2026-09-13 19:51:57,531 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:51:57,532 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:51:57,532 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:51:57,533 - opfython.core.opf — INFO — Class created.
2026-09-13 19:51:57,533 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:51:57,534 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:51:57,536 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:51:57,636 - opfython.models.supervised — DEBUG — Prototypes: [344, 0, 97, 414, 346, 127, 315, 109, 186, 64, 71, 457, 106, 425, 86, 140, 458, 400, 153, 46, 276, 324, 446, 440, 17, 419, 496, 402, 307, 340, 92, 304, 60, 464, 283, 174, 25, 245, 433, 159, 471, 430, 108, 111, 8, 404, 361, 371, 388, 476, 395, 2, 268, 253, 84, 222, 237, 250, 239, 128, 311, 19, 375, 381, 274, 289, 410, 257, 138, 497, 61, 171, 363, 337, 272, 129, 184, 351, 427, 126, 125, 150, 6, 265, 87, 226, 49, 358, 501, 177, 169, 215, 345, 459, 15, 397, 292, 353, 377, 124, 502, 365, 93, 278, 66, 7, 455, 137, 383, 224, 334, 386, 105, 269, 484, 293, 290, 62, 418, 69, 81, 193, 160, 432, 248, 444, 82, 168, 80, 301, 172, 205, 500, 53, 88, 98, 9, 288, 394, 232, 369, 286, 164, 99, 261, 223, 281, 266, 85, 306, 104, 173, 42, 116, 73, 291, 370, 234, 287, 183, 412, 189, 297, 67, 219, 197, 56, 341, 3, 214, 473, 336, 294, 474, 374, 366, 305, 134, 144, 238, 119, 122, 68, 44, 512, 452, 417, 443, 170, 508, 230, 212, 442, 279, 478, 225, 217, 280, 348, 376, 251, 259, 262, 228, 213, 79, 332, 489, 494, 467, 415, 90, 456, 201].
2026-09-13 19:51:57,836 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:51:57,837 - opfython.models.supervised — INFO — Training time: 0.3023364543914795 seconds.
2026-09-13 19:51:57,837 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:51:57,923 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:51:57,924 - opfython.models.supervised — INFO — Prediction time: 0.08678293228149414 seconds.
2026-09-13 19:51:58,069 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:51:58,070 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:51:58,070 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:51:58,071 - opfython.core.opf — INFO — Class created.
2026-09-13 19:51:58,071 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:51:58,071 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:51:58,073 - opfython.models.supervised — DEBUG — Finding prototypes ...

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

Fase 2 MLP {'accuracy': 0.7887323943661971, 'precision_0': np.float64(0.25), 'precision_1': np.float64(0.8208955223880597), 'recall_0': np.float64(0.07692307692307693), 'recall_1': np.float64(0.9482758620689655), 'f1_0': np.float64(0.11764705882352941), 'f1_1': np.float64(0.88), 'f1_macro': 0.4988235294117647, 'f1_weighted': 0.7404142502071251, 'precision_macro': 0.5354477611940298, 'recall_macro': 0.5125994694960212, 'balanced_accuracy': 0.5125994694960212, 'mcc': 0.04226691310547407, 'specificity': np.float64(0.07692307692307693), 'sensitivity': np.float64(0.9482758620689655), 'TN': 1, 'FP': 12, 'FN': 3, 'TP': 55, 'score_source': 'continuous', 'auroc': 0.5351458885941645, 'ap_0': 0.23398530059071357, 'ap_1': 0.8441456550201396, 'scenario': 'mdi80', 'model': 'MLP', 'outer_fold': 5, 'params': {'alpha': 0.01, 'hidden_layer_sizes': (32, 16), 'max_iter': 500}, 'inner_f1_macro': 0.4800104421065277}
Fase 2 LR {'accuracy': 0.8169014084507042, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8169014084507042), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8992248062015504), 'f1_macro': 0.4496124031007752, 'f1_weighted': 0.7345780106998581, 'precision_macro': 0.4084507042253521, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 13, 'FN': 0, 'TP': 58, 'score_source': 'continuous', 'auroc': 0.653183023872679, 'ap_0': 0.3362327919481616, 'ap_1': 0.8892728485629182, 'scenario': 'mdi80', 'model': 'LR', 'outer_fold': 5, 'params': {'C': 0.01, 'max_iter': 1000, 'solver': 'lbfgs'}, 'inner_f1_macro': 0.449488279960383}
Fase 2 XGB {'accuracy': 0.7746478873239436, 'precision_0': np.float64(0.2857142857142857), 'precision_1': np.float64(0.828125), 'recall_0': np.float64(0.15384615384615385), 'recall_1': np.float64(0.9137931034482759), 'f1_0': np.float64(0.2), 'f1_1': np.float64(0.8688524590163934), 'f1_macro': 0.5344262295081967, 'f1_weighted': 0.7463865158162086, 'precision_macro': 0.5569196428571428, 'recall_macro': 0.5338196286472149, 'balanced_accuracy': 0.5338196286472149, 'mcc': 0.08774967086344351, 'specificity': np.float64(0.15384615384615385), 'sensitivity': np.float64(0.9137931034482759), 'TN': 2, 'FP': 11, 'FN': 5, 'TP': 53, 'score_source': 'continuous', 'auroc': 0.48342175066313, 'ap_0': 0.25644876491030333, 'ap_1': 0.7920130582540399, 'scenario': 'mdi80', 'model': 'XGB', 'outer_fold': 5, 'params': {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}, 'inner_f1_macro': 0.4912446821716946}
Fase 2 NB {'accuracy': 0.8169014084507042, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8169014084507042), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8992248062015504), 'f1_macro': 0.4496124031007752, 'f1_weighted': 0.7345780106998581, 'precision_macro': 0.4084507042253521, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 13, 'FN': 0, 'TP': 58, 'score_source': 'continuous', 'auroc': 0.4409814323607427, 'ap_0': 0.21294475489643797, 'ap_1': 0.8143537558566324, 'scenario': 'mdi80', 'model': 'NB', 'outer_fold': 5, 'params': {'var_smoothing': 1e-11}, 'inner_f1_macro': 0.449488279960383}
Fase 2 NC {'accuracy': 0.5774647887323944, 'precision_0': np.float64(0.2571428571428571), 'precision_1': np.float64(0.8888888888888888), 'recall_0': np.float64(0.6923076923076923), 'recall_1': np.float64(0.5517241379310345), 'f1_0': np.float64(0.375), 'f1_1': np.float64(0.6808510638297872), 'f1_macro': 0.5279255319148937, 'f1_weighted': 0.6248501648186995, 'precision_macro': 0.573015873015873, 'recall_macro': 0.6220159151193634, 'balanced_accuracy': 0.6220159151193634, 'mcc': 0.18877604259302586, 'specificity': np.float64(0.6923076923076923), 'sensitivity': np.float64(0.5517241379310345), 'TN': 9, 'FP': 4, 'FN': 26, 'TP': 32, 'score_source': 'continuous', 'auroc': 0.6492042440318302, 'ap_0': 0.34010026535612087, 'ap_1': 0.8892031283685453, 'scenario': 'mdi80', 'model': 'NC', 'outer_fold': 5, 'params': {'metric': 'euclidean', 'shrink_threshold': None}, 'inner_f1_macro': 0.4714489559669398}
2026-09-13 19:53:17,751 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:53:17,751 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:53:17,752 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:53:17,753 - opfython.core.opf — INFO — Class created.
2026-09-13 19:53:17,753 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:53:17,753 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:53:17,756 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:53:17,853 - opfython.models.supervised — DEBUG — Prototypes: [322, 61, 354, 203, 351, 417, 334, 91, 209, 101, 366, 278, 472, 505, 129, 48, 104, 374, 331, 273, 86, 152, 114, 318, 90, 215, 467, 404, 120, 305, 359, 416, 33, 232, 459, 286, 434, 45, 277, 311, 405, 298, 124, 19, 74, 402, 401, 406, 134, 499, 174, 179, 80, 391, 418, 412, 29, 512, 34, 238, 96, 437, 18, 474, 436, 89, 423, 122, 65, 41, 22, 163, 171, 234, 241, 326, 69, 192, 251, 419, 216, 388, 85, 60, 421, 2, 360, 315, 155, 302, 223, 364, 81, 53, 166, 392, 255, 468, 148, 9, 289, 288, 213, 50, 16, 335, 316, 84, 157, 486, 220, 333, 420, 244, 253, 371, 283, 167, 447, 433, 242, 257, 262, 340, 100, 445, 64, 389, 40, 282, 264, 71, 477, 307, 38, 380, 202, 243, 23, 208, 320, 66, 411, 36, 21, 44, 455, 501, 383, 78, 270, 63, 457, 8, 126, 117, 68, 12, 39, 394, 200, 290, 348, 151, 226, 509, 444, 408, 350, 225, 14, 62, 217, 263, 47, 429, 460, 190, 214, 160, 221, 112, 136, 4, 454, 54, 442, 285, 422, 272, 410, 336, 352, 462, 265, 473, 378, 17, 287, 398, 481, 399, 93, 390, 480, 344, 432, 296, 131, 230, 397, 456, 198, 201, 361, 139, 236, 219, 207, 154, 261, 185, 258, 469].
2026-09-13 19:53:18,042 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:53:18,043 - opfython.models.supervised — INFO — Training time: 0.2891428470611572 seconds.
2026-09-13 19:53:18,044 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:53:18,132 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:53:18,133 - opfython.models.supervised — INFO — Prediction time: 0.0881960391998291 seconds.
2026-09-13 19:53:18,274 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:53:18,275 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:53:18,276 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:53:18,277 - opfython.core.opf — INFO — Class created.
2026-09-13 19:53:18,278 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:53:18,278 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:53:18,280 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:53:18,377 - opfython.models.supervised — DEBUG — Prototypes: [314, 66, 348, 215, 345, 219, 210, 54, 67, 106, 417, 489, 126, 312, 107, 225, 73, 169, 504, 461, 48, 277, 322, 138, 296, 496, 462, 141, 429, 301, 17, 416, 404, 92, 24, 342, 466, 401, 400, 406, 148, 498, 414, 183, 491, 135, 38, 387, 418, 198, 95, 16, 175, 245, 113, 435, 97, 260, 231, 358, 287, 163, 236, 96, 87, 15, 55, 282, 374, 152, 311, 174, 341, 43, 71, 318, 37, 20, 80, 184, 220, 458, 241, 194, 162, 434, 247, 350, 64, 419, 421, 81, 477, 446, 3, 353, 119, 398, 365, 256, 172, 317, 166, 250, 420, 331, 264, 336, 116, 444, 261, 178, 428, 248, 377, 70, 42, 396, 346, 2, 464, 339, 99, 5, 454, 57, 273, 36, 185, 61, 382, 85, 130, 181, 327, 495, 320, 402, 478, 267, 386, 343, 176, 232, 204, 463, 187, 140, 503, 86, 100, 51, 177, 475, 375, 125, 286, 480, 35, 316, 479, 110, 63, 131, 19, 506, 46, 223, 381, 455, 509, 74, 72, 93, 272, 68, 203, 388, 459, 8, 105, 139, 129, 144, 75, 13, 41, 390, 101, 486, 288, 411, 84, 82, 83, 303, 309, 271, 253, 394, 98, 378, 94, 249, 127, 335, 371, 233, 340, 443, 408, 482, 143, 237, 393, 457, 170, 124, 206, 186, 243, 214, 354, 310, 460, 432, 171, 263, 201, 453].
2026-09-13 19:53:18,570 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:53:18,571 - opfython.models.supervised — INFO — Training time: 0.2920193672180176 seconds.
2026-09-13 19:53:18,571 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:53:18,661 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:53:18,662 - opfython.models.supervised — INFO — Prediction time: 0.09002947807312012 seconds.
2026-09-13 19:53:18,805 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:53:18,806 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:53:18,806 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:53:18,807 - opfython.core.opf — INFO — Class created.
2026-09-13 19:53:18,807 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:53:18,808 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:53:18,809 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:53:18,906 - opfython.models.supervised — DEBUG — Prototypes: [284, 280, 57, 179, 209, 393, 453, 75, 461, 153, 305, 24, 37, 127, 175, 72, 174, 8, 59, 203, 485, 346, 143, 122, 4, 397, 15, 382, 90, 84, 53, 17, 230, 239, 273, 289, 459, 35, 481, 450, 38, 479, 472, 49, 379, 20, 441, 69, 483, 351, 324, 40, 190, 78, 431, 256, 137, 417, 238, 387, 100, 81, 213, 145, 199, 297, 296, 141, 283, 99, 115, 167, 333, 368, 471, 295, 232, 249, 76, 294, 244, 266, 93, 85, 19, 56, 191, 504, 165, 420, 360, 465, 304, 408, 413, 177, 269, 427, 172, 371, 381, 442, 365, 70, 45, 473, 388, 133, 500, 303, 416, 503, 375, 44, 47, 352, 32, 130, 407, 307, 512, 23, 42, 458, 50, 286, 312, 495, 136, 229, 281, 404, 403, 454, 496, 383, 206, 332, 492, 231, 449, 234, 410, 55, 224, 103, 196, 488, 415, 248, 66, 321, 290, 457, 399, 101, 92, 124, 104, 184, 396, 113, 267, 168, 89, 345, 339, 33, 27, 432, 252, 268, 258, 257, 390, 181, 67, 315, 318, 102, 452, 185, 350, 95, 83, 319, 336, 494, 405, 264, 159, 22, 440, 285, 419, 477, 384, 235, 134, 118, 125, 354, 380, 1, 106, 128, 64, 480, 214, 426, 376, 166, 510, 372, 478, 212, 391, 357, 205, 355, 150, 82, 219, 251, 142, 202, 10].
2026-09-13 19:53:19,094 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:53:19,095 - opfython.models.supervised — INFO — Training time: 0.28649258613586426 seconds.
2026-09-13 19:53:19,095 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:53:19,190 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:53:19,190 - opfython.models.supervised — INFO — Prediction time: 0.09449911117553711 seconds.
2026-09-13 19:53:19,333 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:53:19,333 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:53:19,334 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:53:19,335 - opfython.core.opf — INFO — Class created.
2026-09-13 19:53:19,335 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:53:19,336 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:53:19,338 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:53:19,440 - opfython.models.supervised — DEBUG — Prototypes: [218, 354, 333, 74, 56, 67, 103, 490, 367, 289, 471, 136, 330, 461, 156, 504, 232, 71, 323, 0, 124, 319, 443, 131, 40, 435, 135, 50, 312, 329, 452, 133, 305, 309, 21, 359, 420, 409, 129, 34, 351, 248, 418, 175, 272, 393, 264, 421, 415, 196, 29, 512, 252, 440, 168, 90, 20, 473, 299, 9, 298, 228, 378, 95, 60, 394, 364, 159, 94, 84, 188, 89, 57, 258, 267, 147, 317, 167, 372, 294, 115, 405, 93, 45, 16, 187, 155, 439, 357, 134, 422, 233, 389, 101, 64, 451, 2, 360, 316, 205, 181, 165, 271, 344, 112, 291, 304, 384, 259, 80, 43, 166, 292, 277, 400, 15, 315, 261, 257, 217, 343, 91, 282, 387, 68, 395, 59, 486, 345, 126, 8, 24, 321, 23, 145, 499, 230, 386, 457, 509, 70, 170, 138, 98, 300, 414, 449, 412, 483, 122, 144, 286, 177, 82, 496, 424, 308, 447, 295, 407, 334, 391, 279, 352, 241, 17, 66, 234, 179, 276, 53, 83, 171, 404, 229, 238, 355, 383, 1, 503, 402, 481, 37, 479, 106, 169, 63, 127, 480, 342, 48, 44, 397, 379, 242, 399, 208, 250, 216, 434, 203, 198, 438, 478, 374, 214, 164, 514, 508, 200].
2026-09-13 19:53:19,653 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:53:19,653 - opfython.models.supervised — INFO — Training time: 0.3168613910675049 seconds.
2026-09-13 19:53:19,654 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:53:19,739 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:53:19,740 - opfython.models.supervised — INFO — Prediction time: 0.08558845520019531 seconds.
2026-09-13 19:53:19,901 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:53:19,902 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:53:19,902 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:53:19,903 - opfython.core.opf — INFO — Class created.
2026-09-13 19:53:19,903 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:53:19,904 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:53:19,906 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:53:20,028 - opfython.models.supervised — DEBUG — Prototypes: [212, 4, 352, 328, 73, 219, 206, 49, 63, 366, 475, 504, 136, 374, 226, 69, 162, 100, 506, 354, 418, 442, 27, 349, 468, 326, 283, 449, 463, 37, 434, 406, 472, 409, 141, 497, 187, 416, 174, 263, 25, 513, 28, 167, 476, 257, 227, 99, 59, 199, 420, 284, 19, 77, 439, 248, 41, 22, 322, 35, 78, 203, 165, 303, 314, 146, 98, 487, 402, 92, 84, 186, 323, 222, 375, 234, 364, 93, 52, 178, 261, 394, 470, 109, 288, 379, 369, 289, 114, 90, 3, 360, 313, 433, 249, 382, 23, 335, 266, 342, 111, 447, 299, 66, 40, 391, 149, 456, 20, 70, 318, 412, 68, 88, 275, 64, 51, 460, 485, 343, 96, 294, 218, 287, 79, 81, 80, 250, 399, 94, 311, 252, 383, 55, 72, 272, 376, 237, 347, 350, 236, 176, 62, 13, 228, 267, 170, 83, 464, 428, 455, 290, 95, 346, 6, 279, 56, 387, 445, 291, 421, 411, 82, 332, 407, 126, 269, 392, 223, 131, 233, 403, 381, 16, 292, 474, 58, 127, 480, 340, 2, 396, 505, 401, 432, 298, 371, 308, 398, 458, 208, 202, 243, 164, 265, 197, 373, 138, 509, 60, 372, 179, 194, 39].
2026-09-13 19:53:20,276 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:53:20,277 - opfython.models.supervised — INFO — Training time: 0.37233924865722656 seconds.
2026-09-13 19:53:20,278 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:53:20,385 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:53:20,386 - opfython.models.supervised — INFO — Prediction time: 0.10754060745239258 seconds.
2026-09-13 19:53:20,562 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:53:20,563 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:53:20,563 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:53:20,564 - opfython.core.opf — INFO — Class created.
2026-09-13 19:53:20,566 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:53:20,567 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:53:20,572 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:53:20,702 - opfython.models.supervised — DEBUG — Prototypes: [322, 61, 354, 203, 351, 417, 334, 91, 209, 101, 366, 278, 472, 505, 129, 48, 104, 374, 331, 273, 86, 152, 114, 318, 90, 459, 128, 434, 45, 277, 449, 124, 298, 404, 120, 305, 359, 416, 33, 232, 402, 406, 499, 134, 391, 418, 179, 80, 29, 512, 34, 436, 89, 238, 437, 474, 50, 16, 213, 76, 9, 289, 288, 364, 223, 81, 166, 333, 335, 316, 84, 371, 283, 41, 65, 22, 163, 171, 234, 241, 326, 69, 192, 125, 216, 251, 60, 421, 155, 85, 302, 187, 2, 360, 315, 420, 244, 253, 100, 148, 26, 262, 340, 281, 341, 63, 52, 393, 457, 78, 270, 276, 511, 23, 320, 411, 21, 44, 142, 8, 126, 117, 290, 269, 380, 57, 243, 282, 264, 245, 70, 307, 38, 68, 12, 39, 394, 454, 54, 112, 136, 4, 442, 285, 422, 410, 350, 190, 225, 135, 390, 14, 62, 217, 263, 47, 214, 55, 313, 352, 462, 221, 480, 344, 93, 429, 398, 43, 249, 167, 447, 201, 348, 265, 310, 378, 17, 287, 64, 40, 389, 481, 399, 257, 151, 226, 444, 408, 432, 296, 139, 487, 445, 280, 397, 456, 198, 219, 207, 122, 230, 131, 361, 185, 258, 469].
2026-09-13 19:53:20,948 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:53:20,949 - opfython.models.supervised — INFO — Training time: 0.38097214698791504 seconds.
2026-09-13 19:53:20,950 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:53:21,069 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:53:21,070 - opfython.models.supervised — INFO — Prediction time: 0.11890268325805664 seconds.
2026-09-13 19:53:21,259 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:53:21,260 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:53:21,260 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:53:21,261 - opfython.core.opf — INFO — Class created.
2026-09-13 19:53:21,261 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:53:21,262 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:53:21,264 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:53:21,383 - opfython.models.supervised — DEBUG — Prototypes: [314, 66, 348, 215, 345, 219, 210, 54, 67, 106, 417, 489, 126, 312, 107, 225, 73, 169, 369, 103, 504, 404, 128, 92, 416, 301, 342, 466, 462, 285, 48, 307, 322, 138, 296, 429, 401, 406, 498, 148, 198, 95, 387, 418, 175, 16, 245, 435, 113, 30, 135, 38, 282, 256, 374, 260, 97, 231, 358, 287, 163, 236, 96, 87, 15, 55, 152, 311, 174, 279, 64, 419, 421, 20, 80, 184, 220, 458, 159, 194, 162, 434, 247, 22, 43, 318, 37, 81, 477, 299, 291, 119, 398, 365, 116, 336, 331, 3, 353, 264, 281, 333, 172, 19, 381, 72, 74, 93, 272, 68, 270, 388, 459, 203, 8, 139, 129, 288, 411, 84, 82, 83, 303, 309, 271, 253, 394, 98, 378, 60, 249, 127, 335, 75, 13, 371, 233, 41, 390, 101, 486, 386, 267, 339, 5, 99, 454, 57, 273, 185, 85, 130, 181, 327, 495, 320, 402, 478, 343, 232, 86, 100, 51, 177, 110, 176, 63, 131, 473, 346, 464, 2, 463, 503, 396, 255, 206, 284, 243, 414, 440, 491, 250, 389, 340, 214, 475, 375, 125, 286, 480, 35, 70, 42, 316, 443, 408, 482, 143, 237, 91, 261, 377, 366, 305, 444, 280, 393, 457, 170, 124, 479, 171, 513, 310, 259, 494, 201].
2026-09-13 19:53:21,604 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:53:21,605 - opfython.models.supervised — INFO — Training time: 0.3423304557800293 seconds.
2026-09-13 19:53:21,606 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:53:21,702 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:53:21,704 - opfython.models.supervised — INFO — Prediction time: 0.09718775749206543 seconds.
2026-09-13 19:53:21,853 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:53:21,854 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:53:21,855 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:53:21,855 - opfython.core.opf — INFO — Class created.
2026-09-13 19:53:21,855 - opfython.models.supervised — INFO — Class overrided.

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

Fase 2 MLP {'accuracy': 0.8028169014084507, 'precision_0': np.float64(0.4), 'precision_1': np.float64(0.8333333333333334), 'recall_0': np.float64(0.15384615384615385), 'recall_1': np.float64(0.9482758620689655), 'f1_0': np.float64(0.2222222222222222), 'f1_1': np.float64(0.8870967741935484), 'f1_macro': 0.5546594982078853, 'f1_weighted': 0.7653591801706295, 'precision_macro': 0.6166666666666667, 'recall_macro': 0.5510610079575597, 'balanced_accuracy': 0.5510610079575597, 'mcc': 0.15436473165912776, 'specificity': np.float64(0.15384615384615385), 'sensitivity': np.float64(0.9482758620689655), 'TN': 2, 'FP': 11, 'FN': 3, 'TP': 55, 'score_source': 'continuous', 'auroc': 0.5278514588859416, 'ap_0': 0.2223786578050871, 'ap_1': 0.8587919684634769, 'scenario': 'mdi80', 'model': 'MLP', 'outer_fold': 6, 'params': {'alpha': 0.0001, 'hidden_layer_sizes': (32, 16), 'max_iter': 500}, 'inner_f1_macro': 0.49743488957895377}
Fase 2 LR {'accuracy': 0.8169014084507042, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8169014084507042), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8992248062015504), 'f1_macro': 0.4496124031007752, 'f1_weighted': 0.7345780106998581, 'precision_macro': 0.4084507042253521, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 13, 'FN': 0, 'TP': 58, 'score_source': 'continuous', 'auroc': 0.5702917771883289, 'ap_0': 0.26826425829922146, 'ap_1': 0.8865555594085964, 'scenario': 'mdi80', 'model': 'LR', 'outer_fold': 6, 'params': {'C': 0.01, 'max_iter': 1000, 'solver': 'lbfgs'}, 'inner_f1_macro': 0.449488279960383}
Fase 2 XGB {'accuracy': 0.7887323943661971, 'precision_0': np.float64(0.25), 'precision_1': np.float64(0.8208955223880597), 'recall_0': np.float64(0.07692307692307693), 'recall_1': np.float64(0.9482758620689655), 'f1_0': np.float64(0.11764705882352941), 'f1_1': np.float64(0.88), 'f1_macro': 0.4988235294117647, 'f1_weighted': 0.7404142502071251, 'precision_macro': 0.5354477611940298, 'recall_macro': 0.5125994694960212, 'balanced_accuracy': 0.5125994694960212, 'mcc': 0.04226691310547407, 'specificity': np.float64(0.07692307692307693), 'sensitivity': np.float64(0.9482758620689655), 'TN': 1, 'FP': 12, 'FN': 3, 'TP': 55, 'score_source': 'continuous', 'auroc': 0.5716180371352785, 'ap_0': 0.2656674565199544, 'ap_1': 0.8421569956288208, 'scenario': 'mdi80', 'model': 'XGB', 'outer_fold': 6, 'params': {'learning_rate': 0.05, 'max_depth': 5, 'n_estimators': 200}, 'inner_f1_macro': 0.49509375649943205}
Fase 2 NB {'accuracy': 0.8028169014084507, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8142857142857143), 'recall_0': np.float64(0.0), 'recall_1': np.float64(0.9827586206896551), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.890625), 'f1_macro': 0.4453125, 'f1_weighted': 0.7275528169014085, 'precision_macro': 0.40714285714285714, 'recall_macro': 0.49137931034482757, 'balanced_accuracy': 0.49137931034482757, 'mcc': -0.056585956237831254, 'specificity': np.float64(0.0), 'sensitivity': np.float64(0.9827586206896551), 'TN': 0, 'FP': 13, 'FN': 1, 'TP': 57, 'score_source': 'continuous', 'auroc': 0.519893899204244, 'ap_0': 0.2072067885443987, 'ap_1': 0.8578059447024029, 'scenario': 'mdi80', 'model': 'NB', 'outer_fold': 6, 'params': {'var_smoothing': 1e-11}, 'inner_f1_macro': 0.4705060665871832}
Fase 2 NC {'accuracy': 0.5070422535211268, 'precision_0': np.float64(0.19444444444444445), 'precision_1': np.float64(0.8285714285714286), 'recall_0': np.float64(0.5384615384615384), 'recall_1': np.float64(0.5), 'f1_0': np.float64(0.2857142857142857), 'f1_1': np.float64(0.6236559139784946), 'f1_macro': 0.45468509984639016, 'f1_weighted': 0.5617792778174423, 'precision_macro': 0.5115079365079366, 'recall_macro': 0.5192307692307692, 'balanced_accuracy': 0.5192307692307692, 'mcc': 0.02975274584346603, 'specificity': np.float64(0.5384615384615384), 'sensitivity': np.float64(0.5), 'TN': 7, 'FP': 6, 'FN': 29, 'TP': 29, 'score_source': 'continuous', 'auroc': 0.6100795755968169, 'ap_0': 0.2500232883934934, 'ap_1': 0.9000828129933763, 'scenario': 'mdi80', 'model': 'NC', 'outer_fold': 6, 'params': {'metric': 'euclidean', 'shrink_threshold': None}, 'inner_f1_macro': 0.454606031296746}
2026-09-13 19:54:40,561 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:54:40,561 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:54:40,562 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:54:40,562 - opfython.core.opf — INFO — Class created.
2026-09-13 19:54:40,563 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:54:40,563 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:54:40,564 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:54:40,688 - opfython.models.supervised — DEBUG — Prototypes: [284, 0, 419, 235, 212, 95, 410, 440, 181, 456, 147, 217, 211, 119, 316, 94, 109, 44, 39, 365, 23, 287, 457, 43, 279, 46, 448, 127, 298, 255, 35, 236, 501, 136, 159, 469, 342, 337, 511, 29, 241, 102, 390, 254, 165, 262, 248, 437, 425, 274, 76, 334, 497, 258, 318, 402, 412, 478, 453, 285, 289, 308, 247, 160, 346, 445, 240, 169, 62, 250, 477, 188, 214, 312, 115, 341, 7, 409, 364, 479, 51, 97, 349, 100, 398, 396, 128, 378, 81, 75, 49, 77, 16, 74, 223, 480, 450, 67, 460, 276, 272, 54, 194, 454, 66, 382, 164, 118, 24, 143, 215, 303, 354, 510, 411, 138, 10, 268, 189, 485, 343, 132, 41, 394, 371, 230, 296, 267, 63, 186, 447, 155, 123, 221, 209, 376, 20, 226, 359, 84, 3, 391, 260, 467, 149, 361, 228, 370, 52, 19, 362, 130, 314, 92, 129, 153, 282, 291, 178, 439, 238, 61, 424, 406, 302, 157, 124, 483, 446, 358, 106, 253, 340, 42, 474, 64, 387, 2, 167, 416, 263, 434, 246, 367, 420, 377, 154, 45, 344, 197, 203, 468, 131, 473, 489, 366, 187, 11].
2026-09-13 19:54:40,930 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:54:40,932 - opfython.models.supervised — INFO — Training time: 0.3690462112426758 seconds.
2026-09-13 19:54:40,933 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:54:41,030 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:54:41,031 - opfython.models.supervised — INFO — Prediction time: 0.09727883338928223 seconds.
2026-09-13 19:54:41,206 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:54:41,207 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:54:41,208 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:54:41,208 - opfython.core.opf — INFO — Class created.
2026-09-13 19:54:41,209 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:54:41,210 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:54:41,212 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:54:41,332 - opfython.models.supervised — DEBUG — Prototypes: [314, 66, 216, 340, 322, 78, 222, 212, 145, 364, 172, 504, 404, 31, 301, 347, 418, 465, 243, 459, 285, 448, 279, 141, 296, 497, 482, 401, 399, 407, 149, 499, 416, 188, 265, 387, 419, 289, 350, 22, 138, 40, 185, 247, 438, 117, 352, 332, 298, 475, 369, 178, 471, 291, 19, 413, 198, 435, 68, 122, 100, 398, 358, 286, 9, 235, 365, 54, 317, 91, 101, 158, 233, 242, 177, 310, 487, 396, 153, 423, 422, 345, 260, 226, 46, 23, 316, 39, 195, 80, 21, 370, 458, 166, 437, 252, 64, 420, 85, 426, 313, 206, 3, 349, 175, 109, 170, 254, 120, 119, 425, 264, 182, 431, 375, 71, 267, 45, 69, 388, 97, 273, 156, 151, 49, 455, 348, 378, 409, 72, 75, 485, 334, 287, 84, 393, 102, 88, 87, 230, 376, 444, 61, 98, 215, 217, 77, 272, 44, 389, 366, 237, 371, 446, 410, 294, 70, 338, 89, 238, 186, 325, 496, 276, 106, 189, 62, 379, 131, 103, 6, 341, 116, 2, 454, 58, 402, 269, 385, 15, 67, 227, 191, 53, 90, 339, 236, 460, 28, 181, 503, 395, 397, 372, 18, 224, 231, 473, 162, 63, 479, 331, 8, 406, 356, 200, 113, 179, 392, 457, 299, 209, 190, 173, 266, 94, 241, 508, 65, 201, 43].
2026-09-13 19:54:41,599 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:54:41,600 - opfython.models.supervised — INFO — Training time: 0.3893249034881592 seconds.
2026-09-13 19:54:41,600 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:54:41,733 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:54:41,734 - opfython.models.supervised — INFO — Prediction time: 0.13277053833007812 seconds.
2026-09-13 19:54:41,918 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:54:41,919 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:54:41,920 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:54:41,921 - opfython.core.opf — INFO — Class created.
2026-09-13 19:54:41,922 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:54:41,923 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:54:41,925 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:54:42,040 - opfython.models.supervised — DEBUG — Prototypes: [95, 281, 283, 127, 3, 5, 77, 459, 13, 71, 390, 58, 75, 24, 154, 305, 342, 484, 208, 277, 387, 257, 10, 396, 17, 379, 62, 19, 232, 84, 172, 242, 276, 46, 86, 308, 176, 457, 30, 480, 449, 40, 371, 247, 472, 503, 243, 230, 16, 347, 376, 126, 169, 135, 205, 299, 445, 168, 125, 300, 236, 270, 245, 362, 294, 78, 56, 22, 88, 100, 196, 364, 143, 142, 173, 167, 289, 504, 315, 354, 400, 131, 323, 42, 195, 159, 83, 475, 91, 202, 15, 296, 66, 212, 420, 304, 258, 409, 171, 415, 183, 430, 259, 367, 116, 263, 444, 361, 374, 473, 340, 47, 395, 322, 303, 136, 470, 418, 63, 346, 102, 450, 190, 421, 50, 87, 332, 383, 405, 413, 311, 295, 351, 377, 1, 260, 174, 261, 85, 237, 178, 123, 314, 65, 170, 479, 434, 301, 7, 411, 365, 271, 291, 49, 68, 319, 156, 417, 251, 328, 216, 233, 447, 239, 74, 455, 160, 235, 129, 317, 108, 99, 407, 34, 33, 252, 307, 306, 23, 146, 28, 43, 61, 141, 454, 312, 52, 446, 138, 483, 404, 402, 147, 497, 27, 511, 279, 35, 341, 336, 256, 113, 435, 486, 505, 217, 39, 150, 223, 368, 358, 465, 443, 491, 144, 253, 92, 352, 67, 241, 206, 12, 489, 157].
2026-09-13 19:54:42,279 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:54:42,280 - opfython.models.supervised — INFO — Training time: 0.35666680335998535 seconds.
2026-09-13 19:54:42,281 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:54:42,391 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:54:42,392 - opfython.models.supervised — INFO — Prediction time: 0.11009907722473145 seconds.
2026-09-13 19:54:42,552 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:54:42,553 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:54:42,553 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:54:42,554 - opfython.core.opf — INFO — Class created.
2026-09-13 19:54:42,554 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:54:42,555 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:54:42,557 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:54:42,665 - opfython.models.supervised — DEBUG — Prototypes: [321, 66, 220, 3, 350, 329, 77, 227, 213, 361, 472, 138, 371, 167, 504, 20, 74, 234, 443, 128, 24, 409, 130, 310, 421, 34, 52, 290, 452, 134, 304, 497, 406, 405, 199, 98, 301, 357, 131, 42, 446, 391, 423, 458, 35, 29, 511, 256, 114, 442, 23, 171, 474, 440, 67, 270, 498, 235, 388, 106, 424, 64, 426, 47, 71, 192, 79, 441, 260, 85, 432, 274, 100, 231, 230, 372, 244, 298, 11, 58, 21, 89, 99, 194, 293, 315, 263, 271, 150, 316, 105, 269, 120, 97, 403, 365, 307, 335, 279, 341, 117, 451, 70, 389, 174, 2, 297, 255, 382, 61, 262, 364, 265, 477, 87, 45, 25, 319, 72, 179, 94, 285, 68, 208, 393, 10, 135, 141, 103, 485, 299, 83, 340, 450, 414, 348, 245, 183, 57, 460, 32, 19, 136, 55, 88, 345, 146, 5, 288, 40, 181, 385, 239, 427, 415, 407, 351, 379, 112, 1, 503, 400, 282, 480, 39, 157, 63, 119, 110, 172, 7, 8, 363, 201, 396, 46, 373, 246, 378, 168, 124, 399, 216, 211, 295, 431, 200, 356, 346, 217, 224, 92, 196, 205, 507, 479, 491, 242, 202].
2026-09-13 19:54:42,877 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:54:42,878 - opfython.models.supervised — INFO — Training time: 0.3225388526916504 seconds.
2026-09-13 19:54:42,879 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:54:42,965 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:54:42,966 - opfython.models.supervised — INFO — Prediction time: 0.08624911308288574 seconds.
2026-09-13 19:54:43,114 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:54:43,115 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:54:43,115 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:54:43,116 - opfython.core.opf — INFO — Class created.
2026-09-13 19:54:43,116 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:54:43,117 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:54:43,118 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:54:43,220 - opfython.models.supervised — DEBUG — Prototypes: [289, 0, 326, 108, 220, 207, 223, 412, 442, 194, 71, 228, 128, 19, 107, 222, 459, 401, 419, 153, 20, 142, 39, 137, 291, 375, 56, 458, 309, 44, 47, 408, 132, 305, 304, 467, 242, 407, 405, 143, 499, 365, 214, 254, 62, 25, 512, 274, 30, 338, 332, 118, 265, 266, 438, 346, 144, 445, 364, 182, 51, 63, 256, 82, 454, 185, 343, 100, 84, 495, 424, 158, 383, 225, 55, 508, 60, 479, 299, 439, 109, 93, 276, 278, 126, 5, 74, 464, 65, 393, 180, 282, 140, 21, 151, 509, 69, 174, 339, 9, 273, 139, 42, 396, 203, 272, 390, 83, 49, 85, 234, 172, 399, 13, 461, 32, 480, 451, 35, 475, 344, 213, 359, 237, 98, 4, 224, 239, 10, 370, 293, 243, 86, 322, 97, 191, 104, 312, 169, 120, 281, 352, 362, 504, 506, 426, 468, 197, 295, 321, 37, 189, 77, 157, 244, 252, 440, 80, 81, 430, 141, 89, 320, 167, 105, 410, 294, 357, 436, 253, 3, 178, 417, 267, 398, 448, 358, 380, 302, 67, 269, 389, 43, 336, 208, 377, 17, 447, 453, 66, 298, 271, 165, 510, 391, 355, 175, 333, 166, 134, 367, 356, 348, 148, 230, 138, 90, 427, 245, 61, 478, 217, 489, 366].
2026-09-13 19:54:43,420 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:54:43,421 - opfython.models.supervised — INFO — Training time: 0.3038949966430664 seconds.
2026-09-13 19:54:43,421 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:54:43,515 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:54:43,516 - opfython.models.supervised — INFO — Prediction time: 0.09449887275695801 seconds.
2026-09-13 19:54:43,671 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:54:43,672 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:54:43,673 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:54:43,673 - opfython.core.opf — INFO — Class created.
2026-09-13 19:54:43,674 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:54:43,675 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:54:43,676 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:54:43,781 - opfython.models.supervised — DEBUG — Prototypes: [284, 0, 419, 235, 212, 95, 410, 440, 181, 456, 147, 217, 211, 119, 316, 94, 464, 35, 236, 23, 135, 30, 38, 375, 58, 287, 455, 279, 43, 46, 448, 127, 298, 60, 501, 136, 29, 511, 241, 109, 44, 102, 39, 365, 425, 274, 76, 334, 497, 258, 318, 402, 412, 478, 453, 182, 289, 308, 247, 389, 346, 445, 240, 169, 51, 62, 250, 477, 188, 214, 312, 341, 115, 7, 409, 364, 97, 479, 349, 198, 100, 390, 398, 408, 143, 215, 354, 510, 303, 138, 133, 24, 66, 164, 276, 54, 67, 460, 10, 56, 189, 485, 343, 132, 378, 206, 396, 85, 75, 49, 77, 16, 158, 223, 371, 230, 480, 450, 41, 394, 439, 238, 61, 424, 157, 93, 406, 302, 314, 15, 92, 111, 275, 331, 362, 130, 153, 282, 52, 19, 228, 370, 84, 104, 3, 391, 260, 467, 359, 226, 291, 178, 106, 253, 340, 42, 474, 64, 466, 167, 2, 416, 263, 63, 296, 165, 197, 209, 221, 434, 246, 367, 124, 483, 420, 387, 186, 447, 452, 437, 262, 248, 155, 123, 376, 20, 154, 45, 377, 344, 203, 350, 244, 468, 256, 131, 234, 489, 225, 187, 11, 335, 337].
2026-09-13 19:54:43,991 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:54:43,993 - opfython.models.supervised — INFO — Training time: 0.31746435165405273 seconds.
2026-09-13 19:54:43,993 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:54:44,081 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:54:44,082 - opfython.models.supervised — INFO — Prediction time: 0.08767294883728027 seconds.
2026-09-13 19:54:44,235 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:54:44,236 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:54:44,236 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:54:44,237 - opfython.core.opf — INFO — Class created.
2026-09-13 19:54:44,237 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:54:44,238 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:54:44,240 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:54:44,344 - opfython.models.supervised — DEBUG — Prototypes: [314, 66, 216, 340, 322, 78, 222, 212, 145, 364, 172, 504, 404, 135, 301, 347, 418, 465, 243, 459, 26, 448, 306, 141, 296, 401, 96, 407, 149, 499, 289, 350, 22, 178, 291, 19, 247, 438, 117, 332, 298, 475, 387, 419, 369, 138, 40, 260, 226, 46, 23, 316, 39, 21, 370, 458, 80, 195, 166, 437, 252, 313, 64, 420, 85, 426, 175, 109, 286, 281, 9, 235, 365, 17, 91, 54, 101, 158, 233, 242, 153, 310, 177, 423, 157, 122, 398, 100, 358, 120, 119, 425, 422, 3, 349, 345, 416, 188, 265, 156, 49, 72, 75, 97, 273, 69, 388, 56, 287, 84, 485, 334, 88, 87, 393, 152, 14, 102, 501, 81, 230, 376, 98, 253, 446, 410, 89, 165, 186, 325, 496, 319, 276, 189, 62, 379, 131, 103, 6, 341, 116, 2, 454, 307, 58, 269, 385, 402, 339, 179, 236, 28, 150, 15, 67, 227, 191, 53, 90, 181, 460, 224, 309, 397, 473, 162, 479, 331, 113, 231, 503, 395, 8, 406, 356, 200, 372, 18, 389, 366, 237, 44, 294, 70, 185, 209, 284, 338, 71, 45, 105, 435, 68, 198, 377, 254, 264, 361, 304, 392, 457, 431, 182, 375, 508, 494, 246, 250, 94, 429, 478, 134, 65, 362, 201, 333].
2026-09-13 19:54:44,549 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:54:44,551 - opfython.models.supervised — INFO — Training time: 0.3121626377105713 seconds.
2026-09-13 19:54:44,551 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:54:44,639 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:54:44,640 - opfython.models.supervised — INFO — Prediction time: 0.08885574340820312 seconds.
2026-09-13 19:54:44,792 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:54:44,793 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:54:44,793 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:54:44,794 - opfython.core.opf — INFO — Class created.
2026-09-13 19:54:44,794 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:54:44,795 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:54:44,797 - opfython.models.supervised — DEBUG — Finding prototypes ...

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

Fase 2 MLP {'accuracy': 0.7887323943661971, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8115942028985508), 'recall_0': np.float64(0.0), 'recall_1': np.float64(0.9655172413793104), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8818897637795275), 'f1_macro': 0.4409448818897638, 'f1_weighted': 0.7204169901297549, 'precision_macro': 0.4057971014492754, 'recall_macro': 0.4827586206896552, 'balanced_accuracy': 0.4827586206896552, 'mcc': -0.08060242939383346, 'specificity': np.float64(0.0), 'sensitivity': np.float64(0.9655172413793104), 'TN': 0, 'FP': 13, 'FN': 2, 'TP': 56, 'score_source': 'continuous', 'auroc': 0.4787798408488064, 'ap_0': 0.18040369861723254, 'ap_1': 0.8297049443760954, 'scenario': 'mdi80', 'model': 'MLP', 'outer_fold': 7, 'params': {'alpha': 0.0001, 'hidden_layer_sizes': (32, 16), 'max_iter': 500}, 'inner_f1_macro': 0.4785495273057513}
Fase 2 LR {'accuracy': 0.8169014084507042, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8169014084507042), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8992248062015504), 'f1_macro': 0.4496124031007752, 'f1_weighted': 0.7345780106998581, 'precision_macro': 0.4084507042253521, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 13, 'FN': 0, 'TP': 58, 'score_source': 'continuous', 'auroc': 0.5636604774535809, 'ap_0': 0.23849424501175132, 'ap_1': 0.8541109081907714, 'scenario': 'mdi80', 'model': 'LR', 'outer_fold': 7, 'params': {'C': 0.01, 'max_iter': 1000, 'solver': 'lbfgs'}, 'inner_f1_macro': 0.449488279960383}
Fase 2 XGB {'accuracy': 0.8169014084507042, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8169014084507042), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8992248062015504), 'f1_macro': 0.4496124031007752, 'f1_weighted': 0.7345780106998581, 'precision_macro': 0.4084507042253521, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 13, 'FN': 0, 'TP': 58, 'score_source': 'continuous', 'auroc': 0.49204244031830235, 'ap_0': 0.22480970264116373, 'ap_1': 0.8170615332544283, 'scenario': 'mdi80', 'model': 'XGB', 'outer_fold': 7, 'params': {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 100}, 'inner_f1_macro': 0.4953212415562752}
Fase 2 NB {'accuracy': 0.8169014084507042, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8169014084507042), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8992248062015504), 'f1_macro': 0.4496124031007752, 'f1_weighted': 0.7345780106998581, 'precision_macro': 0.4084507042253521, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 13, 'FN': 0, 'TP': 58, 'score_source': 'continuous', 'auroc': 0.5305039787798409, 'ap_0': 0.21895190809097015, 'ap_1': 0.8463331314186623, 'scenario': 'mdi80', 'model': 'NB', 'outer_fold': 7, 'params': {'var_smoothing': 1e-11}, 'inner_f1_macro': 0.4652581657831574}
Fase 2 NC {'accuracy': 0.5070422535211268, 'precision_0': np.float64(0.19444444444444445), 'precision_1': np.float64(0.8285714285714286), 'recall_0': np.float64(0.5384615384615384), 'recall_1': np.float64(0.5), 'f1_0': np.float64(0.2857142857142857), 'f1_1': np.float64(0.6236559139784946), 'f1_macro': 0.45468509984639016, 'f1_weighted': 0.5617792778174423, 'precision_macro': 0.5115079365079366, 'recall_macro': 0.5192307692307692, 'balanced_accuracy': 0.5192307692307692, 'mcc': 0.02975274584346603, 'specificity': np.float64(0.5384615384615384), 'sensitivity': np.float64(0.5), 'TN': 7, 'FP': 6, 'FN': 29, 'TP': 29, 'score_source': 'unavailable', 'auroc': nan, 'ap_0': nan, 'ap_1': nan, 'scenario': 'mdi80', 'model': 'NC', 'outer_fold': 7, 'params': {'metric': 'manhattan', 'shrink_threshold': 0.1}, 'inner_f1_macro': 0.47699390169450506}
2026-09-13 19:56:06,142 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:56:06,143 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:56:06,143 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:56:06,144 - opfython.core.opf — INFO — Class created.
2026-09-13 19:56:06,144 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:56:06,144 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:56:06,147 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:56:06,244 - opfython.models.supervised — DEBUG — Prototypes: [344, 83, 451, 171, 21, 286, 46, 86, 175, 277, 380, 501, 337, 75, 496, 261, 322, 401, 409, 474, 381, 420, 311, 292, 315, 92, 167, 52, 250, 364, 190, 252, 73, 216, 314, 115, 478, 199, 508, 97, 161, 4, 406, 363, 431, 372, 307, 513, 35, 36, 346, 43, 19, 280, 312, 302, 126, 22, 137, 30, 287, 38, 59, 129, 276, 500, 138, 170, 34, 145, 212, 107, 219, 334, 455, 91, 214, 325, 482, 389, 256, 158, 79, 29, 392, 511, 102, 244, 365, 503, 39, 109, 435, 183, 339, 283, 204, 82, 56, 215, 229, 291, 104, 238, 7, 289, 231, 371, 53, 16, 361, 130, 317, 352, 460, 127, 416, 220, 386, 90, 433, 499, 71, 176, 239, 436, 248, 328, 186, 295, 293, 62, 419, 305, 403, 434, 432, 249, 366, 65, 471, 387, 342, 42, 106, 254, 395, 327, 377, 443, 268, 1, 318, 413, 265, 415, 304, 124, 504, 262, 367, 475, 388, 271, 483, 191, 93, 6, 68, 459, 63, 274, 391, 454, 55, 140, 143, 217, 306, 510, 405, 159, 23, 120, 133, 476, 378, 232, 347, 172, 396, 12, 14, 156, 74, 49, 226, 160, 479, 449, 345, 442, 64, 299, 153, 233, 155, 123, 450, 197, 241, 207, 223, 393, 141, 466, 349, 132, 470, 221, 37, 487, 495, 84, 189, 8].
2026-09-13 19:56:06,430 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:56:06,431 - opfython.models.supervised — INFO — Training time: 0.2860879898071289 seconds.
2026-09-13 19:56:06,431 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:56:06,515 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:56:06,516 - opfython.models.supervised — INFO — Prediction time: 0.08393549919128418 seconds.
2026-09-13 19:56:06,651 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:56:06,652 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:56:06,652 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:56:06,652 - opfython.core.opf — INFO — Class created.
2026-09-13 19:56:06,653 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:56:06,654 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:56:06,655 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:56:06,750 - opfython.models.supervised — DEBUG — Prototypes: [340, 0, 116, 503, 394, 373, 337, 154, 3, 452, 61, 88, 134, 130, 185, 328, 495, 400, 241, 475, 276, 420, 408, 440, 397, 459, 27, 188, 144, 14, 230, 53, 89, 180, 396, 372, 16, 286, 113, 178, 65, 135, 478, 333, 488, 4, 402, 357, 202, 309, 259, 392, 12, 375, 63, 255, 283, 85, 87, 86, 257, 69, 273, 456, 58, 19, 155, 49, 348, 378, 227, 405, 73, 75, 483, 334, 77, 11, 44, 389, 371, 48, 365, 240, 297, 70, 56, 274, 81, 99, 90, 7, 225, 289, 287, 100, 59, 161, 265, 466, 169, 244, 236, 106, 312, 177, 485, 233, 347, 388, 421, 418, 142, 107, 383, 416, 497, 194, 79, 433, 254, 345, 319, 39, 66, 419, 444, 1, 349, 311, 359, 284, 122, 97, 190, 22, 120, 442, 271, 71, 384, 45, 214, 301, 401, 136, 303, 31, 245, 458, 145, 428, 322, 17, 298, 141, 496, 480, 275, 325, 78, 55, 68, 110, 487, 219, 339, 414, 354, 472, 342, 317, 131, 18, 111, 482, 229, 502, 292, 20, 199, 98, 399, 403, 499, 152, 454, 386, 415, 184, 33, 117, 250, 486, 294, 391, 369, 299, 335, 213, 281, 332, 147, 243, 209, 247, 215, 221, 217, 412, 267, 205, 174, 270, 92, 457, 477, 508].
2026-09-13 19:56:06,943 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:56:06,944 - opfython.models.supervised — INFO — Training time: 0.28980088233947754 seconds.
2026-09-13 19:56:06,944 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:56:07,030 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:56:07,031 - opfython.models.supervised — INFO — Prediction time: 0.0859375 seconds.
2026-09-13 19:56:07,170 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:56:07,171 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:56:07,171 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:56:07,172 - opfython.core.opf — INFO — Class created.
2026-09-13 19:56:07,172 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:56:07,173 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:56:07,174 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:56:07,270 - opfython.models.supervised — DEBUG — Prototypes: [6, 140, 130, 343, 484, 23, 151, 51, 358, 382, 497, 508, 407, 75, 25, 410, 73, 77, 13, 46, 394, 375, 50, 261, 54, 64, 379, 316, 265, 291, 281, 84, 83, 263, 245, 296, 170, 347, 372, 440, 70, 480, 302, 205, 420, 186, 57, 456, 30, 16, 280, 176, 85, 239, 246, 346, 150, 1, 450, 62, 403, 131, 417, 286, 409, 438, 400, 334, 282, 387, 351, 458, 398, 376, 20, 478, 39, 132, 67, 477, 340, 3, 4, 396, 397, 503, 475, 404, 34, 462, 348, 252, 309, 357, 455, 142, 427, 328, 288, 138, 305, 495, 147, 481, 380, 241, 74, 332, 502, 78, 216, 109, 110, 197, 491, 408, 117, 235, 229, 350, 56, 69, 107, 486, 454, 105, 127, 320, 108, 299, 361, 136, 42, 496, 324, 406, 402, 198, 412, 436, 389, 180, 414, 35, 27, 511, 256, 435, 341, 306, 470, 344, 21, 173, 366, 399, 248, 7, 371, 58, 19, 86, 97, 331, 318, 172, 416, 47, 15, 326, 41, 24, 162, 82, 374, 183, 451, 79, 289, 323, 139, 242, 385, 189, 442, 26, 116, 163, 441, 279, 71, 386, 426, 260, 378, 217, 224, 227, 144, 469, 169, 278, 272, 232, 255, 89, 453, 487, 493, 212, 476, 233, 208, 45].
2026-09-13 19:56:07,468 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:56:07,469 - opfython.models.supervised — INFO — Training time: 0.2957003116607666 seconds.
2026-09-13 19:56:07,469 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:56:07,558 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:56:07,559 - opfython.models.supervised — INFO — Prediction time: 0.08890628814697266 seconds.
2026-09-13 19:56:07,697 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:56:07,698 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:56:07,699 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:56:07,699 - opfython.core.opf — INFO — Class created.
2026-09-13 19:56:07,699 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:56:07,700 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:56:07,705 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:56:07,816 - opfython.models.supervised — DEBUG — Prototypes: [349, 0, 112, 445, 182, 85, 335, 460, 32, 16, 239, 86, 55, 174, 402, 380, 124, 297, 234, 244, 283, 390, 503, 400, 478, 39, 65, 129, 119, 4, 5, 363, 201, 110, 172, 264, 63, 398, 187, 14, 98, 286, 315, 293, 282, 266, 83, 84, 204, 342, 69, 393, 183, 155, 51, 235, 355, 499, 508, 143, 24, 322, 71, 9, 6, 136, 128, 343, 483, 142, 299, 81, 455, 453, 169, 447, 410, 480, 305, 396, 13, 46, 379, 50, 373, 248, 433, 306, 200, 426, 135, 497, 237, 420, 103, 23, 457, 191, 161, 438, 48, 26, 327, 41, 450, 66, 423, 1, 356, 318, 87, 193, 96, 19, 60, 7, 298, 232, 372, 115, 97, 157, 276, 184, 392, 466, 251, 246, 319, 485, 317, 422, 156, 365, 294, 120, 94, 434, 263, 117, 382, 218, 308, 448, 290, 324, 351, 411, 223, 332, 76, 108, 109, 194, 359, 210, 494, 215, 229, 58, 68, 107, 487, 360, 469, 459, 104, 126, 22, 301, 25, 357, 131, 42, 406, 140, 347, 35, 252, 354, 134, 289, 144, 481, 416, 443, 279, 405, 147, 408, 195, 199, 95, 258, 114, 29, 511, 36, 303, 171, 20, 471, 377, 341, 344, 397, 456, 141, 250, 211, 255, 346, 220, 227, 205, 458, 436, 449, 90, 477, 291, 475, 368, 168, 514, 446, 507, 489, 245, 203].
2026-09-13 19:56:08,032 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:56:08,033 - opfython.models.supervised — INFO — Training time: 0.3314495086669922 seconds.
2026-09-13 19:56:08,034 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:56:08,127 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:56:08,127 - opfython.models.supervised — INFO — Prediction time: 0.09307408332824707 seconds.
2026-09-13 19:56:08,277 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:56:08,278 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:56:08,278 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:56:08,279 - opfython.core.opf — INFO — Class created.
2026-09-13 19:56:08,279 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:56:08,280 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:56:08,284 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:56:08,393 - opfython.models.supervised — DEBUG — Prototypes: [347, 0, 112, 378, 343, 97, 452, 184, 444, 290, 18, 187, 419, 83, 265, 320, 406, 411, 384, 180, 52, 149, 201, 228, 135, 312, 129, 131, 61, 166, 477, 207, 109, 169, 431, 301, 267, 118, 46, 40, 416, 346, 328, 108, 222, 447, 226, 51, 64, 106, 195, 486, 327, 230, 458, 160, 225, 126, 107, 17, 287, 350, 335, 407, 132, 307, 209, 29, 345, 262, 466, 19, 39, 459, 44, 284, 310, 303, 281, 405, 90, 146, 498, 182, 28, 392, 261, 174, 168, 31, 26, 512, 271, 213, 65, 59, 394, 456, 178, 279, 74, 463, 154, 229, 20, 141, 130, 69, 173, 7, 105, 276, 390, 140, 398, 96, 381, 58, 288, 275, 82, 81, 48, 41, 460, 240, 205, 401, 476, 370, 241, 42, 478, 35, 505, 234, 220, 344, 445, 66, 480, 199, 446, 377, 15, 165, 510, 433, 177, 188, 76, 159, 247, 256, 438, 62, 417, 418, 196, 10, 204, 238, 306, 504, 316, 329, 102, 167, 120, 33, 362, 138, 294, 224, 239, 75, 369, 85, 14, 94, 190, 95, 161, 54, 393, 420, 395, 297, 358, 134, 481, 1, 315, 432, 257, 366, 67, 474, 338, 43, 380, 266, 367, 88, 397, 305, 214, 232, 87, 457, 150, 104, 63, 98, 414, 488, 494, 200, 471].
2026-09-13 19:56:08,611 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:56:08,612 - opfython.models.supervised — INFO — Training time: 0.33167076110839844 seconds.
2026-09-13 19:56:08,613 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:56:08,719 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:56:08,720 - opfython.models.supervised — INFO — Prediction time: 0.10679984092712402 seconds.
2026-09-13 19:56:08,877 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:56:08,878 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:56:08,878 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:56:08,879 - opfython.core.opf — INFO — Class created.
2026-09-13 19:56:08,879 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:56:08,880 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:56:08,881 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:56:08,986 - opfython.models.supervised — DEBUG — Prototypes: [344, 83, 451, 171, 75, 80, 337, 496, 261, 322, 401, 409, 474, 46, 21, 420, 381, 311, 292, 315, 92, 167, 52, 252, 73, 216, 314, 478, 199, 508, 250, 364, 115, 35, 346, 36, 307, 513, 22, 287, 456, 43, 280, 331, 126, 302, 61, 500, 138, 145, 212, 107, 219, 67, 455, 91, 214, 158, 79, 29, 511, 244, 325, 482, 102, 365, 438, 39, 109, 378, 347, 396, 12, 68, 459, 63, 274, 391, 454, 55, 6, 93, 191, 483, 166, 143, 217, 306, 510, 405, 134, 23, 120, 271, 388, 133, 14, 72, 74, 49, 226, 160, 11, 476, 53, 16, 231, 69, 371, 7, 291, 238, 82, 56, 215, 208, 361, 130, 317, 127, 416, 220, 386, 90, 62, 419, 186, 295, 293, 176, 148, 436, 248, 433, 71, 328, 305, 403, 434, 26, 395, 327, 65, 471, 342, 42, 106, 104, 254, 194, 318, 233, 1, 413, 265, 197, 241, 479, 449, 170, 34, 345, 393, 304, 387, 415, 432, 249, 366, 97, 161, 4, 406, 363, 431, 300, 64, 442, 299, 435, 183, 153, 155, 123, 262, 124, 504, 443, 282, 367, 475, 141, 389, 256, 207, 377, 349, 221, 37, 339, 283, 223, 466, 487, 495, 132, 236, 84, 189, 8, 494].
2026-09-13 19:56:09,189 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:56:09,190 - opfython.models.supervised — INFO — Training time: 0.3098440170288086 seconds.
2026-09-13 19:56:09,190 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:56:09,284 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:56:09,284 - opfython.models.supervised — INFO — Prediction time: 0.09354257583618164 seconds.
2026-09-13 19:56:09,442 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:56:09,443 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:56:09,443 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:56:09,444 - opfython.core.opf — INFO — Class created.
2026-09-13 19:56:09,444 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:56:09,445 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:56:09,446 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:56:09,552 - opfython.models.supervised — DEBUG — Prototypes: [340, 0, 116, 503, 394, 389, 365, 240, 44, 11, 77, 69, 273, 456, 58, 19, 155, 49, 378, 227, 348, 405, 73, 75, 483, 334, 283, 509, 85, 87, 86, 257, 392, 12, 309, 259, 375, 63, 255, 371, 48, 64, 337, 154, 3, 452, 61, 88, 134, 130, 185, 328, 495, 400, 241, 475, 276, 420, 408, 440, 397, 326, 459, 27, 89, 53, 230, 14, 180, 396, 113, 178, 478, 333, 488, 135, 470, 4, 5, 357, 202, 372, 16, 458, 25, 428, 322, 17, 298, 141, 496, 401, 32, 303, 464, 245, 480, 275, 110, 55, 68, 487, 78, 325, 219, 407, 339, 354, 472, 131, 18, 111, 342, 317, 399, 403, 499, 152, 454, 292, 20, 229, 30, 33, 199, 98, 117, 250, 66, 376, 419, 416, 142, 383, 107, 194, 79, 433, 254, 319, 39, 289, 279, 7, 287, 225, 99, 90, 81, 56, 119, 100, 59, 226, 236, 244, 347, 312, 177, 421, 310, 430, 122, 97, 359, 284, 301, 120, 22, 1, 349, 311, 418, 386, 415, 281, 332, 286, 190, 444, 209, 247, 221, 297, 70, 184, 71, 45, 384, 217, 486, 256, 147, 243, 93, 214, 391, 442, 280, 508, 335, 215, 267, 412, 205, 92, 457, 477].
2026-09-13 19:56:09,805 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:56:09,806 - opfython.models.supervised — INFO — Training time: 0.36121034622192383 seconds.
2026-09-13 19:56:09,807 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:56:09,899 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:56:09,900 - opfython.models.supervised — INFO — Prediction time: 0.09284853935241699 seconds.
2026-09-13 19:56:10,062 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:56:10,063 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:56:10,064 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:56:10,064 - opfython.core.opf — INFO — Class created.
2026-09-13 19:56:10,065 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:56:10,065 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:56:10,067 - opfython.models.supervised — DEBUG — Finding prototypes ...

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

Fase 2 MLP {'accuracy': 0.8309859154929577, 'precision_0': np.float64(1.0), 'precision_1': np.float64(0.8285714285714286), 'recall_0': np.float64(0.07692307692307693), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.14285714285714285), 'f1_1': np.float64(0.90625), 'f1_macro': 0.5245535714285714, 'f1_weighted': 0.7664738430583501, 'precision_macro': 0.9142857142857144, 'recall_macro': 0.5384615384615384, 'balanced_accuracy': 0.5384615384615384, 'mcc': 0.25246042013801634, 'specificity': np.float64(0.07692307692307693), 'sensitivity': np.float64(1.0), 'TN': 1, 'FP': 12, 'FN': 0, 'TP': 58, 'score_source': 'continuous', 'auroc': 0.6677718832891246, 'ap_0': 0.3411262225057754, 'ap_1': 0.9029259935920334, 'scenario': 'mdi80', 'model': 'MLP', 'outer_fold': 8, 'params': {'alpha': 0.01, 'hidden_layer_sizes': (32, 16), 'max_iter': 500}, 'inner_f1_macro': 0.47060380367188304}
Fase 2 LR {'accuracy': 0.8169014084507042, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8169014084507042), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8992248062015504), 'f1_macro': 0.4496124031007752, 'f1_weighted': 0.7345780106998581, 'precision_macro': 0.4084507042253521, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 13, 'FN': 0, 'TP': 58, 'score_source': 'continuous', 'auroc': 0.6359416445623343, 'ap_0': 0.30933726384557114, 'ap_1': 0.8779464131419972, 'scenario': 'mdi80', 'model': 'LR', 'outer_fold': 8, 'params': {'C': 0.01, 'max_iter': 1000, 'solver': 'lbfgs'}, 'inner_f1_macro': 0.449488279960383}
Fase 2 XGB {'accuracy': 0.8169014084507042, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8169014084507042), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8992248062015504), 'f1_macro': 0.4496124031007752, 'f1_weighted': 0.7345780106998581, 'precision_macro': 0.4084507042253521, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 13, 'FN': 0, 'TP': 58, 'score_source': 'continuous', 'auroc': 0.5855437665782492, 'ap_0': 0.2776432614308277, 'ap_1': 0.8488847038438105, 'scenario': 'mdi80', 'model': 'XGB', 'outer_fold': 8, 'params': {'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 100}, 'inner_f1_macro': 0.4679843820112114}
Fase 2 NB {'accuracy': 0.7887323943661971, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8115942028985508), 'recall_0': np.float64(0.0), 'recall_1': np.float64(0.9655172413793104), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8818897637795275), 'f1_macro': 0.4409448818897638, 'f1_weighted': 0.7204169901297549, 'precision_macro': 0.4057971014492754, 'recall_macro': 0.4827586206896552, 'balanced_accuracy': 0.4827586206896552, 'mcc': -0.08060242939383346, 'specificity': np.float64(0.0), 'sensitivity': np.float64(0.9655172413793104), 'TN': 0, 'FP': 13, 'FN': 2, 'TP': 56, 'score_source': 'continuous', 'auroc': 0.6120689655172413, 'ap_0': 0.24057715268614205, 'ap_1': 0.8734252455029409, 'scenario': 'mdi80', 'model': 'NB', 'outer_fold': 8, 'params': {'var_smoothing': 1e-11}, 'inner_f1_macro': 0.476342230659324}
Fase 2 NC {'accuracy': 0.49295774647887325, 'precision_0': np.float64(0.23255813953488372), 'precision_1': np.float64(0.8928571428571429), 'recall_0': np.float64(0.7692307692307693), 'recall_1': np.float64(0.43103448275862066), 'f1_0': np.float64(0.35714285714285715), 'f1_1': np.float64(0.5813953488372093), 'f1_macro': 0.4692691029900332, 'f1_weighted': 0.5403350334565533, 'precision_macro': 0.5627076411960134, 'recall_macro': 0.600132625994695, 'balanced_accuracy': 0.600132625994695, 'mcc': 0.1584813021512623, 'specificity': np.float64(0.7692307692307693), 'sensitivity': np.float64(0.43103448275862066), 'TN': 10, 'FP': 3, 'FN': 33, 'TP': 25, 'score_source': 'continuous', 'auroc': 0.6624668435013262, 'ap_0': 0.29547719107732984, 'ap_1': 0.8873263248016091, 'scenario': 'mdi80', 'model': 'NC', 'outer_fold': 8, 'params': {'metric': 'euclidean', 'shrink_threshold': None}, 'inner_f1_macro': 0.45960089968523343}
2026-09-13 19:57:27,414 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:57:27,414 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:57:27,415 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:57:27,416 - opfython.core.opf — INFO — Class created.
2026-09-13 19:57:27,417 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:57:27,418 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:57:27,420 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:57:27,525 - opfython.models.supervised — DEBUG — Prototypes: [198, 350, 416, 204, 190, 49, 93, 363, 274, 472, 506, 148, 333, 91, 507, 16, 324, 210, 466, 115, 94, 21, 434, 37, 45, 20, 273, 310, 404, 297, 304, 120, 415, 35, 347, 464, 502, 134, 390, 248, 417, 172, 30, 292, 512, 235, 100, 438, 474, 375, 344, 299, 436, 412, 219, 227, 208, 140, 221, 371, 287, 225, 285, 74, 328, 167, 138, 242, 252, 366, 280, 166, 230, 23, 70, 327, 239, 71, 187, 124, 418, 90, 151, 301, 162, 447, 339, 260, 54, 27, 256, 433, 240, 378, 80, 272, 267, 22, 44, 139, 24, 511, 321, 411, 64, 9, 263, 129, 66, 12, 504, 485, 288, 69, 314, 266, 396, 13, 379, 58, 241, 244, 73, 279, 262, 216, 116, 372, 223, 445, 409, 295, 348, 222, 159, 50, 14, 261, 212, 429, 114, 402, 118, 443, 282, 422, 268, 113, 83, 4, 270, 215, 382, 454, 55, 213, 351, 476, 98, 398, 480, 439, 479, 343, 489, 60, 29, 141, 6, 7, 397, 376, 18, 284, 192, 122, 334, 423, 226, 128, 186, 232, 357, 196, 194, 202, 214, 458, 77, 218, 432, 490, 498, 150, 444, 180].
2026-09-13 19:57:27,756 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:57:27,757 - opfython.models.supervised — INFO — Training time: 0.3389902114868164 seconds.
2026-09-13 19:57:27,758 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:57:27,856 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:57:27,857 - opfython.models.supervised — INFO — Prediction time: 0.09902167320251465 seconds.
2026-09-13 19:57:28,032 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:57:28,033 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:57:28,034 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:57:28,035 - opfython.core.opf — INFO — Class created.
2026-09-13 19:57:28,035 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:57:28,036 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:57:28,039 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:57:28,155 - opfython.models.supervised — DEBUG — Prototypes: [316, 66, 345, 210, 342, 416, 325, 274, 110, 200, 355, 494, 410, 118, 215, 53, 68, 108, 142, 119, 323, 365, 161, 427, 222, 72, 128, 19, 109, 506, 168, 467, 134, 300, 415, 465, 339, 430, 141, 322, 273, 448, 401, 406, 499, 148, 413, 178, 261, 288, 352, 22, 136, 39, 387, 177, 417, 242, 436, 114, 334, 297, 475, 370, 337, 192, 290, 489, 318, 38, 21, 458, 187, 160, 435, 245, 347, 256, 418, 223, 105, 65, 421, 83, 201, 446, 170, 285, 275, 9, 218, 366, 284, 55, 319, 86, 97, 98, 157, 104, 311, 488, 225, 153, 279, 369, 248, 257, 359, 280, 429, 246, 117, 335, 24, 376, 392, 457, 206, 298, 411, 20, 36, 48, 509, 220, 379, 455, 408, 71, 73, 93, 268, 270, 198, 8, 107, 130, 75, 13, 43, 389, 243, 372, 47, 250, 302, 42, 278, 84, 264, 309, 503, 252, 393, 185, 377, 61, 247, 444, 409, 481, 293, 69, 167, 230, 193, 423, 2, 343, 113, 374, 271, 62, 380, 95, 402, 131, 126, 58, 5, 340, 149, 28, 181, 54, 67, 461, 85, 172, 219, 227, 397, 373, 16, 283, 505, 395, 37, 473, 490, 479, 159, 64, 132, 111, 171, 7, 405, 357, 194, 362, 304, 208, 239, 152, 495, 197, 89, 233, 478, 213, 195].
2026-09-13 19:57:28,387 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:57:28,387 - opfython.models.supervised — INFO — Training time: 0.35022473335266113 seconds.
2026-09-13 19:57:28,388 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:57:28,489 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:57:28,490 - opfython.models.supervised — INFO — Prediction time: 0.10199356079101562 seconds.
2026-09-13 19:57:28,649 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:57:28,650 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:57:28,650 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:57:28,651 - opfython.core.opf — INFO — Class created.
2026-09-13 19:57:28,651 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:57:28,652 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:57:28,654 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:57:28,763 - opfython.models.supervised — DEBUG — Prototypes: [9, 105, 128, 141, 24, 321, 151, 74, 358, 383, 49, 231, 452, 509, 146, 409, 293, 79, 315, 278, 258, 396, 15, 380, 62, 257, 82, 239, 126, 442, 482, 300, 71, 222, 376, 65, 130, 27, 479, 342, 451, 60, 348, 98, 5, 405, 129, 440, 175, 419, 280, 335, 384, 352, 378, 1, 17, 69, 235, 176, 272, 458, 30, 167, 83, 230, 169, 240, 505, 398, 40, 480, 377, 21, 291, 477, 110, 166, 96, 266, 229, 241, 245, 228, 371, 243, 55, 20, 84, 95, 186, 165, 318, 486, 238, 149, 288, 317, 256, 263, 260, 133, 325, 41, 184, 77, 23, 174, 375, 226, 455, 157, 432, 255, 355, 284, 261, 233, 322, 66, 416, 418, 80, 206, 444, 200, 179, 164, 103, 115, 436, 344, 338, 59, 268, 18, 168, 428, 379, 381, 306, 35, 414, 34, 350, 462, 51, 311, 329, 446, 404, 408, 498, 138, 118, 330, 281, 53, 364, 471, 70, 54, 106, 488, 225, 209, 333, 108, 109, 204, 493, 411, 2, 217, 104, 160, 506, 354, 415, 295, 25, 361, 134, 42, 192, 251, 112, 433, 343, 302, 346, 473, 374, 28, 259, 297, 487, 412, 413, 173, 269, 395, 454, 205, 249, 360, 369, 310, 212, 214, 198, 88, 456, 370, 478, 286, 162, 513, 465, 368, 489, 367, 195, 45].
2026-09-13 19:57:28,979 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:57:28,980 - opfython.models.supervised — INFO — Training time: 0.3269195556640625 seconds.
2026-09-13 19:57:28,980 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:57:29,081 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:57:29,082 - opfython.models.supervised — INFO — Prediction time: 0.10057806968688965 seconds.
2026-09-13 19:57:29,235 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:57:29,236 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:57:29,237 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:57:29,238 - opfython.core.opf — INFO — Class created.
2026-09-13 19:57:29,238 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:57:29,238 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:57:29,240 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:57:29,347 - opfython.models.supervised — DEBUG — Prototypes: [289, 0, 324, 66, 333, 106, 219, 115, 204, 454, 222, 442, 212, 55, 186, 490, 123, 23, 105, 332, 227, 264, 151, 349, 245, 35, 51, 311, 406, 405, 143, 43, 366, 176, 398, 391, 263, 170, 30, 512, 278, 343, 338, 270, 256, 489, 257, 258, 372, 84, 193, 475, 174, 67, 255, 166, 314, 56, 103, 350, 144, 447, 507, 365, 156, 24, 448, 424, 347, 97, 457, 184, 407, 414, 310, 297, 352, 380, 109, 1, 125, 118, 224, 63, 164, 6, 413, 364, 107, 340, 287, 207, 296, 221, 238, 373, 57, 19, 95, 10, 2, 268, 60, 467, 392, 443, 360, 211, 316, 362, 504, 135, 318, 195, 100, 165, 281, 286, 161, 228, 131, 421, 101, 64, 326, 40, 440, 77, 436, 82, 198, 150, 300, 403, 128, 484, 114, 261, 399, 298, 9, 104, 194, 486, 90, 279, 121, 3, 4, 282, 59, 139, 25, 149, 225, 308, 356, 458, 509, 145, 412, 70, 138, 75, 14, 45, 396, 478, 288, 275, 17, 83, 85, 382, 239, 91, 210, 213, 462, 32, 167, 374, 240, 402, 232, 216, 473, 480, 39, 8, 446, 417, 271, 429, 68, 450, 482, 302, 190, 451, 276, 435, 375, 21, 307, 369, 477, 201, 248, 306, 208, 196, 353, 205, 137, 163, 514, 492, 497, 192, 11].
2026-09-13 19:57:29,561 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:57:29,561 - opfython.models.supervised — INFO — Training time: 0.32257533073425293 seconds.
2026-09-13 19:57:29,562 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:57:29,665 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:57:29,665 - opfython.models.supervised — INFO — Prediction time: 0.10290217399597168 seconds.
2026-09-13 19:57:29,835 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:57:29,836 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:57:29,837 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:57:29,837 - opfython.core.opf — INFO — Class created.
2026-09-13 19:57:29,838 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:57:29,839 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:57:29,840 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:57:29,943 - opfython.models.supervised — DEBUG — Prototypes: [321, 62, 351, 417, 349, 329, 362, 363, 3, 136, 64, 116, 370, 154, 430, 220, 69, 101, 462, 124, 317, 294, 358, 22, 278, 47, 326, 449, 435, 288, 305, 18, 30, 467, 407, 405, 409, 145, 500, 391, 255, 418, 168, 487, 296, 25, 513, 242, 444, 340, 300, 343, 17, 438, 104, 413, 184, 415, 492, 375, 202, 291, 9, 232, 289, 92, 82, 16, 50, 180, 93, 151, 217, 231, 360, 148, 315, 100, 163, 401, 284, 313, 419, 366, 285, 134, 221, 20, 78, 178, 74, 439, 247, 79, 427, 60, 195, 420, 172, 447, 302, 434, 248, 381, 334, 268, 53, 341, 114, 14, 162, 480, 35, 378, 122, 81, 402, 223, 13, 63, 265, 347, 146, 233, 429, 198, 463, 273, 446, 287, 421, 331, 275, 58, 384, 123, 95, 455, 54, 174, 390, 218, 132, 229, 475, 129, 479, 339, 489, 6, 408, 364, 187, 107, 164, 506, 113, 292, 412, 21, 319, 70, 67, 270, 89, 272, 283, 121, 147, 399, 94, 249, 57, 228, 80, 72, 269, 41, 396, 377, 45, 371, 234, 186, 425, 159, 138, 237, 398, 458, 199, 368, 308, 206, 239, 85, 461, 478, 281, 160, 514, 490, 496, 194, 189, 40].
2026-09-13 19:57:30,155 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:57:30,155 - opfython.models.supervised — INFO — Training time: 0.3164401054382324 seconds.
2026-09-13 19:57:30,156 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:57:30,244 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:57:30,245 - opfython.models.supervised — INFO — Prediction time: 0.08842849731445312 seconds.
2026-09-13 19:57:30,392 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:57:30,393 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:57:30,393 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:57:30,394 - opfython.core.opf — INFO — Class created.
2026-09-13 19:57:30,394 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:57:30,395 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:57:30,396 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:57:30,498 - opfython.models.supervised — DEBUG — Prototypes: [198, 350, 416, 204, 190, 49, 93, 363, 274, 472, 506, 148, 333, 91, 507, 210, 304, 120, 415, 35, 347, 228, 434, 37, 45, 310, 332, 448, 502, 134, 30, 512, 474, 344, 299, 436, 235, 438, 375, 115, 94, 21, 390, 417, 260, 287, 138, 225, 221, 371, 285, 74, 17, 167, 208, 140, 219, 360, 242, 252, 424, 366, 280, 23, 70, 166, 142, 327, 239, 71, 187, 124, 418, 90, 151, 301, 339, 54, 27, 277, 340, 80, 272, 267, 462, 24, 321, 411, 22, 44, 139, 64, 9, 263, 129, 288, 69, 279, 262, 244, 73, 314, 266, 396, 13, 379, 58, 241, 216, 116, 66, 12, 372, 223, 14, 261, 212, 50, 159, 348, 222, 402, 118, 443, 302, 282, 400, 422, 83, 113, 4, 270, 215, 382, 454, 55, 141, 479, 343, 489, 60, 114, 6, 7, 397, 429, 351, 307, 98, 162, 447, 213, 202, 232, 186, 196, 256, 480, 399, 445, 409, 172, 380, 412, 378, 376, 18, 284, 149, 112, 192, 295, 194, 122, 334, 226, 128, 357, 458, 77, 490, 498].
2026-09-13 19:57:30,710 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:57:30,711 - opfython.models.supervised — INFO — Training time: 0.31537866592407227 seconds.
2026-09-13 19:57:30,711 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:57:30,790 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:57:30,791 - opfython.models.supervised — INFO — Prediction time: 0.0796060562133789 seconds.
2026-09-13 19:57:30,937 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:57:30,938 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:57:30,939 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:57:30,940 - opfython.core.opf — INFO — Class created.
2026-09-13 19:57:30,941 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:57:30,942 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:57:30,946 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:57:31,050 - opfython.models.supervised — DEBUG — Prototypes: [316, 66, 345, 210, 342, 416, 325, 274, 110, 200, 355, 494, 118, 215, 410, 53, 68, 108, 142, 119, 323, 365, 161, 427, 222, 72, 128, 19, 109, 506, 168, 300, 32, 415, 465, 339, 430, 141, 322, 306, 448, 401, 406, 499, 148, 288, 22, 352, 242, 436, 467, 440, 334, 297, 475, 136, 39, 370, 256, 418, 223, 105, 65, 421, 318, 38, 187, 77, 21, 82, 371, 179, 458, 163, 435, 245, 315, 83, 425, 298, 170, 311, 153, 104, 488, 396, 285, 9, 218, 366, 284, 55, 319, 86, 97, 98, 157, 279, 369, 359, 280, 117, 335, 24, 248, 257, 402, 131, 271, 62, 380, 338, 303, 5, 340, 171, 28, 149, 181, 54, 67, 461, 85, 101, 172, 219, 137, 308, 397, 490, 479, 64, 127, 473, 159, 111, 132, 227, 7, 405, 357, 194, 373, 16, 93, 272, 270, 198, 20, 150, 48, 220, 379, 455, 509, 408, 71, 73, 8, 107, 130, 250, 196, 302, 84, 278, 264, 309, 269, 252, 393, 185, 377, 61, 247, 202, 169, 444, 481, 75, 13, 43, 389, 372, 47, 243, 2, 343, 113, 505, 395, 310, 230, 413, 178, 261, 387, 417, 283, 177, 293, 69, 208, 429, 246, 337, 100, 90, 489, 249, 192, 457, 167, 193, 423, 392, 206, 376, 362, 304, 495, 212, 477, 259, 197, 89, 233, 195, 10].
2026-09-13 19:57:31,252 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:57:31,254 - opfython.models.supervised — INFO — Training time: 0.3110368251800537 seconds.
2026-09-13 19:57:31,254 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:57:31,346 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:57:31,347 - opfython.models.supervised — INFO — Prediction time: 0.09176802635192871 seconds.
2026-09-13 19:57:31,505 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:57:31,506 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:57:31,506 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:57:31,507 - opfython.core.opf — INFO — Class created.
2026-09-13 19:57:31,507 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:57:31,509 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:57:31,512 - opfython.models.supervised — DEBUG — Finding prototypes ...

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

Fase 2 MLP {'accuracy': 0.7323943661971831, 'precision_0': np.float64(0.2), 'precision_1': np.float64(0.819672131147541), 'recall_0': np.float64(0.15384615384615385), 'recall_1': np.float64(0.8620689655172413), 'f1_0': np.float64(0.17391304347826086), 'f1_1': np.float64(0.8403361344537815), 'f1_macro': 0.5071245889660212, 'f1_weighted': 0.7183150051202354, 'precision_macro': 0.5098360655737705, 'recall_macro': 0.5079575596816976, 'balanced_accuracy': 0.5079575596816976, 'mcc': 0.01769418874505073, 'specificity': np.float64(0.15384615384615385), 'sensitivity': np.float64(0.8620689655172413), 'TN': 2, 'FP': 11, 'FN': 8, 'TP': 50, 'score_source': 'continuous', 'auroc': 0.4190981432360743, 'ap_0': 0.1745239338365939, 'ap_1': 0.7769877468139312, 'scenario': 'mdi80', 'model': 'MLP', 'outer_fold': 9, 'params': {'alpha': 0.0001, 'hidden_layer_sizes': (32, 16), 'max_iter': 500}, 'inner_f1_macro': 0.4867797031671316}
Fase 2 LR {'accuracy': 0.8169014084507042, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8169014084507042), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8992248062015504), 'f1_macro': 0.4496124031007752, 'f1_weighted': 0.7345780106998581, 'precision_macro': 0.4084507042253521, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 13, 'FN': 0, 'TP': 58, 'score_source': 'continuous', 'auroc': 0.4084880636604774, 'ap_0': 0.17901048368755454, 'ap_1': 0.7695732168801546, 'scenario': 'mdi80', 'model': 'LR', 'outer_fold': 9, 'params': {'C': 0.01, 'max_iter': 1000, 'solver': 'lbfgs'}, 'inner_f1_macro': 0.449488279960383}
Fase 2 XGB {'accuracy': 0.7605633802816901, 'precision_0': np.float64(0.25), 'precision_1': np.float64(0.8253968253968254), 'recall_0': np.float64(0.15384615384615385), 'recall_1': np.float64(0.896551724137931), 'f1_0': np.float64(0.19047619047619047), 'f1_1': np.float64(0.859504132231405), 'f1_macro': 0.5249901613537977, 'f1_weighted': 0.7370060583889009, 'precision_macro': 0.5376984126984127, 'recall_macro': 0.5251989389920424, 'balanced_accuracy': 0.5251989389920424, 'mcc': 0.06164284229930153, 'specificity': np.float64(0.15384615384615385), 'sensitivity': np.float64(0.896551724137931), 'TN': 2, 'FP': 11, 'FN': 6, 'TP': 52, 'score_source': 'continuous', 'auroc': 0.376657824933687, 'ap_0': 0.22596571268109078, 'ap_1': 0.7954148508829133, 'scenario': 'mdi80', 'model': 'XGB', 'outer_fold': 9, 'params': {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}, 'inner_f1_macro': 0.49456866492590323}
Fase 2 NB {'accuracy': 0.8169014084507042, 'precision_0': np.float64(0.5), 'precision_1': np.float64(0.8260869565217391), 'recall_0': np.float64(0.07692307692307693), 'recall_1': np.float64(0.9827586206896551), 'f1_0': np.float64(0.13333333333333333), 'f1_1': np.float64(0.8976377952755905), 'f1_macro': 0.5154855643044619, 'f1_weighted': 0.7576947247791209, 'precision_macro': 0.6630434782608696, 'recall_macro': 0.5298408488063661, 'balanced_accuracy': 0.5298408488063661, 'mcc': 0.13950420472009636, 'specificity': np.float64(0.07692307692307693), 'sensitivity': np.float64(0.9827586206896551), 'TN': 1, 'FP': 12, 'FN': 1, 'TP': 57, 'score_source': 'continuous', 'auroc': 0.4694960212201592, 'ap_0': 0.2120027032915022, 'ap_1': 0.8038475397245652, 'scenario': 'mdi80', 'model': 'NB', 'outer_fold': 9, 'params': {'var_smoothing': 1e-11}, 'inner_f1_macro': 0.4749938033602897}
Fase 2 NC {'accuracy': 0.4788732394366197, 'precision_0': np.float64(0.14705882352941177), 'precision_1': np.float64(0.7837837837837838), 'recall_0': np.float64(0.38461538461538464), 'recall_1': np.float64(0.5), 'f1_0': np.float64(0.2127659574468085), 'f1_1': np.float64(0.6105263157894737), 'f1_macro': 0.4116461366181411, 'f1_weighted': 0.5376969544027885, 'precision_macro': 0.4654213036565978, 'recall_macro': 0.4423076923076923, 'balanced_accuracy': 0.4423076923076923, 'mcc': -0.08932916184634078, 'specificity': np.float64(0.38461538461538464), 'sensitivity': np.float64(0.5), 'TN': 5, 'FP': 8, 'FN': 29, 'TP': 29, 'score_source': 'continuous', 'auroc': 0.4283819628647215, 'ap_0': 0.19490396246455632, 'ap_1': 0.7786659832657418, 'scenario': 'mdi80', 'model': 'NC', 'outer_fold': 9, 'params': {'metric': 'euclidean', 'shrink_threshold': 0.1}, 'inner_f1_macro': 0.48816359785090213}
2026-09-13 19:58:50,258 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:58:50,259 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:58:50,259 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:58:50,260 - opfython.core.opf — INFO — Class created.
2026-09-13 19:58:50,260 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:58:50,261 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:58:50,262 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:58:50,365 - opfython.models.supervised — DEBUG — Prototypes: [285, 0, 215, 95, 439, 52, 93, 458, 90, 336, 220, 118, 322, 94, 307, 513, 403, 497, 35, 470, 351, 36, 255, 466, 24, 289, 44, 312, 333, 448, 128, 302, 240, 401, 400, 455, 499, 371, 248, 421, 31, 511, 37, 159, 242, 101, 261, 453, 287, 76, 81, 339, 495, 324, 257, 478, 274, 23, 443, 288, 423, 387, 311, 293, 353, 382, 99, 316, 53, 91, 352, 140, 442, 507, 370, 169, 63, 250, 74, 217, 315, 62, 156, 481, 198, 300, 6, 409, 369, 96, 160, 380, 433, 75, 49, 15, 158, 212, 266, 384, 207, 226, 459, 231, 430, 80, 270, 272, 116, 141, 5, 55, 276, 168, 194, 395, 64, 8, 92, 305, 25, 117, 121, 135, 482, 451, 474, 299, 267, 65, 185, 446, 155, 124, 381, 19, 232, 269, 42, 46, 129, 313, 392, 419, 435, 72, 329, 39, 73, 78, 138, 182, 296, 328, 259, 83, 216, 228, 230, 9, 376, 320, 89, 131, 154, 505, 282, 318, 295, 175, 363, 157, 406, 365, 397, 105, 151, 344, 297, 43, 202, 66, 125, 503, 258, 374, 479, 319, 2, 415, 262, 418, 434, 247, 373, 383, 428, 283, 204, 341, 355, 264, 196, 142, 210, 223, 205, 143, 469, 134, 239, 184, 489, 494, 84, 187, 10].
2026-09-13 19:58:50,570 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:58:50,571 - opfython.models.supervised — INFO — Training time: 0.30983448028564453 seconds.
2026-09-13 19:58:50,571 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:58:50,663 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:58:50,663 - opfython.models.supervised — INFO — Prediction time: 0.09171509742736816 seconds.
2026-09-13 19:58:50,819 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:58:50,820 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:58:50,821 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:58:50,821 - opfython.core.opf — INFO — Class created.
2026-09-13 19:58:50,821 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:58:50,822 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:58:50,824 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:58:50,929 - opfython.models.supervised — DEBUG — Prototypes: [319, 68, 347, 218, 280, 56, 70, 361, 475, 501, 460, 38, 107, 438, 130, 20, 110, 404, 136, 33, 343, 467, 304, 352, 416, 461, 27, 431, 52, 309, 324, 448, 142, 300, 401, 472, 407, 197, 139, 42, 293, 22, 355, 18, 178, 295, 248, 357, 437, 117, 336, 339, 376, 394, 456, 512, 260, 496, 418, 195, 80, 436, 253, 86, 477, 11, 192, 446, 301, 314, 106, 237, 371, 235, 358, 101, 161, 226, 57, 321, 90, 100, 284, 375, 342, 366, 285, 122, 98, 254, 420, 332, 61, 337, 120, 271, 444, 73, 46, 181, 3, 313, 430, 381, 65, 276, 385, 340, 153, 6, 345, 115, 2, 274, 88, 129, 185, 329, 494, 133, 322, 402, 478, 269, 389, 15, 69, 190, 267, 54, 89, 462, 29, 427, 398, 378, 17, 288, 481, 40, 134, 66, 113, 179, 502, 119, 7, 406, 364, 199, 283, 176, 87, 306, 44, 395, 155, 193, 382, 64, 500, 312, 257, 96, 273, 9, 71, 390, 458, 208, 21, 75, 50, 353, 227, 384, 454, 154, 409, 77, 13, 45, 392, 291, 84, 372, 239, 297, 72, 341, 198, 424, 148, 242, 354, 247, 156, 470, 417, 205, 264, 173, 266, 93, 459, 214, 508, 480, 223, 201].
2026-09-13 19:58:51,138 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:58:51,139 - opfython.models.supervised — INFO — Training time: 0.31661057472229004 seconds.
2026-09-13 19:58:51,140 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:58:51,228 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:58:51,229 - opfython.models.supervised — INFO — Prediction time: 0.08857178688049316 seconds.
2026-09-13 19:58:51,373 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:58:51,374 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:58:51,375 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:58:51,375 - opfython.core.opf — INFO — Class created.
2026-09-13 19:58:51,375 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:58:51,376 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:58:51,378 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:58:51,481 - opfython.models.supervised — DEBUG — Prototypes: [8, 300, 140, 281, 342, 389, 11, 278, 280, 433, 259, 25, 161, 193, 328, 152, 83, 218, 227, 77, 15, 297, 249, 398, 16, 247, 239, 189, 262, 59, 21, 87, 97, 195, 292, 172, 276, 85, 103, 173, 311, 46, 245, 289, 176, 307, 171, 102, 213, 351, 72, 47, 513, 443, 229, 354, 368, 2, 472, 501, 18, 275, 119, 86, 285, 503, 168, 458, 32, 299, 364, 482, 205, 125, 5, 277, 390, 461, 473, 137, 502, 191, 373, 201, 314, 415, 479, 272, 182, 374, 136, 310, 418, 397, 208, 204, 488, 222, 379, 407, 36, 350, 468, 464, 294, 451, 402, 457, 64, 405, 348, 54, 313, 446, 331, 139, 304, 494, 440, 35, 385, 453, 496, 57, 106, 456, 104, 127, 321, 353, 174, 69, 325, 96, 242, 70, 240, 288, 270, 50, 132, 257, 434, 470, 29, 511, 37, 109, 426, 370, 6, 347, 7, 377, 487, 317, 128, 252, 238, 293, 158, 256, 334, 261, 84, 23, 52, 497, 380, 24, 454, 267, 323, 371, 344, 187, 286, 156, 219, 340, 290, 381, 146, 251, 217, 185, 254, 384, 203, 274, 481, 302, 428, 411, 154, 332, 210, 478, 169, 489, 60, 372, 206, 207].
2026-09-13 19:58:51,686 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:58:51,687 - opfython.models.supervised — INFO — Training time: 0.3101022243499756 seconds.
2026-09-13 19:58:51,687 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:58:51,774 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:58:51,774 - opfython.models.supervised — INFO — Prediction time: 0.0868535041809082 seconds.
2026-09-13 19:58:51,918 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:58:51,918 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:58:51,919 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:58:51,919 - opfython.core.opf — INFO — Class created.
2026-09-13 19:58:51,919 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:58:51,920 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:58:51,921 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:58:52,018 - opfython.models.supervised — DEBUG — Prototypes: [326, 68, 357, 224, 3, 59, 69, 106, 368, 472, 502, 140, 332, 168, 237, 467, 36, 131, 352, 311, 360, 420, 461, 139, 437, 54, 314, 135, 496, 485, 407, 405, 411, 194, 418, 179, 132, 45, 199, 96, 469, 126, 24, 107, 257, 442, 113, 31, 511, 343, 309, 347, 22, 171, 382, 216, 119, 95, 295, 269, 319, 381, 156, 98, 244, 365, 234, 377, 246, 61, 20, 88, 97, 192, 427, 48, 72, 328, 44, 190, 79, 25, 84, 231, 459, 162, 441, 261, 260, 136, 422, 393, 325, 2, 361, 320, 436, 262, 263, 424, 339, 283, 63, 345, 116, 450, 275, 400, 16, 387, 64, 317, 284, 294, 280, 265, 476, 85, 312, 46, 70, 397, 290, 94, 285, 178, 26, 8, 137, 129, 143, 76, 15, 47, 399, 302, 83, 383, 51, 344, 378, 248, 305, 71, 351, 66, 130, 118, 481, 490, 425, 414, 161, 448, 298, 330, 86, 336, 288, 180, 350, 149, 5, 456, 297, 408, 282, 394, 355, 463, 1, 87, 56, 18, 279, 138, 353, 247, 182, 60, 433, 384, 21, 300, 235, 133, 243, 239, 482, 42, 479, 109, 172, 6, 7, 371, 202, 503, 218, 310, 201, 430, 211, 254, 362, 220, 228, 92, 460, 480, 293, 491, 495, 507, 375, 184, 203].
2026-09-13 19:58:52,214 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:58:52,215 - opfython.models.supervised — INFO — Training time: 0.29437732696533203 seconds.
2026-09-13 19:58:52,215 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:58:52,295 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:58:52,295 - opfython.models.supervised — INFO — Prediction time: 0.07980132102966309 seconds.
2026-09-13 19:58:52,436 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:58:52,437 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:58:52,437 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 19:58:52,438 - opfython.core.opf — INFO — Class created.
2026-09-13 19:58:52,438 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:58:52,439 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:58:52,440 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:58:52,538 - opfython.models.supervised — DEBUG — Prototypes: [323, 64, 354, 217, 285, 367, 503, 139, 329, 165, 103, 505, 232, 470, 441, 409, 32, 308, 31, 349, 468, 462, 58, 436, 328, 302, 18, 88, 497, 410, 298, 363, 23, 196, 414, 26, 512, 33, 299, 170, 17, 341, 304, 345, 417, 177, 266, 227, 376, 53, 16, 86, 95, 189, 96, 264, 228, 239, 365, 169, 317, 236, 151, 70, 45, 326, 40, 21, 178, 381, 224, 458, 77, 188, 160, 439, 252, 357, 81, 206, 447, 136, 495, 393, 3, 361, 316, 183, 371, 291, 118, 94, 435, 253, 254, 420, 385, 265, 336, 274, 56, 343, 115, 69, 44, 181, 65, 350, 351, 27, 148, 463, 85, 49, 84, 129, 126, 175, 494, 327, 407, 446, 292, 422, 100, 332, 282, 179, 60, 389, 93, 125, 149, 454, 192, 394, 272, 229, 57, 238, 383, 368, 352, 267, 110, 2, 504, 114, 130, 62, 117, 480, 488, 386, 216, 401, 78, 12, 277, 150, 290, 168, 270, 83, 82, 256, 237, 333, 67, 459, 203, 276, 92, 278, 7, 137, 128, 22, 72, 321, 413, 20, 499, 344, 296, 80, 74, 275, 43, 398, 382, 377, 207, 434, 301, 210, 141, 241, 205, 245, 400, 212, 305, 362, 213, 221, 471, 419, 200, 89, 460, 166, 514, 489, 493].
2026-09-13 19:58:52,736 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:58:52,737 - opfython.models.supervised — INFO — Training time: 0.29778337478637695 seconds.
2026-09-13 19:58:52,737 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:58:52,824 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:58:52,825 - opfython.models.supervised — INFO — Prediction time: 0.08741259574890137 seconds.
2026-09-13 19:58:52,969 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:58:52,970 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:58:52,970 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:58:52,971 - opfython.core.opf — INFO — Class created.
2026-09-13 19:58:52,971 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:58:52,972 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:58:52,973 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:58:53,070 - opfython.models.supervised — DEBUG — Prototypes: [285, 0, 215, 95, 439, 52, 93, 458, 90, 336, 220, 24, 32, 44, 312, 21, 302, 128, 403, 35, 497, 470, 351, 36, 255, 466, 307, 306, 273, 240, 401, 455, 499, 371, 37, 159, 31, 511, 118, 322, 94, 101, 242, 453, 287, 76, 81, 339, 495, 324, 257, 478, 86, 23, 443, 288, 423, 387, 293, 411, 311, 348, 310, 250, 74, 169, 63, 316, 53, 91, 352, 140, 442, 507, 370, 217, 315, 508, 62, 156, 300, 6, 409, 369, 481, 198, 96, 393, 433, 353, 99, 166, 25, 121, 80, 270, 272, 116, 141, 5, 55, 276, 168, 194, 395, 64, 456, 8, 92, 135, 384, 207, 15, 212, 158, 266, 49, 75, 309, 399, 12, 482, 451, 459, 231, 232, 269, 46, 114, 505, 226, 154, 320, 89, 131, 230, 376, 216, 9, 3, 259, 56, 394, 440, 318, 228, 392, 129, 419, 435, 72, 329, 39, 73, 78, 138, 357, 157, 406, 295, 175, 363, 182, 296, 328, 437, 365, 28, 397, 445, 105, 319, 2, 415, 262, 65, 344, 43, 196, 506, 299, 42, 418, 85, 41, 434, 247, 373, 474, 185, 446, 428, 155, 124, 125, 503, 248, 361, 261, 381, 19, 258, 283, 355, 341, 264, 202, 66, 374, 479, 143, 221, 383, 210, 271, 223, 205, 239, 469, 256, 489, 494, 134, 235, 84, 187, 10].
2026-09-13 19:58:53,263 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:58:53,264 - opfython.models.supervised — INFO — Training time: 0.29209446907043457 seconds.
2026-09-13 19:58:53,265 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:58:53,352 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:58:53,353 - opfython.models.supervised — INFO — Prediction time: 0.0883171558380127 seconds.
2026-09-13 19:58:53,495 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:58:53,495 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:58:53,496 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:58:53,496 - opfython.core.opf — INFO — Class created.
2026-09-13 19:58:53,496 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 19:58:53,497 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 19:58:53,498 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 19:58:53,596 - opfython.models.supervised — DEBUG — Prototypes: [319, 68, 347, 218, 280, 56, 70, 361, 475, 501, 460, 38, 107, 130, 20, 110, 142, 300, 495, 309, 52, 405, 19, 145, 461, 431, 150, 304, 352, 416, 34, 404, 33, 343, 467, 485, 401, 472, 407, 197, 293, 355, 22, 18, 178, 295, 437, 248, 139, 42, 137, 195, 80, 436, 253, 260, 418, 86, 477, 301, 314, 106, 177, 488, 397, 157, 237, 326, 371, 241, 358, 235, 101, 161, 226, 331, 57, 321, 100, 90, 284, 375, 366, 285, 122, 98, 61, 332, 120, 337, 420, 11, 342, 3, 313, 382, 64, 395, 193, 500, 312, 257, 155, 283, 176, 87, 44, 306, 96, 273, 9, 71, 458, 21, 454, 291, 412, 84, 77, 13, 372, 239, 45, 392, 429, 298, 462, 29, 15, 69, 190, 267, 54, 89, 340, 153, 6, 345, 115, 2, 276, 65, 385, 88, 129, 402, 133, 269, 389, 398, 474, 66, 113, 179, 427, 378, 17, 502, 7, 72, 364, 199, 406, 288, 192, 446, 297, 223, 481, 40, 341, 148, 242, 73, 46, 336, 339, 119, 198, 424, 254, 394, 456, 430, 181, 381, 508, 222, 173, 513, 205, 264, 470, 417, 93, 459, 480, 228, 330, 201, 83].
2026-09-13 19:58:53,797 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 19:58:53,798 - opfython.models.supervised — INFO — Training time: 0.30095911026000977 seconds.
2026-09-13 19:58:53,799 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 19:58:53,882 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 19:58:53,883 - opfython.models.supervised — INFO — Prediction time: 0.08426260948181152 seconds.
2026-09-13 19:58:54,024 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 19:58:54,024 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 19:58:54,025 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 19:58:54,025 - opfython.core.opf — INFO — Class created.
2026-09-13 19:58:54,026 - opfython.models.supervised — INFO — Class overrided.

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

Fase 2 MLP {'accuracy': 0.8309859154929577, 'precision_0': np.float64(1.0), 'precision_1': np.float64(0.8285714285714286), 'recall_0': np.float64(0.07692307692307693), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.14285714285714285), 'f1_1': np.float64(0.90625), 'f1_macro': 0.5245535714285714, 'f1_weighted': 0.7664738430583501, 'precision_macro': 0.9142857142857144, 'recall_macro': 0.5384615384615384, 'balanced_accuracy': 0.5384615384615384, 'mcc': 0.25246042013801634, 'specificity': np.float64(0.07692307692307693), 'sensitivity': np.float64(1.0), 'TN': 1, 'FP': 12, 'FN': 0, 'TP': 58, 'score_source': 'continuous', 'auroc': 0.5716180371352785, 'ap_0': 0.28306314801908994, 'ap_1': 0.87787612756409, 'scenario': 'mdi80', 'model': 'MLP', 'outer_fold': 10, 'params': {'alpha': 0.0001, 'hidden_layer_sizes': (32,), 'max_iter': 500}, 'inner_f1_macro': 0.47010796420262296}
Fase 2 LR {'accuracy': 0.8169014084507042, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8169014084507042), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8992248062015504), 'f1_macro': 0.4496124031007752, 'f1_weighted': 0.7345780106998581, 'precision_macro': 0.4084507042253521, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 13, 'FN': 0, 'TP': 58, 'score_source': 'continuous', 'auroc': 0.5742705570291777, 'ap_0': 0.2519230520135073, 'ap_1': 0.8834737398138631, 'scenario': 'mdi80', 'model': 'LR', 'outer_fold': 10, 'params': {'C': 0.01, 'max_iter': 1000, 'solver': 'lbfgs'}, 'inner_f1_macro': 0.449488279960383}
Fase 2 XGB {'accuracy': 0.8309859154929577, 'precision_0': np.float64(0.6666666666666666), 'precision_1': np.float64(0.8382352941176471), 'recall_0': np.float64(0.15384615384615385), 'recall_1': np.float64(0.9827586206896551), 'f1_0': np.float64(0.25), 'f1_1': np.float64(0.9047619047619048), 'f1_macro': 0.5773809523809523, 'f1_weighted': 0.7848759221998658, 'precision_macro': 0.7524509803921569, 'recall_macro': 0.5683023872679045, 'balanced_accuracy': 0.5683023872679045, 'mcc': 0.26262524348514, 'specificity': np.float64(0.15384615384615385), 'sensitivity': np.float64(0.9827586206896551), 'TN': 2, 'FP': 11, 'FN': 1, 'TP': 57, 'score_source': 'continuous', 'auroc': 0.5424403183023871, 'ap_0': 0.28673673129770416, 'ap_1': 0.839509094507008, 'scenario': 'mdi80', 'model': 'XGB', 'outer_fold': 10, 'params': {'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 200}, 'inner_f1_macro': 0.4809317885888631}
Fase 2 NB {'accuracy': 0.8169014084507042, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8169014084507042), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8992248062015504), 'f1_macro': 0.4496124031007752, 'f1_weighted': 0.7345780106998581, 'precision_macro': 0.4084507042253521, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 13, 'FN': 0, 'TP': 58, 'score_source': 'continuous', 'auroc': 0.583554376657825, 'ap_0': 0.33413882142298895, 'ap_1': 0.8645325144041603, 'scenario': 'mdi80', 'model': 'NB', 'outer_fold': 10, 'params': {'var_smoothing': 1e-11}, 'inner_f1_macro': 0.4422438261479993}
Fase 2 NC {'accuracy': 0.7464788732394366, 'precision_0': np.float64(0.35294117647058826), 'precision_1': np.float64(0.8703703703703703), 'recall_0': np.float64(0.46153846153846156), 'recall_1': np.float64(0.8103448275862069), 'f1_0': np.float64(0.4), 'f1_1': np.float64(0.8392857142857143), 'f1_macro': 0.6196428571428572, 'f1_weighted': 0.7588531187122737, 'precision_macro': 0.6116557734204793, 'recall_macro': 0.6359416445623343, 'balanced_accuracy': 0.6359416445623343, 'mcc': 0.24640348588166783, 'specificity': np.float64(0.46153846153846156), 'sensitivity': np.float64(0.8103448275862069), 'TN': 6, 'FP': 7, 'FN': 11, 'TP': 47, 'score_source': 'unavailable', 'auroc': nan, 'ap_0': nan, 'ap_1': nan, 'scenario': 'mdi80', 'model': 'NC', 'outer_fold': 10, 'params': {'metric': 'manhattan', 'shrink_threshold': 0.1}, 'inner_f1_macro': 0.47140360745817167}
2026-09-13 20:00:13,030 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 20:00:13,031 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 20:00:13,032 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 20:00:13,032 - opfython.core.opf — INFO — Class created.
2026-09-13 20:00:13,033 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 20:00:13,033 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 20:00:13,035 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 20:00:13,129 - opfython.models.supervised — DEBUG — Prototypes: [206, 351, 414, 211, 105, 365, 272, 131, 63, 109, 371, 267, 49, 92, 152, 456, 216, 464, 118, 21, 34, 348, 35, 401, 302, 357, 457, 29, 433, 46, 271, 330, 446, 127, 296, 400, 468, 403, 138, 411, 164, 255, 288, 360, 25, 179, 83, 157, 290, 239, 102, 342, 298, 345, 409, 375, 199, 394, 453, 124, 42, 66, 23, 72, 171, 69, 437, 243, 354, 73, 195, 128, 497, 217, 386, 91, 416, 61, 419, 155, 316, 142, 90, 222, 285, 231, 212, 283, 52, 18, 84, 167, 213, 392, 246, 252, 277, 314, 418, 368, 278, 107, 397, 150, 339, 258, 56, 343, 443, 65, 387, 41, 160, 2, 315, 432, 244, 232, 81, 264, 265, 64, 390, 10, 94, 129, 144, 54, 45, 358, 381, 452, 510, 500, 166, 405, 163, 24, 319, 68, 14, 76, 184, 75, 304, 74, 312, 249, 379, 82, 245, 372, 228, 154, 376, 44, 293, 261, 181, 424, 294, 442, 481, 268, 221, 382, 441, 280, 116, 460, 5, 349, 227, 458, 31, 15, 259, 219, 48, 214, 58, 311, 377, 19, 282, 479, 341, 486, 97, 158, 7, 8, 367, 182, 396, 133, 359, 313, 201, 325, 187, 466, 415, 478, 275, 487, 494, 78, 509, 62].
2026-09-13 20:00:13,321 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 20:00:13,322 - opfython.models.supervised — INFO — Training time: 0.2884409427642822 seconds.
2026-09-13 20:00:13,322 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 20:00:13,420 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 20:00:13,421 - opfython.models.supervised — INFO — Prediction time: 0.09834146499633789 seconds.
2026-09-13 20:00:13,563 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 20:00:13,564 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 20:00:13,564 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 20:00:13,565 - opfython.core.opf — INFO — Class created.
2026-09-13 20:00:13,565 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 20:00:13,565 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 20:00:13,567 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 20:00:13,665 - opfython.models.supervised — DEBUG — Prototypes: [277, 0, 316, 67, 324, 113, 224, 407, 55, 69, 111, 485, 225, 75, 458, 109, 223, 130, 19, 112, 45, 268, 274, 305, 294, 18, 40, 459, 301, 300, 512, 413, 31, 402, 399, 397, 454, 498, 189, 30, 387, 256, 181, 32, 329, 266, 336, 434, 246, 186, 68, 253, 475, 335, 89, 494, 258, 48, 20, 104, 379, 162, 500, 280, 440, 400, 272, 409, 37, 451, 191, 341, 151, 439, 506, 251, 139, 309, 115, 110, 131, 343, 373, 116, 2, 171, 65, 478, 210, 292, 8, 361, 403, 114, 429, 85, 198, 288, 285, 66, 414, 417, 86, 209, 298, 249, 404, 172, 312, 34, 107, 174, 123, 325, 358, 144, 284, 222, 241, 283, 79, 233, 163, 102, 58, 217, 356, 83, 56, 318, 101, 91, 503, 169, 419, 466, 287, 354, 138, 482, 3, 184, 428, 250, 391, 317, 120, 255, 334, 44, 473, 72, 385, 375, 297, 52, 90, 42, 87, 15, 173, 221, 263, 276, 177, 231, 392, 103, 376, 234, 63, 98, 460, 27, 128, 4, 97, 267, 84, 78, 463, 270, 57, 70, 388, 456, 74, 76, 180, 264, 205, 386, 483, 60, 147, 477, 472, 367, 235, 43, 339, 441, 71, 291, 200, 372, 17, 170, 509, 427, 216, 208, 35, 243, 146, 94, 457, 487, 493, 201, 9].
2026-09-13 20:00:13,862 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 20:00:13,863 - opfython.models.supervised — INFO — Training time: 0.2965221405029297 seconds.
2026-09-13 20:00:13,863 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 20:00:13,948 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 20:00:13,948 - opfython.models.supervised — INFO — Prediction time: 0.08499789237976074 seconds.
2026-09-13 20:00:14,090 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 20:00:14,091 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 20:00:14,091 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 20:00:14,092 - opfython.core.opf — INFO — Class created.
2026-09-13 20:00:14,092 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 20:00:14,093 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 20:00:14,094 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 20:00:14,194 - opfython.models.supervised — DEBUG — Prototypes: [10, 141, 129, 146, 25, 320, 155, 76, 360, 380, 50, 451, 508, 152, 409, 73, 78, 16, 394, 17, 313, 501, 286, 270, 46, 247, 49, 348, 298, 271, 71, 439, 480, 18, 269, 241, 69, 181, 54, 87, 171, 56, 457, 29, 237, 137, 125, 151, 5, 353, 112, 1, 450, 185, 86, 130, 126, 176, 327, 402, 474, 438, 180, 272, 469, 66, 131, 478, 7, 8, 395, 140, 495, 239, 105, 325, 41, 190, 251, 376, 24, 258, 431, 83, 216, 442, 88, 97, 57, 21, 235, 248, 98, 157, 236, 317, 104, 168, 397, 332, 287, 315, 417, 369, 288, 117, 398, 183, 420, 115, 160, 26, 259, 440, 268, 72, 385, 285, 299, 378, 331, 192, 232, 116, 415, 352, 55, 70, 142, 111, 119, 372, 37, 366, 502, 468, 503, 165, 455, 68, 321, 463, 20, 435, 127, 108, 318, 294, 363, 136, 42, 281, 51, 329, 444, 139, 494, 456, 27, 404, 34, 33, 350, 120, 401, 400, 407, 149, 497, 193, 198, 96, 254, 432, 341, 302, 470, 375, 344, 386, 416, 175, 413, 178, 264, 486, 393, 453, 145, 249, 314, 215, 252, 226, 207, 224, 166, 477, 487, 493, 507, 203, 45].
2026-09-13 20:00:14,395 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 20:00:14,395 - opfython.models.supervised — INFO — Training time: 0.30237317085266113 seconds.
2026-09-13 20:00:14,396 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 20:00:14,477 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 20:00:14,478 - opfython.models.supervised — INFO — Prediction time: 0.08130621910095215 seconds.
2026-09-13 20:00:14,618 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 20:00:14,619 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 20:00:14,619 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 20:00:14,620 - opfython.core.opf — INFO — Class created.
2026-09-13 20:00:14,620 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 20:00:14,621 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 20:00:14,622 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 20:00:14,719 - opfython.models.supervised — DEBUG — Prototypes: [291, 0, 322, 67, 417, 353, 331, 154, 189, 209, 247, 492, 411, 450, 227, 108, 57, 233, 74, 229, 127, 109, 23, 288, 356, 309, 513, 34, 350, 47, 22, 24, 145, 29, 293, 376, 42, 137, 457, 280, 482, 134, 404, 402, 146, 497, 19, 119, 48, 43, 181, 396, 391, 266, 438, 336, 277, 343, 253, 114, 440, 217, 262, 371, 85, 202, 473, 179, 68, 58, 314, 106, 259, 169, 351, 444, 252, 87, 319, 495, 405, 412, 474, 50, 445, 284, 454, 292, 354, 379, 1, 342, 123, 231, 313, 110, 164, 64, 303, 7, 367, 478, 211, 423, 25, 129, 75, 37, 153, 307, 72, 173, 95, 279, 278, 125, 4, 5, 61, 283, 69, 458, 484, 203, 276, 207, 390, 141, 10, 397, 17, 382, 63, 18, 226, 84, 166, 235, 273, 290, 274, 86, 54, 88, 239, 171, 302, 275, 70, 199, 447, 244, 476, 372, 45, 49, 378, 21, 325, 40, 187, 79, 439, 434, 83, 358, 448, 135, 419, 234, 389, 65, 422, 206, 196, 298, 296, 77, 228, 250, 242, 294, 59, 20, 326, 81, 98, 89, 230, 3, 268, 392, 464, 442, 424, 437, 222, 133, 483, 433, 258, 2, 176, 415, 269, 418, 381, 117, 264, 446, 272, 363, 375, 470, 341, 46, 427, 210, 251, 220, 465, 92, 459, 426, 425, 198, 218, 140, 31, 201, 11].
2026-09-13 20:00:14,913 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 20:00:14,914 - opfython.models.supervised — INFO — Training time: 0.29286766052246094 seconds.
2026-09-13 20:00:14,914 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 20:00:15,004 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 20:00:15,005 - opfython.models.supervised — INFO — Prediction time: 0.09025168418884277 seconds.
2026-09-13 20:00:15,148 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 20:00:15,149 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 20:00:15,149 - opfython.core.opf — DEBUG — Distance: euclidean | Pre-computed distance: False.
2026-09-13 20:00:15,149 - opfython.core.opf — INFO — Class created.
2026-09-13 20:00:15,150 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 20:00:15,150 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 20:00:15,152 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 20:00:15,248 - opfython.models.supervised — DEBUG — Prototypes: [319, 63, 329, 187, 223, 410, 220, 116, 72, 50, 65, 106, 190, 485, 227, 222, 459, 400, 104, 281, 353, 118, 45, 39, 369, 43, 270, 277, 309, 298, 135, 495, 17, 303, 415, 207, 137, 20, 460, 406, 130, 28, 347, 219, 381, 201, 497, 144, 179, 27, 391, 257, 172, 334, 268, 339, 262, 211, 285, 453, 404, 316, 412, 85, 494, 259, 477, 19, 157, 350, 377, 111, 2, 176, 64, 51, 348, 145, 443, 507, 250, 168, 253, 83, 123, 225, 311, 127, 60, 164, 296, 109, 131, 323, 36, 82, 205, 186, 78, 241, 248, 439, 81, 433, 136, 418, 228, 388, 103, 61, 420, 301, 409, 165, 313, 32, 166, 96, 87, 324, 505, 162, 290, 221, 366, 139, 4, 224, 215, 364, 346, 293, 361, 3, 312, 413, 432, 249, 417, 23, 445, 363, 68, 42, 475, 389, 397, 322, 379, 115, 255, 90, 93, 276, 75, 464, 73, 21, 202, 273, 66, 393, 457, 151, 302, 482, 340, 197, 55, 9, 140, 266, 101, 70, 390, 398, 13, 380, 58, 461, 31, 84, 305, 40, 230, 283, 264, 474, 345, 163, 510, 41, 46, 444, 479, 431, 204, 175, 376, 467, 469, 89, 421, 98, 487, 493, 195, 10].
2026-09-13 20:00:15,447 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 20:00:15,448 - opfython.models.supervised — INFO — Training time: 0.29680848121643066 seconds.
2026-09-13 20:00:15,448 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 20:00:15,530 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 20:00:15,530 - opfython.models.supervised — INFO — Prediction time: 0.08177495002746582 seconds.
2026-09-13 20:00:15,672 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 20:00:15,673 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 20:00:15,673 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 20:00:15,673 - opfython.core.opf — INFO — Class created.
2026-09-13 20:00:15,674 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 20:00:15,674 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 20:00:15,676 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 20:00:15,773 - opfython.models.supervised — DEBUG — Prototypes: [206, 351, 414, 211, 105, 365, 272, 131, 63, 109, 371, 267, 49, 92, 152, 456, 118, 21, 271, 46, 330, 446, 127, 296, 457, 281, 433, 302, 20, 357, 413, 35, 401, 34, 348, 400, 403, 288, 360, 25, 157, 468, 290, 239, 102, 342, 298, 179, 83, 128, 217, 386, 91, 416, 171, 69, 23, 72, 454, 437, 243, 354, 66, 42, 178, 318, 123, 195, 73, 321, 61, 419, 155, 285, 273, 231, 283, 212, 52, 18, 84, 55, 167, 389, 254, 465, 363, 148, 142, 316, 90, 222, 277, 314, 246, 252, 368, 278, 107, 397, 343, 56, 339, 26, 325, 418, 64, 301, 390, 455, 54, 264, 81, 265, 22, 510, 144, 24, 319, 10, 129, 379, 207, 245, 76, 75, 248, 223, 312, 249, 68, 14, 268, 221, 382, 441, 280, 116, 305, 5, 349, 158, 227, 31, 139, 458, 214, 58, 311, 15, 48, 219, 259, 479, 341, 486, 97, 44, 396, 376, 411, 164, 255, 2, 315, 228, 372, 438, 345, 432, 244, 86, 377, 19, 282, 65, 41, 387, 431, 294, 442, 481, 7, 8, 367, 182, 293, 261, 181, 424, 443, 274, 394, 453, 375, 511, 509, 201, 124, 331, 232, 133, 313, 466, 415, 187, 478, 275, 487, 494, 78, 429, 215, 62, 336].
2026-09-13 20:00:15,972 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 20:00:15,972 - opfython.models.supervised — INFO — Training time: 0.2977428436279297 seconds.
2026-09-13 20:00:15,973 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 20:00:16,066 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 20:00:16,067 - opfython.models.supervised — INFO — Prediction time: 0.09384441375732422 seconds.
2026-09-13 20:00:16,213 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 20:00:16,214 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 20:00:16,214 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 20:00:16,215 - opfython.core.opf — INFO — Class created.
2026-09-13 20:00:16,216 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 20:00:16,216 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 20:00:16,218 - opfython.models.supervised — DEBUG — Finding prototypes ...
2026-09-13 20:00:16,320 - opfython.models.supervised — DEBUG — Prototypes: [277, 0, 316, 67, 324, 113, 224, 407, 55, 69, 111, 485, 225, 75, 458, 109, 223, 130, 19, 112, 45, 268, 274, 305, 294, 18, 40, 459, 301, 300, 402, 135, 399, 468, 454, 498, 175, 32, 434, 246, 309, 110, 341, 151, 439, 506, 251, 446, 451, 279, 440, 280, 20, 162, 89, 494, 258, 400, 272, 409, 253, 475, 186, 68, 335, 171, 65, 292, 8, 361, 343, 116, 2, 210, 478, 387, 393, 129, 74, 180, 97, 267, 128, 4, 6, 78, 463, 270, 185, 70, 456, 264, 205, 386, 276, 263, 15, 87, 173, 221, 52, 88, 42, 177, 231, 392, 14, 103, 260, 501, 82, 376, 234, 63, 98, 460, 27, 483, 147, 429, 85, 497, 198, 288, 285, 86, 209, 66, 417, 298, 249, 404, 172, 91, 419, 101, 318, 56, 284, 222, 233, 79, 102, 58, 217, 356, 358, 144, 143, 325, 107, 174, 123, 269, 503, 169, 287, 354, 391, 317, 120, 255, 355, 334, 44, 473, 72, 466, 71, 441, 427, 3, 184, 235, 367, 216, 297, 291, 181, 189, 30, 208, 187, 243, 428, 250, 138, 482, 385, 477, 472, 200, 450, 114, 61, 339, 170, 127, 43, 372, 17, 375, 337, 94, 457, 215, 199, 146, 239, 487, 493, 201, 9, 327, 329].
2026-09-13 20:00:16,518 - opfython.models.supervised — INFO — Classifier has been fitted.
2026-09-13 20:00:16,519 - opfython.models.supervised — INFO — Training time: 0.30260252952575684 seconds.
2026-09-13 20:00:16,519 - opfython.models.supervised — INFO — Predicting data ...
2026-09-13 20:00:16,607 - opfython.models.supervised — INFO — Data has been predicted.
2026-09-13 20:00:16,608 - opfython.models.supervised — INFO — Prediction time: 0.08765077590942383 seconds.
2026-09-13 20:00:16,752 - opfython.models.supervised — INFO — Overriding class: OPF -> SupervisedOPF.
2026-09-13 20:00:16,752 - opfython.core.opf — INFO — Creating class: OPF.
2026-09-13 20:00:16,753 - opfython.core.opf — DEBUG — Distance: manhattan | Pre-computed distance: False.
2026-09-13 20:00:16,753 - opfython.core.opf — INFO — Class created.
2026-09-13 20:00:16,753 - opfython.models.supervised — INFO — Class overrided.
2026-09-13 20:00:16,754 - opfython.models.supervised — INFO — Fitting classifier ...
2026-09-13 20:00:16,756 - opfython.models.supervised — DEBUG — Finding prototypes ...

# Fase 3 — Custo sensível
Pesos calculados exclusivamente com labels do treino corrente. KNN, NB, NC e OPF não são aplicáveis.

In [96]:
cost_roster = ["DT", "RF", "SVM", "LR", "XGB"]
phase3_rows = []
phase3_oof = {name: np.full(len(y_array), -1, dtype=int) for name in cost_roster}
phase3_scores = {name: np.full(len(y_array), np.nan) for name in cost_roster}
phase3_weights = []
phase3_non_applicable = {name: "não aplicável" for name in ["KNN", "NB", "NC", "OPF"]}
for name, reason in phase3_non_applicable.items():
    print("Fase 3", name, reason)
for outer_fold, (train_index, test_index) in enumerate(outer_cv.split(X, y_array), 1):
    X_train = X.iloc[train_index]
    X_test = X.iloc[test_index]
    y_train = y_array[train_index]
    y_test = y_array[test_index]
    outer_weights = prevalence_weights(y_train)
    phase3_weights.append({"outer_fold": outer_fold, "weights": outer_weights, "y_fit_indices": train_index.tolist()})
    for name in cost_roster:
        grid = grids[name]
        candidates = []
        for params in ParameterGrid(grid):
            inner_scores = []
            for inner_fold, (inner_train, inner_valid) in enumerate(inner_cv.split(X_train, y_train), 1):
                y_fit = y_train[inner_train]
                preprocessor, encoded_train, encoded_valid, _ = prepare_split(X_train.iloc[inner_train], y_fit, X_train.iloc[inner_valid])
                model = make_estimator(name, params, scenario="cost_sensitive", y_fit=y_fit)
                model.fit(encoded_train, y_fit)
                prediction = model.predict(encoded_valid)
                inner_scores.append(f1_score(y_train[inner_valid], prediction, labels=[0, 1], average="macro", zero_division=0))
            candidates.append((float(np.mean(inner_scores)), dict(params)))
        best_f1, best_params = max(candidates, key=lambda item: item[0])
        preprocessor, encoded_train, encoded_test, _ = prepare_split(X_train, y_train, X_test)
        model = make_estimator(name, best_params, scenario="cost_sensitive", y_fit=y_train)
        model.fit(encoded_train, y_train)
        prediction, score0, score1, _ = predict_with_score(model, encoded_test)
        metrics = binary_metrics(y_test, prediction, score0, score1)
        metrics.update({"scenario": "cost_sensitive", "model": name, "outer_fold": outer_fold, "params": best_params, "inner_f1_macro": best_f1})
        phase3_rows.append(metrics)
        phase3_oof[name][test_index] = prediction
        if score1 is not None:
            phase3_scores[name][test_index] = score1
        print("Fase 3", name, metrics)

Fase 3 KNN não aplicável
Fase 3 NB não aplicável
Fase 3 NC não aplicável
Fase 3 OPF não aplicável
Fase 3 DT {'accuracy': 0.6944444444444444, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.7936507936507936), 'recall_0': np.float64(0.0), 'recall_1': np.float64(0.847457627118644), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.819672131147541), 'f1_macro': 0.4098360655737705, 'f1_weighted': 0.6716757741347905, 'precision_macro': 0.3968253968253968, 'recall_macro': 0.423728813559322, 'balanced_accuracy': 0.423728813559322, 'mcc': -0.1774175796776985, 'specificity': np.float64(0.0), 'sensitivity': np.float64(0.847457627118644), 'TN': 0, 'FP': 13, 'FN': 9, 'TP': 50, 'score_source': 'continuous', 'auroc': 0.423728813559322, 'ap_0': 0.18055555555555555, 'ap_1': 0.7965177517376796, 'scenario': 'cost_sensitive', 'model': 'DT', 'outer_fold': 1, 'params': {'max_depth': None, 'min_samples_leaf': 1}, 'inner_f1_macro': 0.5137522833997994}
Fase 3 RF {'accuracy': 0.7083333333333334, 'precision_0': np.float64(0.16666666666666666), 'precision_1': np.float64(0.8166666666666667), 'recall_0': np.float64(0.15384615384615385), 'recall_1': np.float64(0.8305084745762712), 'f1_0': np.float64(0.16), 'f1_1': np.float64(0.8235294117647058), 'f1_macro': 0.49176470588235294, 'f1_weighted': 0.7037254901960783, 'precision_macro': 0.49166666666666664, 'recall_macro': 0.4921773142112125, 'balanced_accuracy': 0.4921773142112125, 'mcc': -0.016147947019964574, 'specificity': np.float64(0.15384615384615385), 'sensitivity': np.float64(0.8305084745762712), 'TN': 2, 'FP': 11, 'FN': 10, 'TP': 49, 'score_source': 'continuous', 'auroc': 0.6186440677966102, 'ap_0': 0.2329422759211138, 'ap_1': 0.8942264530308914, 'scenario': 'cost_sensitive', 'model': 'RF', 'outer_fold': 1, 'params': {'max_depth': None, 'min_samples_leaf': 1, 'n_estimators': 100}, 'inner_f1_macro': 0.4987710744069016}
Fase 3 SVM {'accuracy': 0.8194444444444444, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8194444444444444), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.9007633587786259), 'f1_macro': 0.45038167938931295, 'f1_weighted': 0.7381255301102629, 'precision_macro': 0.4097222222222222, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 13, 'FN': 0, 'TP': 59, 'score_source': 'continuous', 'auroc': 0.529335071707953, 'ap_0': 0.22218576579286242, 'ap_1': 0.8534346751379787, 'scenario': 'cost_sensitive', 'model': 'SVM', 'outer_fold': 1, 'params': {'C': 0.1, 'kernel': 'linear'}, 'inner_f1_macro': 0.44939986263058634}
Fase 3 LR {'accuracy': 0.6111111111111112, 'precision_0': np.float64(0.2727272727272727), 'precision_1': np.float64(0.8974358974358975), 'recall_0': np.float64(0.6923076923076923), 'recall_1': np.float64(0.5932203389830508), 'f1_0': np.float64(0.391304347826087), 'f1_1': np.float64(0.7142857142857143), 'f1_macro': 0.5527950310559007, 'f1_weighted': 0.6559696342305039, 'precision_macro': 0.5850815850815851, 'recall_macro': 0.6427640156453716, 'balanced_accuracy': 0.6427640156453716, 'mcc': 0.22042312713252596, 'specificity': np.float64(0.6923076923076923), 'sensitivity': np.float64(0.5932203389830508), 'TN': 9, 'FP': 4, 'FN': 24, 'TP': 35, 'score_source': 'continuous', 'auroc': 0.6923076923076924, 'ap_0': 0.2837620498358498, 'ap_1': 0.9242004912633881, 'scenario': 'cost_sensitive', 'model': 'LR', 'outer_fold': 1, 'params': {'C': 0.1, 'max_iter': 1000, 'solver': 'lbfgs'}, 'inner_f1_macro': 0.492756051842549}
Fase 3 XGB {'accuracy': 0.5694444444444444, 'precision_0': np.float64(0.15384615384615385), 'precision_1': np.float64(0.8043478260869565), 'recall_0': np.float64(0.3076923076923077), 'recall_1': np.float64(0.6271186440677966), 'f1_0': np.float64(0.20512820512820512), 'f1_1': np.float64(0.7047619047619048), 'f1_macro': 0.454945054945055, 'f1_weighted': 0.6145502645502645, 'precision_macro': 0.4790969899665552, 'recall_macro': 0.46740547588005216, 'balanced_accuracy': 0.46740547588005216, 'mcc': -0.05220435478825991, 'specificity': np.float64(0.3076923076923077), 'sensitivity': np.float64(0.6271186440677966), 'TN': 4, 'FP': 9, 'FN': 22, 'TP': 37, 'score_source': 'continuous', 'auroc': 0.5984354628422426, 'ap_0': 0.2206846626112881, 'ap_1': 0.897886720378422, 'scenario': 'cost_sensitive', 'model': 'XGB', 'outer_fold': 1, 'params': {'learning_rate': 0.05, 'max_depth': 5, 'n_estimators': 200}, 'inner_f1_macro': 0.49367950978584607}
Fase 3 DT {'accuracy': 0.6388888888888888, 'precision_0': np.float64(0.06666666666666667), 'precision_1': np.float64(0.7894736842105263), 'recall_0': np.float64(0.07692307692307693), 'recall_1': np.float64(0.7627118644067796), 'f1_0': np.float64(0.07142857142857142), 'f1_1': np.float64(0.7758620689655172), 'f1_macro': 0.4236453201970443, 'f1_weighted': 0.6486726874657909, 'precision_macro': 0.4280701754385965, 'recall_macro': 0.41981747066492825, 'balanced_accuracy': 0.41981747066492825, 'mcc': -0.15188831775961306, 'specificity': np.float64(0.07692307692307693), 'sensitivity': np.float64(0.7627118644067796), 'TN': 1, 'FP': 12, 'FN': 14, 'TP': 45, 'score_source': 'continuous', 'auroc': 0.42177314211212513, 'ap_0': 0.1730769230769231, 'ap_1': 0.7954223440022028, 'scenario': 'cost_sensitive', 'model': 'DT', 'outer_fold': 2, 'params': {'max_depth': None, 'min_samples_leaf': 1}, 'inner_f1_macro': 0.5156130711898361}
Fase 3 RF {'accuracy': 0.5694444444444444, 'precision_0': np.float64(0.09090909090909091), 'precision_1': np.float64(0.78), 'recall_0': np.float64(0.15384615384615385), 'recall_1': np.float64(0.6610169491525424), 'f1_0': np.float64(0.11428571428571428), 'f1_1': np.float64(0.7155963302752294), 'f1_macro': 0.41494102228047186, 'f1_weighted': 0.6070263579437891, 'precision_macro': 0.4354545454545455, 'recall_macro': 0.4074315514993481, 'balanced_accuracy': 0.4074315514993481, 'mcc': -0.15459459997091848, 'specificity': np.float64(0.15384615384615385), 'sensitivity': np.float64(0.6610169491525424), 'TN': 2, 'FP': 11, 'FN': 20, 'TP': 39, 'score_source': 'continuous', 'auroc': 0.43350717079530643, 'ap_0': 0.1614486325457874, 'ap_1': 0.8307219576784514, 'scenario': 'cost_sensitive', 'model': 'RF', 'outer_fold': 2, 'params': {'max_depth': None, 'min_samples_leaf': 5, 'n_estimators': 200}, 'inner_f1_macro': 0.49230821135586333}
Fase 3 SVM {'accuracy': 0.8194444444444444, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8194444444444444), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.9007633587786259), 'f1_macro': 0.45038167938931295, 'f1_weighted': 0.7381255301102629, 'precision_macro': 0.4097222222222222, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 13, 'FN': 0, 'TP': 59, 'score_source': 'continuous', 'auroc': 0.470013037809648, 'ap_0': 0.17259594641309367, 'ap_1': 0.826313866807493, 'scenario': 'cost_sensitive', 'model': 'SVM', 'outer_fold': 2, 'params': {'C': 0.1, 'kernel': 'linear'}, 'inner_f1_macro': 0.44939986263058634}
Fase 3 LR {'accuracy': 0.5416666666666666, 'precision_0': np.float64(0.2222222222222222), 'precision_1': np.float64(0.8611111111111112), 'recall_0': np.float64(0.6153846153846154), 'recall_1': np.float64(0.5254237288135594), 'f1_0': np.float64(0.32653061224489793), 'f1_1': np.float64(0.6526315789473685), 'f1_macro': 0.48958109559613316, 'f1_weighted': 0.5937522377372002, 'precision_macro': 0.5416666666666667, 'recall_macro': 0.5704041720990873, 'balanced_accuracy': 0.5704041720990873, 'mcc': 0.10832372170111783, 'specificity': np.float64(0.6153846153846154), 'sensitivity': np.float64(0.5254237288135594), 'TN': 8, 'FP': 5, 'FN': 28, 'TP': 31, 'score_source': 'continuous', 'auroc': 0.6003911342894395, 'ap_0': 0.2477636813622676, 'ap_1': 0.8796690960793229, 'scenario': 'cost_sensitive', 'model': 'LR', 'outer_fold': 2, 'params': {'C': 1, 'max_iter': 1000, 'solver': 'lbfgs'}, 'inner_f1_macro': 0.48986831402972386}
Fase 3 XGB {'accuracy': 0.6111111111111112, 'precision_0': np.float64(0.10526315789473684), 'precision_1': np.float64(0.7924528301886793), 'recall_0': np.float64(0.15384615384615385), 'recall_1': np.float64(0.711864406779661), 'f1_0': np.float64(0.125), 'f1_1': np.float64(0.75), 'f1_macro': 0.4375, 'f1_weighted': 0.6371527777777778, 'precision_macro': 0.44885799404170806, 'recall_macro': 0.43285528031290743, 'balanced_accuracy': 0.43285528031290743, 'mcc': -0.11719924324508467, 'specificity': np.float64(0.15384615384615385), 'sensitivity': np.float64(0.711864406779661), 'TN': 2, 'FP': 11, 'FN': 17, 'TP': 42, 'score_source': 'continuous', 'auroc': 0.41395045632333766, 'ap_0': 0.22409509455227888, 'ap_1': 0.814473626972673, 'scenario': 'cost_sensitive', 'model': 'XGB', 'outer_fold': 2, 'params': {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}, 'inner_f1_macro': 0.4831348878582443}
Fase 3 DT {'accuracy': 0.5, 'precision_0': np.float64(0.15151515151515152), 'precision_1': np.float64(0.7948717948717948), 'recall_0': np.float64(0.38461538461538464), 'recall_1': np.float64(0.5254237288135594), 'f1_0': np.float64(0.21739130434782608), 'f1_1': np.float64(0.6326530612244898), 'f1_macro': 0.42502218278615794, 'f1_weighted': 0.5576752440106478, 'precision_macro': 0.47319347319347316, 'recall_macro': 0.45501955671447203, 'balanced_accuracy': 0.45501955671447203, 'mcc': -0.06944838252120682, 'specificity': np.float64(0.38461538461538464), 'sensitivity': np.float64(0.5254237288135594), 'TN': 5, 'FP': 8, 'FN': 28, 'TP': 31, 'score_source': 'continuous', 'auroc': 0.4784876140808344, 'ap_0': 0.1712324251917012, 'ap_1': 0.8205955656781685, 'scenario': 'cost_sensitive', 'model': 'DT', 'outer_fold': 3, 'params': {'max_depth': 7, 'min_samples_leaf': 5}, 'inner_f1_macro': 0.48701314296925136}
Fase 3 RF {'accuracy': 0.4861111111111111, 'precision_0': np.float64(0.16666666666666666), 'precision_1': np.float64(0.8055555555555556), 'recall_0': np.float64(0.46153846153846156), 'recall_1': np.float64(0.4915254237288136), 'f1_0': np.float64(0.24489795918367346), 'f1_1': np.float64(0.6105263157894737), 'f1_macro': 0.42771213748657355, 'f1_weighted': 0.5445100847356487, 'precision_macro': 0.4861111111111111, 'recall_macro': 0.4765319426336376, 'balanced_accuracy': 0.4765319426336376, 'mcc': -0.036107907233705945, 'specificity': np.float64(0.46153846153846156), 'sensitivity': np.float64(0.4915254237288136), 'TN': 6, 'FP': 7, 'FN': 30, 'TP': 29, 'score_source': 'continuous', 'auroc': 0.4413298565840938, 'ap_0': 0.16249451311692958, 'ap_1': 0.8179746933048389, 'scenario': 'cost_sensitive', 'model': 'RF', 'outer_fold': 3, 'params': {'max_depth': 5, 'min_samples_leaf': 5, 'n_estimators': 100}, 'inner_f1_macro': 0.5167121738406587}
Fase 3 SVM {'accuracy': 0.8194444444444444, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8194444444444444), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.9007633587786259), 'f1_macro': 0.45038167938931295, 'f1_weighted': 0.7381255301102629, 'precision_macro': 0.4097222222222222, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 13, 'FN': 0, 'TP': 59, 'score_source': 'continuous', 'auroc': 0.408735332464146, 'ap_0': 0.15686857419156108, 'ap_1': 0.7790833681839383, 'scenario': 'cost_sensitive', 'model': 'SVM', 'outer_fold': 3, 'params': {'C': 0.1, 'kernel': 'linear'}, 'inner_f1_macro': 0.44939986263058634}
Fase 3 LR {'accuracy': 0.5555555555555556, 'precision_0': np.float64(0.21212121212121213), 'precision_1': np.float64(0.8461538461538461), 'recall_0': np.float64(0.5384615384615384), 'recall_1': np.float64(0.559322033898305), 'f1_0': np.float64(0.30434782608695654), 'f1_1': np.float64(0.673469387755102), 'f1_macro': 0.4889086069210293, 'f1_weighted': 0.6068224391205758, 'precision_macro': 0.5291375291375291, 'recall_macro': 0.5488917861799217, 'balanced_accuracy': 0.5488917861799217, 'mcc': 0.07548737230565958, 'specificity': np.float64(0.5384615384615384), 'sensitivity': np.float64(0.559322033898305), 'TN': 7, 'FP': 6, 'FN': 26, 'TP': 33, 'score_source': 'continuous', 'auroc': 0.42177314211212513, 'ap_0': 0.16094845788306794, 'ap_1': 0.7861352486001316, 'scenario': 'cost_sensitive', 'model': 'LR', 'outer_fold': 3, 'params': {'C': 1, 'max_iter': 1000, 'solver': 'lbfgs'}, 'inner_f1_macro': 0.49559962150088654}
Fase 3 XGB {'accuracy': 0.5, 'precision_0': np.float64(0.10344827586206896), 'precision_1': np.float64(0.7674418604651163), 'recall_0': np.float64(0.23076923076923078), 'recall_1': np.float64(0.559322033898305), 'f1_0': np.float64(0.14285714285714285), 'f1_1': np.float64(0.6470588235294118), 'f1_macro': 0.39495798319327735, 'f1_weighted': 0.5560224089635855, 'precision_macro': 0.43544506816359263, 'recall_macro': 0.3950456323337679, 'balanced_accuracy': 0.3950456323337679, 'mcc': -0.16462468892152052, 'specificity': np.float64(0.23076923076923078), 'sensitivity': np.float64(0.559322033898305), 'TN': 3, 'FP': 10, 'FN': 26, 'TP': 33, 'score_source': 'continuous', 'auroc': 0.438722294654498, 'ap_0': 0.16319840804492103, 'ap_1': 0.8013730714692973, 'scenario': 'cost_sensitive', 'model': 'XGB', 'outer_fold': 3, 'params': {'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 100}, 'inner_f1_macro': 0.5185326425324506}
Fase 3 DT {'accuracy': 0.6527777777777778, 'precision_0': np.float64(0.13333333333333333), 'precision_1': np.float64(0.7894736842105263), 'recall_0': np.float64(0.14285714285714285), 'recall_1': np.float64(0.7758620689655172), 'f1_0': np.float64(0.13793103448275862), 'f1_1': np.float64(0.782608695652174), 'f1_macro': 0.46026986506746626, 'f1_weighted': 0.6572547059803431, 'precision_macro': 0.4614035087719298, 'recall_macro': 0.45935960591133007, 'balanced_accuracy': 0.45935960591133007, 'mcc': -0.07921051985560162, 'specificity': np.float64(0.14285714285714285), 'sensitivity': np.float64(0.7758620689655172), 'TN': 2, 'FP': 12, 'FN': 13, 'TP': 45, 'score_source': 'continuous', 'auroc': 0.4667487684729065, 'ap_0': 0.19841269841269843, 'ap_1': 0.792877233710515, 'scenario': 'cost_sensitive', 'model': 'DT', 'outer_fold': 4, 'params': {'max_depth': None, 'min_samples_leaf': 1}, 'inner_f1_macro': 0.5111570340154474}
Fase 3 RF {'accuracy': 0.6527777777777778, 'precision_0': np.float64(0.07692307692307693), 'precision_1': np.float64(0.7796610169491526), 'recall_0': np.float64(0.07142857142857142), 'recall_1': np.float64(0.7931034482758621), 'f1_0': np.float64(0.07407407407407407), 'f1_1': np.float64(0.7863247863247863), 'f1_macro': 0.4301994301994302, 'f1_weighted': 0.6478315922760367, 'precision_macro': 0.4282920469361148, 'recall_macro': 0.43226600985221675, 'balanced_accuracy': 0.43226600985221675, 'mcc': -0.13938530462494111, 'specificity': np.float64(0.07142857142857142), 'sensitivity': np.float64(0.7931034482758621), 'TN': 1, 'FP': 13, 'FN': 12, 'TP': 46, 'score_source': 'continuous', 'auroc': 0.49014778325123154, 'ap_0': 0.1974676236347725, 'ap_1': 0.8364116912198196, 'scenario': 'cost_sensitive', 'model': 'RF', 'outer_fold': 4, 'params': {'max_depth': None, 'min_samples_leaf': 1, 'n_estimators': 100}, 'inner_f1_macro': 0.5171966922941978}
Fase 3 SVM {'accuracy': 0.8055555555555556, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8055555555555556), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8923076923076924), 'f1_macro': 0.4461538461538462, 'f1_weighted': 0.7188034188034188, 'precision_macro': 0.4027777777777778, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 14, 'FN': 0, 'TP': 58, 'score_source': 'continuous', 'auroc': 0.6157635467980296, 'ap_0': 0.28841600573466103, 'ap_1': 0.8804114843083953, 'scenario': 'cost_sensitive', 'model': 'SVM', 'outer_fold': 4, 'params': {'C': 0.1, 'kernel': 'linear'}, 'inner_f1_macro': 0.4498734455816001}
Fase 3 LR {'accuracy': 0.5277777777777778, 'precision_0': np.float64(0.2222222222222222), 'precision_1': np.float64(0.8333333333333334), 'recall_0': np.float64(0.5714285714285714), 'recall_1': np.float64(0.5172413793103449), 'f1_0': np.float64(0.32), 'f1_1': np.float64(0.6382978723404256), 'f1_macro': 0.4791489361702128, 'f1_weighted': 0.5764066193853429, 'precision_macro': 0.5277777777777778, 'recall_macro': 0.5443349753694582, 'balanced_accuracy': 0.5443349753694582, 'mcc': 0.07018624063435965, 'specificity': np.float64(0.5714285714285714), 'sensitivity': np.float64(0.5172413793103449), 'TN': 8, 'FP': 6, 'FN': 28, 'TP': 30, 'score_source': 'continuous', 'auroc': 0.6268472906403941, 'ap_0': 0.2912341360919878, 'ap_1': 0.8884076828000091, 'scenario': 'cost_sensitive', 'model': 'LR', 'outer_fold': 4, 'params': {'C': 1, 'max_iter': 1000, 'solver': 'lbfgs'}, 'inner_f1_macro': 0.5023082327759821}
Fase 3 XGB {'accuracy': 0.5972222222222222, 'precision_0': np.float64(0.17391304347826086), 'precision_1': np.float64(0.7959183673469388), 'recall_0': np.float64(0.2857142857142857), 'recall_1': np.float64(0.6724137931034483), 'f1_0': np.float64(0.21621621621621623), 'f1_1': np.float64(0.7289719626168224), 'f1_macro': 0.4725940894165193, 'f1_weighted': 0.6292694563722601, 'precision_macro': 0.4849157054125998, 'recall_macro': 0.479064039408867, 'balanced_accuracy': 0.479064039408867, 'mcc': -0.03554176118466, 'specificity': np.float64(0.2857142857142857), 'sensitivity': np.float64(0.6724137931034483), 'TN': 4, 'FP': 10, 'FN': 19, 'TP': 39, 'score_source': 'continuous', 'auroc': 0.5812807881773399, 'ap_0': 0.2400278905701091, 'ap_1': 0.8794569737280379, 'scenario': 'cost_sensitive', 'model': 'XGB', 'outer_fold': 4, 'params': {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 100}, 'inner_f1_macro': 0.49276617537478995}
Fase 3 DT {'accuracy': 0.6619718309859155, 'precision_0': np.float64(0.17647058823529413), 'precision_1': np.float64(0.8148148148148148), 'recall_0': np.float64(0.23076923076923078), 'recall_1': np.float64(0.7586206896551724), 'f1_0': np.float64(0.2), 'f1_1': np.float64(0.7857142857142857), 'f1_macro': 0.4928571428571429, 'f1_weighted': 0.6784708249496981, 'precision_macro': 0.49564270152505446, 'recall_macro': 0.4946949602122016, 'balanced_accuracy': 0.4946949602122016, 'mcc': -0.00961574579050411, 'specificity': np.float64(0.23076923076923078), 'sensitivity': np.float64(0.7586206896551724), 'TN': 3, 'FP': 10, 'FN': 14, 'TP': 44, 'score_source': 'continuous', 'auroc': 0.5006631299734747, 'ap_0': 0.19029561987308463, 'ap_1': 0.8155506747918752, 'scenario': 'cost_sensitive', 'model': 'DT', 'outer_fold': 5, 'params': {'max_depth': None, 'min_samples_leaf': 1}, 'inner_f1_macro': 0.4852891494472892}
Fase 3 RF {'accuracy': 0.647887323943662, 'precision_0': np.float64(0.2), 'precision_1': np.float64(0.8235294117647058), 'recall_0': np.float64(0.3076923076923077), 'recall_1': np.float64(0.7241379310344828), 'f1_0': np.float64(0.24242424242424243), 'f1_1': np.float64(0.7706422018348624), 'f1_macro': 0.5065332221295524, 'f1_weighted': 0.6739262374357348, 'precision_macro': 0.5117647058823529, 'recall_macro': 0.5159151193633953, 'balanced_accuracy': 0.5159151193633953, 'mcc': 0.02736689228925236, 'specificity': np.float64(0.3076923076923077), 'sensitivity': np.float64(0.7241379310344828), 'TN': 4, 'FP': 9, 'FN': 16, 'TP': 42, 'score_source': 'continuous', 'auroc': 0.5318302387267904, 'ap_0': 0.19768301135308414, 'ap_1': 0.8439459956474977, 'scenario': 'cost_sensitive', 'model': 'RF', 'outer_fold': 5, 'params': {'max_depth': None, 'min_samples_leaf': 5, 'n_estimators': 100}, 'inner_f1_macro': 0.5026415417674744}

# Fase 4 — Ensemble
Membros são selecionados por perfis OOF internos, qualidade e diversidade real de erros.

In [98]:
ensemble_candidates = ["KNN", "DT", "RF", "SVM", "MLP", "LR", "XGB", "NB", "AdaBoost"]
ensemble_excluded = {"NC": "sem predict_proba/decision_function", "OPF": "sem predict_proba/decision_function"}
phase4_manifest = {"phase": "ensemble", "excluded_candidates": ensemble_excluded, "members_by_fold": []}
phase4_rows = []
phase4_oof_classes = pd.DataFrame({"y_true": y_array})
phase4_oof_scores = pd.DataFrame({"y_true": y_array})
phase4_inner_oof = []
phase4_profiles = []
phase4_members = []

def ensemble_model(name, params):
    if name not in ensemble_candidates:
        raise ValueError(f"Modelo não calibrável para ensemble probabilístico: {name}")
    base = make_estimator(name, params)
    if name == "SVM":
        return base
    return CalibratedClassifierCV(estimator=base, cv=5, method="sigmoid")


def candidate_inner_profile(X_fit, y_fit, name, params):
    truth = []
    predictions = []
    scores0 = []
    scores1 = []
    indices = []
    for inner_fold, (inner_train, inner_valid) in enumerate(inner_cv.split(X_fit, y_fit), 1):
        preprocessor, encoded_train, encoded_valid, _ = prepare_split(X_fit.iloc[inner_train], y_fit[inner_train], X_fit.iloc[inner_valid])
        model = ensemble_model(name, params)
        model.fit(encoded_train, y_fit[inner_train])
        prediction, score0, score1, score_source = predict_with_score(model, encoded_valid)
        y_outer_train = y_fit
        truth.extend(y_outer_train[inner_valid])
        predictions.extend(prediction)
        indices.extend(inner_valid.tolist())
        if score1 is not None:
            scores0.extend(score0.tolist())
            scores1.extend(score1.tolist())
    truth = np.asarray(truth)
    predictions = np.asarray(predictions)
    score0 = np.asarray(scores0) if scores0 else None
    score1 = np.asarray(scores1) if scores1 else None
    metrics = binary_metrics(truth, predictions, score0, score1)
    metrics.update({
        "model": name,
        "params": dict(params),
        "indices": indices,
        "y_true": truth.tolist(),
        "y_pred": predictions.tolist(),
        "score": score1.tolist() if score1 is not None else None,
        "predictions": predictions.tolist(),
        "errors": (predictions != truth).astype(int).tolist(),
        "score0": score0.tolist() if score0 is not None else None,
        "score1": score1.tolist() if score1 is not None else None,
        "score_source": "predict_proba" if score1 is not None else "unavailable",
    })
    return metrics


for outer_fold, (train_index, test_index) in enumerate(outer_cv.split(X, y_array), 1):
    X_train = X.iloc[train_index]
    X_test = X.iloc[test_index]
    y_train = y_array[train_index]
    y_test = y_array[test_index]
    profiles = []

    params_KNN = []
    f1_val_KNN = []
    acc_val_KNN = []
    for params in ParameterGrid(param_grid_KNN):
        profile = candidate_inner_profile(X_train, y_train, "KNN", params)
        params_KNN.append(dict(params))
        f1_val_KNN.append(profile["f1_macro"])
        acc_val_KNN.append(profile["accuracy"])
    best_params_KNN = params_KNN[int(np.argmax(f1_val_KNN))]
    profile_KNN = candidate_inner_profile(X_train, y_train, "KNN", best_params_KNN)
    profiles.append(profile_KNN)
    print("Fase 4 KNN perfil interno", profile_KNN)

    params_DT = []
    f1_val_DT = []
    acc_val_DT = []
    for params in ParameterGrid(param_grid_DT):
        profile = candidate_inner_profile(X_train, y_train, "DT", params)
        params_DT.append(dict(params))
        f1_val_DT.append(profile["f1_macro"])
        acc_val_DT.append(profile["accuracy"])
    best_params_DT = params_DT[int(np.argmax(f1_val_DT))]
    profile_DT = candidate_inner_profile(X_train, y_train, "DT", best_params_DT)
    profiles.append(profile_DT)
    print("Fase 4 DT perfil interno", profile_DT)

    params_RF = []
    f1_val_RF = []
    acc_val_RF = []
    for params in ParameterGrid(param_grid_RF):
        profile = candidate_inner_profile(X_train, y_train, "RF", params)
        params_RF.append(dict(params))
        f1_val_RF.append(profile["f1_macro"])
        acc_val_RF.append(profile["accuracy"])
    best_params_RF = params_RF[int(np.argmax(f1_val_RF))]
    profile_RF = candidate_inner_profile(X_train, y_train, "RF", best_params_RF)
    profiles.append(profile_RF)
    print("Fase 4 RF perfil interno", profile_RF)

    params_SVM = []
    f1_val_SVM = []
    acc_val_SVM = []
    for params in ParameterGrid(param_grid_SVM):
        profile = candidate_inner_profile(X_train, y_train, "SVM", params)
        params_SVM.append(dict(params))
        f1_val_SVM.append(profile["f1_macro"])
        acc_val_SVM.append(profile["accuracy"])
    best_params_SVM = params_SVM[int(np.argmax(f1_val_SVM))]
    profile_SVM = candidate_inner_profile(X_train, y_train, "SVM", best_params_SVM)
    profiles.append(profile_SVM)
    print("Fase 4 SVM perfil interno", profile_SVM)

    params_MLP = []
    f1_val_MLP = []
    acc_val_MLP = []
    for params in ParameterGrid(param_grid_MLP):
        profile = candidate_inner_profile(X_train, y_train, "MLP", params)
        params_MLP.append(dict(params))
        f1_val_MLP.append(profile["f1_macro"])
        acc_val_MLP.append(profile["accuracy"])
    best_params_MLP = params_MLP[int(np.argmax(f1_val_MLP))]
    profile_MLP = candidate_inner_profile(X_train, y_train, "MLP", best_params_MLP)
    profiles.append(profile_MLP)
    print("Fase 4 MLP perfil interno", profile_MLP)

    params_LR = []
    f1_val_LR = []
    acc_val_LR = []
    for params in ParameterGrid(param_grid_LR):
        profile = candidate_inner_profile(X_train, y_train, "LR", params)
        params_LR.append(dict(params))
        f1_val_LR.append(profile["f1_macro"])
        acc_val_LR.append(profile["accuracy"])
    best_params_LR = params_LR[int(np.argmax(f1_val_LR))]
    profile_LR = candidate_inner_profile(X_train, y_train, "LR", best_params_LR)
    profiles.append(profile_LR)
    print("Fase 4 LR perfil interno", profile_LR)

    params_XGB = []
    f1_val_XGB = []
    acc_val_XGB = []
    for params in ParameterGrid(param_grid_XGB):
        profile = candidate_inner_profile(X_train, y_train, "XGB", params)
        params_XGB.append(dict(params))
        f1_val_XGB.append(profile["f1_macro"])
        acc_val_XGB.append(profile["accuracy"])
    best_params_XGB = params_XGB[int(np.argmax(f1_val_XGB))]
    profile_XGB = candidate_inner_profile(X_train, y_train, "XGB", best_params_XGB)
    profiles.append(profile_XGB)
    print("Fase 4 XGB perfil interno", profile_XGB)

    params_NB = []
    f1_val_NB = []
    acc_val_NB = []
    for params in ParameterGrid(param_grid_NB):
        profile = candidate_inner_profile(X_train, y_train, "NB", params)
        params_NB.append(dict(params))
        f1_val_NB.append(profile["f1_macro"])
        acc_val_NB.append(profile["accuracy"])
    best_params_NB = params_NB[int(np.argmax(f1_val_NB))]
    profile_NB = candidate_inner_profile(X_train, y_train, "NB", best_params_NB)
    profiles.append(profile_NB)
    print("Fase 4 NB perfil interno", profile_NB)

    params_AdaBoost = []
    f1_val_AdaBoost = []
    acc_val_AdaBoost = []
    for params in ParameterGrid(param_grid_AdaBoost):
        profile = candidate_inner_profile(X_train, y_train, "AdaBoost", params)
        params_AdaBoost.append(dict(params))
        f1_val_AdaBoost.append(profile["f1_macro"])
        acc_val_AdaBoost.append(profile["accuracy"])
    best_params_AdaBoost = params_AdaBoost[int(np.argmax(f1_val_AdaBoost))]
    profile_AdaBoost = candidate_inner_profile(X_train, y_train, "AdaBoost", best_params_AdaBoost)
    profiles.append(profile_AdaBoost)
    print("Fase 4 AdaBoost perfil interno", profile_AdaBoost)

    ranked = sorted(profiles, key=lambda item: (item["f1_macro"], item["f1_0"], item["recall_0"], item["balanced_accuracy"], item["mcc"], item["ap_1"]), reverse=True)
    selected = [ranked[0]]
    diversity_matrix = {}
    while len(selected) < 3:
        remaining = [item for item in ranked if item not in selected]
        for candidate in remaining:
            diversity_matrix[candidate["model"]] = [
                float(np.mean(np.asarray(candidate["errors"]) != np.asarray(member["errors"])))
                for member in selected
            ]
        selected.append(max(remaining, key=lambda item: (0.8 * item["f1_macro"] + 0.2 * np.mean(diversity_matrix[item["model"]]), item["f1_0"], item["recall_0"], item["balanced_accuracy"], item["mcc"], item["ap_1"])))
    selected_names = [item["model"] for item in selected]
    assert len(selected_names) == 3
    assert len(set(selected_names)) == 3
    weights = np.ones(3, dtype=float) / 3
    member_models = {}
    member_predictions = {}
    member_score0 = {}
    member_score1 = {}
    selected_params = {item["model"]: item["params"] for item in selected}
    if "KNN" in selected_names:
        preprocessor, encoded_train, encoded_test, _ = prepare_split(X_train, y_train, X_test)
        member_models["KNN"] = ensemble_model("KNN", selected_params["KNN"])
        member_models["KNN"].fit(encoded_train, y_train)
        member_predictions["KNN"], member_score0["KNN"], member_score1["KNN"], _ = predict_with_score(member_models["KNN"], encoded_test)
        print("Fase 4 membro KNN avaliado")
    if "DT" in selected_names:
        preprocessor, encoded_train, encoded_test, _ = prepare_split(X_train, y_train, X_test)
        member_models["DT"] = ensemble_model("DT", selected_params["DT"])
        member_models["DT"].fit(encoded_train, y_train)
        member_predictions["DT"], member_score0["DT"], member_score1["DT"], _ = predict_with_score(member_models["DT"], encoded_test)
        print("Fase 4 membro DT avaliado")
    if "RF" in selected_names:
        preprocessor, encoded_train, encoded_test, _ = prepare_split(X_train, y_train, X_test)
        member_models["RF"] = ensemble_model("RF", selected_params["RF"])
        member_models["RF"].fit(encoded_train, y_train)
        member_predictions["RF"], member_score0["RF"], member_score1["RF"], _ = predict_with_score(member_models["RF"], encoded_test)
        print("Fase 4 membro RF avaliado")
    if "SVM" in selected_names:
        preprocessor, encoded_train, encoded_test, _ = prepare_split(X_train, y_train, X_test)
        member_models["SVM"] = ensemble_model("SVM", selected_params["SVM"])
        member_models["SVM"].fit(encoded_train, y_train)
        member_predictions["SVM"], member_score0["SVM"], member_score1["SVM"], _ = predict_with_score(member_models["SVM"], encoded_test)
        print("Fase 4 membro SVM avaliado")
    if "MLP" in selected_names:
        preprocessor, encoded_train, encoded_test, _ = prepare_split(X_train, y_train, X_test)
        member_models["MLP"] = ensemble_model("MLP", selected_params["MLP"])
        member_models["MLP"].fit(encoded_train, y_train)
        member_predictions["MLP"], member_score0["MLP"], member_score1["MLP"], _ = predict_with_score(member_models["MLP"], encoded_test)
        print("Fase 4 membro MLP avaliado")
    if "LR" in selected_names:
        preprocessor, encoded_train, encoded_test, _ = prepare_split(X_train, y_train, X_test)
        member_models["LR"] = ensemble_model("LR", selected_params["LR"])
        member_models["LR"].fit(encoded_train, y_train)
        member_predictions["LR"], member_score0["LR"], member_score1["LR"], _ = predict_with_score(member_models["LR"], encoded_test)
        print("Fase 4 membro LR avaliado")
    if "XGB" in selected_names:
        preprocessor, encoded_train, encoded_test, _ = prepare_split(X_train, y_train, X_test)
        member_models["XGB"] = ensemble_model("XGB", selected_params["XGB"])
        member_models["XGB"].fit(encoded_train, y_train)
        member_predictions["XGB"], member_score0["XGB"], member_score1["XGB"], _ = predict_with_score(member_models["XGB"], encoded_test)
        print("Fase 4 membro XGB avaliado")
    if "NB" in selected_names:
        preprocessor, encoded_train, encoded_test, _ = prepare_split(X_train, y_train, X_test)
        member_models["NB"] = ensemble_model("NB", selected_params["NB"])
        member_models["NB"].fit(encoded_train, y_train)
        member_predictions["NB"], member_score0["NB"], member_score1["NB"], _ = predict_with_score(member_models["NB"], encoded_test)
        print("Fase 4 membro NB avaliado")
    if "AdaBoost" in selected_names:
        preprocessor, encoded_train, encoded_test, _ = prepare_split(X_train, y_train, X_test)
        member_models["AdaBoost"] = ensemble_model("AdaBoost", selected_params["AdaBoost"])
        member_models["AdaBoost"].fit(encoded_train, y_train)
        member_predictions["AdaBoost"], member_score0["AdaBoost"], member_score1["AdaBoost"], _ = predict_with_score(member_models["AdaBoost"], encoded_test)
        print("Fase 4 membro AdaBoost avaliado")
    predictions = [member_predictions[name] for name in selected_names]
    scores0 = [member_score0[name] for name in selected_names]
    scores1 = [member_score1[name] for name in selected_names]
    majority = (np.sum(predictions, axis=0) >= 2).astype(int)
    probability_score0 = np.average(np.vstack(scores0), axis=0, weights=weights)
    probability_score1 = np.average(np.vstack(scores1), axis=0, weights=weights)
    probability = (probability_score1 >= 0.5).astype(int)
    majority_metrics = binary_metrics(y_test, majority, probability_score0, probability_score1)
    probability_metrics = binary_metrics(y_test, probability, probability_score0, probability_score1)
    phase4_oof_classes.loc[test_index, "majority_class"] = majority
    phase4_oof_classes.loc[test_index, "probability_class"] = probability
    phase4_oof_scores.loc[test_index, "majority_score0"] = probability_score0
    phase4_oof_scores.loc[test_index, "majority_score1"] = probability_score1
    phase4_oof_scores.loc[test_index, "probability_score0"] = probability_score0
    phase4_oof_scores.loc[test_index, "probability_score1"] = probability_score1
    inner_probability = np.mean(np.vstack([np.asarray(item["score1"]) for item in selected]), axis=0)
    phase4_inner_oof.append({
        "outer_fold": outer_fold,
        "indices": selected[0]["indices"],
        "y_true": selected[0]["y_true"],
        "y_pred": (inner_probability >= 0.5).astype(int).tolist(),
        "score": inner_probability.tolist(),
        "members": selected_names,
    })
    member_record = {"outer_fold": outer_fold, "members": selected_names, "weights": weights.tolist(), "profiles": profiles, "diversity_matrix": diversity_matrix, "majority_metrics": majority_metrics, "probability_metrics": probability_metrics, "excluded_candidates": ensemble_excluded}
    phase4_members.append(member_record)
    phase4_manifest["members_by_fold"].append(member_record)
    phase4_profiles.extend([{**profile, "outer_fold": outer_fold} for profile in profiles])
    phase4_rows.extend([{**majority_metrics, "scenario": "ensemble_majority", "outer_fold": outer_fold}, {**probability_metrics, "scenario": "ensemble_probability", "outer_fold": outer_fold}])

Fase 4 KNN perfil interno {'accuracy': 0.8161993769470405, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8161993769470405), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8987993138936535), 'f1_macro': 0.44939965694682676, 'f1_weighted': 0.7335994400004274, 'precision_macro': 0.40809968847352024, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 118, 'FN': 0, 'TP': 524, 'score_source': 'predict_proba', 'auroc': 0.466514102729978, 'ap_0': 0.16847767862280497, 'ap_1': 0.7950644810812072, 'model': 'KNN', 'params': {'n_neighbors': 5, 'weights': 'uniform'}, 'indices': [2, 5, 13, 15, 19, 38, 42, 43, 45, 46, 47, 48, 49, 54, 58, 61, 68, 77, 79, 82, 83, 86, 89, 91, 92, 94, 95, 96, 98, 106, 107, 108, 110, 114, 117, 119, 120, 133, 155, 157, 161, 163, 171, 174, 182, 188, 191, 192, 194, 197, 200, 204, 206, 213, 217, 220, 224, 227, 228, 231, 233, 235, 251, 258, 267, 271, 272, 278, 282, 289, 311, 320, 327, 339, 343, 345, 355, 378, 405, 417, 419, 421, 422, 428, 429, 430, 436, 438, 445, 453, 456, 463, 464, 468, 469, 470, 477, 488, 493, 494, 498, 500, 502, 505, 519, 530, 537, 541, 546, 548, 550, 554, 559, 563, 568, 570, 572, 585, 587, 599, 601, 606, 607, 627, 629, 630, 636, 637, 641, 4, 10, 11, 12, 18, 20, 22, 30, 34, 41, 51, 59, 67, 69, 81, 90, 104, 111, 122, 123, 131, 136, 140, 144, 146, 150, 158, 159, 173, 176, 178, 180, 183, 205, 207, 221, 226, 229, 232, 234, 237, 238, 240, 241, 242, 243, 244, 247, 256, 259, 261, 262, 266, 268, 270, 273, 279, 281, 283, 284, 285, 287, 294, 313, 314, 319, 321, 325, 329, 331, 333, 337, 340, 347, 348, 349, 354, 360, 368, 382, 383, 393, 396, 397, 400, 401, 407, 410, 411, 415, 424, 426, 431, 432, 440, 444, 448, 462, 474, 484, 487, 489, 491, 501, 515, 527, 528, 529, 533, 536, 538, 549, 556, 565, 575, 578, 589, 591, 594, 596, 598, 610, 611, 614, 623, 624, 625, 635, 638, 0, 3, 24, 25, 26, 31, 32, 50, 55, 56, 65, 66, 74, 80, 85, 88, 97, 99, 101, 105, 112, 115, 126, 129, 132, 138, 139, 143, 148, 152, 168, 177, 179, 184, 185, 193, 195, 201, 202, 211, 214, 223, 239, 265, 274, 275, 286, 288, 291, 295, 297, 298, 299, 303, 307, 308, 312, 316, 317, 318, 322, 323, 336, 341, 350, 352, 353, 359, 362, 364, 366, 370, 376, 377, 381, 389, 398, 399, 403, 408, 420, 423, 427, 435, 439, 449, 451, 454, 457, 458, 460, 465, 467, 471, 479, 480, 481, 483, 490, 499, 508, 510, 514, 516, 517, 520, 524, 526, 531, 534, 535, 543, 545, 552, 566, 567, 574, 580, 584, 603, 605, 608, 612, 616, 620, 622, 633, 639, 6, 21, 27, 29, 39, 40, 44, 53, 57, 72, 73, 75, 76, 78, 84, 87, 93, 102, 113, 124, 128, 134, 137, 141, 142, 147, 149, 160, 162, 164, 165, 181, 186, 187, 189, 198, 199, 208, 209, 212, 216, 222, 225, 250, 254, 257, 264, 280, 290, 292, 300, 304, 306, 315, 324, 326, 328, 332, 334, 335, 338, 344, 346, 351, 356, 358, 361, 367, 373, 379, 380, 384, 385, 386, 388, 392, 394, 395, 402, 406, 412, 413, 414, 416, 425, 434, 441, 442, 443, 447, 450, 466, 472, 473, 478, 482, 485, 495, 497, 503, 509, 513, 522, 525, 532, 539, 540, 547, 558, 560, 561, 564, 569, 571, 573, 576, 579, 582, 583, 586, 597, 602, 615, 617, 619, 626, 628, 632, 1, 7, 8, 9, 14, 16, 17, 23, 28, 33, 35, 36, 37, 52, 60, 62, 63, 64, 70, 71, 100, 103, 109, 116, 118, 121, 125, 127, 130, 135, 145, 151, 153, 154, 156, 166, 167, 169, 170, 172, 175, 190, 196, 203, 210, 215, 218, 219, 230, 236, 245, 246, 248, 249, 252, 253, 255, 260, 263, 269, 276, 277, 293, 296, 301, 302, 305, 309, 310, 330, 342, 357, 363, 365, 369, 371, 372, 374, 375, 387, 390, 391, 404, 409, 418, 433, 437, 446, 452, 455, 459, 461, 475, 476, 486, 492, 496, 504, 506, 507, 511, 512, 518, 521, 523, 542, 544, 551, 553, 555, 557, 562, 577, 581, 588, 590, 592, 593, 595, 600, 604, 609, 613, 618, 621, 631, 634, 640], 'y_true': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1], 'y_pred': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'score': [0.7989639810156105, 0.8262249655677125, 0.8215024350989062, 0.8086756645533081, 0.8262249655677125, 0.8086756645533081, 0.8010864272635116, 0.8402435542850517, 0.7993862861966575, 0.8470267954223525, 0.8251053158009958, 0.7993862861966575, 0.8196981849131081, 0.8308155194685364, 0.7993862861966575, 0.82000851077149, 0.8050762972608091, 0.7993862861966575, 0.7942689835765704, 0.8289032937445974, 0.7993862861966575, 0.8196981849131081, 0.8184905754439018, 0.8156752699504374, 0.7993862861966575, 0.8053846539772765, 0.8156752699504374, 0.8196981849131081, 0.7993862861966575, 0.8196981849131081, 0.7993862861966575, 0.7993862861966575, 0.7993862861966575, 0.8418656281636638, 0.7993862861966575, 0.7993862861966575, 0.8107191324148394, 0.8184905754439018, 0.8328397059248065, 0.8262676777922067, 0.7993862861966575, 0.8196981849131081, 0.8196981849131081, 0.811027489131307, 0.8196981849131081, 0.7993862861966575, 0.7993862861966575, 0.8172866561520238, 0.8196981849131081, 0.7939586577181885, 0.7993862861966575, 0.8401143841612161, 0.8184905754439018, 0.8153669132339699, 0.8404227408776836, 0.8481632922481556, 0.8389520221700051, 0.7993862861966575, 0.7993862861966575, 0.8313217705972183, 0.8387728355773731, 0.8196981849131081, 0.8035583619332209, 0.7939586577181885, 0.8501980353064905, 0.8187989321603693, 0.8338973847029887, 0.8341312380398531, 0.82000851077149, 0.8050762972608091, 0.7993862861966575, 0.7993862861966575, 0.7993862861966575, 0.825436139249959, 0.8196981849131081, 0.7993862861966575, 0.8458503693561527, 0.8432895535068923, 0.8196981849131081, 0.8196981849131081, 0.8215024350989062, 0.8149371822821878, 0.8086756645533081, 0.8049151728861084, 0.7993862861966575, 0.7993862861966575, 0.8410510203185144, 0.7993862861966575, 0.8401143841612161, 0.8184905754439018, 0.8170991952936658, 0.825436139249959, 0.8277429008953007, 0.8009042215242456, 0.8265760345086741, 0.8386436654535375, 0.8050762972608091, 0.7993862861966575, 0.7993862861966575, 0.8466925735404771, 0.8386436654535375, 0.8153669132339699, 0.7993862861966575, 0.8196981849131081, 0.7993862861966575, 0.7993862861966575, 0.8312176320461943, 0.82000851077149, 0.8470673667873493, 0.7993862861966575, 0.8282079183008421, 0.804765971402427, 0.8421720186238408, 0.8183014005878221, 0.8381541530025236, 0.8247969590845281, 0.8401143841612161, 0.8418656281636638, 0.8479779444088624, 0.821787586195636, 0.82000851077149, 0.8326605193321746, 0.8340020679160174, 0.8313217705972183, 0.7993862861966575, 0.8404227408776836, 0.82000851077149, 0.8389520221700051, 0.8295219763194469, 0.8240409270352117, 0.8141455846740133, 0.8169828984181133, 0.8169828984181133, 0.8169828984181133, 0.8161389329717436, 0.8169828984181133, 0.8202132965585524, 0.8169828984181133, 0.7852007402921567, 0.7952428691346846, 0.8066668440923047, 0.8169828984181133, 0.7838020439542276, 0.8025748232350637, 0.8169828984181133, 0.7917040380176958, 0.8169828984181133, 0.8235622493403316, 0.8169828984181133, 0.8121563045736447, 0.7952428691346846, 0.8169828984181133, 0.8169828984181133, 0.7917040380176958, 0.7898593709473355, 0.8107367665612504, 0.808747486460882, 0.8404202521276964, 0.8161389329717436, 0.8281108495041574, 0.8169828984181133, 0.7852007402921567, 0.8281108495041574, 0.8123113024950841, 0.838426530909465, 0.8182195753403206, 0.838426530909465, 0.8143919448636613, 0.8123113024950841, 0.8121563045736447, 0.7952428691346846, 0.8143919448636613, 0.8141749556464799, 0.8161389329717436, 0.8457584850098442, 0.7967759428489692, 0.8169828984181133, 0.8316496806211461, 0.8169828984181133, 0.8169828984181133, 0.8169828984181133, 0.7838020439542276, 0.8182195753403206, 0.7917040380176958, 0.7816619091751681, 0.8285356296661293, 0.8161389329717436, 0.8169828984181133, 0.8182195753403206, 0.8296604005207777, 0.8121563045736447, 0.8369923546211571, 0.8325182580642283, 0.8235971297541017, 0.8100756622050677, 0.8143919448636613, 0.8169828984181133, 0.826121569403789, 0.8025748232350637, 0.8182195753403206, 0.8169828984181133, 0.838426530909465, 0.7655110642379962, 0.8121563045736447, 0.8058323676909069, 0.8121563045736447, 0.8169828984181133, 0.8169828984181133, 0.8334535235041682, 0.8005855431346953, 0.7967759428489692, 0.7967759428489692, 0.8169828984181133, 0.8169828984181133, 0.8316496806211461, 0.8228911712633501, 0.8058323676909069, 0.773911142710892, 0.8169828984181133, 0.8208105288947729, 0.8169828984181133, 0.8182195753403206, 0.8230461691847895, 0.8169828984181133, 0.8062480317284081, 0.7926835490712271, 0.8169828984181133, 0.8182195753403206, 0.8281108495041574, 0.8363458885408879, 0.7838020439542276, 0.8169828984181133, 0.8380929728705506, 0.785791324054596, 0.8169828984181133, 0.8121563045736447, 0.8182195753403206, 0.8161389329717436, 0.8290903605576888, 0.8404158110098334, 0.7952083616414156, 0.8264549872975522, 0.8169828984181133, 0.8169828984181133, 0.8369923546211571, 0.7667793285934709, 0.7988565852175465, 0.8143919448636613, 0.7990359921180752, 0.8169828984181133, 0.8402498990770001, 0.8169828984181133, 0.7952428691346846, 0.7936933181180643, 0.8169828984181133, 0.8169828984181133, 0.8239903042122952, 0.8123113024950841, 0.8237108100822679, 0.822643393275896, 0.8242690956712048, 0.8247706078526769, 0.8264946855256328, 0.8124382993904276, 0.8197184949932845, 0.8268351227234829, 0.8223004860211776, 0.8161861009298738, 0.8057514834110746, 0.8069688443433438, 0.8162680717695876, 0.8190016044775943, 0.8057514834110746, 0.8124382993904276, 0.816056097547871, 0.8185262193793703, 0.8057514834110746, 0.8190016044775943, 0.8149721441101063, 0.8057514834110746, 0.8314438486102433, 0.8130567643322866, 0.8090961983428802, 0.8057514834110746, 0.8118394034000174, 0.816056097547871, 0.8313575475163084, 0.8239237139549835, 0.8157107158316498, 0.8130567643322866, 0.816056097547871, 0.816056097547871, 0.8057514834110746, 0.8057514834110746, 0.8057514834110746, 0.8099681775589282, 0.8057514834110746, 0.8199313988660002, 0.8242690956712048, 0.8057514834110746, 0.8157107158316498, 0.816056097547871, 0.8215835955054873, 0.812923356837782, 0.8163990048025894, 0.8132687385540033, 0.8211082104072632, 0.8149721441101063, 0.8130567643322866, 0.8099681775589282, 0.8243990990532076, 0.8163990048025894, 0.8099681775589282, 0.8057514834110746, 0.8130567643322866, 0.8057514834110746, 0.8324878532445459, 0.8130567643322866, 0.8130567643322866, 0.8057514834110746, 0.8130567643322866, 0.8057514834110746, 0.8247706078526769, 0.8060968651272958, 0.8094391055975987, 0.8268351227234829, 0.8130567643322866, 0.8068354368488393, 0.8057514834110746, 0.8057514834110746, 0.8060968651272958, 0.8188716010955914, 0.8157107158316498, 0.8149721441101063, 0.8124382993904276, 0.8130567643322866, 0.8121847851162386, 0.8118394034000174, 0.81921450835031, 0.8118394034000174, 0.8247706078526769, 0.8240561917984891, 0.8247706078526769, 0.8099681775589282, 0.8261517782709143, 0.8212943016866288, 0.8172458987002825, 0.809622795842707, 0.8124382993904276, 0.8057514834110746, 0.8099681775589282, 0.8184542589079001, 0.8341163579588858, 0.8202743061207187, 0.8057514834110746, 0.8190016044775943, 0.8118394034000174, 0.8157107158316498, 0.8270480265961986, 0.8335236419465621, 0.8136116458087217, 0.8202743061207187, 0.8170249237539142, 0.8130567643322866, 0.8200614022480031, 0.823315145615443, 0.8254588968236165, 0.8197184949932845, 0.812570777233933, 0.8223004860211776, 0.8226970067117559, 0.8214535921234845, 0.8099681775589282, 0.8057514834110746, 0.8118394034000174, 0.8162680717695876, 0.8157107158316498, 0.8149721441101063, 0.8266917962622422, 0.8225133898938932, 0.8172458987002825, 0.821310094822735, 0.8057514834110746, 0.8127113826160655, 0.8240561917984891, 0.8057514834110746, 0.7955659256113926, 0.805763578739708, 0.8300665538402392, 0.8039564118580286, 0.8097293998947684, 0.8231194279407493, 0.7955659256113926, 0.805763578739708, 0.7955659256113926, 0.7955659256113926, 0.7971109308692287, 0.7955659256113926, 0.8336990750810387, 0.8300665538402392, 0.805763578739708, 0.802184251507318, 0.802184251507318, 0.7955659256113926, 0.8310125029150612, 0.802184251507318, 0.7955659256113926, 0.7948144472531404, 0.7932694419953045, 0.8133605380867601, 0.8132382258528599, 0.7955659256113926, 0.7865462732404048, 0.8231194279407493, 0.8099420407739281, 0.8115015602454789, 0.8133605380867601, 0.7955659256113926, 0.8231194279407493, 0.802184251507318, 0.7955659256113926, 0.7971109308692287, 0.8101416571763613, 0.8115015602454789, 0.7955659256113926, 0.8057309586708674, 0.7955659256113926, 0.8133605380867601, 0.827608519815944, 0.8133605380867601, 0.7955659256113926, 0.8084095296825714, 0.8216228909000444, 0.8385576513025118, 0.802184251507318, 0.8394052308603728, 0.805763578739708, 0.8231194279407493, 0.818935682743177, 0.7955659256113926, 0.7955659256113926, 0.8366461115756737, 0.7955659256113926, 0.805763578739708, 0.8209056864742106, 0.8377409252311441, 0.7955659256113926, 0.8460807666327945, 0.8099545349404073, 0.8284363206479461, 0.7955659256113926, 0.8174871891613785, 0.7992675650776832, 0.823925195715584, 0.8314675205473782, 0.7971109308692287, 0.8310125029150612, 0.804707890216281, 0.8036807885480229, 0.8159906521206736, 0.8159906521206736, 0.7955659256113926, 0.8099420407739281, 0.8133605380867601, 0.8047658973241003, 0.805763578739708, 0.802184251507318, 0.8099545349404073, 0.805763578739708, 0.7955659256113926, 0.7955659256113926, 0.8162211376808213, 0.7955659256113926, 0.823925195715584, 0.8178505739670996, 0.8093888957322486, 0.8327817348934848, 0.8133605380867601, 0.8200633714284937, 0.8133605380867601, 0.797233243103129, 0.7955659256113926, 0.823925195715584, 0.8156929957535004, 0.823925195715584, 0.8159906521206736, 0.8072601157804131, 0.8008125703355192, 0.7955659256113926, 0.8099545349404073, 0.8054529488987334, 0.7955659256113926, 0.802184251507318, 0.7955659256113926, 0.802184251507318, 0.8301538329253446, 0.7865462732404048, 0.8250262380082717, 0.8102526706149027, 0.8193946352197908, 0.8224506917320467, 0.804707890216281, 0.8099420407739281, 0.8216228909000444, 0.8133605380867601, 0.826111982775239, 0.7955659256113926, 0.7955659256113926, 0.802184251507318, 0.8224506917320467, 0.832322782416871, 0.7971109308692287, 0.8370611142618067, 0.823925195715584, 0.835969452014673, 0.7977652414737859, 0.7977652414737859, 0.8035849889434095, 0.8244331473844599, 0.819860121900079, 0.8542341166824639, 0.835969452014673, 0.8336756538542259, 0.8267269455449069, 0.833442948255162, 0.8277740217201114, 0.7977652414737859, 0.7944243671381345, 0.8336756538542259, 0.8408645777009391, 0.8035849889434095, 0.8117158649638455, 0.7977652414737859, 0.7977652414737859, 0.8232009962357305, 0.7977652414737859, 0.7977652414737859, 0.8000590396342331, 0.819860121900079, 0.8244331473844599, 0.8208253134107923, 0.8341290120605039, 0.7977652414737859, 0.8400714903742669, 0.8297053556668251, 0.8209071980752833, 0.7977652414737859, 0.8116646916055175, 0.8116646916055175, 0.8267269455449069, 0.8244739935641082, 0.833442948255162, 0.8362134498129367, 0.7977652414737859, 0.8268088302093979, 0.7977652414737859, 0.8035849889434095, 0.819860121900079, 0.8035849889434095, 0.8244331473844599, 0.7977652414737859, 0.8244331473844599, 0.8343837816049801, 0.7977652414737859, 0.8470747404762097, 0.819860121900079, 0.856260078021233, 0.8244331473844599, 0.7977652414737859, 0.829042255219582, 0.8341290120605039, 0.819860121900079, 0.8147411360660962, 0.8405438480477525, 0.835969452014673, 0.7977652414737859, 0.8405438480477525, 0.8528228278183413, 0.8244331473844599, 0.8289153432515801, 0.8268763146356092, 0.7885227350040199, 0.8267269455449069, 0.8267677917245553, 0.8387801399485065, 0.8208253134107923, 0.8116646916055175, 0.7977652414737859, 0.8464863263615154, 0.7977652414737859, 0.8277740217201114, 0.833442948255162, 0.8059606717683476, 0.8408645777009391, 0.8300678198805584, 0.8244331473844599, 0.8656078519341601, 0.8244331473844599, 0.8244331473844599, 0.8209071980752833, 0.795389558648848, 0.7977652414737859, 0.7977652414737859, 0.8267269455449069, 0.8244331473844599, 0.804632065118614, 0.8544963699219871, 0.7977652414737859, 0.8244331473844599, 0.8244916868579013, 0.8208253134107923, 0.7977652414737859, 0.7977652414737859, 0.8116646916055175, 0.7977652414737859, 0.8313993566823775, 0.7977652414737859, 0.819860121900079, 0.

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

Fase 4 MLP perfil interno {'accuracy': 0.8161993769470405, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8161993769470405), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8987993138936535), 'f1_macro': 0.44939965694682676, 'f1_weighted': 0.7335994400004274, 'precision_macro': 0.40809968847352024, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 118, 'FN': 0, 'TP': 524, 'score_source': 'predict_proba', 'auroc': 0.4611932332772674, 'ap_0': 0.16835518593426488, 'ap_1': 0.7951824211032998, 'model': 'MLP', 'params': {'alpha': 0.0001, 'hidden_layer_sizes': (32,), 'max_iter': 500}, 'indices': [2, 5, 13, 15, 19, 38, 42, 43, 45, 46, 47, 48, 49, 54, 58, 61, 68, 77, 79, 82, 83, 86, 89, 91, 92, 94, 95, 96, 98, 106, 107, 108, 110, 114, 117, 119, 120, 133, 155, 157, 161, 163, 171, 174, 182, 188, 191, 192, 194, 197, 200, 204, 206, 213, 217, 220, 224, 227, 228, 231, 233, 235, 251, 258, 267, 271, 272, 278, 282, 289, 311, 320, 327, 339, 343, 345, 355, 378, 405, 417, 419, 421, 422, 428, 429, 430, 436, 438, 445, 453, 456, 463, 464, 468, 469, 470, 477, 488, 493, 494, 498, 500, 502, 505, 519, 530, 537, 541, 546, 548, 550, 554, 559, 563, 568, 570, 572, 585, 587, 599, 601, 606, 607, 627, 629, 630, 636, 637, 641, 4, 10, 11, 12, 18, 20, 22, 30, 34, 41, 51, 59, 67, 69, 81, 90, 104, 111, 122, 123, 131, 136, 140, 144, 146, 150, 158, 159, 173, 176, 178, 180, 183, 205, 207, 221, 226, 229, 232, 234, 237, 238, 240, 241, 242, 243, 244, 247, 256, 259, 261, 262, 266, 268, 270, 273, 279, 281, 283, 284, 285, 287, 294, 313, 314, 319, 321, 325, 329, 331, 333, 337, 340, 347, 348, 349, 354, 360, 368, 382, 383, 393, 396, 397, 400, 401, 407, 410, 411, 415, 424, 426, 431, 432, 440, 444, 448, 462, 474, 484, 487, 489, 491, 501, 515, 527, 528, 529, 533, 536, 538, 549, 556, 565, 575, 578, 589, 591, 594, 596, 598, 610, 611, 614, 623, 624, 625, 635, 638, 0, 3, 24, 25, 26, 31, 32, 50, 55, 56, 65, 66, 74, 80, 85, 88, 97, 99, 101, 105, 112, 115, 126, 129, 132, 138, 139, 143, 148, 152, 168, 177, 179, 184, 185, 193, 195, 201, 202, 211, 214, 223, 239, 265, 274, 275, 286, 288, 291, 295, 297, 298, 299, 303, 307, 308, 312, 316, 317, 318, 322, 323, 336, 341, 350, 352, 353, 359, 362, 364, 366, 370, 376, 377, 381, 389, 398, 399, 403, 408, 420, 423, 427, 435, 439, 449, 451, 454, 457, 458, 460, 465, 467, 471, 479, 480, 481, 483, 490, 499, 508, 510, 514, 516, 517, 520, 524, 526, 531, 534, 535, 543, 545, 552, 566, 567, 574, 580, 584, 603, 605, 608, 612, 616, 620, 622, 633, 639, 6, 21, 27, 29, 39, 40, 44, 53, 57, 72, 73, 75, 76, 78, 84, 87, 93, 102, 113, 124, 128, 134, 137, 141, 142, 147, 149, 160, 162, 164, 165, 181, 186, 187, 189, 198, 199, 208, 209, 212, 216, 222, 225, 250, 254, 257, 264, 280, 290, 292, 300, 304, 306, 315, 324, 326, 328, 332, 334, 335, 338, 344, 346, 351, 356, 358, 361, 367, 373, 379, 380, 384, 385, 386, 388, 392, 394, 395, 402, 406, 412, 413, 414, 416, 425, 434, 441, 442, 443, 447, 450, 466, 472, 473, 478, 482, 485, 495, 497, 503, 509, 513, 522, 525, 532, 539, 540, 547, 558, 560, 561, 564, 569, 571, 573, 576, 579, 582, 583, 586, 597, 602, 615, 617, 619, 626, 628, 632, 1, 7, 8, 9, 14, 16, 17, 23, 28, 33, 35, 36, 37, 52, 60, 62, 63, 64, 70, 71, 100, 103, 109, 116, 118, 121, 125, 127, 130, 135, 145, 151, 153, 154, 156, 166, 167, 169, 170, 172, 175, 190, 196, 203, 210, 215, 218, 219, 230, 236, 245, 246, 248, 249, 252, 253, 255, 260, 263, 269, 276, 277, 293, 296, 301, 302, 305, 309, 310, 330, 342, 357, 363, 365, 369, 371, 372, 374, 375, 387, 390, 391, 404, 409, 418, 433, 437, 446, 452, 455, 459, 461, 475, 476, 486, 492, 496, 504, 506, 507, 511, 512, 518, 521, 523, 542, 544, 551, 553, 555, 557, 562, 577, 581, 588, 590, 592, 593, 595, 600, 604, 609, 613, 618, 621, 631, 634, 640], 'y_true': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1], 'y_pred': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'score': [0.8067815046898561, 0.7967704456351479, 0.810849329871381, 0.8230312477457412, 0.7875200073929652, 0.8209142511598065, 0.7947240046855217, 0.8175394531061801, 0.8305173470260397, 0.8141558587503119, 0.7943249494214242, 0.8271317523765254, 0.8176853297246485, 0.80370020698319, 0.8216638294266829, 0.7733920659440956, 0.8135987763940523, 0.8198102378758529, 0.8214223596347967, 0.8254349334711948, 0.8197486616728996, 0.7487341695393567, 0.819799985975021, 0.8255425306005961, 0.8298287705574305, 0.7955931317727885, 0.7584230664535789, 0.8118835530474939, 0.8306281645584914, 0.826741382029431, 0.8234541938437963, 0.8305273629381542, 0.7910603512231041, 0.8005784454213668, 0.8271317523765254, 0.8305240979640505, 0.8114962040888324, 0.8119920653142685, 0.794202272231974, 0.7961043633299315, 0.8284528309578384, 0.8248975885125006, 0.8138540509862613, 0.8307658283884305, 0.8052647819802431, 0.8349209815557321, 0.8276136041997761, 0.7937431267264853, 0.8105446276314503, 0.8152785600436332, 0.8217893060494607, 0.8349899930624292, 0.820232410391141, 0.783847482017411, 0.8221048864021718, 0.797402386048276, 0.8125028782491329, 0.8248127634636608, 0.8261917323781512, 0.772936539542811, 0.831756109976269, 0.8118835530474939, 0.7943028750765968, 0.830148572224927, 0.786684221449274, 0.8265373226310478, 0.7557916459536214, 0.8107843075721568, 0.8044597206732771, 0.8259021522457788, 0.8293312544068151, 0.8302117458109095, 0.8156364643178453, 0.8267442036675756, 0.8265707399140927, 0.8279704605061273, 0.8184911846365839, 0.8352678212644544, 0.821726363055666, 0.826741382029431, 0.8184921522705284, 0.814245095090073, 0.822863264090126, 0.756442245243103, 0.8233776028067915, 0.8273312593779959, 0.7981103628936287, 0.8288158524797952, 0.806637291386051, 0.8164521418032541, 0.7821188218956634, 0.8297487103746833, 0.7467620071323184, 0.8169393333117684, 0.8159942969371906, 0.7905437564858188, 0.8146126412763877, 0.8073012672112114, 0.8264921601702202, 0.7574401624911542, 0.7999344948711062, 0.8071602646762788, 0.8261917323781512, 0.8271404832026856, 0.813499642811542, 0.7956662702390589, 0.8373087200086788, 0.8236855515167608, 0.7974104480718164, 0.8301918435745677, 0.8300599034856069, 0.8230450873293342, 0.8360586186555923, 0.7608409293942444, 0.8098745132109789, 0.7693273875028976, 0.8301590703596935, 0.8005784454213668, 0.8453273231033249, 0.7815230529527373, 0.817647636987885, 0.7892778605738842, 0.7981668683603534, 0.7918598283429018, 0.8305036434905579, 0.7769540931720739, 0.8044597206732771, 0.8125028782491329, 0.8310972644596675, 0.8216433308351692, 0.8176917017647742, 0.8208371693798542, 0.8200142145437237, 0.8109955570293129, 0.8168237276809046, 0.8151942768393615, 0.8143894109470067, 0.811877922355442, 0.7847161920615939, 0.8134033037104966, 0.8153380567243991, 0.8184451102672549, 0.8062941848004567, 0.8272426107771441, 0.8383124299251132, 0.8012065309054993, 0.8073075013074306, 0.8240024281975321, 0.8062772729951926, 0.8038499942272738, 0.7964036098307234, 0.8098925906613443, 0.8153081508431906, 0.8049277737302194, 0.7610587154377122, 0.8145754473970944, 0.8243512134336722, 0.8206069232730748, 0.8701683861745504, 0.8220740717340356, 0.8113755519290857, 0.7591673627291632, 0.8205928659339954, 0.810240976829327, 0.8132621913653791, 0.8184406044351988, 0.8233924906684837, 0.8091603238837599, 0.8112266556650951, 0.8302363164519614, 0.7964036098307234, 0.8091603238837599, 0.7559598266647125, 0.8196888432523689, 0.8208035561412526, 0.8103973481631851, 0.8383384136241464, 0.8248241112184429, 0.8376744829566007, 0.8331081053947986, 0.8062874395907856, 0.8107314489638295, 0.8124337356469036, 0.7955235244142533, 0.7547169902457705, 0.8117129229752628, 0.8150677816292322, 0.8188938312612372, 0.8178242829282694, 0.8254435510286742, 0.8086110362616669, 0.8386070265640967, 0.8135724617633111, 0.8225332232186873, 0.7821064648100441, 0.8231178894070862, 0.8134329470583159, 0.8496228877860071, 0.7508161957791865, 0.8231300906656452, 0.786353571540807, 0.8237894522868426, 0.8138923604467058, 0.818406453214776, 0.7908383009503317, 0.8286566887485328, 0.8151914401715423, 0.8132179165519144, 0.8253755110536789, 0.8261258149752935, 0.823551050605591, 0.8003964384629512, 0.8246549085285574, 0.8368219620932301, 0.7667890343649478, 0.852710082090324, 0.7908383009503317, 0.806894685209928, 0.8179684209575934, 0.8241035402890613, 0.783974372910351, 0.7109008713463988, 0.7634304500101086, 0.8071838704987515, 0.812697910352863, 0.8249114093392237, 0.82064918859053, 0.7643495266296791, 0.8425877384651363, 0.8180104316105382, 0.806615702547953, 0.816221286065056, 0.859614896829607, 0.8057400287017028, 0.8158879665717664, 0.8147870279957564, 0.8142211828994886, 0.8187097028212091, 0.8575295275814095, 0.85178335177322, 0.8187787865524662, 0.8320538907177145, 0.7999238210155324, 0.7882145828632413, 0.7567474888641792, 0.7497189586302015, 0.8311474816258227, 0.8249523280851335, 0.8250231869687825, 0.8300149235237365, 0.82517988762133, 0.825588191559017, 0.7964036098307234, 0.8209507373912824, 0.8121148077365854, 0.8304519977164396, 0.888537409324185, 0.7912254540325517, 0.821567780967351, 0.8266207809955333, 0.8129324700689601, 0.7964059776959553, 0.8240593965221892, 0.81472599829277, 0.8056811059112758, 0.8078080226790076, 0.8015199310452816, 0.8165184877704943, 0.8355102051850833, 0.8103434776646236, 0.8224479241615521, 0.8246467532881179, 0.8042895427649391, 0.81472599829277, 0.8134570193987398, 0.8036083058202956, 0.8040370200167818, 0.8298524184732482, 0.8592701748190624, 0.8012395582472152, 0.8223691239975736, 0.8173269755399794, 0.8185031156625062, 0.8074230858435408, 0.8061556192737435, 0.8163162435639647, 0.8158164660249747, 0.8110987607740027, 0.8104872694289493, 0.8098675021779338, 0.8159549896616667, 0.8151297776591463, 0.8010943617820964, 0.8022247979575411, 0.800537848529918, 0.822451915673214, 0.8069423980076669, 0.82571956315482, 0.8024923764927125, 0.8061530015271924, 0.8041142776812844, 0.8190853864064451, 0.8196352506034612, 0.8063359405157451, 0.8511786766020487, 0.8148126795215245, 0.818446446952829, 0.8246177874617903, 0.8025035863507288, 0.8175138269912873, 0.8055021055773397, 0.8479899775451706, 0.8175138269912873, 0.8096060828050472, 0.8184053264723685, 0.8090789897721657, 0.8076330413747131, 0.8024104404969167, 0.8034212775745411, 0.8142841862633855, 0.8119675677193747, 0.8053703678023009, 0.8154182067469655, 0.8285042591614824, 0.8279435830259692, 0.8078080226790076, 0.8052656096822769, 0.80870507018614, 0.8030315935432126, 0.8054556312772021, 0.8099042900988234, 0.8284209395666384, 0.8157858345410934, 0.836225964628793, 0.81472599829277, 0.8072876343731707, 0.80288723635895, 0.815540028330864, 0.813111754294385, 0.8108964925160226, 0.8052669107841508, 0.8065670515888927, 0.8183723397848279, 0.8084062599161035, 0.8006706901946103, 0.813727327945046, 0.8248686859283991, 0.8198684573180559, 0.81472599829277, 0.8263713201675282, 0.8212371729075214, 0.8280605419861209, 0.8272701579078326, 0.8350406551631824, 0.7989506580920126, 0.8390790392289686, 0.81130344191887, 0.8042897563761319, 0.8247812353888853, 0.8289945594583609, 0.8198349332629817, 0.8160247300110111, 0.8058090624336074, 0.8051593256178394, 0.8267869606658476, 0.8292433274374152, 0.8428838091976297, 0.8373979904538158, 0.8211739747513278, 0.8292867026351708, 0.8191230018913578, 0.8240731155762285, 0.8084062599161035, 0.8017715886067398, 0.8061556192737435, 0.8098071696246428, 0.800822671196389, 0.8179241761337472, 0.8255963712113644, 0.8109695435775258, 0.8332479720759303, 0.8239027683031557, 0.7995469412012172, 0.8020710177089571, 0.8144967796295255, 0.8135762105611765, 0.8153584702103703, 0.8413824251608835, 0.8284499793785965, 0.8018359842203043, 0.8003439618787971, 0.8359370545473892, 0.7977742110506844, 0.834391353407524, 0.8047766866204684, 0.7913416038225993, 0.8071189477933676, 0.7914538680451051, 0.8097441024864466, 0.795576880522534, 0.8432803885434123, 0.8085128462446491, 0.8103975765100303, 0.8099358254387659, 0.8027617483506753, 0.8061016209497638, 0.791083527331579, 0.825643525282602, 0.8205783955344896, 0.7954186210132141, 0.8019611397266123, 0.7988731184478273, 0.8418808535886712, 0.8061417700843576, 0.8304348533486987, 0.8098686708667987, 0.7912003249025299, 0.8187453734579823, 0.8076138538981482, 0.8460712372479232, 0.8023167473529978, 0.8184941751546688, 0.8231231516721884, 0.8142905183655579, 0.7992807611923888, 0.807363365503557, 0.8003243304745589, 0.7989351700785055, 0.7963115764052718, 0.7983999611505646, 0.7866547334103903, 0.7970335865918126, 0.8387111436037518, 0.842347216954102, 0.8031946204475533, 0.826682521669073, 0.7927644192579801, 0.8084620151179166, 0.8178580397048029, 0.7910766953910777, 0.8224448024385763, 0.8233206124675435, 0.8245853234560718, 0.8114424113383544, 0.789997773050865, 0.8165565311552101, 0.8220982836129542, 0.8046167560342207, 0.832073484300993, 0.8080957032869114, 0.7903962774021616, 0.8192605219653248, 0.811498446005386, 0.8100561196755909, 0.8452473395162926, 0.825405128221289, 0.8016570839224846, 0.796556980564979, 0.792052720447864, 0.8058272799787117, 0.8303445986823463, 0.8137781428639927, 0.8249014624994911, 0.8090355840301026, 0.844503348595922, 0.82027618854816, 0.8442830979473328, 0.8207036849784941, 0.812774801039394, 0.7889788133177891, 0.7890703466096994, 0.8258451713508247, 0.815467963494074, 0.8394371213279141, 0.826740989433193, 0.8272735680215437, 0.8177915648450188, 0.793168101907772, 0.8238627760054251, 0.8010273026113393, 0.8006854237358849, 0.8097855827125147, 0.7901054101803058, 0.7959623821290416, 0.8122195820122995, 0.8269097086529198, 0.817451565710998, 0.8289962671062533, 0.8328048788946688, 0.7965110539121538, 0.8369971554285147, 0.8082097955268592, 0.8123781723031834, 0.8135518361584261, 0.8033742669063948, 0.8213424346289218, 0.8038027655665323, 0.8370458302957408, 0.7903253908088075, 0.8010285271603177, 0.7880906665810422, 0.7954743471154672, 0.8115080302853237, 0.812564304606056, 0.7992702474498474, 0.8299367089809861, 0.8007360961909032, 0.8109552142315568, 0.8240342318048388, 0.8117424539103852, 0.8163839241287242, 0.8194546811496812, 0.8172645260347174, 0.798383133102395, 0.8064310540004513, 0.8304826712419937, 0.8076762032073589, 0.8200962255618034, 0.8408007202748337, 0.8084583331486158, 0.8119012926430766, 0.8451635588293085, 0.8190695326023812, 0.8085682952045875, 0.8063849974413395, 0.8153543025127405, 0.8184223441245411, 0.8044533634893277, 0.8190695326023812, 0.811572327525268, 0.8057292185359344, 0.7785030730181002, 0.8097888199831177, 0.8047722891596936, 0.8270205670495482, 0.8056131231853472, 0.8203842428420243, 0.8305627833217988, 0.8091236428109951, 0.8117328045149952, 0.8089262428320175, 0.8330459061643314, 0.8061723019961299, 0.8302367849795557, 0.801956316106307, 0.8192143672548206, 0.8076130907886242, 0.8048914181275567, 0.8215080187431919, 0.8222414483512972, 0.8185446405591066, 0.8216864865780543, 0.8097005101352706, 0.8248031783431335, 0.8150047910729175, 0.8080928590236921, 0.8167711525360133, 0.8006389581630342, 0.8216062558866346, 0.7985261764464499, 0.804914179719329, 0.7947816079000672, 0.8136601910962249, 0.8106621714615129, 0.7752822169437776, 0.8060791086215696, 0.858769141296863, 0.8281588010155696, 0.8117366429383377, 0.801342050526641, 0.8330459061643314, 0.8110639740957459, 0.8138534016507372, 0.814381949535775, 0.8121297884574954, 0.8415938585966549, 0.8246951578657884, 0.8332782394995663, 0.8147052488950305, 0.8143509710107197, 0.820353911095663, 0.815332122301512, 0.809620214411984, 0.8185358464166809, 0.8142834846071049, 0.810828526020917, 0.8172053467655733, 0.8072446909512461, 0.8064190992771414, 0.8070896959851913, 0.7949287882557675, 0.8216864865780543, 0.8108279534932189, 0.811572327525268, 0.806720135497428, 0.8206409427505346, 0.8309637269775528, 0.8131885742968175, 0.8251437366823297, 0.8094256100110624, 0.813433025116783, 0.804559652773496, 0.8248380593365304, 0.8203001024158978, 0.8238906628528018, 0.8064046251238851, 0.828082102941759, 0.8061054288781652, 0.8101046855845506, 0.826568145250226, 0.8018401579094891, 0.8133601272522742, 0.8123509576173644, 0.8022108919612665, 0.7985299633419128, 0.8215105065536905, 0.8070699666253466, 0.8288903926749291, 0.77

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

Fase 4 MLP perfil interno {'accuracy': 0.8161993769470405, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8161993769470405), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8987993138936535), 'f1_macro': 0.44939965694682676, 'f1_weighted': 0.7335994400004274, 'precision_macro': 0.40809968847352024, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 118, 'FN': 0, 'TP': 524, 'score_source': 'predict_proba', 'auroc': 0.48162763617544313, 'ap_0': 0.18370325218314082, 'ap_1': 0.808831537396015, 'model': 'MLP', 'params': {'alpha': 0.0001, 'hidden_layer_sizes': (32,), 'max_iter': 500}, 'indices': [3, 5, 13, 15, 20, 40, 43, 44, 46, 47, 48, 49, 50, 57, 59, 61, 63, 75, 81, 82, 85, 86, 88, 91, 92, 94, 95, 98, 99, 101, 102, 106, 110, 114, 116, 118, 119, 132, 143, 159, 164, 166, 171, 173, 182, 187, 189, 190, 195, 200, 203, 207, 209, 212, 217, 220, 224, 227, 228, 232, 233, 234, 256, 265, 266, 271, 272, 280, 281, 289, 308, 317, 325, 337, 341, 352, 360, 389, 409, 415, 418, 420, 426, 427, 428, 429, 437, 438, 444, 452, 456, 461, 464, 467, 468, 470, 477, 488, 493, 494, 498, 500, 502, 504, 507, 530, 537, 542, 546, 548, 550, 553, 559, 563, 568, 570, 574, 584, 587, 597, 601, 605, 609, 627, 629, 632, 636, 637, 641, 4, 10, 11, 12, 19, 21, 23, 26, 27, 33, 52, 53, 69, 70, 84, 90, 108, 112, 120, 121, 130, 137, 141, 146, 148, 151, 154, 162, 174, 177, 178, 180, 183, 194, 208, 221, 226, 229, 231, 235, 236, 238, 239, 242, 243, 244, 245, 246, 254, 258, 259, 264, 267, 268, 270, 274, 276, 282, 283, 284, 285, 286, 294, 309, 312, 318, 323, 327, 329, 331, 335, 338, 342, 345, 346, 347, 358, 359, 366, 379, 380, 391, 393, 394, 398, 399, 406, 410, 413, 417, 422, 425, 430, 431, 443, 447, 453, 463, 475, 483, 486, 489, 490, 501, 516, 525, 528, 529, 533, 536, 538, 549, 555, 566, 575, 578, 589, 591, 594, 596, 599, 610, 612, 614, 622, 623, 624, 635, 638, 0, 2, 28, 29, 30, 32, 34, 38, 51, 58, 67, 68, 74, 76, 79, 89, 97, 100, 103, 105, 111, 124, 126, 128, 131, 136, 139, 140, 145, 153, 170, 176, 179, 184, 185, 191, 197, 204, 205, 213, 216, 223, 241, 263, 273, 275, 287, 288, 292, 295, 296, 297, 301, 303, 306, 307, 314, 315, 316, 320, 321, 333, 334, 339, 348, 351, 353, 357, 362, 365, 368, 369, 374, 375, 387, 395, 396, 397, 402, 407, 419, 421, 433, 435, 439, 448, 450, 454, 457, 458, 460, 465, 466, 472, 479, 480, 482, 487, 491, 499, 509, 511, 515, 517, 518, 520, 524, 527, 531, 534, 535, 540, 544, 552, 565, 567, 572, 579, 583, 603, 604, 607, 611, 616, 620, 621, 633, 639, 6, 22, 25, 31, 41, 42, 45, 55, 60, 72, 73, 77, 78, 80, 83, 87, 93, 96, 113, 122, 127, 133, 138, 142, 144, 149, 150, 163, 165, 167, 168, 181, 186, 188, 192, 196, 199, 201, 202, 211, 215, 222, 225, 249, 252, 255, 262, 278, 290, 291, 298, 302, 305, 313, 322, 324, 326, 330, 332, 336, 343, 344, 349, 350, 354, 356, 361, 371, 376, 377, 378, 381, 382, 383, 386, 390, 392, 401, 404, 405, 411, 412, 414, 423, 424, 434, 440, 441, 442, 446, 449, 469, 471, 473, 478, 481, 484, 495, 496, 503, 510, 514, 521, 526, 532, 539, 541, 547, 558, 560, 561, 564, 569, 571, 573, 576, 581, 582, 585, 586, 598, 602, 615, 617, 619, 626, 628, 631, 1, 7, 8, 9, 14, 16, 17, 18, 24, 35, 36, 37, 39, 54, 56, 62, 64, 65, 66, 71, 104, 107, 109, 115, 117, 123, 125, 129, 134, 135, 147, 152, 155, 156, 157, 158, 160, 161, 169, 172, 175, 193, 198, 206, 210, 214, 218, 219, 230, 237, 240, 247, 248, 250, 251, 253, 257, 260, 261, 269, 277, 279, 293, 299, 300, 304, 310, 311, 319, 328, 340, 355, 363, 364, 367, 370, 372, 373, 384, 385, 388, 400, 403, 408, 416, 432, 436, 445, 451, 455, 459, 462, 474, 476, 485, 492, 497, 505, 506, 508, 512, 513, 519, 522, 523, 543, 545, 551, 554, 556, 557, 562, 577, 580, 588, 590, 592, 593, 595, 600, 606, 608, 613, 618, 625, 630, 634, 640], 'y_true': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1], 'y_pred': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'score': [0.8253149222273557, 0.8381931454430186, 0.8245663603486149, 0.8294126793427248, 0.8242816918218553, 0.775239460320619, 0.8311988459040791, 0.7931912895410079, 0.8346930295016026, 0.8081515283475141, 0.8312188809269049, 0.8092028115198081, 0.8258337350481387, 0.775112362503937, 0.7723366311912122, 0.807426039750338, 0.8303328519873043, 0.8221572117140956, 0.8136855496095062, 0.8289099054668773, 0.8190188094917057, 0.830618775211741, 0.8051075992796127, 0.8354372260526881, 0.8286347551336182, 0.8338434112520858, 0.7823008939081945, 0.837557429316482, 0.8388437609410475, 0.7959282138289111, 0.7798704987889158, 0.8364529396985334, 0.8377249686140132, 0.7996367939453976, 0.8074001356799061, 0.8372884892035787, 0.8460063680494925, 0.8355467295030083, 0.8114177464763808, 0.8092028115198081, 0.8190188094917057, 0.8173380924136697, 0.8360913022276509, 0.8066919801114112, 0.8242336203464682, 0.8399862209916809, 0.8409322371425481, 0.8272889197631026, 0.765815538119808, 0.7450615353478753, 0.8360155384401574, 0.8014917778151285, 0.8190188094917057, 0.8366190790497658, 0.829190707180288, 0.8384425314512463, 0.8271912230709013, 0.8386767680155696, 0.8277639620836255, 0.8379649654091305, 0.6750945085125443, 0.7868794790899653, 0.8372376489798828, 0.831098458317927, 0.7722722306405716, 0.791346976254738, 0.8121862959376802, 0.8279359783217675, 0.8124316267930831, 0.8339171505756641, 0.8294370461290119, 0.7753303486374965, 0.8358957937339863, 0.8258003335849153, 0.8376598869091285, 0.7875642640647261, 0.8205851632627997, 0.8003867601877648, 0.8236534170244875, 0.83133280150583, 0.8286233055962665, 0.8219726118955162, 0.6432409476513105, 0.7886277338802692, 0.8202725770460984, 0.8163073713838989, 0.8247833152682492, 0.8283777573718982, 0.8360895217942611, 0.8265331217125004, 0.7052534677308467, 0.8374099632520032, 0.827095220916483, 0.8267211973270643, 0.8234123890205135, 0.7762266565295188, 0.8322291035779553, 0.7973860789651003, 0.7857426033326143, 0.8411148621016038, 0.8010887006674295, 0.8219164858654677, 0.8071045398871618, 0.8319853848082414, 0.7924367031018898, 0.8153107158914908, 0.8321628128257931, 0.7960802480278273, 0.7488361727500251, 0.8399962933492601, 0.8271811267974277, 0.7702661262112721, 0.830382802346182, 0.7902866791649537, 0.831675959624012, 0.7910160199332961, 0.8092028115198081, 0.8200180806482417, 0.8453971408930802, 0.8425732940852141, 0.7336239715416297, 0.8204396516409774, 0.7840700665706666, 0.775112362503937, 0.8366437606076559, 0.8375215640183986, 0.7947634411886566, 0.8469070489689365, 0.8261346180370479, 0.8212170872547979, 0.8214961314752486, 0.8122823552533711, 0.818605950330781, 0.8231546280996973, 0.8118865910253437, 0.783722857651574, 0.8256061920898949, 0.8083310117771273, 0.8156295937300552, 0.7928419228667387, 0.8214167219242853, 0.7911503666263106, 0.8204854607365769, 0.8044097124223739, 0.8228609078977597, 0.8184878533393217, 0.8097622983242772, 0.8108198774062156, 0.8212941019043989, 0.8130148393284191, 0.8163471890653126, 0.7886997841525738, 0.8325881414622971, 0.8241039694772582, 0.7994164008986233, 0.8290877243703519, 0.8197568227574277, 0.8201382991067714, 0.812170489320259, 0.817874328489499, 0.8006046618073686, 0.8112089104302507, 0.8278445303111864, 0.8181111046209905, 0.8294079741792869, 0.8057837805698774, 0.8184580303483104, 0.8101925615692295, 0.8251215914837561, 0.8200979434897745, 0.8040528061723491, 0.7912518212741473, 0.8215612815757695, 0.823621415340693, 0.8428290919650848, 0.8172519042231225, 0.8127681293795701, 0.7591317560121068, 0.8089298677758675, 0.8309274577759768, 0.8298627341327901, 0.8025016865196999, 0.8349784982401556, 0.8090575550762656, 0.812170489320259, 0.8219222783578642, 0.77999761704124, 0.7984384558944418, 0.8282326900181511, 0.8149490453698881, 0.8120200289409315, 0.8282517472260607, 0.8201551967486864, 0.8276336191731499, 0.8291772846966184, 0.8268634553734712, 0.8192820424090866, 0.8217200319597897, 0.8249811679037758, 0.8011214375046439, 0.8167847681825267, 0.8210589625088746, 0.8144356738577464, 0.8094586949188948, 0.8227750455818248, 0.8202130432510707, 0.8059978539458108, 0.8092388725944136, 0.7915253931689273, 0.8069868687136358, 0.796427484427948, 0.8148186968414957, 0.8297692380872652, 0.8288181394868452, 0.8348461297802711, 0.81567558375336, 0.7912518212741473, 0.8009240867649379, 0.7996747948190874, 0.7938886499205157, 0.8057393444507008, 0.8210034144686823, 0.813315745743286, 0.8228869632363868, 0.8277937660437727, 0.8259956037434495, 0.81567558375336, 0.8252925744178056, 0.8151856468389822, 0.8162002415571841, 0.8010634002470637, 0.8257868767676875, 0.811373425476878, 0.8120540407518053, 0.820688320292717, 0.8249035881018985, 0.8017109169403571, 0.8258418575457285, 0.8373449177977339, 0.8372185470319271, 0.825085163404809, 0.7973573900705899, 0.7843992103529278, 0.8200553069855208, 0.8197568227574277, 0.8294039521813439, 0.7694002922929077, 0.8121179661623572, 0.8207762822987364, 0.8004076886823253, 0.8216273886629277, 0.8330634355215478, 0.8334247239557315, 0.8208659418920161, 0.8206630940615266, 0.827110541278594, 0.8333140845507833, 0.812170489320259, 0.8182249731544928, 0.8288412148086985, 0.8279663430962566, 0.8184757341098742, 0.8148054655840271, 0.804887892560523, 0.8178771258419039, 0.8106872246595145, 0.8175206182875143, 0.805589884025548, 0.817536028733465, 0.8130681734345011, 0.8159523344088833, 0.8220716268280096, 0.8151929444718384, 0.8171184695554906, 0.8140896125730533, 0.814315865772652, 0.8215612568572308, 0.8030432956780806, 0.8202750456587639, 0.8128385626754628, 0.8112105678661864, 0.8200018428643794, 0.8126759524859226, 0.820268783358215, 0.8172872080113732, 0.817455977817717, 0.8138601572880072, 0.794351378920499, 0.8181643192375396, 0.8086411074052732, 0.8170794084756375, 0.8265584753470282, 0.821924415864643, 0.820520496699215, 0.7988866786609257, 0.8196673762063327, 0.8219272234492848, 0.8142993350647618, 0.813995781792974, 0.8148402097452079, 0.8177400593010506, 0.8049010495583027, 0.823677906161574, 0.8177023611374171, 0.8168126154430674, 0.820390058044856, 0.8193163299245259, 0.8052797591877144, 0.8112941775289675, 0.8210533634325659, 0.8162668870017077, 0.811299724789418, 0.817644084422707, 0.8193163299245259, 0.8160582352631964, 0.8192903110475367, 0.7974293253062655, 0.8147489634545153, 0.8177956514372303, 0.8191118303520177, 0.8012002244376297, 0.8249014795993073, 0.818974671459505, 0.8191184578798303, 0.8159944325750932, 0.8189011542560742, 0.8166156427154643, 0.8171113480593422, 0.8148394738177513, 0.8109285701165831, 0.8269322372271952, 0.8214415392152086, 0.8186399675999109, 0.8182440197081708, 0.8161298725061682, 0.8027895593015524, 0.8358353866422139, 0.8118286413308186, 0.8129056679087074, 0.8151781332625614, 0.8176600652215782, 0.8127307021154107, 0.8143637172104334, 0.8072059330022932, 0.8221778808209621, 0.8182249380827498, 0.8139179125715081, 0.8177948639221236, 0.8237250084476413, 0.8170909453030564, 0.8166189400723601, 0.8195010565848252, 0.8172095700509348, 0.8214142009286366, 0.8204012248967405, 0.8147807131835412, 0.8230225891103531, 0.7942603762549874, 0.8072855215187944, 0.826740071081651, 0.8214789944751668, 0.8126885955578983, 0.8172823871652941, 0.8082547371890364, 0.8061908430592835, 0.8182458443655625, 0.8311414438650424, 0.8187769665115319, 0.8128682142935215, 0.8235721058741836, 0.8249228195282583, 0.8084729710805607, 0.7879638725295364, 0.8140872398259317, 0.7909823652345258, 0.8096072133879078, 0.809396893073387, 0.8226117910296684, 0.8157091942041644, 0.807968533009892, 0.8102364399655354, 0.8171001565247156, 0.8210739718665021, 0.8140896125730533, 0.8103235204865008, 0.8099644391816442, 0.8048385968243202, 0.8097218798437339, 0.8060204524793877, 0.8069844332556153, 0.7903536487599985, 0.7882330534067098, 0.7928568561375092, 0.8044417830536575, 0.7853733431267363, 0.8265978084977637, 0.8175136020413319, 0.8101607398532179, 0.8430255774983051, 0.8170023571449777, 0.8308907827051394, 0.775100900606686, 0.7987095605366978, 0.8345075052996489, 0.8119261910730856, 0.7901270643635288, 0.803915315122272, 0.8261476388194792, 0.8178342666727237, 0.7889702621781639, 0.7974902810505127, 0.8313126881052358, 0.7845748365339305, 0.7883270639658521, 0.803040113293948, 0.7964126717086264, 0.8370604467826478, 0.7865214457855834, 0.7969727712792466, 0.7921736185811685, 0.7994054450032235, 0.8443227675174647, 0.8301386913085791, 0.8018237742166885, 0.8122165970048242, 0.8140037267573481, 0.8108897042336537, 0.828163836403047, 0.8254078351941336, 0.7859101894474494, 0.8100755281328418, 0.8375260226702459, 0.8198765331847662, 0.8564434312018303, 0.8300499575259078, 0.7921607626327547, 0.8224845599739312, 0.794101995570738, 0.8058705897714079, 0.7855936264742132, 0.7932184257193651, 0.7866855086338818, 0.8272838787665876, 0.8349504437104145, 0.7884847803718962, 0.7947861354289459, 0.8392369977022911, 0.8057236757472588, 0.823539788265176, 0.8247462084856615, 0.7853010636546065, 0.7843928543427323, 0.8426239857418277, 0.8210134881434279, 0.8214594265532572, 0.8339378928328024, 0.7932608789046915, 0.7935877314152946, 0.8347995976909244, 0.8397375939075191, 0.7858413729309128, 0.8116796592810779, 0.8034126623687788, 0.8147457574527719, 0.8012489785942337, 0.8347995976909244, 0.8286725131642496, 0.7857020597583038, 0.7652132605581461, 0.8007036100164475, 0.8356378881649036, 0.8332909093461212, 0.7963147453933221, 0.8386012713620156, 0.7928062846047059, 0.831558408774773, 0.7909342721567932, 0.7875918005307, 0.7847602675630674, 0.8166453225126175, 0.8132835437057236, 0.8149701650292988, 0.7503704522758925, 0.8055480824783819, 0.8140547855398633, 0.7947368616873017, 0.8491257045519804, 0.8378846604223726, 0.83004201029194, 0.7861418984451354, 0.7859101894474494, 0.7809107935628692, 0.8132552258344097, 0.835362802121965, 0.8108515455504666, 0.8347995976909244, 0.7886572668502121, 0.797163180604338, 0.8383787676125356, 0.796086553293652, 0.8158281165565959, 0.8165836901755841, 0.8228580083687952, 0.7870770048560145, 0.7933591727438067, 0.8405934418411123, 0.804563143792374, 0.8061956698011794, 0.8315254028371923, 0.8254078351941336, 0.7840859727667014, 0.7962857657390915, 0.7873872269449299, 0.8161569473927983, 0.8218692563205326, 0.8087621804627533, 0.8118961736146215, 0.815765947731151, 0.8291797073853745, 0.8021853759148166, 0.7923664847951427, 0.8223766511864833, 0.7943754133289053, 0.8153723936278305, 0.7840046112818415, 0.8126863389647745, 0.7636547021100872, 0.8346353434702483, 0.8209618385662194, 0.823271366749076, 0.8211172140062162, 0.8124588824583121, 0.7719580686907317, 0.7392859194129511, 0.836758652641379, 0.8144022369204171, 0.8272246501565101, 0.8225979911229968, 0.8356032937417396, 0.8211172140062162, 0.8074550998205208, 0.8151692811772568, 0.8053957132416825, 0.8097968764213256, 0.8182981590793362, 0.829131901829631, 0.804664884602978, 0.8288167574065133, 0.8214331875711889, 0.8195177406486254, 0.8217974549266069, 0.8038567278432776, 0.7891400882290158, 0.8095539853374938, 0.7407284499303435, 0.7368136398150016, 0.8336067601365882, 0.8210418750293945, 0.8000306095150691, 0.8095539853374938, 0.8208482237299558, 0.830202649045809, 0.8201987705253344, 0.799254188820733, 0.7979996486345227, 0.8093428153403049, 0.8284632221161635, 0.8238127334482611, 0.8045169743594396, 0.817790496281589, 0.7777624711106951, 0.8293320280736504, 0.8133179940138666, 0.8229320941698584, 0.8288167574065133, 0.8169837231574062, 0.8127986375232126, 0.8156339265850224, 0.8348151370161727, 0.8198372306522923, 0.8302930391733294, 0.8201775976409824, 0.7952704991199564, 0.8315091855044704, 0.7933126977293985, 0.8066705877571666, 0.8301418589898472, 0.8197204034838229, 0.7916430333615193, 0.7965166693373906, 0.8231912349312047, 0.7609696547917633, 0.8278246948369583, 0.8213701102403521, 0.7614537968868952, 0.8319922916747069, 0.8194419167055702, 0.8255531733825731, 0.8176674101841881, 0.7388629807130511, 0.8205760836897881, 0.8049029202012641, 0.8366118817326896, 0.829131901829631, 0.8172710765862646, 0.6570886704669432, 0.8215928090707948, 0.8207423062536521, 0.806867846568602, 0.8193904314794619, 0.8214111925978775, 0.786163606854301, 0.8213938586291082, 0.825749194257971, 0.795356558198212, 0.7855582853048144, 0.8157845994560873, 

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

Fase 4 MLP perfil interno {'accuracy': 0.8161993769470405, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8161993769470405), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8987993138936535), 'f1_macro': 0.44939965694682676, 'f1_weighted': 0.7335994400004274, 'precision_macro': 0.40809968847352024, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 118, 'FN': 0, 'TP': 524, 'score_source': 'predict_proba', 'auroc': 0.46106385043343256, 'ap_0': 0.17345736115258684, 'ap_1': 0.8193833830165317, 'model': 'MLP', 'params': {'alpha': 0.0001, 'hidden_layer_sizes': (32,), 'max_iter': 500}, 'indices': [2, 5, 13, 15, 19, 39, 42, 43, 45, 46, 47, 48, 49, 54, 58, 61, 69, 77, 80, 82, 83, 85, 90, 91, 92, 93, 94, 96, 98, 106, 107, 109, 111, 113, 116, 118, 119, 131, 153, 157, 161, 163, 171, 174, 182, 188, 190, 192, 194, 197, 200, 204, 206, 213, 217, 220, 224, 227, 228, 229, 230, 234, 254, 258, 267, 271, 272, 278, 279, 287, 310, 318, 328, 331, 340, 344, 361, 376, 404, 416, 418, 420, 422, 428, 430, 431, 438, 439, 446, 454, 457, 461, 464, 467, 469, 470, 476, 487, 493, 494, 497, 499, 501, 503, 518, 530, 537, 542, 545, 547, 549, 552, 561, 564, 568, 571, 573, 586, 588, 600, 602, 605, 607, 627, 629, 630, 636, 637, 641, 4, 10, 11, 12, 18, 20, 23, 30, 31, 36, 51, 60, 67, 68, 79, 89, 104, 110, 120, 121, 129, 135, 139, 145, 147, 150, 155, 159, 173, 176, 178, 180, 183, 205, 208, 221, 226, 231, 233, 235, 236, 238, 239, 241, 242, 243, 244, 245, 256, 260, 261, 262, 266, 268, 270, 273, 280, 281, 282, 283, 285, 288, 293, 311, 312, 319, 323, 326, 330, 333, 335, 338, 341, 348, 349, 350, 354, 359, 367, 382, 383, 393, 396, 397, 400, 401, 407, 408, 411, 415, 425, 427, 432, 433, 436, 445, 449, 463, 473, 482, 486, 488, 490, 500, 515, 526, 528, 529, 533, 536, 538, 550, 551, 558, 576, 580, 590, 592, 595, 597, 598, 610, 611, 614, 623, 624, 625, 635, 638, 0, 3, 25, 26, 27, 32, 33, 50, 55, 57, 65, 66, 74, 81, 86, 87, 97, 99, 101, 105, 115, 124, 127, 130, 134, 137, 138, 143, 144, 152, 170, 177, 179, 184, 185, 193, 195, 201, 202, 212, 214, 223, 240, 265, 274, 277, 286, 290, 291, 294, 295, 297, 299, 304, 308, 309, 314, 315, 317, 320, 321, 322, 337, 342, 345, 351, 353, 358, 362, 364, 366, 369, 377, 378, 380, 390, 398, 399, 403, 409, 421, 423, 424, 437, 440, 441, 450, 452, 455, 458, 460, 465, 466, 471, 478, 479, 481, 489, 492, 498, 508, 510, 514, 516, 517, 520, 524, 527, 531, 534, 535, 540, 544, 556, 566, 567, 575, 581, 585, 604, 606, 608, 612, 616, 620, 621, 633, 639, 6, 22, 28, 29, 40, 41, 44, 53, 56, 72, 73, 75, 76, 78, 84, 88, 95, 103, 112, 122, 126, 132, 136, 140, 142, 148, 149, 160, 162, 164, 166, 181, 186, 187, 189, 198, 199, 209, 210, 211, 216, 222, 225, 250, 253, 257, 264, 284, 289, 296, 298, 305, 307, 313, 324, 325, 327, 329, 334, 336, 339, 346, 347, 352, 355, 357, 360, 371, 372, 379, 381, 384, 385, 387, 389, 392, 394, 395, 402, 406, 412, 413, 414, 417, 426, 435, 442, 443, 444, 448, 451, 468, 472, 474, 477, 480, 483, 495, 502, 504, 509, 513, 521, 525, 532, 539, 541, 548, 554, 560, 562, 565, 569, 570, 572, 574, 577, 579, 582, 584, 587, 603, 615, 617, 619, 626, 628, 632, 1, 7, 8, 9, 14, 16, 17, 21, 24, 34, 35, 37, 38, 52, 59, 62, 63, 64, 70, 71, 100, 102, 108, 114, 117, 123, 125, 128, 133, 141, 146, 151, 154, 156, 158, 165, 167, 168, 169, 172, 175, 191, 196, 203, 207, 215, 218, 219, 232, 237, 246, 247, 248, 249, 251, 252, 255, 259, 263, 269, 275, 276, 292, 300, 301, 302, 303, 306, 316, 332, 343, 356, 363, 365, 368, 370, 373, 374, 375, 386, 388, 391, 405, 410, 419, 429, 434, 447, 453, 456, 459, 462, 475, 484, 485, 491, 496, 505, 506, 507, 511, 512, 519, 522, 523, 543, 546, 553, 555, 557, 559, 563, 578, 583, 589, 591, 593, 594, 596, 599, 601, 609, 613, 618, 622, 631, 634, 640], 'y_true': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1], 'y_pred': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'score': [0.8242376292394995, 0.8095301082660399, 0.8192937872375561, 0.828644025601957, 0.836448480854721, 0.8430149425999176, 0.7810843322739116, 0.8130640118627026, 0.830768757509183, 0.8443174948909032, 0.8252869481457363, 0.8444335662608525, 0.8334827660311184, 0.8415807888289908, 0.8352986050894579, 0.7987731241037648, 0.825506815961025, 0.8378130018719265, 0.8209673584985493, 0.7415519703655398, 0.83925206964149, 0.8437509427263918, 0.8204746207947432, 0.7834346473441631, 0.8094409819758244, 0.8124284803710303, 0.8450202292215756, 0.8302687145255975, 0.8055456280441511, 0.8255853908795789, 0.7974835834010681, 0.8262538749416161, 0.8025679429848853, 0.8263976338064302, 0.7892621425562697, 0.8424401732902027, 0.8434052215353838, 0.8253366549978713, 0.8082607483903956, 0.8304654736028393, 0.8376174983041308, 0.8168890209211973, 0.8197392641198323, 0.8393643772989783, 0.7556095930781189, 0.8260479450637822, 0.8198492118983027, 0.8449465434075775, 0.8446961866058282, 0.8292045135837445, 0.8132032519987351, 0.8332424274869487, 0.8144654519723101, 0.7627062588877793, 0.8450150692990059, 0.8417516736784544, 0.8153130845983275, 0.7905975239778416, 0.7884290917959348, 0.8223395043752053, 0.7191890079487895, 0.8206538691034394, 0.8121447854282596, 0.8068146124459867, 0.8440094746223611, 0.8160082608992122, 0.8366269181429595, 0.817646756797344, 0.7374456429488359, 0.8452985661062897, 0.8359548128389263, 0.8368698301128219, 0.8221104966516508, 0.7945132826218548, 0.8153136086254229, 0.8172430532680612, 0.8110321558196112, 0.8341254328350889, 0.8373000670718372, 0.8272477041633517, 0.810255099570983, 0.8083574511374255, 0.7985331424046448, 0.8431335064669423, 0.7510925711533977, 0.7996203676237063, 0.8347089585595363, 0.8155875127833049, 0.839680695577346, 0.7926541423353675, 0.8168890209211973, 0.8296180413078348, 0.8144414432419923, 0.8349903196968377, 0.7995399972526498, 0.7732219262708994, 0.8448955869002545, 0.8022416500095708, 0.8058466678588634, 0.7605080922703432, 0.7255792269828637, 0.7905975239778416, 0.8217713149780463, 0.796726063139251, 0.8322679353394877, 0.7978243162119467, 0.842298532009303, 0.8244980608944503, 0.8004842668580532, 0.8081527044327752, 0.8404898392350472, 0.795659012755485, 0.8310154183363618, 0.7993296166567732, 0.8058918016692275, 0.820276601365362, 0.8383985186713169, 0.7949186036263196, 0.8336891530353613, 0.8358042481671557, 0.823987067540832, 0.8254356551794471, 0.7906864136844332, 0.8377515089277441, 0.8450593102830026, 0.7862367067528805, 0.7764722662741644, 0.8124284803710303, 0.8285055384948606, 0.8024533083101512, 0.8254928816778296, 0.8299318633210184, 0.8287112100421796, 0.79996397185002, 0.8478549467929758, 0.7820836518378094, 0.8207206541933857, 0.8191008409586393, 0.8375268331108148, 0.8103011893844994, 0.852445216744926, 0.8368141401977081, 0.8516867319570798, 0.8378878472703739, 0.8321209192241389, 0.8500964429740627, 0.8406176759716077, 0.8102062464928416, 0.8430690140150616, 0.8387794604241379, 0.8143459236469395, 0.7647918426833012, 0.8483771215328453, 0.8496934381825714, 0.8152849338480387, 0.8383192544608555, 0.8454104869138431, 0.8318820081343052, 0.6774098376644101, 0.7705301697568114, 0.8586961823656469, 0.8366339533171896, 0.8245742026423472, 0.8226982595819698, 0.8286804206569588, 0.8432595386273783, 0.8437127825820607, 0.8435236797933052, 0.829346246924078, 0.8146075488657963, 0.8468977356742041, 0.8128893157497729, 0.8521621495653171, 0.8465680323857431, 0.7627979531847402, 0.8396134843298533, 0.8494870156247799, 0.7889021785545088, 0.8474049749735707, 0.8517250679905393, 0.8438089620526792, 0.7629489216704133, 0.7797551994215592, 0.846413381077074, 0.8247768672277663, 0.825421300369082, 0.8311076963834049, 0.8531187358295844, 0.7740682181253711, 0.8299358270126082, 0.8124026521625842, 0.8449808326140271, 0.8146075488657963, 0.8519623834114924, 0.8548534934112005, 0.8348420357989624, 0.8449211502224954, 0.8553735672403511, 0.816663121137809, 0.8515790177782419, 0.8251125433829978, 0.6980297584425074, 0.797834588826775, 0.8432483715357231, 0.8380330777071746, 0.850697384139416, 0.8015438420857534, 0.8127165824645205, 0.7463575365830174, 0.8199501991883524, 0.8094054644816744, 0.8562338757295291, 0.8515171489673475, 0.8321209192241389, 0.8211065489087865, 0.7780879418907426, 0.8229093632933134, 0.84227831228184, 0.7876213660931676, 0.7808162458857357, 0.8520207617171375, 0.8513214948061906, 0.6732592572906295, 0.8120359428617714, 0.7388889545782074, 0.7877940955888951, 0.8407238046028256, 0.6510478594812691, 0.8190371505316772, 0.8093086059622137, 0.8508035880567564, 0.8473649215179302, 0.8200991880535644, 0.7676080156360432, 0.8420629187477573, 0.8451356500221513, 0.8562764883017584, 0.8517250679905393, 0.8000933459085605, 0.8355947947000022, 0.713932581445391, 0.8127165824645205, 0.7967461177763024, 0.847791581232985, 0.8449769347609888, 0.7176824602429035, 0.8392744403929646, 0.8175554914808437, 0.814747926898473, 0.8312670603038311, 0.8340544738447353, 0.8218994645202174, 0.8450623125918252, 0.8079629984647054, 0.8177036687439045, 0.8417226566711928, 0.826567689408828, 0.7981136492327336, 0.824985828099587, 0.8289636802364091, 0.7967144410355904, 0.7981504894690397, 0.7638949306769472, 0.8116413673404523, 0.8341111547539299, 0.819166173552218, 0.8080969538683433, 0.8125381545029982, 0.798456456159417, 0.7792383194357908, 0.8481188966696586, 0.8426954445183362, 0.8395672196956877, 0.8028559994810349, 0.8057320946671489, 0.8113727207254009, 0.8481475761244892, 0.8085163073780691, 0.8470188319681944, 0.8483422296031154, 0.8422834913849735, 0.784233937065853, 0.8141959534315368, 0.798222291484622, 0.8069390006561822, 0.8266946316647059, 0.8383982678513311, 0.8365087602342426, 0.835785972707833, 0.8208667628227051, 0.8150395788388016, 0.8347819669596269, 0.8108882930778971, 0.813740894404129, 0.819668888736562, 0.8360048115344922, 0.8452303856544099, 0.7881831508812454, 0.7776106961692733, 0.8208667628227051, 0.8243104817479592, 0.7520146857116854, 0.7016408166512276, 0.7885683167403303, 0.8288221882424922, 0.8215387141111146, 0.6958620698116014, 0.8148167896418166, 0.8299687225296266, 0.8326674005128961, 0.8322613306802478, 0.834678300323006, 0.7980820450326221, 0.841898427955256, 0.8380394998578897, 0.8447738070189846, 0.8475070386300481, 0.8391879060758486, 0.8270886473614407, 0.836807260131273, 0.8259195595415052, 0.6806725072070092, 0.6404900118549653, 0.7521849658611508, 0.8242865100391663, 0.774543683825438, 0.8380526798308597, 0.833393025846432, 0.8326555005316821, 0.8474047279516045, 0.7245213520012236, 0.8322108324867236, 0.8353630689965913, 0.8379066978247641, 0.8050336126955939, 0.8157446283374208, 0.7509884500634678, 0.827287683111386, 0.8326165075114345, 0.8425644361436901, 0.7899337523806539, 0.7505981123582981, 0.8360510794128535, 0.7918132857933682, 0.821740397608745, 0.7559716538470836, 0.8023587617580861, 0.8474850657781928, 0.7853472483035064, 0.8309745141374348, 0.77106023073064, 0.8104445486283234, 0.8395274797878459, 0.8437819749977832, 0.8364675448765937, 0.775033151631962, 0.8302825380004067, 0.8278377439480892, 0.7713943555598689, 0.81759812366325, 0.826569472329234, 0.8373508549719645, 0.8483910887242482, 0.7849144849218261, 0.8009680243665382, 0.8427198114096358, 0.791730184314235, 0.7962437773109026, 0.8139730826699048, 0.8083960907821229, 0.814082834747186, 0.8057614920055481, 0.7856422981903107, 0.8041777787764847, 0.7936366551345098, 0.835389391563331, 0.7918605441633305, 0.8206471626933476, 0.7814377666990435, 0.8091475494314976, 0.8228011681581995, 0.8045109180689881, 0.8066925779338583, 0.8483027475703497, 0.8419825307567026, 0.8406962471415046, 0.8280669051697537, 0.8274842730391245, 0.8157106566249975, 0.8198578327635608, 0.8171865725622626, 0.795476071549354, 0.8006272170424517, 0.8095144156937556, 0.8228061759246108, 0.8325437836050288, 0.8275758128738833, 0.8259876699703927, 0.787557429137308, 0.7854244758955935, 0.8045547959360839, 0.8288153754331861, 0.7950634122165872, 0.8302386441990987, 0.8179548052637873, 0.7939830014405104, 0.8346849181273758, 0.8020762104537621, 0.8211953817975102, 0.8279608755403569, 0.8122646760948667, 0.795476071549354, 0.8282966430278721, 0.7998455231870993, 0.7859324531122981, 0.7821326779080826, 0.8171667140241615, 0.8035533931851158, 0.8202315022075138, 0.8273626822549074, 0.8247701438150404, 0.824463911491998, 0.8194440676500125, 0.7830187464130236, 0.8326734477384538, 0.8146501797312169, 0.8223316490389626, 0.8233518747816557, 0.8154340665965565, 0.8408008236180209, 0.8264496293161443, 0.8271024814969113, 0.8122646760948667, 0.8355872848173881, 0.8136339444340368, 0.8270856504557743, 0.8228506456716398, 0.8259833926797799, 0.8319634170516388, 0.8094797229006228, 0.8277279391543075, 0.8239663947791058, 0.8243933523703377, 0.810375466231392, 0.8267750618514806, 0.8255071778283393, 0.7553327349327679, 0.7913326136427642, 0.8160255686113785, 0.7931006590423907, 0.8267250201483394, 0.8117514878610347, 0.8137113462577819, 0.7979769169154319, 0.8242110773852586, 0.8146093186496766, 0.800281609619249, 0.8286388955834075, 0.8010209462921933, 0.766581317430237, 0.8275554636093228, 0.7708538138961274, 0.8280156841994752, 0.8224997157549172, 0.8282105753263862, 0.8259815458409264, 0.7935510037625756, 0.8107310129121595, 0.836059715772197, 0.8264496293161443, 0.8043489828807975, 0.8031755820721008, 0.8283902196974517, 0.8284301453329252, 0.7839906277546567, 0.8212551437554982, 0.7839643832648548, 0.8255860083793174, 0.8216181823003097, 0.8045723562508511, 0.8196522425952016, 0.8246993573854005, 0.8104070032629528, 0.7689236317505129, 0.793478559724969, 0.8263299779152664, 0.7932418627939974, 0.8214654146709928, 0.8195330868559095, 0.826203764869781, 0.8266723417354969, 0.8031641245454788, 0.8368246158196909, 0.8282417871029111, 0.8327386051787629, 0.8276890044099956, 0.8281678009490927, 0.8279039784472314, 0.7623059278395944, 0.8279092804718843, 0.8265830435256483, 0.8211953817975102, 0.826735521281792, 0.8026849879498595, 0.8040819741236671, 0.7906535515744371, 0.8341387892370413, 0.8125316921044845, 0.8020762104537621, 0.8281443931055266, 0.795343887321204, 0.8331036730473821, 0.8239134910152547, 0.8155425386384314, 0.8014367616512533, 0.8273227173959669, 0.8052789446360947, 0.8248812233753492, 0.8057526665140486, 0.812174567029796, 0.8076202364009097, 0.8158574325739345, 0.8258306758878009, 0.8315637122822134, 0.8054166348810652, 0.8060064956271598, 0.7995227149123146, 0.8060064956271598, 0.8208463901967346, 0.8174233275189868, 0.8170286982169899, 0.8006211291859712, 0.8324245770667946, 0.8101098259978101, 0.8012011335318874, 0.8137631331701376, 0.8035849261825, 0.8204390921159677, 0.7992620593353811, 0.7964028887328816, 0.8242654894414511, 0.834706583805165, 0.818591610742048, 0.8213937621108263, 0.8415088062111146, 0.8113611341600301, 0.8044822946095833, 0.818747450350482, 0.8046413970421658, 0.828807544564348, 0.8124419252923996, 0.8089548604680126, 0.8159928679624464, 0.8060064956271598, 0.8055932940545982, 0.8032174777819516, 0.7965373224381161, 0.808556030900232, 0.8059271472420846, 0.8097148378882035, 0.8248787352932352, 0.8493650909491818, 0.8032195634044582, 0.8112803144744983, 0.8177846718879639, 0.7967227046610078, 0.810546753200333, 0.8141552683235291, 0.8034373081640631, 0.830745194102801, 0.799931583897951, 0.8026628813784281, 0.8034581391866962, 0.8021832648846583, 0.8073742543883504, 0.7976725950040822, 0.8035268766387892, 0.8099224975068455, 0.8328055873049702, 0.7956067285220878, 0.818257558523564, 0.818931917349297, 0.8105712144017867, 0.7986194917531905, 0.8238216541764904, 0.8211860894949302, 0.8264194189030614, 0.7968620797970993, 0.8060064956271598, 0.8007184291113536, 0.8263415525863532, 0.8016118549373106, 0.8073373822660042, 0.8387815392151419, 0.8026619702613533, 0.8571196748407655, 0.8392272971598699, 0.8375318688337856, 0.8056837414843768, 0.8127850693537159, 0.8350486099378065, 0.8166531384793245, 0.826824375196382, 0.8312616183446421, 0.7522245737482923, 0.7666358865939795, 0.7949372908761521, 0.8121683924825742, 0.7969613100530123, 0.8324726532156926, 0.8165367693908197, 0.8080534423415975, 0.8228257816167502, 0.7998655335673625, 0.8119352191931751, 0.8318136653620055, 0.8033135035665178

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

Fase 4 MLP perfil interno {'accuracy': 0.8177570093457944, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8177570093457944), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.8997429305912596), 'f1_macro': 0.4498714652956298, 'f1_weighted': 0.7357710881003292, 'precision_macro': 0.4088785046728972, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 117, 'FN': 0, 'TP': 525, 'score_source': 'predict_proba', 'auroc': 0.4799918599918599, 'ap_0': 0.17490875825461755, 'ap_1': 0.8132321996393284, 'model': 'MLP', 'params': {'alpha': 0.0001, 'hidden_layer_sizes': (32,), 'max_iter': 500}, 'indices': [2, 5, 12, 14, 18, 36, 40, 41, 43, 44, 45, 46, 47, 52, 58, 60, 75, 76, 79, 80, 83, 85, 88, 90, 91, 92, 93, 95, 101, 107, 108, 111, 112, 114, 116, 117, 118, 130, 153, 156, 160, 162, 170, 173, 180, 187, 189, 190, 192, 195, 198, 205, 208, 212, 215, 218, 223, 227, 228, 232, 233, 242, 256, 264, 268, 274, 275, 276, 280, 286, 307, 317, 326, 337, 342, 356, 367, 385, 412, 417, 419, 421, 427, 428, 429, 430, 437, 439, 446, 454, 458, 460, 466, 469, 470, 471, 478, 488, 493, 497, 498, 500, 502, 506, 519, 530, 540, 544, 547, 549, 551, 552, 561, 564, 569, 572, 574, 587, 589, 600, 602, 605, 607, 627, 629, 630, 636, 637, 641, 4, 10, 11, 17, 19, 20, 22, 39, 49, 54, 55, 63, 67, 68, 78, 87, 105, 109, 119, 120, 128, 134, 138, 144, 146, 149, 158, 164, 176, 178, 181, 182, 186, 204, 207, 219, 226, 229, 231, 234, 236, 237, 239, 240, 241, 243, 244, 246, 254, 258, 259, 263, 265, 267, 270, 277, 278, 279, 282, 283, 290, 291, 293, 308, 310, 319, 323, 328, 330, 332, 335, 338, 339, 345, 346, 347, 357, 359, 364, 379, 380, 391, 393, 394, 398, 400, 406, 410, 414, 415, 424, 426, 431, 432, 441, 445, 449, 465, 476, 484, 487, 490, 491, 501, 515, 528, 529, 533, 535, 536, 539, 550, 554, 566, 577, 581, 591, 593, 596, 598, 599, 608, 612, 615, 623, 624, 625, 635, 638, 0, 3, 24, 25, 27, 29, 30, 48, 53, 57, 64, 66, 72, 84, 86, 89, 94, 96, 99, 104, 123, 126, 129, 132, 136, 137, 139, 143, 151, 152, 168, 175, 177, 183, 184, 191, 193, 199, 200, 221, 222, 225, 238, 262, 271, 281, 284, 288, 292, 294, 295, 296, 301, 305, 306, 309, 312, 313, 314, 320, 321, 324, 334, 340, 349, 351, 355, 358, 361, 363, 366, 371, 374, 375, 388, 395, 396, 397, 402, 408, 420, 423, 434, 436, 440, 450, 452, 455, 456, 459, 462, 467, 468, 473, 480, 481, 483, 489, 494, 499, 508, 510, 514, 516, 518, 521, 525, 527, 531, 534, 538, 541, 543, 556, 567, 568, 576, 582, 586, 604, 606, 609, 613, 617, 621, 622, 633, 639, 1, 6, 21, 28, 32, 37, 38, 42, 51, 56, 70, 71, 73, 74, 77, 82, 98, 102, 103, 110, 113, 121, 122, 125, 131, 135, 141, 147, 148, 150, 155, 159, 161, 163, 166, 179, 188, 197, 202, 206, 209, 211, 214, 220, 224, 247, 248, 252, 255, 261, 272, 285, 287, 297, 302, 304, 311, 322, 327, 333, 341, 343, 344, 348, 350, 352, 354, 360, 369, 370, 373, 376, 378, 381, 383, 384, 387, 392, 401, 404, 405, 413, 416, 422, 425, 435, 442, 443, 444, 448, 451, 463, 472, 474, 479, 482, 485, 495, 503, 504, 509, 513, 524, 526, 532, 537, 542, 548, 559, 560, 562, 565, 570, 571, 573, 575, 578, 579, 583, 585, 588, 603, 616, 618, 620, 626, 628, 632, 7, 8, 9, 13, 15, 16, 23, 26, 31, 33, 34, 35, 50, 59, 61, 62, 65, 69, 81, 97, 100, 106, 115, 124, 127, 133, 140, 142, 145, 154, 157, 165, 167, 169, 171, 172, 174, 185, 194, 196, 201, 203, 210, 213, 216, 217, 230, 235, 245, 249, 250, 251, 253, 257, 260, 266, 269, 273, 289, 298, 299, 300, 303, 315, 316, 318, 325, 329, 331, 336, 353, 362, 365, 368, 372, 377, 382, 386, 389, 390, 399, 403, 407, 409, 411, 418, 433, 438, 447, 453, 457, 461, 464, 475, 477, 486, 492, 496, 505, 507, 511, 512, 517, 520, 522, 523, 545, 546, 553, 555, 557, 558, 563, 580, 584, 590, 592, 594, 595, 597, 601, 610, 611, 614, 619, 631, 634, 640], 'y_true': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1], 'y_pred': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'score': [0.7594942266143864, 0.8299977930958156, 0.8311350695446313, 0.8534625377844878, 0.8578533851841378, 0.8417797375277137, 0.810026610585288, 0.8069740942127422, 0.8441495753055828, 0.8150129829997443, 0.8244555714825544, 0.8444452608916713, 0.8354676740488884, 0.7782225105111337, 0.8574145976012437, 0.6969116719144606, 0.8546490697651942, 0.8560916299762834, 0.7848038811243826, 0.8080664360725013, 0.7501164699850523, 0.8065221850177806, 0.858875948820419, 0.8170575318755032, 0.7236886363821381, 0.8214142431002799, 0.8512166181587798, 0.857502197334506, 0.7489985030330619, 0.7483629655369007, 0.8446940788188716, 0.8601995544308176, 0.8029868256590993, 0.8532195664645466, 0.821255311059559, 0.8530117100419355, 0.8490974492378005, 0.8304828914969441, 0.8416161804683704, 0.832726408484719, 0.8360272871617266, 0.8003461467627462, 0.8268347343045137, 0.8588253708164663, 0.852806978898462, 0.8546099850294153, 0.8573161129925134, 0.7884657497224841, 0.821225341915056, 0.8087675428450678, 0.8515885494445673, 0.7731836310393928, 0.8046520315979471, 0.7493643112139783, 0.826702245744922, 0.7574350322488476, 0.8150129829997443, 0.8109009276389824, 0.8513635571391507, 0.8214142431002799, 0.8376577576162558, 0.8252101160670868, 0.8301382637853599, 0.8407772919247813, 0.8547228510223434, 0.7804555863216145, 0.8005438588157865, 0.7515879739921045, 0.8213916975180215, 0.7858480927773276, 0.782793212685445, 0.8586189478666043, 0.8308854836408421, 0.8127735969524477, 0.8085833918189879, 0.8465483619097268, 0.8391053393388466, 0.811745614648191, 0.8049950328503062, 0.8608784340668976, 0.8435121704849727, 0.8143993992874426, 0.7952039579051805, 0.7845927211769539, 0.7641726469274376, 0.8395525473232734, 0.8037804244364205, 0.7523909535817699, 0.8516782517586623, 0.8329483215430219, 0.6682405168158218, 0.8263491374623848, 0.8129585861888762, 0.7724410749024679, 0.8434511686486681, 0.8400616022314054, 0.8608182220322907, 0.7648745973296521, 0.8556416147476031, 0.8416911853419429, 0.7399582208129099, 0.6057079057464649, 0.8259283041882519, 0.810026610585288, 0.8307509053780867, 0.8331819138989991, 0.8580315643705942, 0.7731548692717537, 0.841301396000419, 0.8389994032568353, 0.822396651879431, 0.7789411022506629, 0.8586788798751623, 0.8458321481758025, 0.8341306645781892, 0.8304203914642985, 0.8593812582516268, 0.7206768822275016, 0.8541119193147862, 0.7686744915549167, 0.8408790967322772, 0.8493490923787992, 0.8117509519909287, 0.8108866962620681, 0.8612645132133157, 0.738875768275799, 0.7742399784574052, 0.8368534389030933, 0.8471083355515947, 0.8339668068377515, 0.8247889815507721, 0.8193015358352435, 0.790854902000344, 0.8193002105953088, 0.8303753137559982, 0.8224072539851939, 0.7951467732825463, 0.8307894784364016, 0.8091523242520189, 0.8244301472350534, 0.8174814528566083, 0.7949467704320169, 0.8240293551259932, 0.8292703704785411, 0.8171904369182066, 0.8114744071565694, 0.820599961676088, 0.7981210961932288, 0.8250287877913071, 0.8093077715353421, 0.7984528186555768, 0.7924236124559403, 0.8165584397473277, 0.8132415204630912, 0.7925735860307207, 0.822810042689113, 0.8005785364699378, 0.8221261704378783, 0.7715826327245415, 0.805859843432646, 0.7994414952680019, 0.8093689387782265, 0.8186120039730851, 0.8111319829588617, 0.8253435196165968, 0.8295537927073017, 0.8363176230387304, 0.7957142865413498, 0.8246720238343265, 0.8254958248551281, 0.8280837135147708, 0.8082672013573028, 0.8229042997144148, 0.8211048234434525, 0.8075526051101436, 0.838517889398742, 0.8096944074096388, 0.8091168924600846, 0.8364836495183947, 0.8080025558853204, 0.7676296774879465, 0.8115783946994739, 0.8056130886247745, 0.8203377441383648, 0.8219243301692654, 0.8198671574460941, 0.8088469740926729, 0.8315959854837827, 0.8093689387782265, 0.7565899455894092, 0.8388341278174556, 0.8284418371754697, 0.8211593717617041, 0.8222689150912907, 0.8286983251559434, 0.8333781403628722, 0.8273419603536784, 0.8190545890895237, 0.8280847175181343, 0.7290644203658644, 0.822355220854976, 0.798973219650365, 0.8193560934187081, 0.7735300358756164, 0.823930836458317, 0.8328514985308075, 0.8365904668323203, 0.8258234206210068, 0.8354036271650618, 0.7631313270412068, 0.7698994390714011, 0.8270798790813242, 0.8223856487034957, 0.6975659608431861, 0.8197274753829568, 0.8274652619141598, 0.8274458193914374, 0.7998197207245324, 0.8165996687479462, 0.8067744588333312, 0.8230065097103012, 0.8183836021757918, 0.7901968085399644, 0.8005514175014443, 0.7638127775369544, 0.7756295412582714, 0.8183799180679845, 0.8043309491156855, 0.8434748253367959, 0.8034695253588684, 0.8250083008429175, 0.7724602325821153, 0.8436015935974078, 0.8208696028466738, 0.7780425529323554, 0.844570249857097, 0.8200759969268683, 0.8443929731394902, 0.792043344818188, 0.8231174930924284, 0.6882771968862763, 0.8022610927391227, 0.7997463456032768, 0.8277392685692041, 0.7939823843892735, 0.8322575470850719, 0.8224984998745606, 0.8004049759333105, 0.811926045457042, 0.8360235051924321, 0.7773692998010919, 0.8305065773484175, 0.8165996687479462, 0.7981884022021328, 0.8205259143818069, 0.8333480453873762, 0.8093689387782265, 0.7648258430604851, 0.8110240880502355, 0.8234756426198901, 0.833950959623451, 0.8253582831753551, 0.8323626058346532, 0.8313907426539556, 0.811073388305663, 0.8213394142152165, 0.7973979287397681, 0.8321769626178803, 0.8120843917813423, 0.8343675213034659, 0.8317015057591911, 0.8066750376271334, 0.8266518936055813, 0.8249564626074124, 0.7993969064234501, 0.8145204708318425, 0.7924038681331439, 0.790997082864091, 0.7922196241495962, 0.8409289108539614, 0.8219564435125436, 0.8325767200733208, 0.8238298537536449, 0.7923172860425454, 0.8142805658799723, 0.8002377155789994, 0.827920200508488, 0.7969503391976065, 0.8213394142152165, 0.8248224246795228, 0.815312934996691, 0.8250632705707979, 0.8068271542157394, 0.7912684935176912, 0.8096307703076528, 0.7973057463305168, 0.8172364633989787, 0.8270380315555421, 0.820423666349192, 0.84201085159621, 0.7979390549832782, 0.8338754765888472, 0.824429347969169, 0.8317002491108125, 0.8273116205065513, 0.7943599474764463, 0.829614582423638, 0.7952772791868417, 0.8270228065086854, 0.7919784860307535, 0.7972306353416567, 0.8307420163398943, 0.7938856350718331, 0.8352716734134802, 0.7943393327081407, 0.8231554958674145, 0.8078490962988676, 0.811775844224556, 0.795698371319527, 0.8318949482708252, 0.8202901233812956, 0.8206408459249257, 0.8105048510564694, 0.8036900884313066, 0.8347941200695157, 0.8296412208392482, 0.8048318089491652, 0.8213394142152165, 0.8101990964477483, 0.8023261093186982, 0.8036569345590884, 0.8287104608617497, 0.8053153574089992, 0.812651147077456, 0.7919986391519389, 0.8012179915536182, 0.8144945909912499, 0.8113700009559665, 0.8134594150416262, 0.8075104683243378, 0.8093188308365038, 0.794423155715412, 0.8265149383101351, 0.7986475551235446, 0.8075795109418621, 0.8174912075215435, 0.8102409652189883, 0.7977328460965668, 0.8292620371758161, 0.8213884053583195, 0.8457191432033835, 0.8243877924816758, 0.7922176785249709, 0.8042472252093106, 0.813129442890622, 0.8237229500818832, 0.8305454902081824, 0.8365781214821245, 0.8156101454102853, 0.7994395733905667, 0.8313827637881822, 0.7909979435974157, 0.8233697584622472, 0.8123998938171516, 0.8009515838474377, 0.7946280743406586, 0.8312418315179524, 0.8014350712921777, 0.8256820292921327, 0.8217569834316085, 0.836823508570529, 0.8491595454565829, 0.810180835535277, 0.8243877924816758, 0.8281975239811423, 0.8179868708547564, 0.8319124687126248, 0.8255864567414921, 0.8056669344967627, 0.817364701634523, 0.8294038028694098, 0.7908416361046472, 0.8251115401495894, 0.8121544209819817, 0.8103761574389365, 0.8007868517498803, 0.8395010151998985, 0.8404660010523823, 0.8204179986135444, 0.8291455840755816, 0.827147267554697, 0.8077103711784552, 0.7876964639808701, 0.8304444539729989, 0.8424596360278869, 0.7713745795346274, 0.7850893802330411, 0.8367215519506465, 0.7928401521041774, 0.8151194189505727, 0.8004910545106982, 0.7671291302626122, 0.8288350055192198, 0.8332748092802353, 0.8308707485776127, 0.7670858738787759, 0.8340083503155384, 0.8409920739789036, 0.8317418964208227, 0.8459161431453662, 0.7962988961542152, 0.8232533527469108, 0.8230333913950563, 0.8399367767311448, 0.8077103711784552, 0.8386973017954811, 0.8336589425396127, 0.8378204241037726, 0.8334303072416134, 0.8241487554625166, 0.8188231417499313, 0.7539644304878298, 0.7935092090900793, 0.8420651592677846, 0.7934293474578628, 0.8145904143906009, 0.7809255549761451, 0.8275852083600114, 0.7806475307640481, 0.8349448250507386, 0.8284117200471922, 0.8007914666490062, 0.788071061930405, 0.8394575666181805, 0.810073004721346, 0.8133365039761152, 0.8378244224661262, 0.8266549754343092, 0.834886165523083, 0.7549318856530821, 0.7888623750709034, 0.8345963890389381, 0.8375924699646117, 0.8169895828607358, 0.8352296867213802, 0.8308643150796172, 0.7863190962964834, 0.8382469020279195, 0.8223030152431944, 0.8389578922213967, 0.784958316705469, 0.7923559191659607, 0.8341254620027307, 0.8332971438474734, 0.8525292824568227, 0.8127552586073058, 0.7860118705535927, 0.8228277244126618, 0.8138364305345315, 0.8278335641513397, 0.8315835278497016, 0.7848179631631244, 0.7991439555863693, 0.8224286938772349, 0.8260229560364992, 0.8217251121890354, 0.8028402408768803, 0.812710851207259, 0.788071061930405, 0.831986352095802, 0.8057014597789328, 0.7885586270421614, 0.8347642525095844, 0.8100832856454051, 0.8338211977710124, 0.826728400065346, 0.8296084004153685, 0.8381169264393794, 0.797864930036926, 0.7560976204504233, 0.8406697887804094, 0.8250508101625759, 0.8387445601832063, 0.8346341221406988, 0.8241288106024414, 0.7724499030880386, 0.8279070734055279, 0.8371457986756118, 0.8402788217194033, 0.8336446589990473, 0.8421524386335196, 0.8252117896515104, 0.7735336824500741, 0.8303567893056417, 0.7923559191659607, 0.8133365039761152, 0.8133365039761152, 0.761988309237897, 0.6211191176137844, 0.8326359094497129, 0.8404056176853085, 0.8190498717774812, 0.8284412505461229, 0.7998243805020648, 0.7849254313760621, 0.7670858738787759, 0.8416583811988743, 0.8332498535792713, 0.838186230411883, 0.7662152335427599, 0.8212751565602181, 0.8503289949658914, 0.7789708601806222, 0.8188641893354813, 0.8191534850952028, 0.8343265523046087, 0.814184977438192, 0.8373591424773332, 0.8248459313208707, 0.8217517946009231, 0.7907762270326614, 0.8213965403438312, 0.8287555630404551, 0.7959637969076876, 0.8374338724699131, 0.8334316010826575, 0.8363469010687453, 0.8140787580595825, 0.8138939445370903, 0.8395095696642396, 0.831081161914452, 0.8179323051071157, 0.8335052054237956, 0.826704333374497, 0.8178404565474251, 0.8075514837353641, 0.8226041551437795, 0.8265737896960805, 0.8235915949046115, 0.8055204195696056, 0.8204339442417441, 0.8298568719958326, 0.760836608161636, 0.8264415847714662, 0.8355704494166399, 0.8124881593245522, 0.828816718204183, 0.8130389119736222, 0.829971496055147, 0.8216348474225603, 0.821584899866503, 0.7806037726920201, 0.8173394754037281, 0.824720009863493, 0.8104054580474467, 0.7914634907615717, 0.7734893076644536, 0.8042212763198469, 0.8270211779860255, 0.821584899866503, 0.8140256622560729, 0.8056431715673927, 0.8380132174707933, 0.7602728481938561, 0.8379459788607087, 0.7956236593164121, 0.8311181995414867, 0.8315997803306667, 0.81277510380551, 0.830745820377131, 0.8260458110851676, 0.835131071351612, 0.815759522259404, 0.8335309232104159, 0.8277722810055653, 0.7912088622809856, 0.812986623345817, 0.8230214737353403, 0.8224760435162051, 0.8178404565474251, 0.8388327010632508, 0.8042027013186115, 0.8223216213817709, 0.7913838712463828, 0.800164781654043, 0.7921221123277076, 0.8365828432532572, 0.8243374612059984, 0.817420064745497, 0.817902674845348, 0.8285397451693329, 0.8355182701055671, 0.8349111489113173, 0.819292547897399, 0.8120618793367014, 0.7988987861793572, 0.8236663998809224, 0.7969885060445951, 0.837228462305909, 0.7967146579530351, 0.81457112195764, 0.8349507774481847, 0.8285432967885304, 0.8223018196174344, 0.8251367530251035, 0.8020700214105926, 0.7000806987287238, 0.8395314433991476, 0.8344004100324416, 0.8241144001017991, 0.7767776639125304, 0.7717898497717794, 0.8362329621296448, 0.8182718191148695, 0.825140766150598, 0.7983446884735992, 0.8227753981618221,

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

Fase 4 MLP perfil interno {'accuracy': 0.8164852255054432, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8164852255054432), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.898972602739726), 'f1_macro': 0.449486301369863, 'f1_weighted': 0.7339978482711604, 'precision_macro': 0.4082426127527216, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 118, 'FN': 0, 'TP': 525, 'score_source': 'predict_proba', 'auroc': 0.4167635189669088, 'ap_0': 0.15045132889798915, 'ap_1': 0.7878170038882653, 'model': 'MLP', 'params': {'alpha': 0.0001, 'hidden_layer_sizes': (32,), 'max_iter': 500}, 'indices': [2, 5, 12, 14, 18, 38, 42, 43, 45, 46, 47, 48, 49, 55, 59, 62, 66, 77, 79, 82, 84, 87, 88, 92, 93, 94, 95, 96, 99, 101, 102, 103, 111, 114, 117, 119, 120, 133, 141, 158, 162, 165, 174, 176, 184, 190, 192, 193, 195, 198, 201, 209, 210, 212, 215, 218, 221, 222, 227, 230, 231, 236, 245, 255, 260, 269, 274, 282, 283, 289, 309, 319, 327, 338, 343, 349, 359, 391, 409, 417, 419, 422, 427, 428, 429, 433, 436, 438, 445, 453, 456, 464, 465, 468, 469, 470, 476, 487, 492, 497, 498, 500, 502, 506, 519, 531, 541, 544, 545, 548, 550, 552, 562, 565, 570, 572, 575, 587, 589, 599, 603, 607, 608, 628, 630, 631, 637, 638, 642, 4, 9, 11, 17, 19, 20, 22, 28, 34, 39, 51, 57, 69, 70, 81, 90, 108, 112, 121, 122, 131, 136, 142, 146, 148, 151, 152, 160, 167, 171, 179, 181, 185, 187, 211, 223, 225, 229, 233, 235, 237, 239, 240, 244, 246, 247, 248, 249, 250, 258, 262, 263, 267, 270, 272, 273, 275, 280, 281, 285, 286, 287, 294, 310, 311, 320, 323, 325, 329, 331, 333, 336, 340, 346, 347, 348, 358, 360, 365, 378, 380, 390, 393, 395, 398, 399, 406, 411, 413, 415, 424, 426, 430, 431, 444, 448, 457, 463, 473, 483, 486, 488, 490, 501, 516, 527, 529, 530, 534, 537, 538, 551, 554, 561, 578, 581, 591, 593, 596, 598, 600, 610, 612, 615, 624, 625, 626, 636, 639, 0, 3, 24, 25, 29, 31, 32, 50, 54, 56, 65, 68, 74, 78, 83, 89, 98, 100, 104, 106, 110, 115, 125, 128, 132, 138, 139, 140, 145, 155, 172, 178, 180, 186, 188, 194, 196, 202, 205, 206, 207, 226, 242, 266, 268, 277, 284, 288, 291, 295, 296, 297, 298, 302, 306, 307, 313, 316, 317, 318, 321, 322, 335, 339, 341, 350, 352, 356, 357, 362, 364, 367, 369, 374, 375, 387, 394, 396, 397, 402, 408, 420, 423, 435, 437, 439, 449, 451, 454, 458, 460, 462, 466, 467, 471, 479, 480, 482, 493, 496, 499, 509, 511, 515, 517, 518, 521, 525, 528, 532, 535, 536, 540, 543, 555, 567, 569, 574, 583, 586, 605, 606, 609, 613, 617, 621, 623, 634, 640, 1, 6, 21, 27, 30, 40, 41, 44, 53, 58, 72, 73, 75, 76, 80, 85, 86, 91, 97, 113, 116, 123, 124, 127, 134, 137, 144, 149, 150, 154, 157, 161, 164, 168, 169, 173, 182, 191, 200, 203, 204, 214, 217, 224, 228, 251, 252, 256, 259, 265, 276, 278, 290, 293, 303, 305, 312, 324, 328, 334, 342, 344, 345, 351, 353, 355, 361, 370, 371, 373, 377, 379, 381, 383, 384, 386, 392, 401, 404, 405, 414, 416, 421, 425, 434, 441, 442, 443, 447, 450, 472, 474, 477, 478, 481, 484, 494, 503, 505, 510, 514, 522, 526, 533, 539, 542, 549, 557, 560, 563, 566, 568, 571, 573, 576, 577, 579, 582, 585, 588, 604, 616, 618, 620, 622, 627, 629, 633, 7, 8, 10, 13, 15, 16, 23, 26, 33, 35, 36, 37, 52, 60, 61, 63, 64, 67, 71, 105, 107, 109, 118, 126, 129, 130, 135, 143, 147, 153, 156, 159, 163, 166, 170, 175, 177, 183, 189, 197, 199, 208, 213, 216, 219, 220, 232, 234, 238, 241, 243, 253, 254, 257, 261, 264, 271, 279, 292, 299, 300, 301, 304, 308, 314, 315, 326, 330, 332, 337, 354, 363, 366, 368, 372, 376, 382, 385, 388, 389, 400, 403, 407, 410, 412, 418, 432, 440, 446, 452, 455, 459, 461, 475, 485, 489, 491, 495, 504, 507, 508, 512, 513, 520, 523, 524, 546, 547, 553, 556, 558, 559, 564, 580, 584, 590, 592, 594, 595, 597, 601, 602, 611, 614, 619, 632, 635, 641], 'y_true': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1], 'y_pred': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'score': [0.76443018798632, 0.8535108083764863, 0.845376959418058, 0.8232365125372805, 0.8442320216172357, 0.8117602206770472, 0.8532156107344937, 0.8405203930238632, 0.8523150761751884, 0.835225133142367, 0.7965706313484064, 0.8252538690674095, 0.808099655629911, 0.8418577608931141, 0.795076771668044, 0.7947610010738653, 0.8201125838634411, 0.8327653992921806, 0.7857566766920755, 0.8524420946798905, 0.8108979313513928, 0.8085829886422455, 0.8040855322164757, 0.8336467208296309, 0.7912422443727964, 0.7710958262565661, 0.8474772876701003, 0.822137347398205, 0.8008109295317943, 0.8341468749033399, 0.8249016257092331, 0.8537178738641054, 0.7920588191184954, 0.8169402451577227, 0.8066798912317766, 0.8132964293507234, 0.8528835726429037, 0.8270105866122666, 0.8387654168935932, 0.8434436330249296, 0.8464190172610835, 0.8365316574027138, 0.8408370465564226, 0.8392967010342781, 0.840908196213657, 0.8459930403681282, 0.8416838794167688, 0.8033745576163172, 0.8317023482755248, 0.8403154923032423, 0.8139242906861825, 0.7936280122095404, 0.784489268546556, 0.8218528780214358, 0.8524326171142926, 0.8065889684505805, 0.8306640705830379, 0.8189585789218409, 0.8517335188431122, 0.8112581632347788, 0.8317023482755248, 0.8517335188431122, 0.8513197993003676, 0.847364413630556, 0.831275043958216, 0.8325213426897735, 0.7830420550440708, 0.8123390034724421, 0.8535902799787062, 0.8308048204293556, 0.8430187202868439, 0.8498265624177955, 0.7802109150288714, 0.839286698652469, 0.8456621144156828, 0.8493602853555441, 0.8307116289889015, 0.8219998631461758, 0.8034736826522497, 0.8341468749033399, 0.8222159389339018, 0.8431611233813439, 0.8019032444099071, 0.8313534941173749, 0.8460178090982595, 0.80353048601623, 0.7732736284308301, 0.7709704237057862, 0.7657416362183699, 0.8457535002715402, 0.810644197804038, 0.8481489413065498, 0.8533252586684743, 0.801637613509494, 0.7627150835226033, 0.8132968785792716, 0.7649925175825121, 0.814251127726615, 0.8480997200311714, 0.819926690407566, 0.8066638907130235, 0.8034503035631501, 0.8316251273728097, 0.8003548254650538, 0.8173257126344218, 0.7888097475040954, 0.8059856181416066, 0.77242046739155, 0.7624945846891972, 0.8527529661607135, 0.8349300742524136, 0.79573087804129, 0.831275043958216, 0.7569620864151835, 0.8492714045551206, 0.7631954369444054, 0.8321003169208743, 0.7683548134342854, 0.8350714257029994, 0.7441692808347673, 0.8171452235555485, 0.8312538917048361, 0.7885263753700557, 0.815685193634814, 0.8536274083607079, 0.7916347466978062, 0.8123390034724421, 0.7645068986767944, 0.8484484096786034, 0.8084841144311816, 0.803431492795346, 0.8327370722849098, 0.7938160738323037, 0.8061760525971009, 0.7821158693823019, 0.8061127474864577, 0.8143299297407592, 0.8150404549887282, 0.8203168582315621, 0.8065018630438017, 0.7829464361043593, 0.7809248122970717, 0.784552898882846, 0.8259093892876714, 0.7813899128154725, 0.8256837051986052, 0.8319376436678516, 0.8265538044412221, 0.7999284281906391, 0.8093901959380577, 0.7832765956272768, 0.7759988359979333, 0.8090529773415784, 0.8090529773415784, 0.8270997047186238, 0.7870145052206781, 0.8248277819399672, 0.8268311308969609, 0.8073813909006097, 0.8066980260162797, 0.8112047244853148, 0.8191632305698265, 0.8056521938974435, 0.7953833260230077, 0.8112047244853148, 0.8201506121169417, 0.8026297486104376, 0.8241392277821517, 0.8263459640401196, 0.7976199033470075, 0.8055812206154827, 0.8055709348868427, 0.81853094352286, 0.8376498302525647, 0.8107099061547351, 0.8180352201906077, 0.8107349525730561, 0.7804848600128074, 0.8059185975373134, 0.8035445345177387, 0.8240229681978135, 0.8201046018073047, 0.8482898387370776, 0.7884003734179332, 0.8611878674018285, 0.8313857403847031, 0.8178982221226259, 0.8132640947944733, 0.8268311308969609, 0.8157258129685021, 0.8052935495652356, 0.8024744074325832, 0.7814543176791379, 0.8036389122107392, 0.7938808560477076, 0.8190157393730505, 0.812443927304443, 0.7912332633138505, 0.7906736053102194, 0.8484560672884086, 0.8113915069996862, 0.8341194874630602, 0.8286672399146798, 0.8111839786827659, 0.7914495407027938, 0.84860521263405, 0.7825270933585329, 0.8105293314421154, 0.8301663086042458, 0.8074397342640862, 0.7783126808212253, 0.8322586427174328, 0.8095601595418132, 0.8115429366213599, 0.8341550055846151, 0.835222970759145, 0.85636806713905, 0.8097903541922846, 0.8022685968989327, 0.8231413781401935, 0.7588776897056372, 0.8575888196635413, 0.8432602481127145, 0.7993444789524408, 0.8170506317695505, 0.8010140902050017, 0.8293459625973828, 0.8135374331859161, 0.8155899572097111, 0.8166428135607614, 0.8325627803676487, 0.790625494149314, 0.8223480673550105, 0.8290077007028753, 0.8031834485809914, 0.8257170891283252, 0.7916086008552314, 0.863425714809489, 0.8242708415358363, 0.8211096507372021, 0.7955458964325176, 0.8235442390602492, 0.8304141957932558, 0.807408840564974, 0.845816492260466, 0.7885842869397715, 0.8131599026295298, 0.8271684315345629, 0.7903988852609578, 0.8085151701184525, 0.8056683727067224, 0.8091661520193467, 0.7947771184472797, 0.8178671933073343, 0.7922848522435648, 0.7947143880922347, 0.8622263547432516, 0.8038763791451415, 0.8131252342015196, 0.8257563875695736, 0.8265974631562306, 0.8287749356304568, 0.8247134766692232, 0.8174280217603827, 0.8184228185516504, 0.8136087135592621, 0.8185903484099996, 0.8173581337545757, 0.8078671023012942, 0.8500483846807659, 0.8227207937062427, 0.8154059286740466, 0.8076485776570366, 0.80887818540449, 0.809141671193603, 0.8143715566830334, 0.8106854454666182, 0.8196737985005182, 0.8082876464927473, 0.8258663694779699, 0.8130182401573931, 0.8177788282957522, 0.8215943957438684, 0.813128659221281, 0.8159718684770129, 0.8154128456467775, 0.8118653079719325, 0.8184228185516504, 0.8118625075427894, 0.8239214730007772, 0.809869796688778, 0.8087969283403883, 0.8108445447688972, 0.8226646461343876, 0.8139808948587166, 0.8287010191822995, 0.8112875424751216, 0.8301352357467053, 0.8121663444417596, 0.8101549730590891, 0.8163469414192305, 0.8086209796327823, 0.8173857872685055, 0.8181150440245307, 0.83288292669947, 0.8069432561725464, 0.8241519077986604, 0.8103677833128581, 0.8335004622286053, 0.8081147712352609, 0.8139165890418442, 0.8072658218645117, 0.8156598712567066, 0.8074729986133289, 0.8300722572571321, 0.8149128154573757, 0.8133966926656362, 0.8124162541753309, 0.8059111851763203, 0.8114317010713654, 0.8163672273246625, 0.8388264496276377, 0.8130401242467883, 0.813601101513741, 0.8102438665025055, 0.8320003842470592, 0.8350211939534031, 0.8285235597687091, 0.8083105927447051, 0.81864291248459, 0.8102382325612769, 0.8388237505066017, 0.8216601657251236, 0.8387556766984605, 0.8227225276500825, 0.8066372776716542, 0.817988937741808, 0.8121882352349088, 0.8111252702915595, 0.8281627803828299, 0.8260675282919564, 0.8115427488024908, 0.819733795630117, 0.8211490659681857, 0.8136682179372002, 0.8169942772242379, 0.8321348851095587, 0.818766090565943, 0.830693674492909, 0.8159384764373074, 0.8255295069421873, 0.8254323468785982, 0.8102965455223166, 0.8160034749394214, 0.8093308748232182, 0.8154729062519748, 0.8246718234772356, 0.8163113440795975, 0.8044947981845747, 0.8217837881073977, 0.8214779112817807, 0.8202711062556386, 0.8094245089610681, 0.8093738313160186, 0.8204953725671386, 0.8158528716083799, 0.8105026445352456, 0.8265091973885397, 0.817535960952665, 0.8169723963202207, 0.8185427424547365, 0.8251471243429902, 0.8164009180262095, 0.8035390978699354, 0.8099256399419694, 0.841032044311612, 0.8171566687702001, 0.8054585692599444, 0.8118711582847145, 0.8175550343571982, 0.8250350864872111, 0.8215277462802376, 0.809377309190906, 0.8087047758616608, 0.8153185886167259, 0.8131222607165546, 0.8092476726745048, 0.8037125715426479, 0.8152921697015009, 0.8112560025900137, 0.8003908385706016, 0.8163190988256878, 0.8358157008039926, 0.8175574914529798, 0.8023092357473963, 0.8085025868438169, 0.8046072284185385, 0.8101091149882309, 0.8066113152871, 0.8001462878967647, 0.8014890906061183, 0.8129011663325387, 0.8236187446244185, 0.8163190988256878, 0.8090229672723979, 0.8109638060127542, 0.8112875545986065, 0.7927081920947876, 0.8144842970978516, 0.8132617791483101, 0.814858932257903, 0.813654566894997, 0.7675145524803668, 0.819452011337586, 0.7852452049741071, 0.8097071808446665, 0.799358053070703, 0.8103667484152952, 0.8163190988256878, 0.822191173502681, 0.8013059030283289, 0.8116478747236734, 0.8622847336040784, 0.8200137590169415, 0.8101205332477075, 0.823204105576969, 0.8132303281908962, 0.8085970965575451, 0.803915219711602, 0.796077153037361, 0.8134816381055139, 0.8028247357764073, 0.8203096116492803, 0.809118482320161, 0.811180374692521, 0.8141117855132525, 0.8042206436930848, 0.8046100481157854, 0.8287922850141942, 0.8101243481962808, 0.8013516194872681, 0.819574595589328, 0.816703402435271, 0.8143834706752694, 0.810812873980368, 0.8305553430004178, 0.8262405347567554, 0.8192932085766387, 0.7920481932612575, 0.8112365838553288, 0.7957500362554346, 0.8051280567277275, 0.8188501675899923, 0.811582259726352, 0.8195468735104768, 0.8060500322029265, 0.8074251351138921, 0.8206681798716406, 0.8265820384109974, 0.7998772693344508, 0.8093598546101811, 0.7909716002296541, 0.8086365812229401, 0.8111622005504945, 0.8369751002046103, 0.8239563241301238, 0.8180605428243732, 0.8050008560372831, 0.8069049997410662, 0.8139184992443917, 0.8083542632093114, 0.8203964257403238, 0.8076909726688324, 0.845055333061793, 0.8032021292482021, 0.8192275237480413, 0.8078773296852996, 0.8168174039309756, 0.8071530841520576, 0.8091546201715986, 0.8075822855496989, 0.8123338836773847, 0.8222187685519001, 0.8112183590609703, 0.8154128622589202, 0.8244863494687749, 0.8497420163683668, 0.8127086746752485, 0.8220658149111395, 0.8064638981033688, 0.811180374692521, 0.8008223311801604, 0.8088896586299479, 0.8130096132889317, 0.8192123717047846, 0.8231008995505624, 0.8111283378723334, 0.8094691176085602, 0.8131993000311717, 0.8222204685339317, 0.805428036472177, 0.8073255147915642, 0.8106483188276101, 0.8055509826611441, 0.818395961809175, 0.8008298925403338, 0.8282732761571244, 0.8112321826172788, 0.8123103419924295, 0.8177738143515085, 0.812623957149895, 0.8311828240303486, 0.8274452213343979, 0.8135541422863705, 0.8023092357473963, 0.8097477619605928, 0.8106149482237033, 0.8100029610265729, 0.8226001220038288, 0.8142655278615823, 0.8164695401075468, 0.820807393721744, 0.8116959310464056, 0.8041369757027382, 0.812238018276043, 0.8098665261126087, 0.8047695106174775, 0.7968277024562249, 0.8167642183182624, 0.8037892178912902, 0.8205475110255144, 0.8149729939052449, 0.814987260375783, 0.8204533248303367, 0.8244378262454036, 0.8104051417137843, 0.8160978225069944, 0.8128615897839342, 0.8187748571688722, 0.812028190299133, 0.8252753146860583, 0.8162943836073977, 0.8207304150947019, 0.805283012616014, 0.8075873623389963, 0.8080521943394533, 0.8147575166740632, 0.8111527912921419, 0.8112322655172294, 0.812238018276043, 0.8042606661971041, 0.8152889294532347, 0.8219444979848067, 0.8033218799227371, 0.8217354240654522, 0.8104362151211622, 0.8157987345222377, 0.8005039274362631, 0.8062347156900668, 0.8135730036591816, 0.8146894639996219, 0.818868539026718, 0.8174570444389587, 0.8230803386847919, 0.8150667233804645, 0.8282467049004287, 0.811189714601654, 0.8101697326778794, 0.8142357702503474, 0.806477586048674, 0.8034339947434509, 0.8031734585642859, 0.8426641923226281, 0.8084649682298825, 0.8198338287030488, 0.8044329452593975, 0.8400386125373114, 0.818868539026718, 0.8135746190862385, 0.8242477859430108, 0.8120713752495174, 0.8089503462479911, 0.8069411291206343, 0.8260109847130938, 0.8123418486259011, 0.8180041656794007, 0.812238018276043, 0.8126336552083773, 0.8140881750061656, 0.8133996958014927, 0.8056922325705116, 0.8131461783615732, 0.8070852041842649, 0.8167642183182624, 0.8400166448493914, 0.8066503982342436, 0.8210010616313145, 0.807495630651441, 0.8205116870627636, 0.8418532477653958, 0.8267974009012036, 0.8070852041842649, 0.8104492017699805, 0.8038498829644745, 0.8048484349554406, 0.8124367623187208, 0.8123813483994742, 0.8046206559607862, 0.8111612251768566, 0.8066687258399435, 0.8107387871240096, 0.8085283250149107, 0.8251403853601765, 0.8202942196393972, 0.8049025497532298, 0.8109864380948334, 0.8169658948502324, 0

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

Fase 4 MLP perfil interno {'accuracy': 0.8164852255054432, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8164852255054432), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.898972602739726), 'f1_macro': 0.449486301369863, 'f1_weighted': 0.7339978482711604, 'precision_macro': 0.4082426127527216, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 118, 'FN': 0, 'TP': 525, 'score_source': 'predict_proba', 'auroc': 0.449273607748184, 'ap_0': 0.16552876848483103, 'ap_1': 0.7902706127533141, 'model': 'MLP', 'params': {'alpha': 0.0001, 'hidden_layer_sizes': (32,), 'max_iter': 500}, 'indices': [2, 5, 13, 15, 19, 38, 42, 43, 45, 46, 47, 48, 49, 54, 58, 60, 75, 78, 80, 81, 83, 84, 89, 90, 91, 92, 94, 96, 102, 104, 108, 111, 112, 114, 115, 117, 118, 131, 155, 157, 161, 163, 170, 172, 181, 187, 190, 191, 193, 196, 199, 203, 205, 212, 216, 219, 223, 226, 227, 232, 237, 245, 256, 265, 269, 270, 276, 277, 278, 287, 309, 317, 327, 339, 342, 344, 365, 382, 409, 416, 419, 421, 427, 428, 429, 430, 438, 439, 445, 454, 458, 459, 465, 469, 471, 472, 478, 489, 494, 495, 499, 501, 503, 505, 508, 532, 539, 541, 545, 549, 551, 557, 558, 563, 568, 570, 574, 586, 588, 598, 602, 607, 609, 628, 630, 631, 637, 638, 642, 4, 10, 11, 12, 18, 20, 23, 29, 34, 40, 51, 62, 66, 67, 77, 87, 101, 109, 119, 120, 129, 134, 139, 143, 146, 150, 158, 159, 175, 177, 179, 182, 185, 204, 207, 220, 225, 229, 231, 233, 235, 236, 239, 240, 241, 242, 243, 247, 254, 258, 259, 264, 266, 268, 271, 275, 279, 280, 282, 284, 286, 288, 292, 310, 311, 318, 322, 325, 330, 332, 334, 337, 340, 347, 348, 349, 358, 360, 364, 380, 381, 391, 394, 395, 399, 400, 406, 411, 414, 417, 424, 426, 431, 433, 444, 448, 451, 464, 476, 484, 488, 490, 491, 502, 517, 524, 529, 530, 531, 535, 538, 550, 559, 572, 576, 579, 590, 592, 595, 597, 600, 611, 612, 615, 623, 625, 626, 636, 639, 0, 3, 25, 26, 27, 31, 32, 50, 55, 57, 64, 65, 72, 85, 86, 88, 95, 97, 99, 107, 121, 124, 127, 130, 135, 137, 138, 142, 147, 152, 168, 176, 178, 183, 184, 192, 194, 200, 201, 213, 222, 228, 238, 263, 272, 281, 285, 290, 293, 294, 295, 297, 298, 303, 307, 308, 314, 315, 316, 320, 321, 323, 328, 336, 341, 350, 352, 353, 357, 361, 363, 368, 369, 375, 376, 388, 392, 396, 397, 403, 408, 420, 423, 432, 437, 440, 449, 452, 455, 456, 460, 462, 466, 468, 473, 480, 481, 483, 487, 492, 500, 510, 512, 516, 518, 519, 522, 526, 528, 533, 536, 537, 546, 548, 553, 565, 566, 575, 580, 584, 604, 605, 608, 613, 617, 621, 622, 634, 640, 1, 6, 22, 28, 30, 39, 41, 44, 53, 56, 70, 71, 73, 74, 76, 82, 93, 105, 106, 110, 113, 122, 123, 126, 132, 136, 141, 148, 149, 151, 154, 160, 162, 164, 165, 180, 188, 189, 198, 208, 210, 211, 215, 221, 224, 244, 246, 252, 255, 262, 273, 283, 289, 296, 304, 306, 313, 324, 329, 335, 343, 345, 346, 351, 354, 356, 359, 370, 371, 373, 374, 378, 383, 384, 385, 387, 393, 401, 402, 405, 413, 415, 422, 425, 436, 441, 442, 443, 447, 450, 467, 470, 475, 479, 482, 485, 496, 497, 504, 511, 515, 521, 527, 534, 540, 542, 547, 556, 560, 564, 567, 569, 571, 573, 577, 581, 583, 585, 587, 599, 603, 616, 618, 620, 624, 627, 629, 633, 7, 8, 9, 14, 16, 17, 21, 24, 33, 35, 36, 37, 52, 59, 61, 63, 68, 69, 79, 98, 100, 103, 116, 125, 128, 133, 140, 144, 145, 153, 156, 166, 167, 169, 171, 173, 174, 186, 195, 197, 202, 206, 209, 214, 217, 218, 230, 234, 248, 249, 250, 251, 253, 257, 260, 261, 267, 274, 291, 299, 300, 301, 302, 305, 312, 319, 326, 331, 333, 338, 355, 362, 366, 367, 372, 377, 379, 386, 389, 390, 398, 404, 407, 410, 412, 418, 434, 435, 446, 453, 457, 461, 463, 474, 477, 486, 493, 498, 506, 507, 509, 513, 514, 520, 523, 525, 543, 544, 552, 554, 555, 561, 562, 578, 582, 589, 591, 593, 594, 596, 601, 606, 610, 614, 619, 632, 635, 641], 'y_true': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1], 'y_pred': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'score': [0.7445959171603463, 0.8149912721491097, 0.8398168920060878, 0.8312898554511617, 0.8619137864039643, 0.8453191706787944, 0.731588980347515, 0.8606269303039216, 0.7882113797387612, 0.8278466601557654, 0.8672760278094291, 0.8402943804108343, 0.7954386064979485, 0.8508026164109314, 0.8438346894497697, 0.8493436234227628, 0.6824848411305596, 0.8402268709197218, 0.5051049248676057, 0.8150434698886351, 0.8613126321099107, 0.8479244014179074, 0.7402590127261643, 0.7467694538306979, 0.8265917000693538, 0.8670830249614108, 0.8393265030341557, 0.7735218775100348, 0.825873539411614, 0.8170861538107144, 0.8678722153795266, 0.7793676010298848, 0.7601124035311992, 0.790779526552718, 0.8666095558240826, 0.8402943804108343, 0.857443379674692, 0.8130708944472346, 0.7396908230965946, 0.824984995110022, 0.8569363969516457, 0.8079953211683637, 0.8109205882782797, 0.8103720121099991, 0.8199669957582042, 0.8175731676595237, 0.8638798383554149, 0.7040431683737159, 0.8588674994911439, 0.8438703217948842, 0.8531629143368921, 0.8496434328026414, 0.8653013166318348, 0.7289266583503726, 0.6279174373653863, 0.8238697040953952, 0.8265917000693538, 0.8510453498081901, 0.8056062537308897, 0.8669860642315175, 0.7735218775100348, 0.8263295287969882, 0.7917616622703731, 0.7963583253584, 0.8509179629527284, 0.8599842307219034, 0.7123266482852294, 0.6696966123835075, 0.800355433902161, 0.7798978912740917, 0.8565819494831792, 0.8184598766159159, 0.8678716139605068, 0.6456315307989406, 0.6924555330020777, 0.7156855506657119, 0.849032624493252, 0.82009064490024, 0.827293838617976, 0.8364607986577506, 0.8237854229713989, 0.8675355050201874, 0.7031668364827305, 0.8211466788693216, 0.8324249402546384, 0.7138175141690254, 0.7680832399666025, 0.8650885101578941, 0.8664977780878906, 0.8641027374228223, 0.863885715268561, 0.8676298963620456, 0.8514999188583345, 0.8119569775895583, 0.8310064598088946, 0.8229716434371015, 0.8491595902646241, 0.8327761046389556, 0.6936256486531436, 0.8632741493085019, 0.800485206096184, 0.8224774497187187, 0.8230294702992336, 0.8013990855410322, 0.8079953211683637, 0.8387993624720383, 0.798411009325988, 0.848969196538772, 0.8603074036103753, 0.7700518720328573, 0.8608680412708003, 0.826890348569961, 0.7639850240236619, 0.842047388980629, 0.8398773688774662, 0.8105347430337695, 0.8667797034160459, 0.8520162127137458, 0.8114068503261999, 0.830180025096008, 0.8509324440118247, 0.8395123384959324, 0.790388126741466, 0.7971806019953425, 0.8678608534895996, 0.5670362064667761, 0.7396908230965946, 0.8265917000693538, 0.8567715415625152, 0.8311511347917377, 0.8166130387546013, 0.8116155050096439, 0.8031957385838998, 0.8245822737798078, 0.8287067719368719, 0.8497297180687664, 0.8029727796524458, 0.8325987529360794, 0.820518601443504, 0.8125757872870393, 0.8175582563761858, 0.8097304110956867, 0.8074286681261057, 0.8002101087422936, 0.8103360929267793, 0.791555173936451, 0.7917517030756407, 0.7910733595627237, 0.8278042818333894, 0.8279814274934733, 0.810711454743414, 0.7863702675441154, 0.7951209438471272, 0.817526843172843, 0.8245798230491239, 0.7910711100754131, 0.7967322388407536, 0.8652106958286101, 0.79577142290525, 0.8240461319101353, 0.7930109541206687, 0.8116073184862893, 0.792004208844261, 0.8070719177412972, 0.7882144728148016, 0.8106175596982237, 0.800527486564589, 0.7983128633735131, 0.7922088712366636, 0.8296280125799343, 0.8093858424970497, 0.8206842468906087, 0.8139400890768502, 0.7999011994044083, 0.8325726582638744, 0.8174860099923416, 0.8155122074560988, 0.8333961909663825, 0.7951641949544851, 0.8000257488143776, 0.8335974612761958, 0.8468362612216553, 0.7943317467878128, 0.8060838771582093, 0.8126314036587423, 0.8077569402074205, 0.8389811393685148, 0.8459174556490394, 0.8011308605158298, 0.8237800085239935, 0.8332439667421321, 0.7990684304306324, 0.8123840216139795, 0.7939662564324084, 0.8263651221100258, 0.8120102505837282, 0.8105505955799887, 0.8095247535793229, 0.811661495284086, 0.7894069573746882, 0.8178612053628378, 0.8009190058542253, 0.8033513735148059, 0.7966273833189069, 0.8215574666079515, 0.819719591695723, 0.8350087596408446, 0.793198183870483, 0.8137572396675321, 0.8255288506523094, 0.803018846123711, 0.8112463345443037, 0.8103360929267793, 0.8531726837161397, 0.786473594750307, 0.7946949798693512, 0.8094569117555878, 0.8227354666910852, 0.816934567289144, 0.7988340310685724, 0.8246097700493118, 0.8214049021510567, 0.8367869767492607, 0.8125312671892738, 0.8560359613372455, 0.8277554524548509, 0.8098445064397035, 0.8095923853140856, 0.8344476641939899, 0.7881779885727794, 0.8193006493124748, 0.7850775507225031, 0.8166107070663321, 0.8343294384050427, 0.8280548325615671, 0.7841818693135557, 0.806407715964343, 0.7930195896531916, 0.8049750828139242, 0.7966231912269011, 0.816448714925283, 0.8207505309007308, 0.8089286475604738, 0.8101547006304106, 0.785645209335941, 0.8198697588487045, 0.8055213667452114, 0.8025800867176163, 0.8031306637820451, 0.8381757763874569, 0.7990244835699828, 0.8281505344669597, 0.8316098925616501, 0.7839883742815984, 0.8174870943268335, 0.8050169718710437, 0.8011308605158298, 0.8111291086344938, 0.8131519956313582, 0.8223927699385583, 0.8184028551626115, 0.7777490123593535, 0.8251717754258596, 0.8231931715213733, 0.8193922151190961, 0.8320975982959838, 0.8104262169854326, 0.8235817255179263, 0.8141052965864939, 0.8198415135154604, 0.813606002207532, 0.8176634480437599, 0.8257677544072821, 0.812758289160012, 0.8347251750435916, 0.805926536753916, 0.8120694186665569, 0.812450879458072, 0.82260147849462, 0.8431668631269094, 0.8269685125132046, 0.8122868116593178, 0.8187932589385898, 0.8190627707153781, 0.8055862411919714, 0.8127936613931392, 0.8169089314793959, 0.8067186034167255, 0.8141936946568317, 0.8078727825178806, 0.8226084970866351, 0.8118329222168018, 0.8119331495487818, 0.8132737348938297, 0.8091449092867726, 0.8212812619874177, 0.8131382490451864, 0.7909069745333763, 0.81322939042009, 0.8121795919834701, 0.8130659181491058, 0.8151306460877628, 0.7993775484220278, 0.8173663767257062, 0.8121485057709255, 0.8206821294287355, 0.8210985354796743, 0.8354047015446975, 0.8270114310626342, 0.8070476212116219, 0.8366044449878475, 0.810856285714291, 0.8253854756024397, 0.8242294952989248, 0.8168103378364725, 0.8116920352187353, 0.8168237936429403, 0.8102181571088813, 0.8113462579117074, 0.8190272640358088, 0.8049946294439033, 0.7962578888669709, 0.8159097670697637, 0.8288033980499989, 0.8297019376250343, 0.816842689703939, 0.8136091849808904, 0.8043617281928249, 0.8130804496248034, 0.834147489155694, 0.8094017319875529, 0.8353710015368442, 0.8154128155098895, 0.8129605124555374, 0.8308397643027551, 0.8088477034636785, 0.8119310762269102, 0.8137883459314283, 0.8141727956716551, 0.8153644039400699, 0.8233109214249736, 0.8178984992496712, 0.8223750532281914, 0.81341485633598, 0.8126582556382888, 0.8184933348544403, 0.8160396216531984, 0.8220469355746974, 0.8265660337346734, 0.8260521513994126, 0.8219516146486345, 0.813043302773435, 0.8379284449033708, 0.8312306972039891, 0.8286994901891298, 0.8113036884048344, 0.8106682515920749, 0.8119614590754937, 0.8097836907069851, 0.8219464295501766, 0.8162555687004904, 0.8230620445045403, 0.7894803111800954, 0.8136631020375897, 0.8125752051811148, 0.8177830176485367, 0.8178647385357142, 0.8106376560303625, 0.8158673031722184, 0.843476045653308, 0.8210603270492959, 0.8282888978897006, 0.8241770778519355, 0.8221546273223371, 0.8230825007115273, 0.8122276157478627, 0.8150013799558595, 0.8213514208735144, 0.8133679754978083, 0.8181174159173292, 0.8273790640715422, 0.8170975763174813, 0.810818586353831, 0.8353710015368442, 0.8129666927928039, 0.8235465389995829, 0.8095925565861084, 0.821918459696745, 0.8119037076692237, 0.8194544892022657, 0.8050173862399085, 0.8203781552973594, 0.8140423695151815, 0.7915844411943399, 0.8176620455926755, 0.8172835565260634, 0.8009688443403583, 0.821912934604469, 0.8209839030254205, 0.8273698427612004, 0.7909202809764044, 0.8119562080232061, 0.8218700870082571, 0.8007722247423594, 0.794564512430725, 0.8218497366044154, 0.8044488606550431, 0.8176174321715932, 0.8230927822398094, 0.8037557578913417, 0.8178765147004396, 0.8297947040105337, 0.8160350231977909, 0.8138795454994213, 0.7762992484402262, 0.791875509194517, 0.8224368311512011, 0.8116622122165851, 0.8260402007723225, 0.8229659406054376, 0.8210369666816394, 0.8202179248624131, 0.718236917493343, 0.8227292539601739, 0.8120238643384952, 0.8178765147004396, 0.8282020895314135, 0.7832481214060832, 0.7965906304683602, 0.8176421185723267, 0.8112502065136737, 0.8149269359540398, 0.8151604348804703, 0.7931603574189202, 0.8052966787695188, 0.8237079628922397, 0.8006491169622253, 0.8288176843365376, 0.8256601048375177, 0.8139131313652646, 0.8086023462328689, 0.8264788040526783, 0.8206175432768262, 0.8217319709669153, 0.8357323557763807, 0.8269621114001099, 0.8098724134433889, 0.7784996242499782, 0.7805870209741614, 0.8229633756822716, 0.8232700175508885, 0.8068111502885179, 0.8192605419573844, 0.8375951950866807, 0.7843474978749229, 0.828389309230871, 0.82298344810943, 0.8263508920723142, 0.7947850829993403, 0.7877340305068042, 0.8063050799336796, 0.8139013218632171, 0.8073801043113976, 0.8181403857783195, 0.7823521433516076, 0.8318781832565548, 0.8155985588967003, 0.8218497366044154, 0.7910497177237366, 0.7872469835810018, 0.8226429480200839, 0.8136035197022725, 0.8369970158037054, 0.8120238643384952, 0.7693368684915746, 0.8199560822992542, 0.8228771258209961, 0.8028681949110208, 0.821260153872678, 0.8179553531010131, 0.8152670600559201, 0.821765691841277, 0.8038166180871992, 0.8119598576031339, 0.7996087057019146, 0.8201908397804637, 0.8231397738242812, 0.8226348271322002, 0.8123795677570074, 0.8064014118343881, 0.786038435365856, 0.782303246393343, 0.815702480862336, 0.8179275767562771, 0.8204153669446974, 0.793714926120915, 0.8327363005335755, 0.7905477361813954, 0.8218504643071419, 0.8023239508620034, 0.8198795645413641, 0.7481160453961342, 0.8066783129091801, 0.8254105095692268, 0.8050822806205862, 0.781677296946561, 0.819645260267019, 0.8137694293352036, 0.8167689193883716, 0.8264617757324422, 0.8218497366044154, 0.718236917493343, 0.8268904841972559, 0.8129095630142403, 0.8090589267694929, 0.8096737413982993, 0.8139320391554273, 0.8341462130626235, 0.8297261917798874, 0.8217786410459194, 0.8261544076498499, 0.8243739321806721, 0.8050590370318342, 0.8077112129847365, 0.8119718548444776, 0.8139332524767935, 0.8061785523217552, 0.8173866236765199, 0.8104802170052338, 0.8052856327933213, 0.809510665430196, 0.8170912950552843, 0.8078838764955181, 0.8160932012105704, 0.8403270564775918, 0.8102247410123509, 0.8090849952781737, 0.8245006936634633, 0.808310338241116, 0.8099290492883047, 0.8064162218421366, 0.8119939227547887, 0.8169872942952127, 0.8098163005395781, 0.8117371355144556, 0.8267442302023298, 0.847596172777745, 0.8144206636037895, 0.815541783625601, 0.8128567150185184, 0.8010771663564762, 0.8082705488121176, 0.8137801133777831, 0.8170959188232383, 0.8152302089577372, 0.811970175612978, 0.7957866110058294, 0.8187721673728884, 0.7994452516929839, 0.8109134458773953, 0.8053723684428435, 0.8230059512298901, 0.8323749946540653, 0.8130813698490542, 0.8227595462741911, 0.825701113810281, 0.8185357060649711, 0.8143338408703767, 0.813301454996877, 0.8201563622125813, 0.8146487324966, 0.8221040061774859, 0.809826228458074, 0.7938449024384996, 0.8083862031417679, 0.7779268653641574, 0.8132093038312768, 0.8123711965091587, 0.7877441699947221, 0.8110007748830956, 0.8079767081890935, 0.7920666523689895, 0.8142179992727563, 0.8349405353873742, 0.821803135710249, 0.8142456428591371, 0.8277826305115308, 0.8097773313297173, 0.8297535885545919, 0.8227039994994932, 0.8054816160980625, 0.8270422190643751, 0.8189921155478916, 0.8094474016307212, 0.8080598277561016, 0.8048184503335516, 0.8308835692279761, 0.8178047173709089, 0.7965616028111647, 0.808692612642651, 0.7605272106616219, 0.8093102225344116, 0.8081459938859314, 0.8096255336774891, 0.8239616979361271, 0.7762597774992523, 0.8178047173709089, 0.780113804623069, 0.8271609214239323, 0.8107071429352855, 0.8118102867370715, 0.810670979586557, 0.8153341428996506, 0.8197123955776989, 0.8095576276474288, 0.8147493161299583, 0.8097163039042634,

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

Fase 4 MLP perfil interno {'accuracy': 0.8164852255054432, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8164852255054432), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.898972602739726), 'f1_macro': 0.449486301369863, 'f1_weighted': 0.7339978482711604, 'precision_macro': 0.4082426127527216, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 118, 'FN': 0, 'TP': 525, 'score_source': 'predict_proba', 'auroc': 0.44706214689265533, 'ap_0': 0.182811916139069, 'ap_1': 0.7941717363737775, 'model': 'MLP', 'params': {'alpha': 0.0001, 'hidden_layer_sizes': (32,), 'max_iter': 500}, 'indices': [3, 6, 13, 15, 20, 39, 43, 44, 46, 47, 48, 49, 50, 55, 59, 62, 68, 77, 80, 82, 83, 87, 88, 91, 92, 94, 95, 96, 98, 105, 106, 109, 110, 113, 115, 117, 119, 131, 155, 157, 160, 162, 168, 172, 180, 185, 187, 189, 191, 195, 198, 202, 204, 209, 213, 216, 220, 223, 224, 230, 248, 249, 255, 264, 268, 273, 275, 278, 282, 284, 308, 316, 325, 337, 341, 360, 371, 396, 413, 416, 418, 420, 426, 427, 428, 434, 436, 437, 443, 452, 456, 463, 466, 468, 469, 470, 476, 486, 491, 497, 499, 501, 503, 505, 519, 530, 540, 543, 547, 549, 551, 552, 560, 563, 568, 570, 573, 586, 588, 600, 602, 607, 608, 628, 630, 631, 637, 638, 642, 4, 8, 11, 12, 19, 21, 23, 27, 28, 34, 52, 57, 67, 69, 79, 90, 107, 111, 120, 121, 129, 134, 139, 143, 146, 150, 158, 166, 175, 178, 181, 188, 192, 203, 212, 217, 222, 225, 228, 231, 233, 234, 237, 238, 239, 240, 241, 251, 252, 257, 258, 263, 265, 267, 269, 276, 277, 279, 280, 286, 290, 291, 296, 309, 310, 317, 321, 327, 329, 332, 335, 338, 344, 345, 346, 347, 355, 362, 368, 377, 378, 389, 391, 393, 397, 398, 404, 410, 414, 422, 424, 425, 430, 431, 442, 446, 458, 462, 473, 482, 485, 488, 489, 500, 515, 528, 529, 533, 536, 537, 538, 550, 554, 571, 576, 579, 590, 592, 595, 598, 599, 610, 612, 615, 624, 625, 626, 636, 639, 0, 1, 25, 29, 30, 32, 33, 41, 51, 56, 65, 66, 74, 81, 84, 89, 97, 99, 101, 104, 118, 124, 127, 130, 135, 137, 138, 142, 147, 152, 167, 174, 177, 182, 183, 190, 193, 199, 200, 219, 235, 236, 246, 262, 270, 281, 285, 287, 292, 293, 294, 299, 300, 303, 306, 307, 312, 313, 314, 318, 319, 331, 334, 339, 348, 350, 354, 357, 358, 361, 364, 367, 372, 373, 382, 386, 394, 395, 400, 403, 407, 419, 421, 435, 438, 447, 449, 450, 453, 457, 460, 464, 465, 467, 471, 478, 479, 481, 494, 495, 498, 508, 510, 514, 516, 518, 521, 524, 527, 531, 534, 535, 542, 544, 556, 566, 567, 575, 581, 585, 605, 606, 609, 613, 617, 621, 622, 634, 640, 2, 7, 22, 26, 31, 40, 42, 45, 54, 58, 72, 73, 75, 76, 78, 85, 86, 93, 103, 112, 114, 122, 123, 126, 132, 136, 141, 148, 149, 151, 154, 159, 161, 163, 164, 179, 186, 197, 206, 207, 211, 218, 221, 226, 229, 242, 243, 247, 253, 261, 271, 283, 289, 301, 302, 305, 311, 320, 326, 333, 340, 342, 343, 349, 351, 353, 356, 365, 366, 370, 375, 379, 380, 381, 384, 385, 390, 399, 402, 409, 412, 415, 423, 429, 433, 439, 440, 441, 445, 448, 472, 474, 477, 480, 483, 487, 493, 502, 504, 509, 513, 525, 526, 532, 539, 541, 548, 559, 561, 564, 565, 569, 572, 574, 577, 580, 583, 584, 587, 597, 603, 616, 618, 620, 623, 627, 629, 633, 5, 9, 10, 14, 16, 17, 18, 24, 35, 36, 37, 38, 53, 60, 61, 63, 64, 70, 71, 100, 102, 108, 116, 125, 128, 133, 140, 144, 145, 153, 156, 165, 169, 170, 171, 173, 176, 184, 194, 196, 201, 205, 208, 210, 214, 215, 227, 232, 244, 245, 250, 254, 256, 259, 260, 266, 272, 274, 288, 295, 297, 298, 304, 315, 322, 323, 324, 328, 330, 336, 352, 359, 363, 369, 374, 376, 383, 387, 388, 392, 401, 405, 406, 408, 411, 417, 432, 444, 451, 454, 455, 459, 461, 475, 484, 490, 492, 496, 506, 507, 511, 512, 517, 520, 522, 523, 545, 546, 553, 555, 557, 558, 562, 578, 582, 589, 591, 593, 594, 596, 601, 604, 611, 614, 619, 632, 635, 641], 'y_true': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1], 'y_pred': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'score': [0.823543154358471, 0.8290444038409921, 0.7923541986382772, 0.7701591427919638, 0.8029662200437191, 0.8138973426732796, 0.7844335909150272, 0.8409680278683901, 0.7975046475741936, 0.8492715198344672, 0.8378058983409433, 0.799823855156484, 0.810224563637599, 0.8104761521069273, 0.8312644366010506, 0.7928382137898671, 0.8154987636377543, 0.7050901669327405, 0.8059760548873038, 0.7640227494103432, 0.8481027210760722, 0.8244049476413406, 0.8166040857710154, 0.8218639572284026, 0.8498762343393906, 0.8071273422324172, 0.7845408095064761, 0.8221114477465836, 0.8478143412971182, 0.8289016189353161, 0.8498783270194478, 0.6593863520015005, 0.8423134333115534, 0.764925031643914, 0.8340330866709682, 0.8161910369466117, 0.839336080264918, 0.8154987636377543, 0.8498638391073049, 0.8431512968073642, 0.8080915857121503, 0.8216958422677682, 0.8419130617726225, 0.8326415418128367, 0.8433500366621519, 0.8348253601191089, 0.7596914135624268, 0.83504989643594, 0.8101977402406412, 0.8498459955584086, 0.8308724623337703, 0.8486695688009833, 0.8355644542834716, 0.7920431932222808, 0.7930854259794129, 0.8498513523384945, 0.8350862856272098, 0.8141766795643303, 0.8411970238277904, 0.8403998502350156, 0.7010386163178415, 0.8089941108270621, 0.8498086293902934, 0.810983111655092, 0.8253994607021549, 0.8300202785916863, 0.7050901669327405, 0.7931126089371642, 0.8492189775846338, 0.8139434296945763, 0.8135820247912019, 0.8418690213898901, 0.8424445541239317, 0.8498629249215538, 0.8399312071365579, 0.7297855353136529, 0.8407473573916049, 0.8324557092149215, 0.8193697561532052, 0.8498783876254741, 0.79673029965673, 0.8338992925410669, 0.8498702478639085, 0.673507703923301, 0.8247513450529622, 0.8312285882745188, 0.8160146126906904, 0.8171075189762238, 0.8173581647449663, 0.8244049476413406, 0.8202890945142854, 0.7640237924576982, 0.8219411829885844, 0.7945612346443565, 0.8027776146985219, 0.8498779748090748, 0.8309138692371235, 0.8121619177743105, 0.8498513594606842, 0.7985523385845935, 0.7677347729213281, 0.8161900458745321, 0.8071489556930038, 0.7976725475073929, 0.8030286543783081, 0.7585717580892897, 0.8135777971187783, 0.7592014617968893, 0.8478571796235453, 0.8300966194670668, 0.8253932112269453, 0.7760073386776494, 0.8468280522239482, 0.8420462236773977, 0.7945612346443565, 0.7258455921509854, 0.8497707435921582, 0.7732261591599019, 0.8223563665284557, 0.813536033674054, 0.8498277078723859, 0.8015822724401032, 0.8251025604091649, 0.7994955825952482, 0.849878821668667, 0.7893643704596163, 0.7790770985338628, 0.8218639572284026, 0.8450059748831531, 0.8293007070638512, 0.8268737091095046, 0.8180097770083947, 0.8249336276592331, 0.831800810736131, 0.8133953276469488, 0.7862550631814311, 0.8302936123063838, 0.8139137976422196, 0.810923153218128, 0.8255631838494336, 0.8300994427158137, 0.8347355393648834, 0.8017986767773964, 0.8338414828529181, 0.7626908238076956, 0.8303149391507496, 0.8106456012972336, 0.7761596366382679, 0.8339131137356054, 0.8041717766393705, 0.806605391362654, 0.8189678332609454, 0.7887864708517472, 0.8139784505240776, 0.7391946613050486, 0.8097370861224595, 0.8258046101323678, 0.8295556982597745, 0.820567791775785, 0.8350621259018073, 0.8283044317813001, 0.8270404157737998, 0.8313798212752108, 0.7732411451690377, 0.8161612837560448, 0.820567791775785, 0.809833585454651, 0.8312407344610365, 0.8230872084345207, 0.8173687148894079, 0.7688458755488051, 0.8135100418248264, 0.8245358544055239, 0.7839881880704642, 0.8047259639874875, 0.8230872084345207, 0.8351911913864738, 0.8253896696933204, 0.8354153873969825, 0.7854496337734606, 0.8021292889351347, 0.8149384038562284, 0.8289791035652447, 0.8223748253072621, 0.8328067477877192, 0.834084078600769, 0.7642211281383064, 0.8265729236317096, 0.8296786602951819, 0.7857054292002605, 0.8318985309066027, 0.804851541301406, 0.8293247727608339, 0.8045894073799772, 0.8333359776303689, 0.8155895062490369, 0.8278374497347134, 0.794634713623982, 0.8361842306829133, 0.8158110250374229, 0.8331670262149228, 0.8034965325379588, 0.7776786798278013, 0.7329640725635, 0.8082367621557672, 0.8107214498171167, 0.7870728074113043, 0.8244076903469759, 0.8365240205989739, 0.7699250860676049, 0.8107214498171167, 0.8344467420998736, 0.8229407008560351, 0.8131588579232947, 0.8027699320934942, 0.7691294287682684, 0.8111734285338494, 0.8054974914964654, 0.8327761450087751, 0.7866178551010963, 0.8130511579186989, 0.7817898086862867, 0.7445802176831775, 0.8186621730428453, 0.8285903558826633, 0.8252804916041914, 0.8076906468012316, 0.7932527514607681, 0.8355785422075167, 0.8051812526296699, 0.8271778589562689, 0.8141755562715527, 0.8192446362816268, 0.8244091982211741, 0.7995628392296859, 0.8366295327446975, 0.8137786407301884, 0.8232038324874518, 0.8380332994224305, 0.7859210129968265, 0.7500622246009735, 0.8196498037543488, 0.8223073314349142, 0.7525985054913431, 0.7787069812275893, 0.7632756472599345, 0.8294002607534127, 0.7798868029764199, 0.7925515243807346, 0.8222516761000696, 0.8277847978220645, 0.8140500931135424, 0.7839881880704642, 0.8271171009794445, 0.8314040472942287, 0.8229099660517193, 0.8270404157737998, 0.799594393442749, 0.7899483615632615, 0.8163274863970582, 0.8129955270296468, 0.8076085427142432, 0.8303699469208714, 0.8327165720319611, 0.83505044141711, 0.8105258831785042, 0.8145124464208416, 0.8231444795353792, 0.8128625198863348, 0.8306605941878722, 0.8182284792920175, 0.8346788732675006, 0.8306661150157535, 0.8160195135760473, 0.827228979067961, 0.8281929729830212, 0.8298769705952704, 0.8218402572624693, 0.8317484542992715, 0.8191573351720829, 0.8304136169566905, 0.8301962048575746, 0.8231039581936732, 0.8122945951944669, 0.7796405035723476, 0.8361304275195602, 0.8282147617945268, 0.819827866558712, 0.8292996333919224, 0.8341294440777208, 0.8327151173695231, 0.7924388313543874, 0.7598414416508439, 0.835336635788207, 0.8263594318666586, 0.8337083674275464, 0.8120817497245503, 0.8368171271292197, 0.8117816186050074, 0.8294074194865866, 0.8181976749495057, 0.7958365998403185, 0.7896661287462947, 0.8316472985538003, 0.834514905527727, 0.8258831225444933, 0.8190890493269446, 0.7115221252910995, 0.8157570081208927, 0.8328930574778692, 0.8343394323582676, 0.7467671499480908, 0.8349604320152821, 0.8188244563589153, 0.8118711956749559, 0.827772416004182, 0.8277771687256003, 0.8346647031751656, 0.8345798881205685, 0.8185856654693875, 0.8255607827086162, 0.739209679872447, 0.797340350009336, 0.8310726387590576, 0.8052661771396646, 0.805024332155511, 0.8175715512702457, 0.8336387629931294, 0.8365446578028666, 0.8335383602256277, 0.8268408951678718, 0.8109540017736663, 0.8324886337515126, 0.8211215203752659, 0.8319599298085475, 0.8072132988970042, 0.803042301447166, 0.8203460574050693, 0.7978954954968794, 0.8298545921104893, 0.795381415544264, 0.7999621141839027, 0.8108711804529063, 0.8164005185918043, 0.8269585245854227, 0.8320040652358136, 0.7467148515061897, 0.7825626150645305, 0.8231354829152441, 0.7813660334648935, 0.8292753129114583, 0.7933774964585703, 0.8132732262361271, 0.8319317565327939, 0.8284245251811443, 0.8344619795958559, 0.8251096701909966, 0.8102779556691398, 0.7978539902844353, 0.8226686428156771, 0.7654387197818652, 0.7955893270998298, 0.8359215766172013, 0.8326083863597648, 0.8343135541561436, 0.8371381199656123, 0.8287045563695982, 0.8349739704757855, 0.8314809658923995, 0.8328214760942021, 0.8220413174130105, 0.8279682793207976, 0.7814031739556437, 0.8332614145966554, 0.79581404175449, 0.8122945951944669, 0.8079444708161636, 0.8072423469228165, 0.8025784312546955, 0.7934454834706683, 0.8163877961847034, 0.7753365779029443, 0.8367759218486561, 0.814818409886003, 0.828528376231328, 0.7975724704156241, 0.829703929348773, 0.8109389990978816, 0.81201773251947, 0.8237094405199159, 0.8163195660912674, 0.7892681851083332, 0.847498375325884, 0.8167419589463865, 0.7984121779493707, 0.764227999987807, 0.826372814449298, 0.7824065805538011, 0.798787325485892, 0.8025548183128643, 0.825677853928593, 0.8093643463101092, 0.75410970435327, 0.7529953937822768, 0.8282160782869392, 0.8215020468219475, 0.8103394395274236, 0.7965381343949761, 0.7927515929901772, 0.8224788436780951, 0.8088151029469376, 0.834293189549603, 0.8113324579490231, 0.82906884700697, 0.7727669421903325, 0.804122304982781, 0.7962039616972321, 0.8164995605841046, 0.8194614521005527, 0.8050063185429084, 0.8167419589463865, 0.8355635484298846, 0.804948655367293, 0.8121477121444952, 0.7888259424511042, 0.8335571362976861, 0.8047757804361737, 0.8115222993842066, 0.7991769662677904, 0.7932738111091154, 0.8260450996638319, 0.7858197347596712, 0.7898827234212769, 0.807110597833983, 0.8164342583680353, 0.8424422636189309, 0.794827556382182, 0.8126039333347352, 0.8288675590388216, 0.8502314221421413, 0.8513748548509785, 0.7940599019429375, 0.8158774146245029, 0.7969852716634439, 0.8099843995535887, 0.8314358725662438, 0.8161828140313773, 0.8165662643648559, 0.8255147936662659, 0.7892351050321034, 0.7937448885688593, 0.8380643595724321, 0.8352895374843623, 0.8184815383725889, 0.7962340746858725, 0.8115460451276657, 0.8109389990978816, 0.776193135808954, 0.8307823963123214, 0.8111969322395375, 0.8057277561757598, 0.84211000446314, 0.8136893521895768, 0.8168601618193723, 0.8355635484298846, 0.8243659232699588, 0.8383853449871159, 0.8232529141354439, 0.8098459312588775, 0.7578172952450295, 0.8136047989718987, 0.824573373840116, 0.8326145952674849, 0.7975116760934985, 0.8036318061487864, 0.7902528058954675, 0.797818592734686, 0.803893898923081, 0.8474238295244307, 0.7945306355606204, 0.7702299859767349, 0.7981807160539622, 0.8215002646973201, 0.8197103368941008, 0.8192406839225018, 0.8133958444426252, 0.7894693184401806, 0.8001351202508469, 0.8120745148903901, 0.8131246892208688, 0.866955955340227, 0.8237491139111978, 0.8073491067606422, 0.8449475806407409, 0.8147522280635482, 0.8147522280635482, 0.7494905900486616, 0.8002605338382214, 0.812078629957691, 0.8155335908746277, 0.7921862252275338, 0.7983853449791549, 0.8026881137059189, 0.8082266470275579, 0.8314971040422806, 0.8319953920645335, 0.8230542427690061, 0.8563255888345587, 0.8299434333565422, 0.7599344744363437, 0.8307823963123214, 0.7812001473038523, 0.8488260510334247, 0.7928014310555764, 0.8111225341403993, 0.8194469764542243, 0.829389765797201, 0.8292218358746816, 0.7983823082941941, 0.8003164921356198, 0.816248206477173, 0.8119494544075379, 0.8239676853366769, 0.8108457807284315, 0.8048120013129505, 0.7992414020357875, 0.7990803783979373, 0.7973373348794507, 0.7993038663282294, 0.8053685616954223, 0.7979701279090687, 0.8147028747950682, 0.8187073984353553, 0.836614949936821, 0.8045475559643396, 0.8182024226144209, 0.8138234561446819, 0.8107008559568876, 0.800475485393995, 0.8251805637467106, 0.8200082269727167, 0.8004526493402919, 0.8158084506037367, 0.8162357520076009, 0.8009689407713643, 0.799040517101171, 0.8082075609687852, 0.8069148475348612, 0.8237115069313324, 0.7959932437902564, 0.8108457807284315, 0.8521375982773802, 0.8188592722246628, 0.8320457008989621, 0.7948373969978366, 0.8104250776518105, 0.8048789135010992, 0.7969882473903941, 0.8187492063186923, 0.7958967596334051, 0.8106281702002501, 0.8037851470766963, 0.8076769887548432, 0.8005036639918393, 0.8017924169114605, 0.8275552863340874, 0.797836710559563, 0.7988286469094755, 0.8013315377443526, 0.8052369441317431, 0.829120652023333, 0.7993353573235709, 0.8147843159874514, 0.8006014666766855, 0.8293754250103668, 0.8193700301746322, 0.8113923518669945, 0.7989795870127324, 0.8119404932190102, 0.8139619441281842, 0.7977984165107859, 0.8182024226144209, 0.7830396157576611, 0.8031385206315951, 0.8095423711512755, 0.8048293810558054, 0.8089559347912388, 0.8108457807284315, 0.8009350988072323, 0.8008629047430891, 0.8134000502195378, 0.8019049312299679, 0.8065546013743299, 0.8353689644837985, 0.8132524136136411, 0.8216583535453829, 0.8288832380690829, 0.8354431381308312, 0.8080094998703433, 0.8298522755237048, 0.7940441844799706, 0.8348209715346038, 0.7975622727375129, 0.8292826602028909, 0.8002898369180803, 0.8267906531530699, 0.7723687634328574, 0.8227534747114529, 0.7967641232788093, 0.8194123455035223, 0.8216652581532033, 0.8142442651131399, 0.8136826473908091, 0.8081173144479953, 0.8363590132256598, 0.8261613092426691, 0.79982

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

Fase 4 MLP perfil interno {'accuracy': 0.8164852255054432, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8164852255054432), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.898972602739726), 'f1_macro': 0.449486301369863, 'f1_weighted': 0.7339978482711604, 'precision_macro': 0.4082426127527216, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 118, 'FN': 0, 'TP': 525, 'score_source': 'predict_proba', 'auroc': 0.3907506053268765, 'ap_0': 0.14563347314906785, 'ap_1': 0.7661733587561409, 'model': 'MLP', 'params': {'alpha': 0.0001, 'hidden_layer_sizes': (32,), 'max_iter': 500}, 'indices': [2, 4, 12, 14, 18, 38, 42, 43, 45, 46, 47, 48, 49, 54, 57, 60, 67, 76, 79, 81, 82, 84, 88, 89, 90, 92, 93, 95, 102, 105, 109, 112, 114, 115, 116, 128, 133, 141, 151, 157, 159, 165, 168, 169, 177, 182, 185, 187, 189, 192, 195, 202, 205, 208, 211, 214, 220, 223, 225, 229, 237, 241, 254, 263, 268, 273, 275, 277, 279, 285, 307, 317, 325, 336, 340, 355, 367, 395, 414, 416, 418, 421, 427, 428, 429, 431, 438, 439, 445, 454, 458, 459, 465, 469, 470, 472, 478, 489, 494, 495, 499, 501, 503, 505, 518, 531, 538, 543, 546, 548, 550, 552, 560, 564, 569, 571, 576, 586, 588, 598, 602, 606, 610, 628, 630, 632, 637, 638, 642, 3, 9, 10, 17, 19, 20, 22, 29, 35, 41, 51, 61, 68, 69, 80, 87, 101, 106, 117, 118, 126, 131, 136, 140, 143, 146, 155, 172, 173, 175, 178, 200, 201, 204, 216, 218, 222, 226, 228, 230, 233, 236, 239, 240, 242, 243, 244, 248, 252, 256, 257, 262, 264, 267, 270, 274, 280, 281, 282, 283, 289, 291, 292, 308, 309, 318, 323, 327, 329, 331, 334, 337, 343, 344, 346, 352, 357, 362, 364, 377, 379, 389, 392, 393, 397, 398, 404, 409, 413, 420, 423, 425, 430, 432, 444, 448, 452, 464, 476, 484, 488, 490, 491, 502, 516, 527, 529, 530, 534, 537, 539, 551, 555, 568, 574, 579, 590, 592, 595, 597, 600, 611, 613, 615, 623, 624, 626, 636, 639, 0, 8, 24, 25, 26, 31, 32, 50, 55, 58, 64, 66, 73, 85, 86, 91, 94, 96, 98, 111, 121, 124, 127, 134, 135, 139, 148, 152, 154, 164, 166, 171, 174, 179, 180, 188, 190, 196, 197, 219, 234, 235, 238, 260, 271, 278, 284, 288, 293, 294, 295, 296, 300, 304, 306, 311, 312, 314, 316, 319, 320, 333, 338, 345, 347, 349, 354, 356, 359, 361, 363, 366, 373, 374, 378, 386, 394, 396, 400, 402, 407, 419, 422, 434, 436, 440, 449, 451, 455, 456, 460, 462, 466, 467, 473, 480, 481, 483, 487, 492, 500, 509, 511, 515, 517, 519, 522, 525, 528, 532, 535, 536, 541, 544, 554, 566, 567, 573, 580, 584, 604, 605, 608, 612, 617, 621, 622, 634, 640, 1, 5, 21, 28, 30, 39, 40, 44, 53, 56, 71, 72, 74, 75, 77, 83, 99, 103, 107, 108, 110, 119, 120, 123, 129, 132, 138, 144, 145, 147, 150, 156, 158, 160, 161, 176, 184, 194, 203, 207, 210, 217, 221, 224, 232, 245, 246, 250, 253, 259, 272, 286, 287, 301, 303, 305, 310, 321, 326, 332, 339, 341, 342, 348, 350, 353, 358, 368, 369, 371, 376, 380, 381, 382, 383, 385, 390, 399, 403, 410, 412, 415, 424, 426, 435, 441, 442, 443, 447, 450, 468, 471, 474, 479, 482, 485, 496, 497, 504, 510, 514, 521, 526, 533, 540, 542, 549, 559, 561, 562, 565, 570, 572, 575, 577, 581, 583, 585, 587, 599, 603, 616, 618, 620, 625, 627, 629, 633, 6, 7, 11, 13, 15, 16, 23, 27, 33, 34, 36, 37, 52, 59, 62, 63, 65, 70, 78, 97, 100, 104, 113, 122, 125, 130, 137, 142, 149, 153, 162, 163, 167, 170, 181, 183, 186, 191, 193, 198, 199, 206, 209, 212, 213, 215, 227, 231, 247, 249, 251, 255, 258, 261, 265, 266, 269, 276, 290, 297, 298, 299, 302, 313, 315, 322, 324, 328, 330, 335, 351, 360, 365, 370, 372, 375, 384, 387, 388, 391, 401, 405, 406, 408, 411, 417, 433, 437, 446, 453, 457, 461, 463, 475, 477, 486, 493, 498, 506, 507, 508, 512, 513, 520, 523, 524, 545, 547, 553, 556, 557, 558, 563, 578, 582, 589, 591, 593, 594, 596, 601, 607, 609, 614, 619, 631, 635, 641], 'y_true': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1], 'y_pred': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'score': [0.7732364832043307, 0.8167099152897792, 0.818496605682763, 0.8291817447502815, 0.827960089748054, 0.8256234460441227, 0.8027471925710914, 0.8350111378844389, 0.8311672475845328, 0.8065088269251863, 0.8296394445783379, 0.8192536531406838, 0.8215362428191948, 0.8027201796983603, 0.829052614362868, 0.7849337135591539, 0.8311349197275308, 0.8129434620949711, 0.8403231192211317, 0.8221596581001609, 0.8170435218961078, 0.8017582140101925, 0.7965717353674275, 0.7977245935894366, 0.8346286098704983, 0.8134692224851967, 0.816579658295983, 0.8255017113839334, 0.8186965629304682, 0.8073907478355519, 0.8258907540265856, 0.7987077081569163, 0.8324131417967633, 0.8319890404571348, 0.8411805287642611, 0.8278467694146501, 0.8067665515916678, 0.838442836563409, 0.8316746699699464, 0.8173912406100674, 0.8047654718174165, 0.8243178787940243, 0.8101233444140327, 0.8221505067287371, 0.8238267854508683, 0.7967020235693415, 0.8307017305680795, 0.8247402575667904, 0.8358518199863575, 0.827761157344255, 0.8307428880288033, 0.7849135989890977, 0.8014586115356643, 0.8165803614578561, 0.8202335912710202, 0.8059049601720043, 0.8306166342218197, 0.8083371773058348, 0.831071389426187, 0.8188300029713306, 0.83052469034527, 0.8179424596381624, 0.7343682776103857, 0.7772270778128216, 0.7802077475517765, 0.818079956670245, 0.8251732668243369, 0.835136740777687, 0.8266143527743797, 0.8295340241515923, 0.8153373299013579, 0.8176271619234177, 0.813683310800813, 0.8285902154350137, 0.822619644886619, 0.8289287147923726, 0.834012143229846, 0.8210418832295779, 0.8224635530512794, 0.8173066385098986, 0.8125368249957953, 0.8210843697739932, 0.8200543185490847, 0.8348444764726335, 0.7105996263277208, 0.8225480198759675, 0.8304903493858589, 0.8274061875320984, 0.7818765514472623, 0.7287316976736917, 0.8162675056571095, 0.8337216915533263, 0.7093157759886887, 0.8094484690686464, 0.7109704157636226, 0.7914130958226363, 0.8359498065770161, 0.8105848100265011, 0.7896309831652676, 0.8380192018349424, 0.8235342512577637, 0.836186591826072, 0.8145502808953632, 0.8203726400160589, 0.8290405839777609, 0.7512315871448718, 0.8328859749303941, 0.8341141206090297, 0.8108116709592192, 0.8020046521011525, 0.8305076346167866, 0.8250139094996161, 0.8152041756075914, 0.8293546097406808, 0.8122117043896864, 0.8280794555139741, 0.8307130272959397, 0.8215529269978058, 0.8188221293182846, 0.8279856995505186, 0.7237249142547071, 0.825703207989012, 0.7897068813450268, 0.8341262895325127, 0.8191331769943251, 0.8364951531629627, 0.8122117043896864, 0.7643144989284187, 0.8332622054500771, 0.8261499363398498, 0.817787030294074, 0.8060985679193484, 0.7992757246310639, 0.8323376175339124, 0.8084748453118469, 0.8126726676570473, 0.8070134892764494, 0.8038481470125406, 0.8097702876243289, 0.8227156285764039, 0.8127040917805679, 0.8277063671919805, 0.7903291441609624, 0.8706887815103862, 0.8249351669558879, 0.8256691207958159, 0.8117230289209765, 0.7989482450620257, 0.7998607431167618, 0.8222790811316765, 0.8095446327128156, 0.8182933598557695, 0.8175345491033147, 0.809816497255426, 0.8004853892771729, 0.8175905826589931, 0.8344773660574092, 0.8121367519667864, 0.8161561937986, 0.8098343301081613, 0.8212227644670133, 0.7986040807730856, 0.8074998116083114, 0.812129701962931, 0.8286819078778735, 0.8309208857210223, 0.8106521342670143, 0.7969969727693164, 0.8134092801583035, 0.8003234025108317, 0.8364327184309188, 0.833776136732493, 0.8053620660372218, 0.8006307367637693, 0.7956040991029438, 0.8231069732342997, 0.8264548314199975, 0.8083693901066141, 0.7989634206383713, 0.8544067819363736, 0.815712242605908, 0.7996446178519442, 0.8108657822386387, 0.81628894230414, 0.837481124073714, 0.8545001601189112, 0.8341336667651106, 0.835166055934199, 0.7903643013152902, 0.8201217305200231, 0.8369354394056068, 0.7964864525110371, 0.7981379472606165, 0.8179946748299193, 0.8083361950043721, 0.7995238008077222, 0.8195824984659031, 0.8174075834031111, 0.8252687281554169, 0.8335302610122242, 0.807674722841546, 0.8199395488059326, 0.8258908863305614, 0.8179355947070501, 0.8274980717269601, 0.7960188907943154, 0.813629914305352, 0.8184085350957611, 0.8216473362602722, 0.8260117923470602, 0.8115693393030312, 0.810960097999476, 0.8122290212550863, 0.8267898514807592, 0.8128963875720341, 0.8036250178235734, 0.8019913271304443, 0.8291881133036009, 0.8006615072921202, 0.8123174062620621, 0.8036413445234952, 0.8178945200604097, 0.8036096402681927, 0.8105438506919631, 0.8084484529221664, 0.8224472747378595, 0.8140179569355688, 0.7950930165595808, 0.8065507610862351, 0.807883411217931, 0.804105865720446, 0.7975937007609218, 0.8224899277093494, 0.8089546764885658, 0.8191487159496532, 0.8104561218503001, 0.8146995645418528, 0.8317038110401127, 0.8446369978395577, 0.8318263006828003, 0.830363578683875, 0.8219796085923893, 0.7915388422499342, 0.8376464949131808, 0.7989509816459839, 0.8517199526973881, 0.8126342816041656, 0.8025535370948191, 0.7972761774675333, 0.8487684641833452, 0.8069348547420955, 0.8041141203005002, 0.8275793682908216, 0.8179276690775567, 0.7963755090762616, 0.7940553295786016, 0.8273164813732553, 0.806162981481798, 0.8173471763634279, 0.816600496260454, 0.7824903522672042, 0.806957171386826, 0.8171929891666133, 0.8211326154689363, 0.8114914286837249, 0.8098312424700469, 0.8069545992896595, 0.8215052584929478, 0.8197889655689915, 0.8063651910463341, 0.820235526933805, 0.8211326154689363, 0.8196553013681889, 0.8247781335450645, 0.8080953912658453, 0.8210195821847416, 0.8199878045054383, 0.8213058344592354, 0.8111802995155186, 0.8237170830031613, 0.8082950712286874, 0.8102313282806026, 0.8034548521299627, 0.8205343096030194, 0.8214144585288027, 0.8016501467665524, 0.81857956860789, 0.8121744141733533, 0.8144509197152653, 0.8182120868653715, 0.8205149671673613, 0.7947041110763136, 0.8160372281796006, 0.8124394554738339, 0.8121639399227358, 0.8130545917336116, 0.8206985492071187, 0.8217975187065061, 0.8063647606133115, 0.8226350648304918, 0.8171882770723631, 0.8198135215177134, 0.8164257187161377, 0.8113670717744743, 0.8122266254435286, 0.825907675442006, 0.8264269515371104, 0.8195500660056746, 0.8175277651411423, 0.8235107418629948, 0.8155819823661121, 0.8154061766550775, 0.8207651751608601, 0.8148624923495416, 0.8109980324109503, 0.8200987480913104, 0.8146519799145533, 0.8190479904967016, 0.8136864591479036, 0.7980296104868525, 0.8049370673306416, 0.8206210474624764, 0.8196648871257823, 0.8144198095112145, 0.8187463746772687, 0.8161449257205062, 0.8098312424700469, 0.8230428168182445, 0.8183464452423218, 0.8180247302322659, 0.8265670440563673, 0.8127154219070292, 0.8109436145253037, 0.8037951105200138, 0.8261154846525871, 0.8060764585100173, 0.8263177819285203, 0.8169655247891097, 0.8323904990982758, 0.8097844042444429, 0.8120767567550594, 0.8124710679718611, 0.8129356630009156, 0.8146983104997568, 0.8231432168096809, 0.8232294307693377, 0.8205597344940548, 0.8247619405220789, 0.781045780996328, 0.8069252592008738, 0.816850626547858, 0.8249880863411523, 0.8160333243729309, 0.8211301335455184, 0.7985182994978101, 0.8200209711218871, 0.8159752539000387, 0.8263597610129203, 0.7876843899837882, 0.8136591666772126, 0.8198656553812164, 0.8131036847638125, 0.8206226155789818, 0.8208078885829442, 0.802594187182341, 0.8082408433826705, 0.819219002075882, 0.8174582865212109, 0.809087260546838, 0.8080127827709542, 0.8085989407588583, 0.8177941079148676, 0.8046046484331176, 0.818736862788068, 0.823464859312993, 0.8206859972601567, 0.792858419951018, 0.8153500599787942, 0.8155503031164002, 0.8165898313285904, 0.8103973994140663, 0.8189840825508835, 0.8196354663148805, 0.798857938215894, 0.8127154219070292, 0.8112448286462339, 0.8039017775107716, 0.8009495979300297, 0.802591930804135, 0.8438407818533591, 0.8265821568410658, 0.8206081345157376, 0.804730540308937, 0.8364065110728497, 0.7999218726195698, 0.8085772274824153, 0.8093007442253569, 0.8067747058261181, 0.816406043575402, 0.8275404171563137, 0.8099526675782457, 0.8100188105641916, 0.8184754946648984, 0.8108144888982496, 0.799599621521005, 0.8444958913925724, 0.8245159664532877, 0.8229777024947065, 0.8072018866282769, 0.7995519969283746, 0.7998344131911196, 0.8226408676432285, 0.8174952503784167, 0.8171209726941052, 0.8267193586459903, 0.8154549448401344, 0.804730540308937, 0.8160593955616905, 0.816749660066464, 0.8007952293534644, 0.8027972543055222, 0.8155810444893467, 0.8148426248391081, 0.8098018472098024, 0.8059807620388473, 0.810806234598332, 0.7995752051115941, 0.7995437694257258, 0.8011309368148778, 0.8082053251442687, 0.8241062422124399, 0.8312397472897496, 0.8081617398478441, 0.8012130636396385, 0.8107503529477927, 0.8255965536294416, 0.7995363638419436, 0.8340173977776152, 0.8339945958846421, 0.802908873279035, 0.8076176913210024, 0.8063720158235268, 0.8158470884011081, 0.8113199355835489, 0.7996520857160974, 0.806237747567638, 0.8287017132212202, 0.8241167639787281, 0.8034632097522962, 0.813389246435196, 0.8243559390866608, 0.8122939664407459, 0.8399396416666788, 0.8261282147461063, 0.8012631153022338, 0.8228948790114913, 0.8045077110016987, 0.810845206410691, 0.8060877380215853, 0.8203887827545879, 0.815281996236598, 0.8134536882085849, 0.7992900149874848, 0.7991741306679391, 0.8066981315491963, 0.8222241060432726, 0.8243559390866608, 0.8218109873048082, 0.8043790173014974, 0.8011109263358256, 0.815228123028489, 0.8318615381614173, 0.8264288396972403, 0.8012694809900548, 0.8095402364427571, 0.806435808315728, 0.8039155100889527, 0.825522152050923, 0.7998467204966516, 0.8326929461722283, 0.8031034751513888, 0.8166281761491815, 0.8280514421768341, 0.808035525987212, 0.8122006555856333, 0.8077393546776406, 0.8316202516193133, 0.8196813972260305, 0.8255884652752821, 0.7986520244696866, 0.7983782860227512, 0.8069808544721745, 0.8210552731967133, 0.8117632828177443, 0.8196368344801079, 0.8243559390866608, 0.8024170683131185, 0.8279974482898502, 0.7996105577775824, 0.8182237038583093, 0.8302485276667243, 0.7976883684553038, 0.81208582216166, 0.8053722967931733, 0.8275313906498246, 0.8229777024947065, 0.8125564034586723, 0.8097811605956062, 0.8233645632075446, 0.8093956990760693, 0.7994107553343334, 0.8000752537400228, 0.8010765507932526, 0.8280417947463174, 0.833573250946088, 0.8279726176382656, 0.7984063603051872, 0.7971428737691852, 0.8406022852076278, 0.8031784666833527, 0.7999660531171637, 0.7937961369567396, 0.7970609543577549, 0.8250976721219547, 0.7975175149197962, 0.8024213630163629, 0.7949410730415664, 0.7886244266159094, 0.7970609543577549, 0.8257204806064615, 0.798444087132389, 0.834342865613231, 0.7912926279280719, 0.8139136778769614, 0.8072208756408712, 0.7894010548935649, 0.8029977153424375, 0.8013541936490511, 0.823099093653241, 0.818051762677609, 0.8305318580440486, 0.7971590721710021, 0.8113494913877618, 0.806156393659727, 0.7924828556008949, 0.8211013737088461, 0.8001131921149449, 0.8124475997483508, 0.7996427056652897, 0.7984647287237661, 0.8502147388642968, 0.7952680474750486, 0.8070447908932424, 0.8162427742587696, 0.8163179974878878, 0.8196163256105022, 0.814941947339104, 0.8275054025438884, 0.8070072551904286, 0.8072020441878689, 0.8094359928935339, 0.8302833675744207, 0.7932813219430205, 0.7914256741367494, 0.7961164941035511, 0.8054525064434402, 0.8686927169657352, 0.7957695039985009, 0.8063665117427948, 0.7903701844931084, 0.8107033951950573, 0.794921955324086, 0.7952680474750486, 0.8095438054945943, 0.8362651054926747, 0.7949254388612662, 0.8014763253482098, 0.8367567904843705, 0.7967269474868461, 0.8144044296077778, 0.8157315636447067, 0.8143622416616141, 0.7878795550876629, 0.8047045785329985, 0.8141887565983831, 0.8338005173255869, 0.7894063469304913, 0.8174012235428251, 0.8122446740344056, 0.7975751669820899, 0.8002092623987516, 0.808326767974909, 0.8262306047231215, 0.8212101054372397, 0.8059973017950348, 0.8118152521272919, 0.845814271739847, 0.8032686448011821, 0.8078583776517663, 0.8212616828087421, 0.7887119019023435, 0.8046628981174833, 0.7937669750623046, 0.8283108777277841, 0.8211013737088461, 0.8145926177866686, 0.8252090727668288, 0.841732485369701, 0.8203062798505802, 0.7983217846246146, 0.791858140564837, 0.7956510539067974, 0.8025848901624206, 0.8220731998032823, 0.8160093982614963, 0.8353014761921678, 0.7873138900

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

Fase 4 MLP perfil interno {'accuracy': 0.8164852255054432, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8164852255054432), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.898972602739726), 'f1_macro': 0.449486301369863, 'f1_weighted': 0.7339978482711604, 'precision_macro': 0.4082426127527216, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 118, 'FN': 0, 'TP': 525, 'score_source': 'predict_proba', 'auroc': 0.5044632768361582, 'ap_0': 0.1887731752564532, 'ap_1': 0.8260539516085412, 'model': 'MLP', 'params': {'alpha': 0.0001, 'hidden_layer_sizes': (32,), 'max_iter': 500}, 'indices': [2, 5, 13, 15, 19, 39, 42, 44, 46, 47, 48, 49, 50, 55, 59, 62, 64, 71, 78, 82, 83, 85, 90, 91, 92, 93, 94, 95, 97, 106, 107, 109, 111, 113, 116, 118, 120, 132, 146, 158, 162, 164, 172, 174, 183, 188, 191, 192, 194, 197, 200, 204, 206, 212, 216, 219, 223, 226, 228, 229, 233, 235, 253, 258, 267, 271, 274, 277, 278, 284, 310, 318, 327, 339, 342, 344, 361, 382, 405, 418, 420, 422, 423, 429, 430, 431, 439, 441, 447, 455, 458, 459, 467, 470, 471, 472, 479, 490, 494, 495, 498, 500, 502, 504, 506, 532, 539, 544, 547, 548, 550, 552, 560, 564, 569, 571, 575, 587, 589, 599, 603, 607, 610, 628, 629, 631, 637, 638, 642, 4, 10, 11, 12, 18, 21, 23, 29, 30, 36, 52, 58, 68, 70, 80, 89, 103, 110, 121, 122, 130, 136, 140, 145, 148, 151, 155, 160, 171, 175, 179, 181, 184, 205, 207, 220, 225, 230, 232, 234, 237, 238, 240, 241, 242, 243, 244, 245, 256, 260, 261, 262, 266, 268, 270, 272, 280, 281, 282, 285, 287, 290, 293, 311, 312, 319, 322, 325, 330, 332, 334, 337, 340, 347, 348, 349, 358, 359, 366, 380, 381, 392, 395, 396, 400, 401, 407, 408, 413, 416, 425, 428, 432, 433, 438, 446, 450, 465, 476, 486, 489, 491, 492, 503, 518, 520, 528, 530, 531, 535, 538, 551, 555, 567, 577, 580, 591, 593, 596, 598, 601, 611, 612, 615, 624, 625, 626, 636, 639, 0, 3, 25, 26, 27, 32, 33, 43, 51, 56, 66, 67, 75, 81, 86, 87, 96, 98, 100, 105, 114, 119, 125, 128, 131, 138, 139, 143, 144, 153, 169, 177, 180, 185, 186, 193, 195, 201, 202, 213, 222, 227, 239, 265, 273, 279, 283, 289, 291, 294, 295, 297, 298, 304, 308, 309, 315, 316, 317, 320, 321, 323, 328, 336, 341, 350, 352, 353, 357, 363, 365, 368, 370, 375, 377, 385, 389, 397, 399, 403, 410, 421, 424, 427, 437, 440, 442, 451, 453, 456, 460, 462, 468, 469, 473, 477, 481, 482, 483, 485, 501, 511, 513, 517, 519, 521, 523, 526, 529, 533, 536, 537, 541, 542, 554, 566, 568, 573, 581, 585, 605, 606, 608, 613, 617, 621, 623, 634, 640, 1, 6, 22, 28, 31, 40, 41, 45, 54, 57, 73, 74, 76, 77, 79, 84, 88, 102, 104, 112, 115, 123, 124, 127, 133, 137, 142, 149, 150, 152, 156, 161, 163, 165, 166, 178, 182, 190, 199, 208, 210, 211, 215, 221, 224, 248, 250, 254, 257, 264, 275, 286, 288, 296, 305, 307, 314, 324, 329, 335, 343, 345, 346, 351, 354, 356, 360, 369, 371, 372, 374, 379, 383, 384, 386, 388, 393, 398, 402, 406, 412, 415, 417, 426, 436, 443, 444, 445, 449, 452, 463, 466, 475, 480, 484, 487, 496, 497, 507, 508, 512, 516, 527, 534, 540, 543, 549, 559, 561, 562, 565, 570, 572, 574, 576, 578, 583, 584, 586, 588, 604, 616, 618, 620, 622, 627, 630, 633, 7, 8, 9, 14, 16, 17, 20, 24, 34, 35, 37, 38, 53, 60, 61, 63, 65, 69, 72, 99, 101, 108, 117, 126, 129, 134, 135, 141, 147, 154, 157, 159, 167, 168, 170, 173, 176, 187, 189, 196, 198, 203, 209, 214, 217, 218, 231, 236, 246, 247, 249, 251, 252, 255, 259, 263, 269, 276, 292, 299, 300, 301, 302, 303, 306, 313, 326, 331, 333, 338, 355, 362, 364, 367, 373, 376, 378, 387, 390, 391, 394, 404, 409, 411, 414, 419, 434, 435, 448, 454, 457, 461, 464, 474, 478, 488, 493, 499, 505, 509, 510, 514, 515, 522, 524, 525, 545, 546, 553, 556, 557, 558, 563, 579, 582, 590, 592, 594, 595, 597, 600, 602, 609, 614, 619, 632, 635, 641], 'y_true': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1], 'y_pred': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'score': [0.8079474598936998, 0.8183438955938842, 0.8266287080644872, 0.8375498814027053, 0.8305308784555988, 0.8260398023513691, 0.7875894289707389, 0.7961824433500085, 0.8254006489074293, 0.8330504877278717, 0.8101148364782886, 0.8154205130972265, 0.8327033510142361, 0.7985673994289613, 0.8331241692532189, 0.7972351392993777, 0.7974548834089181, 0.8235547393032501, 0.7823551017804999, 0.7059054201426467, 0.8333120117165308, 0.8318708362538313, 0.804464847059759, 0.8198964737904184, 0.8300705103247212, 0.7990529340493007, 0.8123806490733958, 0.7604987081351571, 0.8163171367453774, 0.826978981585822, 0.8333110194640071, 0.8185400071206441, 0.8315496801020764, 0.8194236163851315, 0.820443118707281, 0.8123288519017995, 0.7834862500565136, 0.8188103820150341, 0.8105472132539682, 0.8077262376117883, 0.8132008849492317, 0.7961824433500085, 0.7984281594951976, 0.8202531590641172, 0.8228061633999907, 0.7919489092688792, 0.8185173450109318, 0.8138026102474486, 0.8022025546103582, 0.8326904220483635, 0.8148038280415497, 0.8244168723267474, 0.8144249262316269, 0.789507850046136, 0.8326485020668436, 0.8320910545599632, 0.8137516637132391, 0.8110361050521654, 0.8154205130972265, 0.7565508275058235, 0.8053110085923898, 0.8261791024225227, 0.831624981818813, 0.81510416883482, 0.7810860056295648, 0.8165559831795214, 0.8290441320300168, 0.8215414121470437, 0.830044623611044, 0.7726338355620495, 0.8080582569614483, 0.8209500117742057, 0.8333257047708219, 0.8249801317375514, 0.7848782026897887, 0.7458993432001256, 0.7745329691338869, 0.8270847027442729, 0.8328807077717588, 0.8332227124109615, 0.8148217844272164, 0.7882814168106383, 0.8247650561202097, 0.787366191952983, 0.8279962529093334, 0.6887216022007293, 0.8105288688142972, 0.8312753645883666, 0.8332395246417443, 0.8283522154192315, 0.8283237850767149, 0.8208588201946551, 0.8344883882516221, 0.7688733404068265, 0.8028962644309183, 0.8200549095063498, 0.832426105502031, 0.8111168784878607, 0.8124002408544764, 0.7657991093986044, 0.8013018353247092, 0.7887477495853081, 0.8110361050521654, 0.8208243761102322, 0.7813612096224075, 0.7982753591065641, 0.8332887901226924, 0.8242302719879293, 0.82631447809042, 0.740705154875078, 0.8350843589222066, 0.8137460561084211, 0.8202512520043923, 0.8274696028833246, 0.8305629077885024, 0.792160988429228, 0.8202531590641172, 0.8299871935137377, 0.8002240642083331, 0.7939384917198595, 0.8332873456665812, 0.8303477624580673, 0.7816389804954477, 0.8053867610926122, 0.8333240516984202, 0.7926742866801135, 0.8089293834110215, 0.8198964737904184, 0.8226445178860147, 0.8155931305047689, 0.8347173066828966, 0.8158231552416785, 0.8259261082170107, 0.8248522036184557, 0.8355834437086255, 0.8158139346723455, 0.8213690535554367, 0.827805030647118, 0.8256556523059386, 0.8259401069126824, 0.8145613689924358, 0.8337183854007302, 0.815037249201724, 0.8368536674383872, 0.8280907594528044, 0.7934032278312888, 0.8141163543753915, 0.7959906297975854, 0.8375781713154499, 0.7990762049113823, 0.8138337563616675, 0.8148368573156917, 0.8236341097133446, 0.8124072542840673, 0.8097954880492011, 0.8095633454882085, 0.8359468482340888, 0.8276160585109184, 0.8124072542840673, 0.8372887390512309, 0.7995536660274885, 0.743754641932519, 0.8327713631473511, 0.7845167052660773, 0.8300995121594397, 0.8324178976065897, 0.835433012742581, 0.822299115118535, 0.8230864164447382, 0.8263162010698343, 0.8047199126237186, 0.8370758414530346, 0.8072668335064899, 0.8333699725272771, 0.8308917669137784, 0.8159558338760563, 0.8027319042154548, 0.8235849179790667, 0.8298657722274193, 0.8330567805283753, 0.8232443481579168, 0.7102333958528021, 0.8220427238636278, 0.7446017801077185, 0.8375488872876131, 0.7589250374009906, 0.7917003150306764, 0.8293743572477906, 0.7969951427911477, 0.8278170675220272, 0.7877337481758762, 0.8029475334291156, 0.821025713880279, 0.8332396915565894, 0.8222971887179163, 0.7934032278312888, 0.7909448307873987, 0.8317161798347839, 0.8250832585996488, 0.8244957298766241, 0.8213845621976414, 0.7572970083988044, 0.8147650404383949, 0.8350820475169793, 0.7868662156917965, 0.770935451604031, 0.7964566751561474, 0.7935757631042227, 0.8372008713304744, 0.7771714017693594, 0.8197246935946426, 0.832598177713914, 0.8298909280158231, 0.829014109287559, 0.8280907594528044, 0.8174353442529199, 0.8252108727330836, 0.8013741628596179, 0.806247268829163, 0.8331750003978581, 0.763125936264779, 0.7228775312219751, 0.8219040626284441, 0.8288717361638895, 0.8309228555115069, 0.8024129798282734, 0.7928635614851097, 0.7964339291733195, 0.804960198220811, 0.8326793893779726, 0.8136177455421167, 0.8196084774042938, 0.7851189735935722, 0.8335333284492433, 0.823673239394029, 0.8313783774600709, 0.8295271177576122, 0.8299706196008408, 0.8330567805283753, 0.8316354276650673, 0.8285786320366106, 0.8142945635576444, 0.8095454843527978, 0.8369647243568895, 0.8336127477433317, 0.8301918227296359, 0.8295688636624279, 0.8146753099619974, 0.8342072154335177, 0.8148621397909988, 0.8232921556777443, 0.8359633499248178, 0.8298298079833891, 0.8216344428000228, 0.83624874331489, 0.8279976131762605, 0.8303333890424665, 0.7566166248688145, 0.8297878913783805, 0.8319495445662453, 0.6770606312898104, 0.7710327792441711, 0.7981389779505674, 0.821229153399862, 0.7705048745856863, 0.7970889752386485, 0.8357592727023855, 0.8237676435351121, 0.7854629834421413, 0.8306492584034055, 0.7932047709688056, 0.8205306456131882, 0.8314058363126442, 0.8019239712317621, 0.801476975479888, 0.8362393490368774, 0.8285916694772961, 0.8275227687341941, 0.8431367247279896, 0.8448961372773617, 0.8414736470057823, 0.8154772783030589, 0.8124041542477334, 0.8318216382966428, 0.8277274880469294, 0.8258538318298008, 0.8292328972628249, 0.8139586127361602, 0.8258888084285992, 0.8395822471896658, 0.8346507754971186, 0.8276534116666616, 0.8280384922497206, 0.842021315759907, 0.8411466078592855, 0.8410835255287304, 0.845397090618842, 0.7367211226078355, 0.8346507754971186, 0.8011225407093608, 0.7682356246207295, 0.8292328972628249, 0.8381883137101489, 0.7675563699805946, 0.8317163523764911, 0.8429602264967404, 0.7618913570047828, 0.8234208414134401, 0.8297091683085874, 0.8431052953008367, 0.82513573781684, 0.8206241089471213, 0.801476975479888, 0.8367127619654393, 0.8362046688566928, 0.8434227473437529, 0.8413282376389144, 0.8323435745104885, 0.835321849826211, 0.8388105801061145, 0.821669710856838, 0.783309436398218, 0.8322264047267082, 0.8216619877551942, 0.8345885827790186, 0.8053306014902857, 0.8414960659996437, 0.8411911215753847, 0.8077429684429772, 0.8433224628174575, 0.812526937134025, 0.8201414565451532, 0.8247044263998553, 0.7995685609307348, 0.790645707984931, 0.8349415037141507, 0.805447319620073, 0.8364372958928812, 0.840829790465879, 0.7941684519641592, 0.8264834428728787, 0.7712376183064109, 0.7970889752386485, 0.8097864644632564, 0.7984224583241172, 0.729507330006175, 0.8214273162722929, 0.8223371018888432, 0.821229153399862, 0.8414226656579441, 0.8339729136886384, 0.8140526215273451, 0.8402193976319803, 0.8423791322867563, 0.8121760821310102, 0.8351052244093274, 0.8431688702832947, 0.841955698344823, 0.7443049064641576, 0.7380131314020352, 0.829658163464393, 0.7438899903436597, 0.8442170078730488, 0.8379834451784912, 0.7654045896757893, 0.8129241180672745, 0.8417646044079865, 0.8147351826116177, 0.7730946643489961, 0.8329233128066089, 0.8221802923968035, 0.8140534916328841, 0.829629741566588, 0.8438736680012354, 0.8293086756523284, 0.705900547163022, 0.8420489439716624, 0.8317028526529249, 0.8413282376389144, 0.835784914174155, 0.82937624543089, 0.8291770655428135, 0.7478353325978315, 0.8432051737485565, 0.7793268932662112, 0.8241641611787636, 0.8327225309092962, 0.8189883455551286, 0.8131855750226797, 0.8427126546117119, 0.8156702779704494, 0.834619183309362, 0.8064307860814809, 0.8138607880747722, 0.7896264688584623, 0.8139858449235755, 0.8080134407204568, 0.8123869540404586, 0.8197773647181055, 0.8174829273189832, 0.802873006703396, 0.7963152003387116, 0.8149351042207675, 0.8045950440423464, 0.8213534894837687, 0.819726197940643, 0.8216981188696998, 0.8120911029508576, 0.8150322539241239, 0.8131919983792939, 0.8253141181271898, 0.8122989716514395, 0.7931980754543559, 0.7954641274057368, 0.7836120977615064, 0.819109564041069, 0.8138607880747722, 0.8164350696067728, 0.816215821306414, 0.816105842090499, 0.8228838220203883, 0.8160851680355894, 0.8297532779945241, 0.8200095153946746, 0.8042111988972712, 0.8306173956908729, 0.819705335999017, 0.8193328679373442, 0.8234147492872431, 0.8119167054932669, 0.8164350696067728, 0.822884484024297, 0.8289990006296796, 0.825842546752512, 0.8198907976995325, 0.8156944297489955, 0.7824386496982054, 0.8123848160125599, 0.8418158263243501, 0.815952628299965, 0.8107590960114323, 0.8202070514085815, 0.8128715006362354, 0.82058318094758, 0.7977361243350154, 0.8191666687680808, 0.8267075224731352, 0.8143848028598997, 0.8227806430942838, 0.816844392823134, 0.8158606145866834, 0.7909554101514236, 0.818448693618808, 0.8218516661309231, 0.799953310820716, 0.8014514477064945, 0.8268035014494082, 0.794224752587213, 0.8256086965611678, 0.819463486665439, 0.7467031849672713, 0.8146073343883453, 0.795005919230119, 0.8172334774309528, 0.8242876910079977, 0.7988198273297888, 0.8191648875094124, 0.8110405832402077, 0.7632286364689154, 0.8274266391035408, 0.8201153557118491, 0.8222318115445247, 0.8134034289583292, 0.8182386234704847, 0.7669599861345021, 0.815952628299965, 0.8092434170536225, 0.8085023404404854, 0.8187418733966169, 0.8072983577819415, 0.8072778366971191, 0.817633041313967, 0.8189582189647577, 0.8155904190381763, 0.8302657078102029, 0.8192629036615582, 0.7952546180848046, 0.8160747997871358, 0.7952184418393821, 0.819410117791764, 0.8472068680675111, 0.8244248287014908, 0.8227059300739554, 0.8079371793680691, 0.7809216178125663, 0.8110405832402077, 0.8181537276231262, 0.7728398397794756, 0.8110050468927337, 0.804289499250717, 0.8322754722570533, 0.8177818921962092, 0.8204966827950002, 0.8051610771456295, 0.8181710269620156, 0.7310693266937918, 0.7890207046791078, 0.795931414854979, 0.8200163147456415, 0.8075564220463836, 0.7791338246766119, 0.7774004859727481, 0.8053107964104113, 0.8101513742865638, 0.8124369949036006, 0.8222257624564719, 0.8212646931823511, 0.8058399666375153, 0.8113849991956886, 0.8047092044878248, 0.8040224275767935, 0.8192408537230353, 0.8086002058444152, 0.8194045099493101, 0.8054718587483862, 0.804397002404315, 0.8070081305237702, 0.8140364414940041, 0.8092187018908643, 0.8033104235666914, 0.8035987499631958, 0.8027341621044011, 0.8065692782360078, 0.83499383979143, 0.8048239326276804, 0.8071190278224462, 0.8040251214578593, 0.8030567312991147, 0.8153104631760468, 0.8037184699843479, 0.824471047861955, 0.8074271563065484, 0.8041658864114852, 0.808353897862984, 0.8054313477988557, 0.8067523550247253, 0.8194045099493101, 0.8240515499917525, 0.8140104809539336, 0.8048612005384317, 0.8140036685324112, 0.808572689119878, 0.8005469558496362, 0.8191821142860866, 0.7984683432767751, 0.8093353881372017, 0.8070637389271222, 0.8091483660777108, 0.8201025074381219, 0.8118730929350342, 0.8313130698392805, 0.807554028095438, 0.811016207906708, 0.8122992792021705, 0.803288329795472, 0.8090436029724148, 0.8242518588136575, 0.8137836564535144, 0.8150162667141171, 0.8016741410110961, 0.8092656288328783, 0.8027720007317776, 0.8135316047184512, 0.8137538561151372, 0.811033471423374, 0.8281596108319272, 0.8020550695228634, 0.8190793869729992, 0.8057435588884774, 0.821188923881861, 0.8019300127818356, 0.7996429754899063, 0.8240255865875803, 0.8017471375013407, 0.8327913839957711, 0.8043788991022869, 0.8154460562216526, 0.812243405936367, 0.8028502504307667, 0.809601265721521, 0.8021123246516291, 0.829713101850001, 0.8137716778687226, 0.8021318317846143, 0.8220458942390874, 0.8081696125200362, 0.8149775457681695, 0.8148164537981051, 0.8103127094360673, 0.8202509140858384, 0.8018447047119267, 0.8209286027254936, 0.8093036519091397, 0.8138660021265887, 0.8024157963717975, 0.8339089101314834, 0.8148046758724504, 0.8014238740126423, 0.8038280911096368, 0.8087881575238616, 0.8043585943094698, 0.8000438054056442, 0.8220926867534452, 0.8286802537158575, 0.8192721024335956, 0.8058399666375153, 0.8139014477826741, 0.

/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/pk/Studing/projects/machine_learning/Artigo_veis/analyze-medical-services/.venv/lib/python3.14/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

Fase 4 MLP perfil interno {'accuracy': 0.8164852255054432, 'precision_0': np.float64(0.0), 'precision_1': np.float64(0.8164852255054432), 'recall_0': np.float64(0.0), 'recall_1': np.float64(1.0), 'f1_0': np.float64(0.0), 'f1_1': np.float64(0.898972602739726), 'f1_macro': 0.449486301369863, 'f1_weighted': 0.7339978482711604, 'precision_macro': 0.4082426127527216, 'recall_macro': 0.5, 'balanced_accuracy': 0.5, 'mcc': 0.0, 'specificity': np.float64(0.0), 'sensitivity': np.float64(1.0), 'TN': 0, 'FP': 118, 'FN': 0, 'TP': 525, 'score_source': 'predict_proba', 'auroc': 0.4432687651331719, 'ap_0': 0.16198845590501748, 'ap_1': 0.7937950720535627, 'model': 'MLP', 'params': {'alpha': 0.0001, 'hidden_layer_sizes': (32,), 'max_iter': 500}, 'indices': [2, 5, 13, 15, 19, 38, 42, 43, 45, 46, 47, 48, 49, 54, 58, 62, 67, 77, 79, 82, 83, 86, 89, 91, 92, 93, 95, 96, 98, 106, 107, 108, 110, 114, 117, 119, 121, 133, 143, 159, 163, 165, 174, 177, 184, 189, 192, 193, 195, 198, 201, 208, 211, 214, 217, 220, 222, 225, 226, 229, 230, 235, 246, 258, 260, 268, 273, 279, 280, 290, 311, 321, 328, 335, 340, 345, 353, 377, 400, 412, 420, 422, 425, 430, 432, 433, 438, 441, 442, 448, 457, 461, 468, 472, 473, 475, 480, 486, 491, 494, 497, 500, 503, 504, 507, 532, 542, 543, 546, 549, 551, 556, 563, 565, 567, 571, 576, 588, 590, 601, 603, 604, 610, 622, 629, 631, 637, 638, 642, 4, 10, 11, 12, 18, 21, 23, 28, 29, 40, 51, 59, 68, 70, 81, 90, 104, 112, 122, 123, 131, 137, 141, 146, 147, 149, 152, 161, 169, 170, 180, 182, 185, 190, 210, 221, 228, 231, 232, 234, 236, 238, 239, 242, 245, 247, 248, 249, 250, 257, 262, 263, 267, 269, 271, 274, 278, 282, 283, 284, 286, 288, 295, 312, 313, 317, 322, 326, 330, 332, 334, 338, 341, 348, 349, 350, 351, 361, 368, 382, 383, 393, 396, 397, 401, 402, 404, 408, 414, 417, 427, 429, 431, 434, 436, 447, 451, 466, 478, 487, 490, 492, 495, 506, 516, 519, 520, 530, 531, 535, 541, 545, 554, 555, 579, 582, 583, 592, 594, 597, 600, 606, 613, 616, 625, 626, 627, 636, 639, 0, 3, 25, 26, 30, 32, 33, 50, 55, 56, 65, 66, 74, 80, 85, 88, 97, 99, 101, 105, 111, 115, 126, 129, 132, 135, 139, 140, 145, 154, 172, 179, 181, 186, 187, 194, 196, 202, 205, 206, 209, 224, 240, 266, 272, 275, 285, 289, 292, 293, 297, 299, 300, 304, 308, 310, 315, 316, 318, 319, 320, 323, 324, 337, 342, 343, 352, 356, 360, 362, 364, 367, 371, 376, 378, 380, 389, 398, 399, 405, 411, 419, 423, 426, 435, 440, 443, 452, 454, 458, 462, 464, 469, 470, 471, 474, 476, 482, 483, 485, 501, 511, 513, 518, 521, 522, 524, 527, 529, 533, 536, 538, 539, 540, 559, 569, 570, 578, 584, 587, 607, 608, 611, 614, 618, 623, 624, 634, 640, 1, 6, 22, 27, 31, 39, 41, 44, 53, 57, 72, 73, 75, 76, 78, 84, 87, 94, 102, 113, 116, 124, 125, 128, 134, 138, 144, 150, 151, 153, 158, 162, 164, 167, 168, 173, 183, 191, 200, 203, 204, 213, 216, 223, 227, 251, 252, 255, 259, 265, 276, 281, 287, 291, 305, 307, 314, 325, 329, 336, 344, 346, 347, 355, 357, 359, 363, 365, 372, 373, 375, 381, 384, 385, 386, 388, 394, 395, 403, 407, 409, 416, 418, 428, 439, 444, 445, 446, 450, 453, 455, 459, 477, 481, 484, 488, 493, 498, 505, 508, 512, 517, 528, 534, 537, 544, 550, 553, 558, 562, 564, 568, 572, 573, 574, 575, 577, 580, 586, 589, 605, 609, 617, 619, 621, 628, 630, 633, 7, 8, 9, 14, 16, 17, 20, 24, 34, 35, 36, 37, 52, 60, 61, 63, 64, 69, 71, 100, 103, 109, 118, 120, 127, 130, 136, 142, 148, 155, 156, 157, 160, 166, 171, 175, 176, 178, 188, 197, 199, 207, 212, 215, 218, 219, 233, 237, 241, 243, 244, 253, 254, 256, 261, 264, 270, 277, 294, 296, 298, 301, 302, 303, 306, 309, 327, 331, 333, 339, 354, 358, 366, 369, 370, 374, 379, 387, 390, 391, 392, 406, 410, 413, 415, 421, 424, 437, 449, 456, 460, 463, 465, 467, 479, 489, 496, 499, 502, 509, 510, 514, 515, 523, 525, 526, 547, 548, 552, 557, 560, 561, 566, 581, 585, 591, 593, 595, 596, 598, 599, 602, 612, 615, 620, 632, 635, 641], 'y_true': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1], 'y_pred': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'score': [0.824297456109095, 0.8169418017698129, 0.8176480055447113, 0.8271709575176031, 0.8217221546164059, 0.8132663885300566, 0.7980182703292241, 0.8249867876957822, 0.8239604038707965, 0.8229247912250932, 0.8249262286097456, 0.8169303646111847, 0.8419100236124513, 0.8105628088307878, 0.8029801318203077, 0.8219478492939782, 0.8058088617087783, 0.8102899553584905, 0.8335761585127971, 0.82335798603334, 0.8342369699170018, 0.7971826298390206, 0.8352322247439877, 0.8206194658859053, 0.8295150224827956, 0.8245660715561789, 0.7747258264118934, 0.7242237049075959, 0.8165262275250166, 0.8296661178294003, 0.8214550646085812, 0.8257140897823231, 0.7615320633859695, 0.7968352774150602, 0.8249262286097456, 0.8109171220621967, 0.8150708454669562, 0.8100009488567629, 0.8087792831300004, 0.8196577012931636, 0.7986950111458702, 0.8170375324961172, 0.8206724484954219, 0.8256334501134941, 0.8222590933194152, 0.8080967068782202, 0.8110606072105497, 0.7895055028379301, 0.8232740754293907, 0.8157026634983481, 0.8360521601720791, 0.7731656527423, 0.8254473263733508, 0.8181707182860201, 0.8257820066113407, 0.8273368754178894, 0.8241011735663519, 0.7759954713336679, 0.8231806346124142, 0.8267759147055113, 0.7279179369599647, 0.7884452175647845, 0.8101592127718446, 0.82910223639054, 0.8176893678602595, 0.7761052774770494, 0.8110985961714322, 0.8244985185363172, 0.8062556708480377, 0.8219557751690783, 0.8142803363292007, 0.8213504731347558, 0.8078680602622171, 0.8285703310961271, 0.8220582893008382, 0.8149590953517587, 0.7832021489825679, 0.8330054789374879, 0.8265785000838303, 0.8168276188476448, 0.7723316666590171, 0.8252481091340996, 0.78916420579687, 0.8205349630851652, 0.8220640063480271, 0.8153435434936338, 0.8223879495194334, 0.8041263861422557, 0.8194569177439537, 0.7811205109477342, 0.8237330559743345, 0.8330678014206484, 0.8078967326910531, 0.8247588497974986, 0.746284136919291, 0.8256882906270775, 0.7414213280257519, 0.8188020345807552, 0.8250120682171078, 0.8059253601283556, 0.7917686845070898, 0.8057564611307807, 0.8212733840152463, 0.821924222938876, 0.8191079795738435, 0.8212058873205444, 0.8240280088047556, 0.823056916923386, 0.7844815967548829, 0.8256310656210635, 0.8035215793768085, 0.7999524432265394, 0.8281515488614867, 0.8182226476785962, 0.8242622760941195, 0.728769343878342, 0.8124809004742826, 0.7991380380597686, 0.7869743978978686, 0.8226847888279634, 0.8214698488669135, 0.820291829357849, 0.8128932937517035, 0.8077799182754303, 0.7501010738611804, 0.7876579218165363, 0.8221761291141547, 0.8295150224827956, 0.8189210679664172, 0.8213729365760292, 0.8000948496904691, 0.817007734232091, 0.8300800359352296, 0.8249936925629922, 0.8246568817501826, 0.8176289504112354, 0.8327323350803129, 0.8129511772035547, 0.7918957871245933, 0.8023741073335897, 0.827126699222152, 0.7649985984310244, 0.7783780903975522, 0.8154462958652484, 0.8007076640547149, 0.7782453371721935, 0.8271536374412312, 0.8167841641954728, 0.8205549858353687, 0.8221528903040145, 0.8148358516054248, 0.8189804612472134, 0.8173259392639782, 0.8088036761063124, 0.7747721377077067, 0.8217918241543727, 0.8179828746646823, 0.810021827195996, 0.8436164974927053, 0.806608344656994, 0.7672650950660376, 0.8166811800257541, 0.8219460901416596, 0.7415897019153271, 0.8113422066232856, 0.8301042444122402, 0.8061462664912028, 0.824989293188707, 0.8062410316265062, 0.8228334051880862, 0.8243081946768367, 0.8218065345540235, 0.8335932516678835, 0.8651993885768163, 0.8067136195670402, 0.7490170833021887, 0.8204225870804791, 0.8411278236263998, 0.8240576948166314, 0.8236070785885012, 0.8109036126740563, 0.8213621396749666, 0.8216672036111833, 0.8277707806738395, 0.7506851450451499, 0.8151915634499236, 0.8398029288018918, 0.8151622194234734, 0.8196358166455908, 0.8436164974927053, 0.8140197556773667, 0.8214603693518552, 0.8220441293957113, 0.8315011376817958, 0.8121218435449029, 0.8190521221191661, 0.8379092614906796, 0.7980062659242468, 0.8200179812920961, 0.8229455047572409, 0.8233338848009785, 0.8061462664912028, 0.8244209479406669, 0.8338771762453149, 0.777903933581232, 0.8309970846788373, 0.8244385484114553, 0.8260356311804568, 0.8310596186681387, 0.7933469517365517, 0.7806438200906037, 0.8262476872810882, 0.8222532437328824, 0.8127502047588164, 0.8237463613523005, 0.8259183999379444, 0.8123764243090813, 0.8273235141195894, 0.8151285854408584, 0.8211154579870324, 0.8012889710093452, 0.804114032844496, 0.7918957871245933, 0.8198356262935634, 0.8219460901416596, 0.8034205804579878, 0.8370664834770798, 0.8185921491041427, 0.8188053613393986, 0.8187652380862216, 0.816366765446894, 0.7675114488283828, 0.8237409950544876, 0.818104010936912, 0.8213638466063546, 0.8059455041469233, 0.8348027634377825, 0.8313444876484258, 0.8609323425510146, 0.8363518182068663, 0.8264599774086167, 0.7378343166763343, 0.7487560868116061, 0.7893234335994103, 0.8242440587041683, 0.729461038603284, 0.8339044502941478, 0.8006323137225543, 0.8278087146545428, 0.8208647577637249, 0.8005263700630934, 0.823260315541323, 0.8222355095358829, 0.8216104116869662, 0.8361700254386154, 0.8314797926225698, 0.8219460901416596, 0.7883369348832912, 0.819638587048345, 0.8333397061933236, 0.8044170714509216, 0.8231885502951167, 0.8225769137056386, 0.8336850475562549, 0.8251169517795585, 0.8190709823394915, 0.8041477746782585, 0.8208504541534015, 0.825915459328067, 0.8348826197595969, 0.8026841994891314, 0.8361328287352434, 0.8331636662999538, 0.8307199000336911, 0.8177257876003658, 0.835971703621652, 0.8228971020601163, 0.8083368468153642, 0.8219748084879746, 0.8337395973130276, 0.8348786348960322, 0.8061415389881261, 0.8058278006543947, 0.8181329267681547, 0.8183780472778451, 0.8206337474649242, 0.8268052111518326, 0.8137966813917015, 0.8190709823394915, 0.7770357337058394, 0.7983090798376244, 0.8112001812940848, 0.7526056857952158, 0.8301230013660252, 0.8214596851144179, 0.8317799879582106, 0.8015558644420733, 0.8217425591996601, 0.7995915652805629, 0.8181736238315824, 0.8233428088396131, 0.827601547232344, 0.8084724747227415, 0.8316473954651705, 0.8159963608646074, 0.8225396075182374, 0.8177559691398301, 0.8225619716908806, 0.8348517503548551, 0.8300959474812325, 0.8365670359009363, 0.8319224693064016, 0.8177447543061597, 0.8351017425332266, 0.8236812052134279, 0.8240986982490485, 0.8348521182608201, 0.8070380145207782, 0.8296408800188086, 0.8118121358757012, 0.8269241596582642, 0.8110381224013846, 0.8260115488576959, 0.8371791166769258, 0.840585467921624, 0.815716322358357, 0.8360640159247238, 0.8282996994609432, 0.8305389018040312, 0.7811528762851733, 0.783405020020144, 0.8279516722754178, 0.8341669287471728, 0.8088384701827394, 0.8348649781875388, 0.8396980335617075, 0.7943539134486602, 0.8059257050489936, 0.8138737711532474, 0.8187795470889088, 0.8202169099207532, 0.8128745031383865, 0.8268897969343479, 0.8260436061232405, 0.8108219819232494, 0.7553629398532661, 0.8111300099474572, 0.7388250394456258, 0.8327291160973935, 0.8265515695818474, 0.7946998323993901, 0.8348895530742357, 0.8153995108518671, 0.8135524462830693, 0.8363711107628194, 0.8341626495696289, 0.8263747034509962, 0.7908614037879304, 0.8325827513236991, 0.8095847829109047, 0.8191886914503306, 0.8096486581408427, 0.8365456731319995, 0.8346610886888683, 0.8339431186885381, 0.8363039055188356, 0.8219306519255865, 0.8206578784875399, 0.8406696127298904, 0.8305171971684036, 0.8079715179892102, 0.8352769033871272, 0.8211459509441024, 0.8280695013610833, 0.8331636662999538, 0.8309600865466866, 0.7762196732495454, 0.8526329726751927, 0.8097898622874155, 0.8348529984782997, 0.8255150791444474, 0.8055819445363138, 0.8234641328312072, 0.7942575994758958, 0.824671103233066, 0.8169416112127085, 0.833504687537547, 0.8220420937527493, 0.8238300168817849, 0.8204416221991895, 0.8185736252276115, 0.8056213081924259, 0.8191326812228542, 0.8120113212779702, 0.8215472565029425, 0.8201578718241114, 0.8241688642096803, 0.8222257774767747, 0.8146333546446577, 0.8220788822741245, 0.818162780996313, 0.8127623225690039, 0.8295337088384096, 0.8176041084440537, 0.8099574651598761, 0.8220533954572262, 0.8071304073647155, 0.8200137383900443, 0.8157351288511914, 0.8208065297190149, 0.8094613921320766, 0.8248866373645413, 0.8087733505039305, 0.8216822071467252, 0.8233140468348317, 0.8176537182145097, 0.8176537182145097, 0.8118927951192367, 0.8281036984502548, 0.8218059435061686, 0.8178246438573579, 0.817519287434038, 0.8208138029370147, 0.8211425937854997, 0.8205861909093594, 0.8065697924731788, 0.8179203768037882, 0.8215750774814465, 0.8208810292403259, 0.799739254041107, 0.8133467934000137, 0.8259326100192335, 0.8229168230137345, 0.7971060065048514, 0.8173128002288523, 0.8228133777911889, 0.8156693470130655, 0.814706427760035, 0.8124443702608275, 0.8318626814946158, 0.8072039302007443, 0.813036248665109, 0.8048366585177563, 0.8123627693407605, 0.8210129899380816, 0.8096055515299392, 0.8126605327936858, 0.8214624360490541, 0.811585926810095, 0.8194437309198079, 0.8222697681540383, 0.8095057714774514, 0.8232433004529307, 0.821003309943231, 0.8228643649181843, 0.8039588634976276, 0.8231837423583791, 0.8097117736036423, 0.822248249011205, 0.819934988304602, 0.7993713174219892, 0.8194437309198079, 0.8228353035424648, 0.8225696303850688, 0.8249223178960914, 0.8139751624278764, 0.8177013151447238, 0.8194437309198079, 0.8262605231735641, 0.8173407808990343, 0.7847126473026986, 0.8100740570810554, 0.8201809193856177, 0.8204122295532453, 0.8214177126596672, 0.8208230901845299, 0.8106650857596304, 0.8170785569131258, 0.8178021840592132, 0.8227234684577291, 0.8204793869179247, 0.8263690083590417, 0.8037158224222596, 0.8159757765016868, 0.8170534616463521, 0.8120113212779702, 0.8053961211842781, 0.819485567186988, 0.8167922281720787, 0.8012771439889115, 0.820416113871897, 0.8232985049675439, 0.8068669743096748, 0.8165607581177028, 0.8189891248100472, 0.8194437309198079, 0.8115522825756415, 0.8280313483504098, 0.7920444474663364, 0.8221671192468685, 0.8193714677994759, 0.8224417095621182, 0.820574886550045, 0.7963513212345592, 0.8229690541852162, 0.8218282487410198, 0.8219630242643458, 0.8066584739236665, 0.8234787516928119, 0.8222352471723126, 0.8231837423583791, 0.8206654922461949, 0.8133388015816971, 0.8179203768037882, 0.8243015302618213, 0.8158301638164527, 0.825557995279925, 0.8070419794981587, 0.819822679886294, 0.8265008903121279, 0.7993263450188196, 0.8239034107445784, 0.7977451784462763, 0.81710728195915, 0.8062480270752556, 0.8028974188736229, 0.7922025167832493, 0.8023749695972325, 0.8091085464614854, 0.8234900249464749, 0.8383861852924678, 0.829424276142136, 0.819282026869603, 0.7875464788441294, 0.8021089331288908, 0.7921602527213294, 0.8008526697284195, 0.8210036466122282, 0.8190144326348868, 0.8340725066977444, 0.8008500481286536, 0.8049234062423689, 0.8046201376381562, 0.8394578949411464, 0.8157124583181867, 0.8020034362323862, 0.7987432929973952, 0.7922305297971477, 0.811861800573932, 0.7992307389409402, 0.8024196893820814, 0.8434924285470083, 0.8125693464105088, 0.8142704549880504, 0.8143883789165764, 0.8074174682254489, 0.8251255192012256, 0.8286781061285102, 0.799410028414122, 0.8125693464105088, 0.842686439030963, 0.8118996212171335, 0.7948354347359081, 0.8537663881804308, 0.8385797452291222, 0.7973954240647363, 0.792589527825992, 0.8348259058541622, 0.7945873247578026, 0.7997391616044477, 0.805954866136892, 0.7950231192798753, 0.819819975665952, 0.8303452356924946, 0.8225384905043722, 0.8335176776759795, 0.8138992097869648, 0.8009939711815116, 0.8280436925346389, 0.8188867025748202, 0.8219099935310281, 0.8362659645276287, 0.8235945037909133, 0.8040363507264869, 0.8067731056873637, 0.8185524377557651, 0.81710728195915, 0.8371100804728215, 0.7985760189338265, 0.8039797759367486, 0.8091256951320448, 0.8149358982268012, 0.828157484237899, 0.7979575208398172, 0.8096448528405846, 0.8030905633237362, 0.8427550156441844, 0.8268580389275545, 0.8100587250724761, 0.7919896524170248, 0.8250968299936339, 0.7956147353427614, 0.8304367560242216, 0.8006582272627639, 0.7982338902404853, 0.7987043523328625, 0.8411498114734043, 0.795329875404388, 0.7977755080406904, 0.819822679886294, 0.8148245886496281, 0.8090640342211548, 0.8162348851297917, 0.8312036455656854, 0.828649608903671, 0.812351360016495

# Fase 5 — Limiar e consolidação
O limiar é escolhido somente em OOF interno do ensemble calibrado e aplicado ao mesmo score externo da Fase 4.

In [99]:
phase5_rows = []
phase5_thresholds = []
phase5_oof_classes = pd.DataFrame({"y_true": y_array})
phase5_oof_scores = pd.DataFrame({"y_true": y_array})
threshold_grid = np.arange(0.10, 0.91, 0.05)
for outer_fold, (train_index, test_index) in enumerate(outer_cv.split(X, y_array), 1):
    internal = phase4_inner_oof[outer_fold - 1]
    inner_truth = np.asarray(internal["y_true"])
    inner_indices = np.asarray(internal["indices"])
    inner_score1 = np.asarray(internal["score"], dtype=float)
    inner_prediction = np.asarray(internal["y_pred"])
    assert len(inner_indices) == len(inner_truth) == len(inner_prediction) == len(inner_score1)
    assert not pd.isna(inner_indices).any()
    assert len(np.unique(inner_indices)) == len(inner_indices)
    assert np.isfinite(inner_score1).all()
    threshold_records = []
    for threshold in threshold_grid:
        inner_prediction = (inner_score1 >= threshold).astype(int)
        threshold_records.append({
            "threshold": float(threshold),
            "f1_macro": f1_score(inner_truth, inner_prediction, labels=[0, 1], average="macro", zero_division=0),
            "balanced_accuracy": balanced_accuracy_score(inner_truth, inner_prediction),
            "mcc": matthews_corrcoef(inner_truth, inner_prediction),
        })
    chosen = max(threshold_records, key=lambda row: (row["f1_macro"], row["balanced_accuracy"], row["mcc"]))
    threshold = chosen["threshold"]
    outer_score1 = phase4_oof_scores.loc[test_index, "probability_score1"].to_numpy(dtype=float)
    outer_score0 = phase4_oof_scores.loc[test_index, "probability_score0"].to_numpy(dtype=float)
    assert np.isfinite(outer_score1).all()
    y_test = y_array[test_index]
    prediction_05 = (outer_score1 >= 0.5).astype(int)
    prediction_threshold = (outer_score1 >= threshold).astype(int)
    metrics_05 = binary_metrics(y_test, prediction_05, outer_score0, outer_score1)
    metrics_threshold = binary_metrics(y_test, prediction_threshold, outer_score0, outer_score1)
    phase5_oof_classes.loc[test_index, "threshold_05_class"] = prediction_05
    phase5_oof_classes.loc[test_index, "threshold_selected_class"] = prediction_threshold
    phase5_oof_scores.loc[test_index, "score0"] = outer_score0
    phase5_oof_scores.loc[test_index, "score1"] = outer_score1
    phase5_thresholds.append({
        "outer_fold": outer_fold,
        "threshold": threshold,
        "inner_oof_size": len(inner_truth),
        "members": internal["members"],
        "selection": threshold_records,
    })
    phase5_rows.extend([
        {**metrics_05, "scenario": "threshold_0.5", "outer_fold": outer_fold, "threshold": 0.5},
        {**metrics_threshold, "scenario": "threshold_selected", "outer_fold": outer_fold, "threshold": threshold},
    ])
    print("Fase 5 fold", outer_fold, "threshold", threshold)

Fase 5 fold 1 threshold 0.8000000000000002
Fase 5 fold 2 threshold 0.8000000000000002
Fase 5 fold 3 threshold 0.8000000000000002
Fase 5 fold 4 threshold 0.8000000000000002
Fase 5 fold 5 threshold 0.8000000000000002
Fase 5 fold 6 threshold 0.8000000000000002
Fase 5 fold 7 threshold 0.8000000000000002
Fase 5 fold 8 threshold 0.8000000000000002
Fase 5 fold 9 threshold 0.8000000000000002
Fase 5 fold 10 threshold 0.8000000000000002

# Consolidação e exportação
Exportação executada somente quando este notebook for executado. O diretório é separado dos resultados legados.

In [104]:
run_id = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
artifact_root = Path("src/artifacts/revisao_experimental") / run_id
fold_metrics_df = pd.DataFrame(phase1_rows + phase2_rows + phase3_rows + phase4_rows + phase5_rows)
search_df = pd.DataFrame(phase1_search)
folds_df = pd.DataFrame(fold_indices)
mdi_df = pd.DataFrame(phase2_mdi)
weights_df = pd.DataFrame(phase3_weights)
ensemble_profiles_df = pd.DataFrame(phase4_profiles)
ensemble_members_df = pd.DataFrame(phase4_members)
thresholds_df = pd.DataFrame(phase5_thresholds)
assert len(folds_df) == 10
assert all(set(row["train_index"]).isdisjoint(row["test_index"]) for row in fold_indices)
assert all(len(values) == 714 and np.all(np.asarray(values) != -1) for values in phase1_oof.values())
assert all(len(values) == 714 and np.all(np.asarray(values) != -1) for values in phase2_oof.values())
assert all(len(values) == 714 and np.all(np.asarray(values) != -1) for values in phase3_oof.values())
assert phase4_oof_classes["majority_class"].notna().sum() == 714
assert phase4_oof_classes["probability_class"].notna().sum() == 714
assert phase5_oof_classes["threshold_05_class"].notna().sum() == 714
assert phase5_oof_classes["threshold_selected_class"].notna().sum() == 714
assert phase5_oof_scores["score1"].notna().sum() == 714
assert phase5_oof_scores["score0"].notna().sum() == 714
assert all(len(internal["indices"]) == len(set(internal["indices"])) for internal in phase4_inner_oof)
assert all(len(internal["indices"]) == len(internal["y_true"]) == len(internal["score"]) for internal in phase4_inner_oof)
assert all(np.isfinite(np.asarray(internal["score"], dtype=float)).all() for internal in phase4_inner_oof)
score_availability = []
for scenario, score_map in [("baseline", phase1_scores), ("mdi80", phase2_scores), ("cost_sensitive", phase3_scores)]:
    for model_name, score_values in score_map.items():
        finite = np.isfinite(score_values)
        missing = np.isnan(score_values)
        if model_name == "OPF":
            assert missing.all()
            status, reason = "all_nan", "OPF sem score contínuo"
        elif finite.all():
            status, reason = "all_finite", None
        elif missing.all():
            status, reason = "all_nan", "helper registrou score indisponível"
        else:
            score_map[model_name] = np.full_like(score_values, np.nan, dtype=float)
            status, reason = "partial_score_suppressed", "mistura de scores finitos e NaN"
        score_availability.append({"scenario": scenario, "model": model_name, "status": status, "reason": reason})

assert all(len(record["members"]) == 3 and len(set(record["members"])) == 3 for record in phase4_members)
assert all(abs(sum(record["weights"]) - 1.0) < 1e-12 for record in phase4_members)
assert all(0.10 <= record["threshold"] <= 0.90 for record in phase5_thresholds)
mdi_frequency_df = pd.DataFrame(columns=["feature_origin", "selection_frequency", "total_folds"])
if not mdi_df.empty:
    selected_rows = []
    for record in phase2_mdi:
        mdi_records = record.get("mdi_records") or []
        assert all({"feature_transformed", "feature_origin", "importance", "cumulative", "selected"}.issubset(item) for item in mdi_records)
        selected_rows.extend(
            {**item, "outer_fold": record["outer_fold"]}
            for item in mdi_records
        )
    selection_table = pd.DataFrame(selected_rows)
    if not selection_table.empty:
        selected_only = selection_table[selection_table["selected"]]
        mdi_frequency_df = selected_only.groupby("feature_origin").agg(selection_frequency=("selected", "sum"), total_folds=("outer_fold", "nunique")).reset_index()

wilcoxon_rows = []
from scipy.stats import wilcoxon
for model in roster:
    corrected = fold_metrics_df[(fold_metrics_df["scenario"] == "mdi80") & (fold_metrics_df["model"] == model)].drop_duplicates("outer_fold").set_index("outer_fold")["f1_macro"]
    dummy = fold_metrics_df[(fold_metrics_df["scenario"] == "baseline") & (fold_metrics_df["model"] == "Dummy")].drop_duplicates("outer_fold").set_index("outer_fold")["f1_macro"]
    pairs = pd.concat([corrected, dummy], axis=1, join="inner").dropna()
    if len(pairs) == 0 or np.allclose(pairs.iloc[:, 0], pairs.iloc[:, 1]):
        statistic = 0.0
        p_value = 1.0
    else:
        statistic, p_value = wilcoxon(pairs.iloc[:, 0], pairs.iloc[:, 1])
    difference = pairs.iloc[:, 0] - pairs.iloc[:, 1] if len(pairs) else pd.Series(dtype=float)
    wilcoxon_rows.append({"contrast": model + " vs Dummy", "W": float(statistic), "p": float(p_value), "mean_difference": float(difference.mean()) if len(difference) else np.nan, "n_folds": len(pairs), "limitation": "10 folds dependentes, exploratório"})
order = np.argsort([row["p"] for row in wilcoxon_rows])
running = 0.0
adjusted = np.zeros(len(wilcoxon_rows), dtype=float)
for rank, position in enumerate(order):
    running = max(running, min(1.0, (len(order) - rank) * wilcoxon_rows[position]["p"]))
    adjusted[position] = min(1.0, running)
for position, row in enumerate(wilcoxon_rows):
    row["p_holm"] = min(1.0, float(adjusted[position]))
assert all(0 <= row["p_holm"] <= 1 for row in wilcoxon_rows)

manifest = {"run_id": run_id, "seed": SEED, "n": len(y_array), "target_mapping": TARGET_MAP, "class_counts": class_counts.to_dict(), "class_percentages": class_percentages.to_dict(), "data_path": str(DATA_PATH), "data_sha256": hashlib.sha256(DATA_PATH.read_bytes()).hexdigest(), "nested_cv": {"outer": 10, "inner": 5, "shuffle": True}, "fold_indices": fold_indices, "roster": roster + ["AdaBoost", "Dummy"], "versions": {"python": sys.version, "numpy": np.__version__, "pandas": pd.__version__, "sklearn": sklearn.__version__}, "limitations": ["n=714", "desenho transversal", "base única", "sem validação externa", "generalização limitada"], "opf_score_note": "OPF sem score contínuo mantém AUROC/AP como NaN"}
manifest["phase4_ensemble"] = phase4_manifest
manifest["score_availability"] = score_availability
artifact_root.mkdir(parents=True, exist_ok=False)
folds_df.to_csv(artifact_root / "folds.csv", index=False)
fold_metrics_df.to_csv(artifact_root / "metrics_per_fold.csv", index=False)
search_df.to_csv(artifact_root / "search.csv", index=False)
mdi_df.to_json(artifact_root / "mdi_detailed.json", orient="records", indent=2)
mdi_frequency_df.to_csv(artifact_root / "mdi_frequency.csv", index=False)
weights_df.to_json(artifact_root / "weights.json", orient="records", indent=2)
ensemble_profiles_df.to_json(artifact_root / "ensemble_profiles.json", orient="records", indent=2)
ensemble_members_df.to_json(artifact_root / "ensemble_members.json", orient="records", indent=2)
thresholds_df.to_json(artifact_root / "thresholds.json", orient="records", indent=2)
pd.DataFrame(wilcoxon_rows).to_json(artifact_root / "wilcoxon_holm.json", orient="records", indent=2)
phase4_oof_classes.to_csv(artifact_root / "oof_ensemble_classes.csv", index=False)
phase4_oof_scores.to_csv(artifact_root / "oof_ensemble_scores.csv", index=False)
phase5_oof_classes.to_csv(artifact_root / "oof_threshold_classes.csv", index=False)
phase5_oof_scores.to_csv(artifact_root / "oof_threshold_scores.csv", index=False)
for name, values in phase1_oof.items():
    if np.isfinite(phase1_scores[name]).all():
        pd.DataFrame({"y_true": y_array, "prediction": values, "score1": phase1_scores[name]}).to_csv(artifact_root / f"oof_baseline_{name}.csv", index=False)
for name, values in phase2_oof.items():
    if np.isfinite(phase2_scores[name]).all():
        pd.DataFrame({"y_true": y_array, "prediction": values, "score1": phase2_scores[name]}).to_csv(artifact_root / f"oof_mdi80_{name}.csv", index=False)
for name, values in phase3_oof.items():
    if np.isfinite(phase3_scores[name]).all():
        pd.DataFrame({"y_true": y_array, "prediction": values, "score1": phase3_scores[name]}).to_csv(artifact_root / f"oof_cost_{name}.csv", index=False)
for scenario, scores in [("baseline", phase1_scores), ("mdi80", phase2_scores), ("cost_sensitive", phase3_scores)]:
    for name, values in scores.items():
        valid = np.isfinite(values)
        if valid.all():
            fpr, tpr, _ = roc_curve(y_array, values)
            pd.DataFrame({"fpr": fpr, "tpr": tpr}).to_csv(artifact_root / f"roc_{scenario}_{name}.csv", index=False)
            precision, recall, _ = precision_recall_curve(y_array, values)
            pd.DataFrame({"precision": precision, "recall": recall}).to_csv(artifact_root / f"pr_{scenario}_{name}.csv", index=False)
plot_sources = [("baseline", phase1_scores), ("mdi80", phase2_scores), ("cost_sensitive", phase3_scores)]
for scenario, score_map in plot_sources:
    for model_name, score_values in score_map.items():
        valid = np.isfinite(score_values)
        if valid.all():
            false_positive_rate, true_positive_rate, _ = roc_curve(y_array, score_values)
            figure, axis = plt.subplots()
            axis.plot(false_positive_rate, true_positive_rate)
            axis.set_title(f"ROC — {scenario} — {model_name} — seed {SEED}")
            axis.set_xlabel("False positive rate")
            axis.set_ylabel("True positive rate")
            figure.savefig(artifact_root / f"roc_{scenario}_{model_name}.png", bbox_inches="tight")
            plt.close(figure)
            precision, recall, _ = precision_recall_curve(y_array, score_values)
            figure, axis = plt.subplots()
            axis.plot(recall, precision)
            axis.set_title(f"PR — {scenario} — {model_name} — seed {SEED}")
            axis.set_xlabel("Recall")
            axis.set_ylabel("Precision")
            figure.savefig(artifact_root / f"pr_{scenario}_{model_name}.png", bbox_inches="tight")
            plt.close(figure)
manifest["artifacts"] = sorted(str(path.relative_to(artifact_root)) for path in artifact_root.iterdir())
(artifact_root / "manifest.json").write_text(json.dumps({**manifest, "artifact_root": str(artifact_root)}, ensure_ascii=False, indent=2))
print("Artefatos exportados em", artifact_root)

Artefatos exportados em src/artifacts/revisao_experimental/20260914T000127Z